### ISSUE TITLE
Gas estimation message for EIP1559 txs is extremely misleading

### ISSUE THREAD

**Issue by simplyoptimistic** [foundry-rs/foundry#5709] opened 2023-08-24 09:47 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (1143e57 2023-08-24T00:28:32.561836000Z)

### What command(s) is the bug in?

forge script

### Operating System

None

### Describe the bug

--priority-gas-price was implemented in #5281 

My version of foundry is up to date. 

Expected behavior: when I use --priority-gas-price, it lowers my gas fee on deployment and doesn't use foundry's default 3 gwei tip. 

To reproduce, create a fresh repository and deploy. I ran the following command:

`forge script script/Counter.s.sol:CounterScript --priority-gas-price 100 --broadcast --slow --rpc-url optimism -vvvv`

This is the output:

```
Estimated gas price: 3.0000001 gwei

Estimated total gas used for script: 138734

Estimated amount required: 0.0004162020138734 ETH
```

Following the suggestion in #5281, I use `--legacy --with-gas-price`:

`forge script script/Counter.s.sol:CounterScript --legacy --with-gas-price 100 --broadcast --slow --rpc-url optimism -vvvv`

This is the output:

```
Chain 420

Estimated gas price: 0.0000001 gwei

Estimated total gas used for script: 138734

Estimated amount required: 0.0000000000138734 ETH
```

I have also tried by using the environment variable alias, it also doesn't work.

**Comment by Evalir** [comment] 2023-08-30 22:41
cc @Sabnock01

**Comment by Sabnock01** [comment] 2023-08-30 22:43
> cc @Sabnock01 

Taking a look

**Comment by simplyoptimistic** [comment] 2023-11-06 04:21
Are there any updates on this? It is inconvenient to deploy on L2s without being able to specify the priority fee especially if there is network congestion and the base fee is fluctuating.

**Comment by Evalir** [comment] 2023-11-06 13:05
@simplyoptimistic ack—we thought this had been fixed with new refactors. Looking

**Comment by Evalir** [comment] 2023-12-22 06:47
So, this flag is working as intended, but the estimation output *is* wrong.

This happens because the priority gas price is applied just before sending the transaction ()https://github.com/foundry-rs/foundry/blob/master/crates/forge/bin/cmd/script/broadcast.rs#L106), instead of being applied when the script sequence is being created (https://github.com/foundry-rs/foundry/blob/master/crates/forge/bin/cmd/script/broadcast.rs#L541-L544). This means that when calculating the EIP1559 price, the default estimator is used which has the hardcoded tip, but the transaction is sent with the correct priority gas price and the most up-to-date base fee possible.

The correct fix for this is to make a custom estimator which can take a non-hardcoded tip, but this will require changes upstream on alloy / ethers.

**Comment by ultrasecreth** [comment] 2023-12-22 19:01
The problem is deeper, even when you specify the tip by hand you overpay, and this affect both L1 & L2
The issue is that the tip is set to match the gas price, so you end up paying whatever value you specify on `with-gas-price` 

Exhibit A: 
  - tx: https://basescan.org/tx/0x4145ae44ac3679cecc733e23b4f56e5f716736448a6ef41821e2a3269515291c
  - params: `--with-gas-price 1100058 --priority-gas-price 100000`
  - effective params: `Base: 0.000000059 Gwei |Max: 0.001100058 Gwei |Max Priority: 0.001100058 Gwei`
  - Gas Price: `0.000000000001100058 ETH (0.001100058 Gwei)`

Exhibit B:
  - tx: https://etherscan.io/tx/0xdda862b5765aa8efc40025b9d12408bc11d93836545d179f1506d47fa8c5102e
  - params: `--with-gas-price 52000000000 --priority-gas-price 1000000000 `
  - effective params: `Base: 41.38366894 Gwei |Max: 52 Gwei |Max Priority: 52 Gwei`
  - Gas Price: `52 Gwei (0.000000052 ETH)`

Been overspending on deployments/scripts for a while now, I'm pretty sure I raised a separate issue a while ago for this.

**Closed** 2024-04-09 20:52 UTC
Labels: T-bug

**Comment by simplyoptimistic** [comment] 2024-04-12 04:10
Looks like this has been fixed, at least with simulations. Thanks for the hard work! Will report if I have any issues with this.

**Comment by advock** [comment] 2024-04-13 16:31
@simplyoptimistic whats the solution ??

**Comment by Sabnock01** [comment] 2024-04-13 18:06
> @simplyoptimistic whats the solution ?? 

It simply shows accurate gas estimates now.
![image-189.png](https://github.com/foundry-rs/foundry/assets/24715302/4d471c31-bfe5-4b6b-8ca6-22a11d15c261)
