### ISSUE TITLE
feat(`anvil`): be able to specify a prefix path for temp disk storage

### ISSUE THREAD

**Issue by kahuang** [foundry-rs/foundry#3512] opened 2022-10-18 23:38 UTC
### Component

Anvil

### Describe the feature you would like

When anvil state grows, it persists it temporarily to disk. I'd like to be able to specify a prefix path for the directory that gets created by anvil for this state.

### Additional context

I am running Anvil in the cloud, and want to attach a persistent disk to the instance and mount it at the path anvil will use for storing state. Because it's a random directory each time, there's no way for me to programatically mount my disk at that location before anvil starts.

**Comment by gakonst** [comment] 2022-10-19 08:45
@mattsse PTAL^

**Comment by mattsse** [comment] 2022-10-19 08:59
Does this also concern the RPC cache dir @kahuang ?

**Comment by kahuang** [comment] 2022-10-19 13:02
Anywhere that disk space can grow unbounded!

**Comment by emilianobonassi** [comment] 2023-03-02 18:15
I need it too to be able to restart a session from a specific state.

**Comment by grandizzy** [comment] 2024-10-17 12:15
> I need it too to be able to restart a session from a specific state.

@emilianobonassi this is possible in latest versions by using
```
      --state <PATH>
          This is an alias for both --load-state and --dump-state.
          
          It initializes the chain with the state and block environment stored
          at the file, if it exists, and dumps the chain's state on exit.
```
https://book.getfoundry.sh/reference/anvil/

We're also going to look into implementing the original cache dir request

**Comment by zerosnacks** [comment] 2024-11-05 13:33
Marking as duplicate of https://github.com/foundry-rs/foundry/issues/3512 which aims to add an Anvil cache path

**Closed** 2024-11-21 07:02 UTC
Labels: good first issue, T-feature, P-normal, C-anvil
