### ISSUE TITLE
`forge test --debug` fails with `Invalid hex calldata` when invoked on tests that take fuzz arguments

### ISSUE THREAD

**Issue by emo-eth** [foundry-rs/foundry#5563] opened 2023-08-08 15:09 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (6672134 2023-08-08T00:21:59.824374000Z)

### What command(s) is the bug in?

forge test --debug

### Operating System

None

### Describe the bug

This has previously been mentioned in #3438 as a feature request. 

I am opening this issue because, if this is not a supported feature, Forge should fail in a way that informs the end user that fuzz test debugging is not supported, perhaps recommending the `--sig` flag as an alternative (which has a separate open issue,  #4722). 

Further, the error's implication that calldata was not passed correctly to the debugger, as mentioned in #4722, appears to me to be a bug in the way Forge is relaying fuzz test calldata to the debugger.

Minimal reproduction:

run `forge test --debug testFuzz` with the following code

```solidity
pragma solidity ^0.8.17;

import {Test} from "forge-std/Test.sol";

contract FuzzFailTest is Test {
    function testFuzz(uint256 arg) public {}
}
```

Results in output:

```
[⠑] Compiling...
[⠔] Compiling 1 files with 0.8.20
[⠑] Solc 0.8.20 finished in 734.48ms
Compiler run successful!
Error: 
Invalid hex calldata

Context:
- Invalid character 'x' at position 1
```

**Comment by iFrostizz** [comment] 2023-09-11 21:51
Should be fixed as well

**Comment by Evalir** [comment] 2023-09-11 21:53
Fixed with the merged refactors—let's reopen if we still see this happening!

**Comment by iFrostizz** [comment] 2023-09-12 10:29
@Evalir No debug traces are collected, so it still crashes on latest foundryup. Probably slipped into the refactor parts, can we reopen ?

**Comment by zerosnacks** [comment] 2024-07-03 13:10
Closing per https://github.com/foundry-rs/foundry/pull/5822#issuecomment-1789537712

Unable to reproduce wit h given setup

```
Ran 1 test for test/Counter.t.sol:CounterTest
[PASS] testFuzz(uint256) (runs: 256, μ: 234, ~: 234)
Suite result: ok. 1 passed; 0 failed; 0 skipped; finished in 718.01ms (10.19ms CPU time)

Ran 1 test suite in 1.02s (718.01ms CPU time): 1 tests passed, 0 failed, 0 skipped (1 total tests)
```

**Closed by zerosnacks** 2024-07-03 13:10 UTC
Labels: T-bug
