### ISSUE TITLE
forge build produce corrupted byte code containing $__ symbol 

### ISSUE THREAD

**Issue by sirgarfieldc** [foundry-rs/foundry#5325] opened 2023-07-07 10:50 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (4b0d5d8 2023-07-07T00:04:10.359853565Z)

### What command(s) is the bug in?

forge build

### Operating System

Linux

### Describe the bug

compiled output contains $__ symbol. 

Example `65b038173__$792ef0ccaaa9`

string representation of the bytecode can not be converted to byte[] in go because `err=encoding/hex: invalid byte: U+005F '_' `

I have a minimal example for repro. 

https://github.com/sirgarfieldc/debug_forge/blob/master/out/MyTest.sol/Test.json#L32

The problem seems to be that I put constants into a library and use it in other contracts.
If I change the library to contract, then the $__ goes away.

**Comment by mattsse** [comment] 2023-07-07 10:52
this is because https://github.com/sirgarfieldc/debug_forge/blob/master/src/TestConstants.sol is a library 

the `$__` is a solc placeholder for the address of a (yet to be linked) library deployment

**Comment by mattsse** [comment] 2023-07-07 10:53
see also https://docs.soliditylang.org/en/v0.8.20/using-the-compiler.html#library-linking

closing this because this is the expected behaviour

**Closed by mattsse** 2023-07-07 10:53 UTC
Labels: T-bug
