### ISSUE TITLE
msg.sender not consistent after using vm.startPrank()

### ISSUE THREAD

**Issue by Carolina-Pinheiro** [foundry-rs/foundry#4556] opened 2023-03-14 11:48 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (df8ab09 2023-03-14T09:59:20.944687208Z)

### What command(s) is the bug in?

forge test -vvvv

### Operating System

Linux

### Describe the bug

I run into the issue that when I'm calling a function within a test file after starting a prank the `msg.sender` is not the one I started the prank with before calling that function. However, if I call a function from another contract inside the first function the `msg.sender` is correct. You can see code attached below that replicates this issue as well as a screenshot of the forge test. I was expecting that the `msg.sender` in both` LogAddress()` emits would be "Phoebe", however that doesn't happen.

Code snippet replicating the issue:

**Counter.t.sol**
```
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import "forge-std/Test.sol";
import { showMsgSender } from "test/contract.sol";

contract CounterTest is Test {
    showMsgSender public show;
    address public phoebe = vm.addr(15);

    event LogAddress(address);

    function setUp() public {
        show = new showMsgSender();
        vm.label(phoebe, "Phoebe");
    }

    function testMSGSender() public {
        vm.startPrank(phoebe); 
        withinTest();
        vm.stopPrank();
    }

    function withinTest() public {
        emit LogAddress(msg.sender);  // THE BUG HAPPENS HERE
        show.show();
    }
}
```

**Contract.sol**

```
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

contract showMsgSender {
    event LogAddress(address);

    function show() public {
        emit LogAddress(msg.sender);
    }
}

```

![image](https://user-images.githubusercontent.com/57190987/224990221-4865cc55-7556-4f2d-a9f2-584723eb1f45.png)

**Comment by mds1** [comment] 2023-03-14 15:10
Yep exactly what @mattsse said, `prank` cheats only change the `msg.sender` within CALLs, not within the current context, and the line labeled "THE BUG HAPPENS HERE" is the same context as the test contract. Going to close this since this is the expected behavior, but @Carolina-Pinheiro feel free to ask any more questions here

**Closed by mds1** 2023-03-14 15:10 UTC
Labels: T-bug

**Comment by Carolina-Pinheiro** [comment] 2023-03-14 15:22
Thanks for the quick response!
I was under the impression that the `prank` changed `msg.sender` "everywhere" from then on, glad to have that clarified!

**Comment by polus-arcticus** [comment] 2024-07-21 10:59
In the case where it is required to have msg.sender in the show.show() to be the correct address(CounterTest) (like in the case where we are enforcing show.show() to only be called by CounterTest.  What is one to do in foundry?

**Comment by Viquetour** [comment] 2024-10-29 02:51
I was trying to run a test though in a hardhat project I integrated foundry to it but I keep getting `vm` undeclared identifier, pls how do I resolve this?
 ✘  viquetour   main -+  forge build
[⠒] Compiling...
[⠔] Compiling 1 files with Solc 0.8.26
[⠒] Solc 0.8.26 finished in 307.56ms
Error: 
Compiler run failed:
Error (7576): Undeclared identifier.
  --> test/InvariantTest/SwanInvariant.sol:48:9:
   |
48 |         vm.startPrank(owner);
   |         ^^

               
 [~/Documents/Competitive_Audit/2024-10-swan-dria]
 ✘  viquet
