### ISSUE TITLE
Using `--interactives` result in unexpected behavior

### ISSUE THREAD

**Issue by hexcowboy** [foundry-rs/foundry#4763] opened 2023-04-18 16:21 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What command(s) is the bug in?

forge script --interactives

### Operating System

macOS (Intel)

### Describe the bug

Broadcasting a script does not seem to prompt for an interactive private key like the help documentation says.

```bash
forge script script/DeployV6.s.sol:Deploy \
  --chain-id 1 \
  --rpc-url https://mainnet.infura.io/v3/omitted \
  --broadcast \
   -i 1
```

In this scenario, when the traces fail the interactive prompt is never displayed and the command fails before it's even broadcasted.

It should also be noted that even when a `-a` or `--froms` address is supplied, it does not fix the bug.

I cannot supply a repro currently as I don't have enough bandwidth. I will come back to this in the future if it still isn't resolved to try and help.

**Comment by hexcowboy** [comment] 2023-04-18 16:22
this bug was also reported in the telegram group by someone else https://t.me/foundry_support/34596

**Comment by mrmemes-eth** [comment] 2023-10-12 20:57
This is still true as of `forge 0.2.0 (5068b7a 2023-10-12T00:21:35.672528000Z)`

**Comment by susuper** [comment] 2023-12-15 17:45
Try to add --sender ADDRESS to arguments.

**Comment by zerosnacks** [comment] 2024-07-02 08:58
Unable to reproduce

```
forge script script/Counter.s.sol --chain-id 1 --rpc-url <RPC_URL> --broadcast -i 1
[⠊] Compiling...
No files changed, compilation skipped
Enter private key

<PROMPTS>

[....]
```

And then continues 

```
Script ran successfully.

## Setting up 1 EVM.

==========================

Chain 1

Estimated gas price: 7.004518334 gwei

Estimated total gas used for script: 138713

Estimated amount required: 0.000971617751664142 ETH

==========================

[...]
```

It is likely this has been resolved by now

Feel free to re-open with a minimal reproduction

**Closed by zerosnacks** 2024-07-02 08:58 UTC
Labels: T-bug, C-forge, Cmd-forge-script
