### ISSUE TITLE
forge no longer finds test

### ISSUE THREAD

**Issue by sakulstra** [foundry-rs/foundry#7578] opened 2024-04-05 20:59 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (1281421 2024-04-05T00:21:15.963758000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

On latest nightly (which we run on ci), our testing setup stopped working.
This seems to be related to https://github.com/foundry-rs/foundry/pull/7334

On BGD we usually co-locate tests with the contracts (instead of having them in a separate directory) and then run:
`forge test --match-path src/20240402_AaveV2Ethereum_UpgradeAMPLImplementation/AaveV2Ethereum_UpgradeAMPLImplementation_20240402.t.sol`, where --match-path is the fully qualified path of the test.

Running the same test before and after upgrading to nightly:
<img width="1215" alt="image" src="https://github.com/foundry-rs/foundry/assets/4396533/2c806f43-7f92-467c-938b-5be78f01c4a0">

**Comment by mattsse** [comment] 2024-04-05 21:13
most likely caused by https://github.com/foundry-rs/foundry/issues/7569

possibly fixed by https://github.com/foundry-rs/foundry/pull/7572

@klkvr

**Closed** 2024-04-05 22:21 UTC
Labels: T-bug
