### ISSUE TITLE
forge fmt does not make the right line breaks to preserve print width

### ISSUE THREAD

**Issue by d1onys1us** [foundry-rs/foundry#4939] opened 2023-05-14 08:56 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (58a2729 2023-05-14T00:16:25.254741000Z)

### What command(s) is the bug in?

forge fmt

### Operating System

macOS (Apple Silicon)

### Describe the bug

there are a few instances of this but basically running `forge fmt` does not always make the correct choices to format the file according to the single configuration i have set, which you can see here from my `foundry.toml`:
```
[fmt]
line_length = 100
```

to reproduce this bug, you can use this forge version i have specified along and execute `forge fmt` against this file:

```
// SPDX-License-Identifier: MIT
//  _____     _ _         _         _
// |_   _|_ _(_) |_____  | |   __ _| |__ ___
//   | |/ _` | | / / _ \ | |__/ _` | '_ (_-<
//   |_|\__,_|_|_\_\___/ |____\__,_|_.__/__/

pragma solidity ^0.8.18;

import {OwnableUpgradeable} from "@openzeppelin/contracts-upgradeable/access/OwnableUpgradeable.sol";
import {ReentrancyGuardUpgradeable} from
    "@openzeppelin/contracts-upgradeable/security/ReentrancyGuardUpgradeable.sol";
import {AddressResolver} from "./AddressResolver.sol";

/**
 * @dev This abstract contract serves as the base contract for many core
 *      components in this package.
 */
abstract contract EssentialContract is
    ReentrancyGuardUpgradeable,
    OwnableUpgradeable,
    AddressResolver
{
    function _init(address _addressManager) internal virtual override {
        ReentrancyGuardUpgradeable.__ReentrancyGuard_init();
        OwnableUpgradeable.__Ownable_init();
        AddressResolver._init(_addressManager);
    }
}

```

you (should) notice that line 10 is formatted correctly, but line 9 is not. line 9 should have made a line break after `from`, like was done on line 10.

this is just one example, but there are a few files that do not format properly / respect the print width configuration i have. let me know if this is not reproducible or if i can share more examples--thanks!

**Comment by mds1** [comment] 2023-05-15 16:40
Closing in favor of https://github.com/foundry-rs/foundry/issues/4450 since this is expected behavior

Line 9 in this example has a length of 101, just one character over the line length, and line length is not a hard requirement as discussed in As mentioned in https://github.com/foundry-rs/foundry/issues/4021#issuecomment-1448701684. This is common in formatters, e.g. from the prettier [docs](https://prettier.io/docs/en/options.html#print-width):

> Prettier’s printWidth ... is not the hard upper allowed line length limit. It is a way to say to Prettier roughly how long you’d like lines to be. Prettier will make both shorter and longer lines, but generally strive to meet the specified printWidth.

**Closed by mds1** 2023-05-15 16:40 UTC
Labels: T-bug
