### ISSUE TITLE
Contracts Created via CREATE2 from a Factory constructor aren't automatically being verified 

### ISSUE THREAD

**Issue by Elyx0** [foundry-rs/foundry#2518] opened 2022-07-29 17:12 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (2f4dc6c 2022-07-29T00:10:41.103997Z)

### What command(s) is the bug in?

forge script script/PreProxyDeploy.s.sol:Deploy --fork-url $ALCHEMY_APIKEY_POLYGON --private-key $TESTNET_KEY --etherscan-api-key $POLYGONSCAN_APIKEY --verify

### Operating System

macOS (Apple Silicon)

### Describe the bug

Polygon Mainnet.

```sh
forge script script/PreProxyDeploy.s.sol:Deploy --fork-url $ALCHEMY_APIKEY_POLYGON --broadcast --private-key $TESTNET_KEY --etherscan-api-key $POLYGONSCAN_APIKEY --verify
```

```sh
[⠔] Compiling...
No files changed, compilation skipped
Script ran successfully.

== Logs ==
  Factory: 0xc71cf7eb2839d864f356da13ebe22883fcbc9b0f
  Create2 deploy from Factory constructor: 0xbed690780a7d5fd13fe29d3fdcb800733fd62245

==========================

Estimated total gas used for script: 8983932

Estimated amount required: 0.4491966 ETH

==========================

###
Finding wallets for all the necessary addresses...
##
Sending transactions [0 - 0].
⠁ [00:00:00] [###################################################################################################################################################################################################################################] 1/1 txes (0.0s)
Transactions saved to: broadcast/PreProxyDeploy.s.sol/137/run-latest.json

##
Waiting for receipts.
⠉ [00:00:07] [###############################################################################################################################################################################################################################] 1/1 receipts (0.0s)
#####
✅ Hash: 0x01dea60687c3f77f986ed02fb17d548fe7b161d8602182c2189e3010c79e867c
Contract Address: 0xc71cf7eb2839d864f356da13ebe22883fcbc9b0f
Block: 31254493
Paid: 0.34553585 ETH (6910717 gas * 50 gwei)


Transactions saved to: broadcast/PreProxyDeploy.s.sol/137/run-latest.json



==========================

ONCHAIN EXECUTION COMPLETE & SUCCESSFUL. Transaction receipts written to "broadcast/PreProxyDeploy.s.sol/137/run-latest.json"
##
Start Contract Verification
warning: Unknown section [default] found in foundry.toml. This notation for profiles has been deprecated and may result in the profile not being registered in future versions. Please use [profile.default] instead or run `forge config --fix`.
warning: Unknown section [default] found in foundry.toml. This notation for profiles has been deprecated and may result in the profile not being registered in future versions. Please use [profile.default] instead or run `forge config --fix`.

Submitting verification for [contracts/FastLaneFactory.sol:FastLaneFactory] Ok("0xc71Cf7EB2839d864F356dA13ebe22883FCbC9B0F").

Submitting verification for [contracts/FastLaneFactory.sol:FastLaneFactory] Ok("0xc71Cf7EB2839d864F356dA13ebe22883FCbC9B0F").

Transactions saved to: broadcast/PreProxyDeploy.s.sol/137/run-latest.json

Error:
Etherscan could not detect the deployment.
```

I reran the command without `--broadcast` to get the verification going.

```sh
[⠰] Compiling...
No files changed, compilation skipped
##
Start Contract Verification
warning: Unknown section [default] found in foundry.toml. This notation for profiles has been deprecated and may result in the profile not being registered in future versions. Please use [profile.default] instead or run `forge config --fix`.
warning: Unknown section [default] found in foundry.toml. This notation for profiles has been deprecated and may result in the profile not being registered in future versions. Please use [profile.default] instead or run `forge config --fix`.

Submitting verification for [contracts/FastLaneFactory.sol:FastLaneFactory] Ok("0xc71Cf7EB2839d864F356dA13ebe22883FCbC9B0F").
Submitted contract for verification:
	Response: `OK`
	GUID: `somethingsomething`
	URL: https://polygonscan.com/address/0xc71cf7eb2839d864f356da13ebe22883fcbc9b0f
Waiting for verification result...
Contract successfully verified.
```

It did verify the factory but not 0xbed690780a7d5fd13fe29d3fdcb800733fd62245 made from the Factory constructor.

From https://github.com/foundry-rs/foundry/issues/2005 I tried cleaning the cache, and retry with --force but nothing changed.

```sh
[⠑] Solc 0.8.15 finished in 3.00s
Compiler run successful
##
Start Contract Verification
warning: Unknown section [default] found in foundry.toml. This notation for profiles has been deprecated and may result in the profile not being registered in future versions. Please use [profile.default] instead or run `forge config --fix`.
warning: Unknown section [default] found in foundry.toml. This notation for profiles has been deprecated and may result in the profile not being registered in future versions. Please use [profile.default] instead or run `forge config --fix`.

Submitting verification for [contracts/FastLaneFactory.sol:FastLaneFactory] Ok("0xc71Cf7EB2839d864F356dA13ebe22883FCbC9B0F").
Contract source code already verified

Transactions saved to: broadcast/PreProxyDeploy.s.sol/137/run-latest.json
```

Should I move the CREATE2 out of the constructor and call it as a separate `forge script` tx on the factory for it to work?
I still have the `run-` files if needed.

---
Edit: Deploy Script
```solidity
// SPDX-License-Identifier: AGPL-3.0-only
pragma solidity ^0.8.15;

import "forge-std/Test.sol";
import "forge-std/Script.sol";

import {FastLaneFactory} from "contracts/FastLaneFactory.sol";

contract Deploy is Script {
    FastLaneFactory fastlaneFactoryV0;

    function run() public {

        vm.startBroadcast();
        bytes32 salt = bytes32("hello");
        FastLaneFactory FLF = new FastLaneFactory(salt);

        address deployed = FLF.fastlane();
        console2.log(address(FLF));
        console2.log(deployed);
    }

}
```

**Comment by joshieDo** [comment] 2022-07-29 21:35
If i understood correctly, verification of any factory derived contracts are not supported at the moment. It's unrelated to `CREATE2`.

The snippet below would verify successfully.
```
vm.startBroadcast();
...
Test t = new Test{salt: bytes32(uint256(1337))}();
...
```

**Comment by Elyx0** [comment] 2022-07-30 10:43
I think you got it right I didn't read #1999 fully and it seems it was just a CREATE2 directly like your example VS a CREATE2 from another contract. So yeah if your `Test t` would deploy something else during it's creation (or maybe even after?) using CREATE2 it wouldn't get verified.

I'm a bit oblivious on how to do it manually as well through polygonscan, I don't know if just a flattened version would do it.

**Comment by onbjerg** [comment] 2022-07-30 22:57
Flattened version should do it I think. Closing this as a duplicate of https://github.com/foundry-rs/foundry/issues/1893 though since it's the same underlying issue if I understand correctly :)

**Closed by onbjerg** 2022-07-30 22:57 UTC
Labels: T-bug, C-forge, Cmd-forge-script

**Comment by Elyx0** [comment] 2022-08-09 15:32
> If i understood correctly, verification of any factory derived contracts is not supported at the moment. It's unrelated to `CREATE2`.
> 
> The snippet below would verify successfully.
> 
> ```
> vm.startBroadcast();
> ...
> Test t = new Test{salt: bytes32(uint256(1337))}();
> ...
> ```

It didn't work with flatten but maybe it's me I'll retry with a fresh deploy from current commit.
Also I thought EOA can't CREATE2, so your example wouldn't work, or am I missing something?

I'll most likely use @pcaversaccio https://twitter.com/pcaversaccio/status/1555822908441755648 in the future to deploy an UUPS and hope it will pass verification

**Comment by Elyx0** [comment] 2022-08-11 13:58
Okay from @sambacha https://github.com/foundry-rs/foundry/issues/2638 I understand better how it works.
I think it should be made clearer in the doc that this is what's happening when you CREATE2 from a script. (also for vanity & verification)

```rs
    // Prepare CREATE2 Deployer
    let addr = Address::from_str("0x4e59b44847b379578588920ca78fbf26c0b4956c").unwrap();
    let code = hex::decode("7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe03601600081602082378035828234f58015156039578182fd5b8082525050506014600cf3").expect("Could not decode create2 deployer init_code").into();
    api.anvil_set_code(addr, code).await.unwrap();
```
Cause from reading the EIP I would expect it to ignore the salt.
