### ISSUE TITLE
`forge script` panicked

### ISSUE THREAD

**Issue by ryanli-me** [foundry-rs/foundry#2566] opened 2022-08-03 04:06 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (01325bc 2022-08-03T00:04:48.802271Z)

### What command(s) is the bug in?

forge script script/Deploy.s.sol:DeployScript --rpc-url $GOERLI_RPC_URL --private-key $PRIVATE_KEY

### Operating System

macOS (Apple Silicon)

### Describe the bug

The same deployment script that I used two weeks ago broke when I upgraded to the latest foundry today.

```
The application panicked (crashed).
Message:  called `Option::unwrap()` on a `None` value
Location: cli/src/cmd/forge/script/executor.rs:34

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   2: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   3: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   4: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   5: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   6: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   7: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   8: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   9: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  10: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  11: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  12: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  13: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  14: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  15: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  ```

**Comment by onbjerg** [comment] 2022-08-03 10:17
Does your contract use libraries by any chance?

cc @joshieDo it seems that the `into_bytes` unwrap fails, so probably an unlinked artifact somehow. We should also replace the `unwrap` with an `expect` so we have more context

**Comment by joshieDo** [comment] 2022-08-04 19:04
do you have a reproducible repo you can share?

**Comment by ryanli-me** [comment] 2022-08-09 03:07
i'm trying to create a reproducible repo to share. but while i was recreating, i found it might be related to deploying a big contract (23.646 KB) thru a `create2` deployer.

**Comment by ryanli-me** [comment] 2022-08-09 03:08
also a separate issue came up as foundry gets updated in our CI, tests that involves deploying a new contract thru `create2` starts to break while showing a very large gas consumption.

**Comment by ryanli-me** [comment] 2022-08-10 00:40
https://github.com/foundry-rs/foundry/issues/2665

**Comment by onbjerg** [comment] 2022-08-11 18:23
So is this issue the same as #2665? If it is, we should close this one

**Comment by ryanli-me** [comment] 2022-08-16 22:54
sorry for the late reply, this is a separate issue than #2665 . also i couldn't reproduce this in a separate repo.

**Comment by onbjerg** [comment] 2022-08-23 17:02
Closing as can't reproduce, please feel free to reopen with a reproducible example if it's still an issue :smile:

**Closed by onbjerg** 2022-08-23 17:02 UTC
Labels: T-bug, C-forge, Cmd-forge-script
