### ISSUE TITLE
Trying to compile generates unable to resolve import and expected pragma error

### ISSUE THREAD

**Issue by bitcoinmeetups** [foundry-rs/foundry#1740] opened 2022-05-26 06:16 UTC
Trying to compile this:

```solidity
pragma solidity ^0.8.0;

 import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
 import "@openzeppelin/contracts/utils/Counters.sol";

 contract NFT is ERC721 {
     using Counters for Counters.Counter;
     Counters.Counter private currentTokenId;

     constructor() ERC721("NFTTutorial", "NFT") {}

     function mintTo(address recipient)
         public
         returns (uint256)
     {
         currentTokenId.increment();
         uint256 newItemId = currentTokenId.current();
         _safeMint(recipient, newItemId);
         return newItemId;
     }
 }
```

Generates this error message:

```
[⠰] Unable to resolve import: "@openzeppelin/contracts/utils/Counters.sol" with remappings:
        ds-test/=/home/pi/forge6/lib/solmate/lib/ds-test/src/
        forge-std/=/home/pi/forge6/lib/forge-std/src/
        openzeppelin-contracts/=/home/pi/forge6/lib/openzeppelin-contracts/
        solmate/=/home/pi/forge6/lib/solmate/src/
        src/=/home/pi/forge6/src/
[⠔] Compiling 1 files with 0.8.13
[⠒] Solc 0.8.13 finished in 6.85ms
Error:
   0: Compiler run failed
      error[7858]: ParserError: Expected pragma, import directive or contract/interface/library/struct/enum/constant/function definition.
       --> /home/pi/forge6/src/NFT.sol:1:1:
        |
      1 | [ Submit ]// SPDX-License-Identifier: MIT
        | ^


   0:
```

I would like to say something. These tools are a bit difficult to work with. There's a lot of error messages. Thing is, if normal web developers find them difficult to work with then everyone will just switch to solana or something like that. I want ethereum to work but making an ERC-20 and an ERC-721 is not something that should be difficult or generate a lot of error messages. It's something that everyone in the world should be able to do. The platform that can empower everyday users with something like ERC-20 and ERC-721 tools conveniently is the platform that will win the users.
   Maybe someone should just write another unix tool on top of foundry which makes it super easy to make an ERC-20 and an ERC-721, a bit like the gochain/web3 tool. There has been attempts. But timing is a bit of the essence now. Everyone wants to make NFT's these days. Can ethereum and L2 deliver tools that everyone can use?
   Love foundry, just wish there was like one higher-level tool built on top of foundry or even implemented into foundry so everyone can make at least an ERC-20 and an ERC-721 in 5 seconds with unix piping and bash in a one-liner without thinking about imports, error messages, deserialization, underpriced transactions and so on.

**Comment by onbjerg** [comment] 2022-05-27 16:33
For the first error you need to setup your remappings: https://book.getfoundry.sh/projects/dependencies.html#remapping-dependencies

Specifically, you need a remapping that looks like:

```
@openzeppelin/=lib/openzeppelin-contracts/
```

For the second error, it tells you where the error is:

```
Error:
   0: Compiler run failed
      error[7858]: ParserError: Expected pragma, import directive or contract/interface/library/struct/enum/constant/function definition.
       --> /home/pi/forge6/src/NFT.sol:1:1:
        |
      1 | [ Submit ]// SPDX-License-Identifier: MIT
        | ^
```

You have some text that is not valid Solidity in your `NFT.sol` file: it says `[ Submit ]`, but that's not valid.

>I would like to say something. These tools are a bit difficult to work with. There's a lot of error messages. Thing is, if normal web developers find them difficult to work with then everyone will just switch to solana or something like that.

This is a bit off-topic, but I don't think this is true. Solana is also difficult to use since the programs are mostly written in Rust. If you just want to create an ERC20 or ERC721 and deploy it without bothering with code, it's possible to use one of the many available visual tools. For example, OpenZeppelin has one: https://docs.openzeppelin.com/contracts/4.x/wizard

I'm closing this since it's not a bug in Foundry, but feel free to ask for help on Telegram: https://t.me/foundry_support :smile:

**Closed by onbjerg** 2022-05-27 16:33 UTC
