### ISSUE TITLE
misleading error message on failed expectEmit cheat code

### ISSUE THREAD

**Issue by devtooligan** [foundry-rs/foundry#908] opened 2022-03-11 20:28 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (05eb664 2022-03-07T00:08:24.917561+00:00)

### What command(s) is the bug in?

forge test

### Operating System

macOS (M1)

### Describe the bug

After invoking the `expectEmit` cheatcode, if any of the topics or data in the log does not match what was expected, it gives a misleading fail  message, `FAIL. Reason: Expected an emit, but no logs were emitted afterward`   

In my example, I had coded:
```
        vm.expectEmit(true, true, true, true);
        emit Liquidity(maturity, user2, user1, address(0), -INITIAL_BASE, 0, INITIAL_BASE);
```

but I made a mistake, the 3rd parameter shouldve been user2.

I got this:
![Screen Shot 2022-03-11 at 12 17 05 PM](https://user-images.githubusercontent.com/71567643/157956741-a6c979d4-004c-4220-9b78-fbb89d22293c.png)

It would be nice to have a better message - at least something like "topics or data did not match what was expected" or even better if we could show exactly what was wrong, e.g. "Expected 0xabcbcbcbcb for topic2 but got 0x010191911991"

**Comment by mds1** [comment] 2022-03-11 20:35
Seems there may have been an `expectEmit` regression at some point? In https://github.com/gakonst/foundry/issues/592 the failure message was `Reason: Log != expected log`, but I've just confirmed on `forge 0.1.0 (f01d2f7 2022-03-11T00:04:44.960707+00:00)` that when topics don't match I get the same `no logs were emitted` error

**Comment by onbjerg** [comment] 2022-03-12 16:37
Damn the `expectEmit` issues are stacking up. I would love a tracking issue of some sort so I can fix them during/after the REVM port.

FWIW this is probably a regression as @mds1 pointed out. The error message is for when you call `expectEmit` but do not emit a log afterwards, which you seem to be doing.

**Comment by onbjerg** [comment] 2022-07-03 12:36
I can't reproduce this anymore:

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import "forge-std/Test.sol";

contract A {
    event Test(uint256 a);

    function b() external {
        emit Test(1);
    }
}

contract ContractTest is Test {
    event Test(uint256 a);

    function testExample() public {
        A a = new A();

        vm.expectEmit(false, true, false, true);
        emit Test(2);
        a.b();
    }
}
```

Because of this I am going to close this issue: improved error messages for `expectEmit` is tracked in #592. Let me know if this is still an issue for you :smile:

**Closed by onbjerg** 2022-07-03 12:36 UTC
Labels: T-bug, good first issue, Cmd-forge-test, C-forge, A-cheatcodes, P-normal, D-easy

**Comment by kwamentw** [comment] 2024-01-27 22:40
hi @onbjerg,
I am getting this same issue after evoking my `vm.expectEmit()` in my test script, When running the test you can see the values emit, but the error tells you it expected an Emit whilst there was an emit, So i do not know whether foundry can detect the emit or I am just doing something wrong. My test script and error is below ;

error:
```solidity
$ forge test --mt testEmitEventTrycatch -vvvvvvv
[⠰] Compiling...
[⠃] Compiling 2 files with 0.8.20
[⠒] Solc 0.8.20 finished in 1.48s
Compiler run successful!

Running 1 test for test/TestTryCatch.t.sol:TryCatchTest
[FAIL. Reason: Expected an emit, but the call reverted instead. Ensure you're testing the happy path when using the `expectEmit` cheatcode.] testEmitEventTrycatch() (gas: 11742)
Traces:
  [273525] TryCatchTest::setUp() 
    ├─ [218863] → new TryCatchEg@0x5615dEB798BB3E4dFa0139dFa1b3D433Cc23b72f
    │   └─ ← 1093 bytes of code
    └─ ← ()

  [11742] TryCatchTest::testEmitEventTrycatch() 
    ├─ [0] VM::expectEmit() 
    │   └─ ← ()
    ├─ [3701] TryCatchEg::LetsTryCatch(21, 4234) 
    │   ├─ [411] TryCatchEg::Add(21, 4234) [staticcall]
    │   │   └─ ← 4255
    │   ├─ emit ShowResult(result: 4255)
    │   ├─ emit Log(message: Add successful)
    │   └─ ← ()
    └─ ← "Log != expected log"

Test result: FAILED. 0 passed; 1 failed; 0 skipped; finished in 610.74µs
 
Ran 1 test suites: 0 tests passed, 1 failed, 0 skipped (1 total tests)

Failing tests:
Encountered 1 failing test in test/TestTryCatch.t.sol:TryCatchTest
[FAIL. Reason: Expected an emit, but the call reverted instead. Ensure you're testing the happy path when using the `expectEmit` cheatcode.] testEmitEventTrycatch() (gas: 11742)

Encountered a total of 1 failing tests, 0 tests succeeded
```

my test script:
```solidity
    function testEmitEventTrycatch() public {
        vm.expectEmit();
        egoftrycatch.LetsTryCatch(21, 4234);
    }

```
The function I am testing:
```solidity
function LetsTryCatch(uint256 firstDigit, uint256 secondDigit) external {
        try this.Add(firstDigit, secondDigit) returns (uint256 result) {
            emit ShowResult(result);
            emit Log("Add successful");
        } catch Error(string memory errorMessage) {
            emit Log(errorMessage);
            // revert(errorMessage);
        } catch (bytes memory errorData) {
            emit Log(string(errorData));
            // revert(string(errorData));
        }
    }
```

Thanks in advance
