### ISSUE TITLE
Invariant tests function breakdown

### ISSUE THREAD

**Issue by FredCoen** [foundry-rs/foundry#5011] opened 2023-05-23 11:04 UTC
### Component

Forge

### Describe the feature you would like

Invariant testing is very powerful. However I feel like it is hard to be very confident about it without knowing exactly what happened during a run. Right now the output prints runs, calls and reverts. If the distribution is similar across all function calls than that would give me more confidence then if one function only reverted and wasn't part of the simulation through a successful execution at all.

An output with calls + reverts per function would be very helpful

**Comment by PaulRBerg** [comment] 2023-05-23 12:28
Potential duplicate of https://github.com/foundry-rs/foundry/issues/3607 and/ or https://github.com/foundry-rs/foundry/issues/2985.

Also see https://github.com/foundry-rs/foundry/issues/4438.

In the meantime, you can roll your own instrumentation system in Solidity by following @lucas-manuel's example:

https://github.com/lucas-manuel/invariant-examples/blob/ecca083dbda5419c3a6c3d09555938350944ba82/test/WrappedTests.t.sol#L85-L99

And my example here:

https://github.com/foundry-rs/book/pull/760#issuecomment-1415750475

**Comment by FredCoen** [comment] 2023-05-23 12:50
ah thanks @PaulRBerg this is great

**Closed** 2023-05-24 06:45 UTC
Labels: T-feature
