### ISSUE TITLE
Predeploy CreateX contract (like Nick's CREATE2 factory)

### ISSUE THREAD

**Issue by radeksvarz** [foundry-rs/foundry#6660] opened 2023-12-24 01:41 UTC
### Component

Anvil

### Describe the feature you would like

CreateX already deployed on 56 chains: https://github.com/pcaversaccio/createx

Includes Create3 factory. 

Proposal - handle in the similar manner like Nick's contract is handled. 

https://github.com/foundry-rs/foundry/pull/5391

i.e. Include the CreateX factory deployer when starting up anvil by default, and add a new --disable-default-createx-deployer flag to not deploy it. It will also not be deployed if anvil is forking, to properly simulate the conditions of that chain.

**Comment by zerosnacks** [comment] 2024-06-27 12:26
Closing as duplicate of #2638

**Closed by zerosnacks** 2024-06-27 12:26 UTC
Labels: T-feature
