### ISSUE TITLE
bug(`forge script`): `failed to read artifact source` with lib dependencies that include files without a matching contract name

### ISSUE THREAD

**Issue by thedavidmeister** [foundry-rs/foundry#6572] opened 2023-12-11 18:57 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (0ae39ea 2023-12-11T00:27:32.487222000Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

Running `forge script` in a repo that has a dependency with .sol files that don't contain a contract (e.g. the file contains only error definitions or constants) results in an error like 

```
thedavidmeister@davids-iMac polytrade % forge script scripts/OrderBookNPE2.s.sol                
[⠒] Compiling...
No files changed, compilation skipped
Error: 
failed to read artifact source file for `lib/rain.interpreter/src/error/ErrBitwise.sol:ErrBitwise`

Context:
- Error #0: failed to read from "/Users/thedavidmeister/Code/polytrade/src/error/ErrBitwise.sol": No such file or directory (os error 2)
- Error #1: No such file or directory (os error 2)
```

This error can be worked around by adding an empty contract like `contract ErrBitwise {}` in the file that forge is complaining about

**Comment by Alec1017** [comment] 2023-12-14 17:32
+1 on this. Also receiving the same error. Using forge 0.2.0 as well

**Comment by Alec1017** [comment] 2023-12-14 17:49
For context, I was able to fix this error by changing the imports in my dependency contracts.

Switching from `import {Data} from "src/some/path/file.sol"` to `import {Data} from "./some/path/file.sol"` is what fixed it for me.

So im assuming this bug has to do with the way remappings are handled in scripts?

**Comment by mejango** [comment] 2023-12-17 00:54
same. haven't found a fix yet.
import in script is `import {IJBController} from "@juice/interfaces/IJBController.sol";`
remapping is `@juice=lib/juice-buyback/lib/juice-contracts-v4/src/`
error is `Failed to read artifact source file for `lib/juice-buyback/lib/juice-contracts-v4/src/enums/JBApprovalStatus.sol:JBApprovalStatus``

**Comment by thedavidmeister** [comment] 2023-12-17 06:45
afaics the relative paths doesn't make a difference for me because i think i'm already using relative paths everywhere

actually i was seeing the error _without any imports_ and simply trying to run an empty script file

**Comment by crystalbit** [comment] 2024-01-08 00:13
Bump

This is a script where I get the error

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

import "forge-std/Script.sol";

interface IMainFactory {
  function test() external;
}

contract Mint2Script is Script {
  function run() external {
    IMainFactory mainFactory = IMainFactory(0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0); // in anvil
    mainFactory.test();
  }
}
```

I run it as `forge script Mint2Script --rpc-url http://127.0.0.1:8545 -vvvvv`


and get 
```
[⠒] Compiling...
Traces:
  [95968] → new Mint2Script@0x5b73C5498c1E3b4dbA84de0F1833c4a029d90519
    └─ ← 258 bytes of code

  [23909] Mint2Script::run()
    └─ ← EvmError: Revert


Error: 
script failed: <no data>
```

**Comment by mds1** [comment] 2024-01-12 18:56
Also seeing this issue, cc @mattsse, same cause and fix described by @thedavidmeister above

A more complex repro can be found [here](https://github.com/ethereum-optimism/superchain-ops/pull/34/files), notice the empty contracts added in `DeployConfig.s.sol` and `Chains.sol`

**Comment by 0xTimepunk** [comment] 2024-02-14 19:08
No fix?

@gakonst @Evalir

**Comment by script-money** [comment] 2024-03-16 14:01
has some issue

**Comment by alfredo-stonk** [comment] 2024-04-05 18:58
had similar issue running op-stack deployment scripts. ` No matching artifact found`
revert to an early foundry version fixed it
`foundryup -v nightly-5b7e4cb3c882b28f3c32ba580de27ce7381f415a`

**Comment by havi-kim** [comment] 2024-04-06 08:31
I have same issue after founryup.

**Comment by danieliniguezv** [comment] 2024-04-23 06:06
I reinstalled foundry since I believe I had an outdated version from last year and that did the trick. Just head over to installation on foundry book and reinstall and that should help.

**Comment by coffiasd** [comment] 2024-06-04 08:49
> had similar issue running op-stack deployment scripts. ` No matching artifact found` revert to an early foundry version fixed it `foundryup -v nightly-5b7e4cb3c882b28f3c32ba580de27ce7381f415a`

this works for me

**Comment by hungtran2492** [comment] 2024-07-01 11:30
so an annoyable bug. With no fix from the team.

**Comment by viveknath13** [comment] 2024-07-03 05:24
Any time I get an error with artifacts, the first step I take is forge clean followed by forge build

**Comment by zerosnacks** [comment] 2024-07-05 12:58
Hi all, having a cloneable minimal reproduction repo would be greatly appreciated to help narrow this down.

I'm unable to reproduce it with this setup: https://github.com/zerosnacks/foundry-bug-6572-repro I created based on the description of the issue. Any pointers are appreciated @thedavidmeister.

It imports files from https://github.com/zerosnacks/foundry-bug-6572-repro-lib/tree/master/src containing just constants and errors

**Comment by ismailmoazami** [comment] 2024-07-16 12:28
> Any time I get an error with artifacts, the first step I take is forge clean followed by forge build



> Any time I get an error with artifacts, the first step I take is forge clean followed by forge build

This worked for me

**Comment by KPR-V** [comment] 2024-08-21 11:20
> ### Component
> Forge
> 
> ### Have you ensured that all of these are up to date?
> * [x]  Foundry
> * [ ]  Foundryup
> 
> ### What version of Foundry are you on?
> forge 0.2.0 ([0ae39ea](https://github.com/foundry-rs/foundry/commit/0ae39ea8e43e629d67e9373d189f3730019b4bfc) 2023-12-11T00:27:32.487222000Z)
> 
> ### What command(s) is the bug in?
> forge script
> 
> ### Operating System
> macOS (Apple Silicon)
> 
> ### Describe the bug
> Running `forge script` in a repo that has a dependency with .sol files that don't contain a contract (e.g. the file contains only error definitions or constants) results in an error like
> 
> ```
> thedavidmeister@davids-iMac polytrade % forge script scripts/OrderBookNPE2.s.sol                
> [⠒] Compiling...
> No files changed, compilation skipped
> Error: 
> failed to read artifact source file for `lib/rain.interpreter/src/error/ErrBitwise.sol:ErrBitwise`
> 
> Context:
> - Error #0: failed to read from "/Users/thedavidmeister/Code/polytrade/src/error/ErrBitwise.sol": No such file or directory (os error 2)
> - Error #1: No such file or directory (os error 2)
> ```
> 
> This error can be worked around by adding an empty contract like `contract ErrBitwise {}` in the file that forge is complaining about

**Comment by KPR-V** [comment] 2024-08-21 11:21
using 
```bash
forge clean 
```
worked for me

**Comment by Joyosmit** [comment] 2024-08-28 13:40
> Any time I get an error with artifacts, the first step I take is forge clean followed by forge build

Did this and it fixed it for me. Reinstalling foundry didnt

**Comment by FredrikCarlssn** [comment] 2024-08-30 13:36
Noticed the bug popped up when changing pathnames and them sticking but not updating in foundry. 

> Any time I get an error with artifacts, the first step I take is forge clean followed by forge build

This resolved the issue for me

**Comment by henriquemenegaz** [comment] 2024-09-06 13:41
Hi. I had the same problem and solved it by clearing foundry's cache with the following command:
```bash
forge clean
```

See [forge-clean](https://book.getfoundry.sh/reference/forge/forge-clean).

**Comment by zhiqiangxu** [comment] 2024-09-25 11:23
`forge clean` doesn't work for me.

It seems a random bug, but is now always showing up on my machine:

<img width="1551" alt="image" src="https://github.com/user-attachments/assets/e2899f3b-6e8b-4550-9740-3ac7e82a9826">


Clearly the correct path should be `L2/interfaces/ICrossL2Inbox.sol`, but it's looking for `L2/ICrossL2Inbox.sol`.

I've already upgraded to the latest version:

```bash
% forge --version                                                                       
forge 0.2.0 (883bb1c 2024-09-25T00:24:44.893538000Z)
```

**Comment by zhiqiangxu** [comment] 2024-09-25 11:31
> Hi all, having a cloneable minimal reproduction repo would be greatly appreciated to help narrow this down.
> 
> I'm unable to reproduce it with this setup: https://github.com/zerosnacks/foundry-bug-6572-repro I created based on the description of the issue. Any pointers are appreciated @thedavidmeister.
> 
> It imports files from https://github.com/zerosnacks/foundry-bug-6572-repro-lib/tree/master/src containing just constants and errors

@zerosnacks  I can stably reproduce , is there something you'd like me to check for this bug?

**Comment by justefg** [comment] 2024-10-09 11:02
i can confirm `forge clean` didn't work for me either with 0.2.0. unfortunately, i cannot give a minimal reproducible example. this such a bummer though as i'll probably need to use another tool for testing and deployment.

**Comment by Neddie28** [comment] 2024-10-13 23:36
> Any time I get an error with artifacts, the first step I take is forge clean followed by forge build

This worked for me. thanks a lot🙏

**Comment by grandizzy** [comment] 2024-10-24 12:46
@zhiqiangxu could you provide a way to reproduce this issue consistently? thank you!

**Comment by zhiqiangxu** [comment] 2024-10-24 12:50
> @zhiqiangxu could you provide a way to reproduce this issue consistently? thank you!

Sorry I can't,last time when I was debugging from source code, the issue suddenly went away, I guess it's a random bug with cache. That's all I can say.

**Comment by grandizzy** [comment] 2024-10-29 12:37
we're going to close this optimistically as were not able to reproduce it and looks like `forge clean` eventually solves it for all mentioned cases. Please open new ticket with details to reproduce if still occurs. Thank you!

**Closed by grandizzy** 2024-10-29 12:37 UTC
Labels: T-bug, C-forge, Cmd-forge-script, T-to-reproduce
