### ISSUE TITLE
forge coverage for libraries is not updating

### ISSUE THREAD

**Issue by snreynolds** [foundry-rs/foundry#7054] opened 2024-02-08 23:08 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (a5efe4f 2024-02-08T00:16:00.244105000Z)

### What command(s) is the bug in?

forge coverage

### Operating System

macOS (Apple Silicon)

### Describe the bug

I am writing unit tests for some libraries and am getting 0% coverage with forge coverage. Feel free to look at this branch as an example! https://github.com/Uniswap/relayer/pull/57

**Comment by 0xalpharush** [comment] 2024-02-09 01:09
I believe this is a duplicate of https://github.com/foundry-rs/foundry/issues/2567

**Comment by snreynolds** [comment] 2024-02-09 15:11
@0xalpharush 

I moved to using the library explicitly and I'm still not seeing updates in `forge coverage`. See commits here https://github.com/Uniswap/relayer/pull/57

**Comment by superical** [comment] 2024-03-01 14:51
@0xalpharush I'm having a similar issue. I've tried calling my library functions explicitly and still don't see the coverage being updated. Are there other workarounds to this?

**Closed** 2024-03-29 13:34 UTC
Labels: T-bug
