### ISSUE TITLE
forge test hangs forever

### ISSUE THREAD

**Issue by frank20171214** [foundry-rs/foundry#8462] opened 2024-07-17 17:06 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (cb9dfae 2024-07-17T00:18:52.785532000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

<img width="905" alt="image" src="https://github.com/user-attachments/assets/cdbf47c1-6281-4d43-b568-c649f197a58f">

forge test hangs forever with the latest forge version. There is no problem when running the command 1 months ago.
This is the test script file: https://github.com/Mint-Blockchain/Contract-GreenID/blob/main/test/GreenID.t.sol.
it's really depressing that this kind of problem can happen to foundry.

**Comment by grandizzy** [comment] 2024-07-17 17:25
I cannot reproduce this, completes quite fast (only diff I see is the Solc version but don't think that's an issue)

![image](https://github.com/user-attachments/assets/e2bc9b59-cad0-4018-a29c-d0130dcc9b41)

**Comment by underwood2024** [comment] 2024-07-18 01:49
<img width="707" alt="image" src="https://github.com/user-attachments/assets/f9b16e23-7075-4b7d-bfdf-5db647124c2f">
it's always waiting there, that's really strange. Found that this might happen after i ran this script: https://github.com/mintrich/MintRich-Contracts/blob/main/test/MintRich.t.sol
is there anything that may cause this problem for this script ?
Really appreciate your help.

**Comment by underwood2024** [comment] 2024-07-18 01:54
<img width="722" alt="image" src="https://github.com/user-attachments/assets/d2a90f91-bda7-4341-9485-422b3e77059d">

God, it now completed the test, but took 350s. How could this happen ?

**Comment by grandizzy** [comment] 2024-07-18 02:12
hm, try checking processes running on your machine, cpu usage and so  (top)

**Comment by underwood2024** [comment] 2024-07-18 02:16
<img width="960" alt="image" src="https://github.com/user-attachments/assets/79700ce6-758a-43c6-aa60-da6923fcbc6a">

<img width="960" alt="image" src="https://github.com/user-attachments/assets/f89d47ee-3669-4612-9097-b0d1ece4fab0">

everything is just fine

**Comment by grandizzy** [comment] 2024-07-18 02:22
try `RUST_LOG=trace forge test` and check the output, should show where execution is slow

**Comment by underwood2024** [comment] 2024-07-18 02:50
<img width="1136" alt="image" src="https://github.com/user-attachments/assets/9fc4b1b9-356b-4fd7-b292-49fac75d71b5">

 this is the log, what can i get from this

**Comment by grandizzy** [comment] 2024-07-18 02:55
what if `forge cache clean` and `forge clean` before test?

**Comment by grandizzy** [comment] 2024-07-18 03:00
ah, now I notice you run with ffi=true in foundry.toml turn on false and see if better

**Comment by underwood2024** [comment] 2024-07-18 03:01
> what if `forge cache clean` and `forge clean` before test?

<img width="1130" alt="image" src="https://github.com/user-attachments/assets/077d1632-ebe8-456c-bf31-005648ff4af9">
 The same

**Comment by underwood2024** [comment] 2024-07-18 03:03
> ah, now I notice you run with ffi=true in foundry.toml turn on false and see if better

<img width="1144" alt="image" src="https://github.com/user-attachments/assets/8c335266-707b-447a-8d0b-3b7a26a4d55c">

its required for openzeppelin-foundry-upgrades

**Comment by grandizzy** [comment] 2024-07-18 04:06
Pretty sure something related to your machine,  maybe disk is the bottleneck. Try from other machine and see if better

**Comment by underwood2024** [comment] 2024-07-18 05:46
okay, thanks for your kind help

**Comment by grandizzy** [comment] 2024-07-18 05:48
I am going to close this for now, pls reopen if you hit same problem on different envs. thank you

**Closed by grandizzy** 2024-07-18 05:48 UTC
Labels: T-bug

**Comment by meitedaf** [comment] 2024-07-30 02:34
I have the same problem that has been bothering me for a long time. How did you solve it bro?

**Comment by underwood2024** [comment] 2024-08-06 07:42
> I have the same problem that has been bothering me for a long time. How did you solve it bro?

use another computer

**Comment by meitedaf** [comment] 2024-08-06 07:55
> > I have the same problem that has been bothering me for a long time. How did you solve it bro?
> 
> use another computer 

I did solve this problem, you can check at https://github.com/foundry-rs/foundry/issues/8559
