### ISSUE TITLE
Debugger: Memory Allocation Error On Windows When Using --debug Flag in Forge Test

### ISSUE THREAD

**Issue by DamirS09** [foundry-rs/foundry#8384] opened 2024-07-08 09:42 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0

### What command(s) is the bug in?

forge test --match-contract PerformanceSwapUpgraded --debug testUpgradedSwapMode

### Operating System

Windows

### Describe the bug

I am encountering a memory allocation error when attempting to run my Solidity project using Forge with the --debug flag. The error message is as follows:
```
forge test --match-contract PerformanceSwapUpgraded --debug testUpgradedSwapMode
[⠒] Compiling...
[⠰] Compiling 11 files with Solc 0.8.26
[⠔] Solc 0.8.26 finished in 7.19s
Compiler run successful!
memory allocation of 922528 bytes failed
```
### Steps to Reproduce
Run the command **forge test --match-contract PerformanceSwapUpgraded --debug testUpgradedSwapGuideStarMode.**
Observe the memory allocation error during compilation.
System Information
Operating System: **Windows**
RAM: **16 GB**
Solc Version: **0.8.26**
Forge Version: **forge 0.2.0 (1ddea96f 2024-05-20T10:22:21.490868500Z)**
Hardware: Tested on both a _laptop_ and a _desktop_ computer

Troubleshooting Steps Taken
Closed unnecessary applications: Ensured that there is enough free memory by closing other applications.
Restarted the system: Rebooted the system to free up memory.
Increased virtual memory: Configured the Windows page file settings to increase the virtual memory:
Initial size: **16 GB (16384 MB)**
Maximum size: **32 GB (32768 MB)**

Additional Information
Running _forge test without the --debug flag works correctly._
Running _forge build_ also works without any issues.

Despite these steps, the issue persists when using the **--debug** flag. Any assistance or recommendations on how to resolve this memory allocation error would be greatly appreciated. If there are any additional logs or details required, please let me know.

**Comment by DaniPopes** [comment] 2024-07-08 19:24
Are you able to share the code to reproduce this?

**Comment by NikitaZ** [comment] 2024-07-09 11:10
Not yet, we tried creating a simple project with foundry - debugger works fine.

Now we are trying to run a Uniswap-v4-core test to see if that works...

**Comment by NikitaZ** [comment] 2024-07-09 11:33
We just checked out v4-core, commented out line in their tests which tries to call _mkdir() to create .gas-snapshot
and now forge build is stalling, solc is taking forever and its RAM usage is growing (I saw growth from 1.6gb to 1.7gb in a few seconds...)

**Comment by NikitaZ** [comment] 2024-07-09 11:37
```
cd lib/forge-gas-snapshot
PS C:\Users\...\v4-core\lib\forge-gas-snapshot> git status
HEAD detached at 9161f7c
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   src/GasSnapshot.sol

no changes added to commit (use "git add" and/or "git commit -a")

PS C:\Users\...\v4-core\lib\forge-gas-snapshot> git diff
diff --git a/src/GasSnapshot.sol b/src/GasSnapshot.sol
index e2326e2..72e9d51 100644
--- a/src/GasSnapshot.sol
+++ b/src/GasSnapshot.sol
@@ -25,7 +25,7 @@ contract GasSnapshot is Script {
     string private cachedName;

     constructor() {
-        _mkdirp(SNAP_DIR);
+        //  _mkdirp(SNAP_DIR);
         try vm.envBool(CHECK_ENV_VAR) returns (bool _check) {
             check = _check;
         } catch {
```

**Comment by NikitaZ** [comment] 2024-07-09 12:46
This seems to be related to details of the code, we are working on the reproduces, please, stay tuned.
If we pick a random test from v4-core, debugger works (opens) fine.

**Comment by NikitaZ** [comment] 2024-07-09 15:09
Ok, it is not related to v4-core at all!

**Comment by NikitaZ** [comment] 2024-07-09 15:14
Here is a reproducer:
1. created a sample project via `foundry init`
2. add the following test to the 'test' directory
3. run
```forge test --match-contract DebuggerTest --debug test```

**Comment by NikitaZ** [comment] 2024-07-09 15:19
Without debugger it outputs:
```
forge test --match-contract DebuggerTest
[⠊] Compiling...
No files changed, compilation skipped

Ran 1 test for test/DebuggerTest.t.sol:DebuggerTest
[PASS] test() (gas: 71445326)
Suite result: ok. 1 passed; 0 failed; 0 skipped; finished in 33.67ms (32.87ms CPU time)
```

**Comment by NikitaZ** [comment] 2024-07-09 15:20
Actually, this reproducer fails not just on Windows, but on my Mac too...

**Comment by NikitaZ** [comment] 2024-07-09 15:21
It seems that at least some check is missing in the foundry debugger and so it can eat all available memory, instead of just stopping and giving a user-friendly message. Plus it is a bit strange that forge test is capable of running code which forge debugger cannot handle...

**Comment by DaniPopes** [comment] 2024-07-09 15:27
It is not strange at all considering we have to save memory snapshots on each opcode step. If you allocate multiple megabytes of memory, this goes exponential. This never worked in the debugger

**Comment by NikitaZ** [comment] 2024-07-09 15:31
We have a reproducer with
```
[PASS] testSwap() (gas: 50167392)
Suite result: ok. 1 passed; 0 failed; 0 skipped; finished in 187.65ms (186.26ms CPU time)
```
It fails on Windows, but not on MacOS...
Is it worth sharing here?

**Comment by NikitaZ** [comment] 2024-07-09 15:33
> If you allocate multiple MiB of memory in the EVM
are you sure the above code allocates... (its a 'view' function') oh yes, EVM never gives memory back, so it keeps allocating and allocating...

**Comment by NikitaZ** [comment] 2024-07-09 15:36
Maybe it is possible to put some limit on it, so that if it is hit forge users will get a friendly error message instead of an OS failure?

**Comment by NikitaZ** [comment] 2024-07-09 15:36
On MacOS the above snippet fails already with 20000 iterations.

**Comment by NikitaZ** [comment] 2024-07-09 15:38
While debugger works fine with 10000 iterations. (although, it takes quite some time to start).

Thank you for educating us on how the debugger works! We love it! and dream of contributing to it someday when our Rust will mature enough ;-)

**Comment by NikitaZ** [comment] 2024-07-10 06:00
Just for fun, I added `assembly` sections to save and restore free memory pointer at the start and end of the loop interation and memory pressure is now gone!
```
for (salt; salt < 50000; salt++) {
           // save free memory pointer
            assembly {
               fmp := mload(0x40)
            }
            addr = uint256(
                keccak256(
                    abi.encodePacked(
                        bytes1(0xFF),
                        address(this),
                        salt,
                        keccakOfCreationCodeWithArgs
                    )
                )
            );
            if (addr & 0x3FFF == FLAGS) {
                return;
            }
            // restore free memory pointer
            assembly {
               mstore(0x40, fmp)
            }
        }
```

**Comment by zerosnacks** [comment] 2024-07-16 15:47
@DaniPopes can this be marked as `resolved` by the conversation or is there an actionable item?

**Comment by zerosnacks** [comment] 2024-07-16 15:48
Marking as `resolved` by conversation

**Closed by zerosnacks** 2024-07-16 15:48 UTC
Labels: T-bug, Cmd-forge-test, C-forge, A-debugger

**Comment by NikitaZ** [comment] 2024-07-17 18:31
@gakonst I don't think this issue is resolved. At least the debugger should issue some sort of helpful warning in this case.

**Comment by DaniPopes** [comment] 2024-07-17 19:18
We don't know how much memory we're going to use, the best you can do is OOM killer :D
