### ISSUE TITLE
forge docs vs image path

### ISSUE THREAD

**Issue by rafales** [foundry-rs/foundry#4265] opened 2023-02-03 13:02 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (cd7850b 2023-02-01T00:04:58.420758Z)

### What command(s) is the bug in?

forge doc

### Operating System

macOS (Apple Silicon)

### Describe the bug

It seems that "forge doc" copies over README.md in repo root over to `docs/src/README.md`.

Now - I have some diagrams as SVG which I would like for people to be able to see. Sadly this mechanism sabotages any chance of giving it the right URL.

And I can't simply say in root's README.md that docs are available in "docs/src/README.md" because it will be copied over.

This is super unexpected behavior, my first instinct was to provide some basic info in `README.md` and then fill out all information in `docs/src/README.md`, which then got overwritten to my surprise. Thanks to using local history I was able to recover everything, but that was a close call.

**Comment by gakonst** [comment] 2023-02-05 05:12
So we should be checking if a README.md exists and only copy if it doesn't perhaps?

**Comment by rafales** [comment] 2023-02-06 13:56
Which one? The one in the book's directory? Or the one in root's repo? If the repo's root then that already happens.

I'd say don't copy at all as this will always break relative paths, so it doesn't really make sense to do that.

Another approach would be to simply treat `README.md` from repo's root as part of the book, without any copying, but this would highly depend on what you can do with `mdbook` and I'm not sure if that's possible.

**Comment by zerosnacks** [comment] 2024-06-28 14:34
Marking as duplicate of https://github.com/foundry-rs/foundry/issues/4115

**Closed by zerosnacks** 2024-06-28 14:34 UTC
Labels: T-bug, Cmd-forge-doc
