### ISSUE TITLE
EvmError: OutOfGas with vm.pauseGasMetering() enabled

### ISSUE THREAD

**Issue by joejordan** [foundry-rs/foundry#3971] opened 2022-12-27 06:39 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (02cb1c0 2022-12-26T21:26:07.6623747Z)

### Operating System

Windows

### Describe the bug

I have created a repo to replicate the issue here: https://github.com/joejordan/foundry-OutOfGas-error

My use case was that I was attempting to seed an NFT contract upon deploy with some randomized data. This data was to be stored in `bytes` chunks on-chain. Past a certain number of entries to seed, Forge fails with an `EvmError: OutOfGas` error, even when `vm.pauseGasMetering()` is enabled before any gas is used in the script.

You can tweak the variables in [NFT.sol](https://github.com/joejordan/foundry-OutOfGas-error/blob/eefc31ad59abcdad219b50fd040e43ca3dd5135e/src/NFT.sol#L10) to see the script work successfully. If run as-is the script should fail with an OutOfGas error.  More details are included in the [repo comments](https://github.com/joejordan/foundry-OutOfGas-error/blob/eefc31ad59abcdad219b50fd040e43ca3dd5135e/script/NFT.s.sol#L12).

**Comment by JuanCoRo** [comment] 2023-01-18 13:29
Just bumped into this as well. Here's another test to reproduce it. Note that with or without `vm.pauseGasMeter()`, it fails with an `OutOfGas` error at the same iteration: 129053.

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity >=0.6.2 <0.9.0;

import "forge-std/Test.sol";

contract OutOfGas is Test {

    function testOutOfGas() public {
        vm.pauseGasMetering();

        for(uint256 i = 0; i <= 129100; i++){
            console2.log("Run #", i, gasleft());
        }
    }
}
```

**Comment by brockelmore** [comment] 2023-01-20 17:22
Sorry about this. I've started looking into this. Its due to how revm handles the end of a call. i.e. you can see it works *inside* the function:
```haskell
    ├─ [0] console::log(Run #, 129052, 9223372036854751794) [staticcall]
    │   └─ ← ()
    ├─ [0] console::log(Run #, 129053, 9223372036854751794) [staticcall]
    │   └─ ← ()
    └─ ← "EvmError: OutOfGas"
```

but the exiting of the call doesnt work. Will try to get this sorted today

**Comment by brockelmore** [comment] 2023-01-20 18:27
> Just bumped into this as well. Here's another test to reproduce it. Note that with or without `vm.pauseGasMeter()`, it fails with an `OutOfGas` error at the same iteration: 129053.
> 
> ```solidity
> // SPDX-License-Identifier: UNLICENSED
> pragma solidity >=0.6.2 <0.9.0;
> 
> import "forge-std/Test.sol";
> 
> contract OutOfGas is Test {
> 
>     function testOutOfGas() public {
>         vm.pauseGasMetering();
> 
>         for(uint256 i = 0; i <= 129100; i++){
>             console2.log("Run #", i, gasleft());
>         }
>     }
> }
> ```

turns out, this is solidity just being very dumb with memory: 
![IMAGE 2023-01-20 10:21:30](https://user-images.githubusercontent.com/31553173/213776996-e60a2bfa-2834-451c-ac66-98ef582da503.jpg)


adding:
```
memory_limit = 43554432
```

to foundry.toml fixes the above. and should probably open an issue on solc cuz this *really* shouldn't happen.

**Comment by brockelmore** [comment] 2023-01-20 18:53
https://github.com/ethereum/solidity/issues/13885

Creating a solc issue for this. current work around, in your `foundry.toml` add the following line and adjust as needed:
```
memory_limit = 33554432
```

default is 33.5mb, you can bump it up as far as you want

**Comment by brockelmore** [comment] 2023-01-20 19:05
alternatively you can manually memory manage like so:
```solidity
    function testOutOfGas() public {
        vm.pauseGasMetering();

        bytes32 free_mem;
        assembly ("memory-safe") {
            free_mem := mload(0x40)
        }
        for(uint256 i = 0; i <= 129100; i++){
            console2.log("Run #", i, gasleft());
            assembly ("memory-safe") {
                mstore(0x40, free_mem)
            }
        }
    }
```

**Comment by JuanCoRo** [comment] 2023-01-20 20:48
Thank you for debugging this! Will use the `foundry.toml` workaround until the memory leak in loops is fixed. And good to know that second workaround :ok_hand: 
If you don't mind the newb question, how is the image you posted generated?

**Comment by brockelmore** [comment] 2023-01-20 21:21
Not a newb question, i hopped into revm source, adding some debugging prints, and used the patch mechanism in Cargo.toml pointing to a local version of revm

**Comment by JuanCoRo** [comment] 2023-01-20 22:45
Not newb, indeed. Thanks!

**Comment by mds1** [comment] 2023-03-10 19:10
Closing this per the above solutions/workarounds, since there are no issues on the forge side here

**Closed by mds1** 2023-03-10 19:10 UTC
Labels: T-bug, C-forge, A-cheatcodes

**Comment by jdbertron** [comment] 2023-04-12 16:23
That workaround doesn't work for me. The function I'm testing works fine on Goerli, but for some reason, it gets a  "EvmError: OutOfGas" even when I set 
[profile.default]
memory_limit = 1073741824
gas_limit = "18446744073709551615" 
with a         vm.pauseGasMetering();   right before the call.

**Comment by mds1** [comment] 2023-04-12 17:10
Did you try both workarounds (the increased memory limit and the manual memory management)? If so can you open a new issue with steps to reproduce?

**Comment by jdbertron** [comment] 2023-04-12 18:12
Yes, sure. There are two problems with this test. One is that one call hangs forge, I'll file a separate issue. The other is the above.
You can simply clone the repo and run

`forge test --ffi -vvvv -m "testCanRegisterPuzzle"   `

In that test the last 2 calls are problematic. Just comment the one that hangs. 
As I said, I currently have memory_limit = 1073741824
gas_limit = "18446744073709551615"  in my foundry.toml  default profile. 

I shrank it down to 3 puzzles, but the original has 32, which have been working fine on Goerli so far e.g. https://goerli.etherscan.io/tx/0xc2cb33930b4008252cb934dc796a50e9607ec104dd32b64a6e434a6bcc2c5f71

**Comment by drortirosh** [comment] 2023-08-30 07:38
Another workaround, is open a new context with "external" call:
```js
    function thisIsMyTest() public {
        for(uint256 i = 0; i <= 129100; i++){ 
            // "this" is important: you WANT to open a new context (required if inner function is "external")
            this.innerFunction();
        }
    }

    function innerTest() external {
       // put code that wastes memory here. 
       // uses a fresh memory context each time (with the same storage variables)
    }
```

**Comment by varun-doshi** [comment] 2024-06-26 13:46
> That workaround doesn't work for me. The function I'm testing works fine on Goerli, but for some reason, it gets a "EvmError: OutOfGas" even when I set [profile.default] memory_limit = 1073741824 gas_limit = "18446744073709551615" with a vm.pauseGasMetering(); right before the call.

I've been having the same issue and it turns out on increasing the memory, it works. But I'd like to know whats the effect of increasing the memory on the system running the code and what is the maximum value for the `memory_limit` ?
