### ISSUE TITLE
`forge create` and `forge verify-contract` not verifying contracts correctly

### ISSUE THREAD

**Issue by barrutko** [foundry-rs/foundry#6515] opened 2023-12-04 14:56 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (ec3f9bd 2023-09-19T13:46:42.143604000Z)

### What command(s) is the bug in?

forge create; forge verify-contract

### Operating System

macOS (Apple Silicon)

### Describe the bug

**TL;DRL: `forge create` is not verifying contracts on Etherscan (Ethereum Mainnet) and `forge verify-contract` is not verifying contracts on Etherscan (Ethereum Mainnet) without explicit `--compiler-version` setting.**

`forge create` with `--verify` flag always fails on Etherscan (Ethereum Mainnet) despite passing all necessary params. I can't get this to work under any configuration.

`forge verify-contract` falsely reports successful verification, while the verified code would not appear on etherscan. Only explicitly passed `--compiler-version` param specifying the compiler version makes the command actually verify contract.

**All of the details, exact steps and exact configuration can be found in the PoC repo linked below
https://github.com/barrutko/verification-issue-poc**

**Comment by zerosnacks** [comment] 2024-07-05 12:00
Hi @barrutko thank you for your detailed and extensive PoC!

I'm unfortunately unable to reproduce your issue on Holesky. I generally recommend testing on an Ethereum testnet. You can get free testnet ETH for Holesky here: https://cloud.google.com/application/web3/faucet/ethereum/holesky

`ETHERSCAN_API_KEY=<API_KEY> forge create CounterForTestingVerification --rpc-url <RPC_URL> --verify --keystore <KEYSTORE>`

```
No files changed, compilation skipped
Enter keystore password:
Deployer: 0x4dF398704f3aAe761A83289044ab7121bB90c83E
Deployed to: 0xdf8ae039BA5ec4F4F1cC26595912cfA8d3b8e39f
Transaction hash: 0x5a062e21edc347f23bd89d566f484e600360e4b54984c83c9978dede3b298c6b
Starting contract verification...
Waiting for etherscan to detect contract deployment...
Start verifying contract `0xdf8ae039BA5ec4F4F1cC26595912cfA8d3b8e39f` deployed on holesky

Submitting verification for [src/CounterForTestingVerification.sol:CounterForTestingVerification] 0xdf8ae039BA5ec4F4F1cC26595912cfA8d3b8e39f.

Submitting verification for [src/CounterForTestingVerification.sol:CounterForTestingVerification] 0xdf8ae039BA5ec4F4F1cC26595912cfA8d3b8e39f.

Submitting verification for [src/CounterForTestingVerification.sol:CounterForTestingVerification] 0xdf8ae039BA5ec4F4F1cC26595912cfA8d3b8e39f.
Submitted contract for verification:
	Response: `OK`
	GUID: `qaeplzcezbxyehxuhkdahyqtttx8bbqae9gqwj77e7qsazuq9c`
	URL: https://holesky.etherscan.io/address/0xdf8ae039ba5ec4f4f1cc26595912cfa8d3b8e39f
Contract verification status:
Response: `NOTOK`
Details: `Pending in queue`
Contract verification status:
Response: `OK`
Details: `Pass - Verified`
Contract successfully verified
```

Would it be possible for you to re-verify if this is still an issue on your end?

My apologies it has taken so long to get to this ticket

**Comment by zerosnacks** [comment] 2024-07-30 15:19
Optimistically marking this as `resolved` by discussion, feel free to re-open or leave a comment if you are still experiencing issues around this.

**Closed by zerosnacks** 2024-07-30 15:19 UTC
Labels: T-bug, C-forge, Cmd-forge-create, A-verification
