### ISSUE TITLE
bug(`anvil`): block number returned after resetting the fork with a new fork url is wrong

### ISSUE THREAD

**Issue by cvcdyedid** [foundry-rs/foundry#1819] opened 2022-06-02 14:21 UTC
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e0a5372 2022-06-02T00:13:59.438564Z)

### What command(s) is the bug in?

anvil --fork-url https://eth-mainnet.alchemyapi.io/v2/<KEY>

### Operating System

macOS (Apple Silicon)

### Describe the bug

Anvil returns the block number of the previous fork url when resetting the fork with a new URL.

Here is a code to reproduce:
```
import requests
import random

r = requests.post(
	"http://127.0.0.1:1234",
	json={
	    "method": "hardhat_reset",
	    "jsonrpc": "2.0",
	    "id": random.randint(1, 10000),
	    "params":[{"forking":{"jsonRpcUrl":"https://eth-mainnet.alchemyapi.io/v2/<KEY>"}}]
})

r = requests.post(
	"http://127.0.0.1:1234",
	json={
	    "method": "eth_chainId",
	    "jsonrpc": "2.0",
	    "id": random.randint(1, 10000),
})
print(r.json())  # returns 0x1 - mainnet

r = requests.post(
	"http://127.0.0.1:1234",
	json={
	    "method": "eth_blockNumber",
	    "jsonrpc": "2.0",
	    "id": random.randint(1, 10000),
})
print(r.json())  # returns mainnet block

r = requests.post(
	"http://127.0.0.1:1234",
	json={
	    "method": "hardhat_reset",
	    "jsonrpc": "2.0",
	    "id": random.randint(1, 10000),
	    "params":[{"forking":{"jsonRpcUrl":"https://eth-goerli.alchemyapi.io/v2/<KEY>"}}]
})

r = requests.post(
	"http://127.0.0.1:1234",
	json={
	    "method": "eth_chainId",
	    "jsonrpc": "2.0",
	    "id": random.randint(1, 10000),
})
print(r.json())  # returns 0x5 - goerli

r = requests.post(
	"http://127.0.0.1:1234",
	json={
	    "method": "eth_blockNumber",
	    "jsonrpc": "2.0",
	    "id": random.randint(1, 10000),
})
print(r.json())  # returns mainnet block - wrong
```

**Comment by mattsse** [comment] 2022-06-02 14:35
thanks for raising this, 

this is currently a limitation due to the underlying provider, which makes reconnecting to different endpoints difficult. Still, we should implement a workaround that actually allows changing the endpoint.

**Comment by bscNinja** [comment] 2023-07-21 02:34
Any update on this ?

> thanks for raising this,
> 
> this is currently a limitation due to the underlying provider, which makes reconnecting to different endpoints difficult. Still, we should implement a workaround that actually allows changing the endpoint.

**Comment by grandizzy** [comment] 2024-08-27 07:29
I cannot reproduce this with latest anvil, script output from switching between mainnet and sepholia with the same provider shows proper block number:
```
{'jsonrpc': '2.0', 'id': 555, 'result': '0x13a9cad'}
{'jsonrpc': '2.0', 'id': 2613, 'result': '0x6466a4'}
```

going to close it for now, please reopen if you still see an issue. thank you!

**Closed by grandizzy** 2024-08-27 07:29 UTC
Labels: T-bug, C-anvil
