### ISSUE TITLE
forge build fails when contract pragma >=0.8.15 

### ISSUE THREAD

**Issue by sambacha** [foundry-rs/foundry#1991] opened 2022-06-16 11:25 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (2457e5f 2022-06-16T00:04:29.19997Z)

### What command(s) is the bug in?

forge build

### Operating System

macOS (Intel)

### Describe the bug

running `forge build` fails if the contract pragma is 0.8.15

example:
```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.15;

contract Contract {}
```

debug output:
```shell
[⠃] Compiling...2022-06-16T11:16:11.692503Z ERROR ethers_solc::resolver: failed to resolve versions
[⠊] Compiling...
[⠒] Unable to resolve import: "forge-std/Script.sol" with remappings:
        src/=/Users/sbacha/latest-sol/src/
        script/=/Users/sbacha/latest-sol/script/
Error:
   0: Discovered incompatible solidity versions in following
      : script/Contract.s.sol (^0.8.13) imports:
          src/Contract.sol (^0.8.15)
      Discovered incompatible solidity versions in following
      : src/Contract.sol (^0.8.15) imports:

Location:
   cli/src/compile.rs:100

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   2: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   3: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   4: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   5: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   6: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   7: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   8: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   9: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
```

**Comment by sambacha** [comment] 2022-06-16 11:46
additionally here is a reproduction repo

https://github.com/sambacha/foundry-build-bug/pull/1


disabling auto-detect and removing remappings and script as a config field let it build
https://github.com/sambacha/foundry-build-bug/pull/3/commits/1ef999eb3603ca13d040d353ea0b6c2e53975bc7#diff-bac743fe3d899998e32393af53af8cc7d28c89c3d7fabfa48b01361cf8d42d9bR2-L38

note, that ^0.8.13 pragma version is compatible to the compiler directive of having ^0.8.15, >=0.8.15, ~0.8.15

**Comment by sambacha** [comment] 2022-06-17 10:08
> ![963f3c42a12513c03a0ad95265710456](https://user-images.githubusercontent.com/706218/174105819-350376b4-bc0e-4e82-8465-a52f15bb9ddb.png)
> 
> 
> 
> Same here, did `foundryup` before.

I am not getting a checksum error , this is new

**Comment by sambacha** [comment] 2022-06-18 19:01
still an intermittent issue with the latest binary

**Comment by onbjerg** [comment] 2022-06-18 22:30
We're getting the releases from solc's own list on platforms they support, so the issue seems to be upstream? cc @mattsse

**Comment by mattsse** [comment] 2022-06-19 11:22
can't reproduce this on today's nightly and intel mac

can you try removing rm -rf ~/.svm/0.8.15 ?

**Comment by sambacha** [comment] 2022-06-19 11:25
> We're getting the releases from solc's own list on platforms they support, so the issue seems to be upstream? cc @mattsse 
> 
> 
> 
> Edit: https://github.com/foundry-rs/foundry/issues/2003#issuecomment-1158234632

The solidity binary server does have intermittent outages, i have a cache proxy for our CI because of this

**Comment by sambacha** [comment] 2022-06-19 11:27
> can't reproduce this on today's nightly and intel mac
> 
> 
> 
> can you try removing rm -rf ~/.svm/0.8.15 ?   

Will check soon 🙏 thx

**Comment by waynehoover** [comment] 2022-06-19 18:32
I'm getting a similar error, but on a fresh install of forge.

```
❯ forge build
[⠊] Compiling...
[⠃] installing solc version "0.8.15"
[⠊] Failed to install solc 0.8.15: Checksum mismatch for version 0.8.15
Error: 
   0: Checksum mismatch for version 0.8.15
```

**Comment by mattsse** [comment] 2022-06-19 18:42
what's your OS and build?

**Comment by waynehoover** [comment] 2022-06-19 18:45
OS X 12.4
`forge 0.2.0 (e4a2915 2022-06-19T00:05:22.438573Z)`

**Comment by mattsse** [comment] 2022-06-19 18:46
intel or apple silicon?

**Comment by waynehoover** [comment] 2022-06-19 18:47
apple silicon

**Comment by mattsse** [comment] 2022-06-19 18:48
@roynalnaruto looks like we have some issue with the newest M1 native release

**Comment by onbjerg** [comment] 2022-06-24 22:14
Status on this?

**Comment by sambacha** [comment] 2022-06-24 22:18
> Status on this?

working wrt intel latest release

**Comment by mattsse** [comment] 2022-06-25 00:27
two issues fixed since this was opened
* 0.8.15 baked in
* fixed incorrect apple silicon native builds

so closing this

**Closed by mattsse** 2022-06-25 00:27 UTC
Labels: T-bug, C-forge, Cmd-forge-build

**Comment by ebaizel** [comment] 2022-07-05 20:24
What's the fix for this? I just got this on a Mac Intel with build `forge 0.2.0 (f016135 2022-07-04T00:15:02.930499Z)`

**Comment by mattsse** [comment] 2022-07-05 22:27
this should have been resolved, 

can you try again after nuking: `rm -rf ~/.svm/0.8.15`

**Comment by ebaizel** [comment] 2022-07-06 17:07
still fails :/ 

```
➜  hello_foundry (master) ✗ forge --version
forge 0.2.0 (f016135 2022-07-04T00:15:02.930499Z)
➜  hello_foundry (master) ✗ pwd
/Users/damontucker/workspace/git/hello_foundry
➜  hello_foundry (master) ✗ ls
foundry.toml script       src          test
➜  hello_foundry (master) ✗ rm -rf ~/.svm/0.8.15
➜  hello_foundry (master) ✗ forge build
[⠊] Compiling...
[⠒] Unable to resolve import: "forge-std/Script.sol" with remappings:
        src/=/Users/damontucker/workspace/git/hello_foundry/src/
        test/=/Users/damontucker/workspace/git/hello_foundry/test/
        script/=/Users/damontucker/workspace/git/hello_foundry/script/
[⠢] Unable to resolve import: "forge-std/Test.sol" with remappings:
        src/=/Users/damontucker/workspace/git/hello_foundry/src/
        test/=/Users/damontucker/workspace/git/hello_foundry/test/
        script/=/Users/damontucker/workspace/git/hello_foundry/script/
[⠘] installing solc version "0.8.15"
[⠊] Successfully installed solc 0.8.15
[⠒] Compiling 3 files with 0.8.15
[⠢] Solc 0.8.15 finished in 13.83ms
Error:
Compiler run failed
error[6275]: ParserError: Source "forge-std/Script.sol" not found: File not found. Searched the following locations: "/Users/damontucker/workspace/git/hello_foundry".
 --> script/Contract.s.sol:4:1:
  |
4 | import "forge-std/Script.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



error[6275]: ParserError: Source "forge-std/Test.sol" not found: File not found. Searched the following locations: "/Users/baizele/workspace/git/hello_foundry".
 --> test/Contract.t.sol:4:1:
  |
4 | import "forge-std/Test.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^



➜  hello_foundry (master) ✗
```

**Comment by mattsse** [comment] 2022-07-06 18:51
you're liking missing the dependency

**Comment by ebaizel** [comment] 2022-07-06 19:58
Worked after I did that. Thanks!

Created a pr to add this step: https://github.com/foundry-rs/book/pull/422

**Comment by ebaizel** [comment] 2022-07-07 00:38
Closed that above pr as I figured out why it wasn't working for me.

Turns out I have a local git defender check that interferes with forge-std being built. Once I set up the git defender, I was able to successfully install with `forge init hello_foundry --force --no-commit`

**Comment by kaushikc44** [comment] 2023-09-29 19:46
You saved me @ebaizel 🙇🏼 thanks alot

**Comment by MohiniVasisth** [comment] 2023-10-10 13:33
forge script \
> broadcast
[⠊] Compiling...
[⠒] Unable to resolve imports:
      "forge-std/Script.sol" in "C:/Users/hp/Desktop/practice/script\SolveTutorial.sol"
with remappings:
[⠢] Unable to resolve imports:
      "forge-std/Script.sol" in "C:/Users/hp/Desktop/practice/script\SolveTutorial.sol"
with remappings:
[⠆] Unable to resolve imports:
      "forge-std/Script.sol" in "C:/Users/hp/Desktop/practice/script\SolveTutorial.sol"
with remappings:
      
[⠔] Compiling 1 files with 0.8.21
[⠒] Solc 0.8.21 finished in 53.04ms
Error:
Compiler run failed:
Error (6275): Source "forge-std/Script.sol" not found: File not found. Searched the following locations: "/Users/hp/Desktop/practice".
 --> script/SolveTutorial.sol:3:1:
  |
3 | import {Script} from "forge-std/Script.sol";
  | How can I fix this issue.
