### ISSUE TITLE
Enable manually selecting what gets snapshotted by `forge snapshot`

### ISSUE THREAD

**Issue by 0xCLARITY** [foundry-rs/foundry#2944] opened 2022-08-25 18:30 UTC
### Component

Forge

### Describe the feature you would like

Forge snapshot is great, but you often have to write minimal tests of the form `testXGas()` to get accurate gas information about a function instead of just the broad strokes.

You can manually build something akin to `forge snapshot` that measures the gas usage you  actuallywant to measure by littering your test suite with `gasLeft()` calls... but why not build that into forge snapshot?

I'm proposing a cheatcode like `vm.snapshotStart()` which under the hood would call `gasLeft()`, and then another call like `vm.snapshotEnd()` that would call `gasLeft()` again and do the math to determine how much gas had actually been spent. If a test doesn't include `snapshotStart()/snapshotEnd()`, then the current behavior would run.

```solidity
function testExample() external {
  memory bytes[] data = loadDataFromFFI();
  
  vm.snapshotStart();
  contract.functionOne(data);
  vm.snapshotEnd();
}
```

Another fun possibility here would be to have this function take a `tag` argument, since if testing part of a contract requires a lot of setup, it is sometimes easier to write a more robust test with multiple assert statements and function calls. Something rougly like this:

```solidity
function testExampleTwo() external {
    memory bytes[] data = loadDataFromFFI();
  
    vm.snapshotStart("With normal data");
    contract.functionWeCareAbout(data);
    vm.snapshotEnd();
    
    memory bytes[] malformedData = loadMalformedDataFromFFI();
    
    vm.snapshotStart("With malformed data");
    contract.functionWeCareAbout(malformedData);
    vm.snapshotEnd();
}
```

**Comment by mds1** [comment] 2022-08-25 19:16
Does the `--gas-report` flag solve your issue? That gives function-level gas costs

**Comment by onbjerg** [comment] 2022-08-26 08:03
Duplicate of https://github.com/foundry-rs/foundry/issues/2429

**Closed by onbjerg** 2022-08-26 08:03 UTC
Labels: T-feature
