### ISSUE TITLE
Parsing .env fails silently and inconsistently with ZSH and Bash

### ISSUE THREAD

**Issue by espendk** [foundry-rs/foundry#3457] opened 2022-10-05 13:05 UTC
### Component

Forge

### Describe the feature you would like

It would be great if Forge would follow symlinks when reading .env files. Currently, it appears that .env symlinks are ignored.

### Additional context

If I create a symlink to a .env file (eg using `ln -s ../.env .env`) outside of the project folder, then Forge ignores the .env file.
If I instead copy the same file (`cp -s ../.env .env`) into the project folder, Forge reads it. But this means I have multiple copies of my .env file that must be maintained.

**Comment by iFrostizz** [comment] 2022-10-08 19:43
Cannot reproduce, did you sourced the symlinked .env file ?
![image](https://user-images.githubusercontent.com/51274081/194724730-addb53a5-d318-4e47-9cf6-6c03881b7293.png)

**Comment by espendk** [comment] 2022-10-11 08:50
Sorry, further experiments revealed that the problem was caused by the following line in the .env file, not symlinks:

```shell
export PRIVATE_KEY_MNEMONIC=test test test test test test test test test test test junk
```

ZSH and Bash source this without failing and interprets that line as `PRIVATE_KEY_MNEMONIC=test`:

```shell
❯ cat >.env
export PRIVATE_KEY_MNEMONIC=test test test test test test test test test test test junk
❯ source .env
❯ printenv PRIVATE_KEY_MNEMONIC
test
```

Clearly, the above .env file is flawed as there should have been quotes around the mnemonic.
But it would be good if Forge either interpreted .env consistently with shells such as ZSH and Bash or would print an error message instead of failing silently to read the .env file.

**Comment by mattsse** [comment] 2022-10-11 10:04
the [dotenv](https://crates.io/crates/dotenv) dependency we're using has its limitations, this is raised from time to time.

Not a priority to get this fixed at this point, since this would require writing an entirely new parser.

**Comment by zerosnacks** [comment] 2024-08-02 08:06
Marking as `not planned`

**Closed by zerosnacks** 2024-08-02 08:06 UTC
Labels: T-feature, C-forge, P-low
