### ISSUE TITLE
Make `vm.env*` methods to check if ENV exist

### ISSUE THREAD

**Issue by nduchak** [foundry-rs/foundry#3051] opened 2022-08-31 16:50 UTC
Currently, when you try to get env var using `vm` and it does not exist the whole process is crashing with 
```
Location: cli/src/cmd/forge/script/runner.rs:66

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

Make it possible to check if you have specific ENV variable

**Comment by mds1** [comment] 2022-09-02 17:03
You can do something like this as a workaround:

```
bool MY_ENV_VAR = false; // Assign default value.
try vm.envBool("MY_ENV_VAR") returns (bool val) {
  MY_ENV_VAR = val;
} catch {}
```

But perhaps the `vm.env*` cheats should return a tuple of `(bool success, <type> value)` so it can be more easily handled? This could also be done in a forge-std helper too

**Comment by nduchak** [comment] 2022-09-03 18:15
Yes, I am using exactly the same workaround now.

**Comment by 0xYYY** [comment] 2022-09-05 14:34
Is it possible that it's caused by other uncaught error? because with the following `forge test` and `forge script` runs, i can see the correct error message `environment variable not found` reported

`test/Contract.t.sol`:
```solidity
pragma solidity 0.8.10;

import "forge-std/Test.sol";

contract ContractTest is Test {
    function setUp() public {
    }

    function test() public {
        string memory key = "BOOL_VALUE";
        bool output = vm.envBool(key);
    }
}
```
```console
❯ forge test
[⠰] Compiling...
[⠆] Compiling 2 files with 0.8.10
[⠔] Solc 0.8.10 finished in 869.22ms
Compiler run successful (with warnings)
warning[2072]: Warning: Unused local variable.
  --> test/Contract.t.sol:11:9:
   |
11 |         bool output = vm.envBool(key);
   |         ^^^^^^^^^^^

Running 1 test for test/Contract.t.sol:ContractTest
[FAIL. Reason: environment variable not found] test() (gas: 3275)
Test result: FAILED. 0 passed; 1 failed; finished in 671.58µs

Failing tests:
Encountered 1 failing test in test/Contract.t.sol:ContractTest
[FAIL. Reason: environment variable not found] test() (gas: 3275)

Encountered a total of 1 failing tests, 0 tests succeeded
```



`script/Contract.s.sol`:
```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import "forge-std/Script.sol";

contract MyScript is Script {
    function run() external {
        string memory key = "BOOL_VALUE";
        bool output = vm.envBool(key);
    }
}
```
```console
❯ forge script script/Contract.s.sol:MyScript
[⠰] Compiling...
[⠰] Compiling 2 files with 0.8.10
[⠔] Solc 0.8.10 finished in 862.66ms
Compiler run successful (with warnings)
warning[2072]: Warning: Unused local variable.
  --> test/NFT.t.sol:11:9:
   |
11 |         bool output = vm.envBool(key);
   |         ^^^^^^^^^^^



Traces:
  [122071] → new MyScript@"0x5b73…0519"
    └─ ← 499 bytes of code

  [24245] MyScript::run()
    ├─ [0] VM::envBool("BOOL_VALUE")
    │   └─ ← "environment variable not found"
    └─ ← "environment variable not found"


Gas used: 24245
Error:
environment variable not found
```

**Comment by 0xYYY** [comment] 2022-09-06 13:11
also tried `envString` and `envAddress`, also showing the correct error message on my end

**Comment by nduchak** [comment] 2022-09-06 14:10
Ok, so I try it again (after updating foundry), and now it's fails with `Execution reverted: environment variable not found`.
Another thing if you are using `--broadcast` it won't fail with the same error, it's just sad `No onchain transactions generated in script` which is a bit confusing and hard to debug. As you don't know which ENV is missing and why your script is not deploying something...

**Comment by nduchak** [comment] 2022-09-06 20:27
Thank you guys for a quick fix

**Comment by mds1** [comment] 2023-03-09 23:12
There is now `envOr` to use a fallback value when an env var doesn't exist, so closing this

**Closed by mds1** 2023-03-09 23:12 UTC
Labels: Cmd-forge-test, C-forge, A-cheatcodes
