### ISSUE TITLE
Verifying contracts on optimsm doesn't work on Optimism

### ISSUE THREAD

**Issue by FredCoen** [foundry-rs/foundry#1322] opened 2022-04-16 08:02 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (6130af7 2022-04-06T00:04:11.858449+00:00)

### What command(s) is the bug in?

 forge verify-contract

### Operating System

macOS (M1)

### Describe the bug

Trying to verify an optimism contract with:

forge verify-contract --chain-id 69 --num-of-optimizations 1000000 --constructor-args < abi-encoded-args > --compiler-version v0.8.13+commit.abaa5c0e < contract-address > < path:contract > < etherscan-key >

does not work. When verifying the verification I get the message below which is not very telling. Not sure what could be wrong, followed the docs very closely. 

Error: 
   0: Contract verification failed:
      Response: `NOTOK`
      Details: `Fail - Unable to verify`

**Comment by onbjerg** [comment] 2022-04-16 08:04
You're passing an empty `--constructor-args` flag so it thinks your constructor arg is `--compiler-version`

**Comment by mattsse** [comment] 2022-04-16 09:06
if there are no constructor args you can remove `--constructor-args`

**Comment by FredCoen** [comment] 2022-04-16 13:22
sorry guys my bad, didnt want to paste the whole abi encoded args in. But yeah they come after the args flag like this

forge verify-contract --chain-id 69 --num-of-optimizations 1000000 --constructor-args <abi-encoded-args> --compiler-version v0.8.0+commit.c7dfd78e <path:contract?> <etherscan-api-key>

**Comment by onbjerg** [comment] 2022-04-17 00:50
Does `--num-of-optimizations` match what you deployed the contract with using `forge create`?

**Comment by FredCoen** [comment] 2022-04-17 05:33
I deployed it with forge default settings. Do you know how I can check this? I thought this is the default optimization value

**Comment by onbjerg** [comment] 2022-04-17 05:41
The default is 200, see [here](https://book.getfoundry.sh/reference/forge/forge-build.html#the-optimizer)

**Comment by FredCoen** [comment] 2022-04-17 16:08
thanks did that still same behaviour. though i might be using the wrong solc version. I am using the one that I found in the cache folder under artifacts. Is that right?

**Comment by onbjerg** [comment] 2022-04-18 12:47
I'm not entirely sure what you mean - if you run `forge build` it should show you the version used. Then, run `~/.svm/x.y.z/solc-x.y.z --version` (replacing x.y.z with the version number) to get the full version. Finally, look up the actual version on https://etherscan.io/solcversions

It's a bit of an adventure, unfortunately, but we hope to make this a lot easier over time

**Comment by FredCoen** [comment] 2022-04-18 20:33
in the cache folder that gets generated through forge build there is a file called solidity-files-cache in which i found what i think is the compiler version that was used (see screenshot below)
<img width="706" alt="Screenshot 2022-04-18 at 22 28 26" src="https://user-images.githubusercontent.com/43670554/163873000-2f3e9035-0202-47fb-b0ac-88bc00f25cff.png">

The way you recommended yields the same result. So I guess i am using the right compiler version 0.8.13+commit.abaa5c0e

Not sure why the verification isen't working. Should I provide something to reproduce?

**Comment by onbjerg** [comment] 2022-04-18 21:38
Do you add the `v` in front of the compiler version?

Otherwise yes, something to reproduce would be helpful :smile:

**Comment by FredCoen** [comment] 2022-04-19 05:41
yeah yeah i did :) will send something over to reproduce! Thanks

**Comment by FredCoen** [comment] 2022-04-20 12:06
@onbjerg here you go, the README includes the instructions to deploy and verify the way it fails for me. You need an optimism kovan provider and optimistic etherscan key.

https://github.com/FredCoen/cryptotesters-merkle-whitelist-nft

Let me know if I can help in any way

**Comment by onbjerg** [comment] 2022-04-21 19:44
I was able to verify the contract:

```
forge create --rpc-url $ETH_RPC_URL --private-key $PRIVATE_KEY src/ERC721CryptoTesters.sol:ERC721CryptoTesters --constructor-args "test" "test" 0x320d00a7b006cf53ef07d9d44030a767bd2703919199d3373c726f5322a3d7d8 0 0
```

```
forge verify-contract --chain-id 69 --num-of-optimizations 200 --compiler-version v0.8.13+commit.abaa5c0e --constructor-args (cast abi-encode "constructor(string,string,bytes32,bool,bool)" "test" "test" 0x320d00a7b006cf53ef07d9d44030a767bd2703919199d3373c726f5322a3d7d8 0 0) 0x3a3bf482cb19c65e2606d22fa3e8f2b56d248f1c src/ERC721CryptoTesters.sol:ERC721CryptoTester $ETHERSCAN_API_KEY
```

**Comment by FredCoen** [comment] 2022-05-01 14:04
doesn't work for me.. are you sure you verified it? Cause the contract i see in your command is not verified @onbjerg  (https://kovan-optimistic.etherscan.io/address/0x3a3bf482cb19c65e2606d22fa3e8f2b56d248f1c)

**Comment by onbjerg** [comment] 2022-05-02 04:38
Ah, maybe I forgot to run `verify-check`.

**Comment by mattsse** [comment] 2022-05-02 08:36
will debug this on optimism!

**Comment by outdoteth** [comment] 2022-05-02 22:00
I am unable to verify on rinkeby too.

```
forge create --rpc-url <alchemy rinkeby url> --private-key <private key> src/Cally.sol:Cally
```

```
forge verify-contract --chain-id 4 --num-of-optimizations 200 --compiler-version v0.8.13+commit.abaa5c0e  <address>  src/Cally.flattened.sol:Cally <etherscan key>
```

```
forge verify-check --chain-id 4 <guid> <etherscan key>
```

output:

```
Error: 
   0: Contract verification failed:
      Response: `NOTOK`
      Details: `Fail - Unable to verify`
```

(there are no constructor args in my contract either)

**Comment by mattsse** [comment] 2022-05-02 22:05
> src/Cally.flattened.sol

I assume this was flattened first? does this file compiles successfully on its own?

**Comment by outdoteth** [comment] 2022-05-02 22:08
Yes. In either case using Cally.flattened.sol or Cally.sol, both fail.

**Comment by outdoteth** [comment] 2022-05-02 22:28
ah, after updating to the latest version with `foundryup` it works on rinkeby now. I was using a version from early April.

**Comment by mattsse** [comment] 2022-05-02 22:46
@FredCoen @onbjerg 

same problem as on ftm, can verify manually with the same content we send in `forge verify`, it's flaky...

super annoying, not sure what's causing this

**Comment by FredCoen** [comment] 2022-05-03 07:55
by verifying manually you mean trough etherscan ui? i managed to verify with hardhat as well as long as i deploy with hardhat. For some reason when i deploy with forge the verification won't work with hardhat for that contract.. unfortunately i have no idea how to debug this

**Comment by mattsse** [comment] 2022-05-03 08:00
thanks for checking, I'll have a look at both requests

**Comment by mattsse** [comment] 2022-05-03 09:30
> by verifying manually you mean through etherscan ui? I managed to verify with hardhat as well as long as I deploy with hardhat. For some reason when I deploy with forge the verification won't work with hardhat for that contract.. unfortunately, i have no idea how to debug this

still have no idea, why this is failing in the command, the API is also not helpful.
any chance you could dump the working request object that hardhat is sending?

doesn't make much sense why it works manually but the same content fails when send as request...

**Comment by mattsse** [comment] 2022-06-06 18:52
fixed a lot of verify bugs since 
therefore and because op verify tests pass in CI, closing this optimistically

**Closed by mattsse** 2022-06-06 18:52 UTC
Labels: T-bug, C-forge, Cmd-forge-verify
