### ISSUE TITLE
The forge command cannot be used

### ISSUE THREAD

**Issue by Lxy-eth** [foundry-rs/foundry#6169] opened 2023-10-30 15:08 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

0.2.0

### What command(s) is the bug in?

forge

### Operating System

macOS (Apple Silicon)

### Describe the bug

I use the forge command from the terminal to kill the process directly, but cast's does not

**Comment by mattsse** [comment] 2023-10-30 15:55
sorry can you please elaborate, unclear what this means

**Comment by Lxy-eth** [comment] 2023-10-30 19:26
已经解决foundryup是我网络的原因导致下载错误

**Comment by Evalir** [comment] 2023-10-30 21:04
Alright, if I understood correctly the issue is solved. Closing!

**Closed by Evalir** 2023-10-30 21:04 UTC
Labels: T-bug
