### ISSUE TITLE
feat(forge): add `fork_url` as an alias for `eth_rpc_url` in foundry.toml

### ISSUE THREAD

**Issue by OliverNChalk** [foundry-rs/foundry#1414] opened 2022-04-26 01:20 UTC
### Component

Forge

### Brief

A user is able to setup fork scenarios using the following declaration:

```toml
[arbitrum]
eth_rpc_url = "https://rpc.ankr.com/arbitrum"
match_contract = "Saddle"
```

If we want to continue the convention of letting config set CLI options, then it would make sense to alias `fork_url` to `eth_rpc_url`, as shown:
```toml
[arbitrum]
fork_url = "https://rpc.ankr.com/arbitrum"
match_contract = "Saddle"
```

This was prompted after testing the changes in: #1378

### Scope

- Are `eth_rpc_url` in `foundry.toml` and `forge test --fork-url` already equivalent? Is priority given to the command line flag?
- Is it as simple as adding `fork_url` as an alias for `eth_rpc_url`, do we want to reverse the relationship and make `eth_rpc_url` an alias for `fork_url`?

**Comment by onbjerg** [comment] 2022-04-26 13:38
>Are eth_rpc_url in foundty.toml and forge test --fork-url already equivalent? Is priority given to the command line flag?

Yes, and yes.

>Is it as simple as adding fork_url as an alias for eth_rpc_url, do we want to reverse the relationship and make eth_rpc_url an alias for fork_url?

I think it's easier to alias `fork_url` since Cast also depends on `eth_rpc_url`

**Comment by malawadd** [comment] 2022-04-27 13:15
how would I approach this if i wanted to work on this issue

**Comment by onbjerg** [comment] 2022-04-27 17:55
Actually, I think we might not want to create this alias since that would also run all tests in fork mode if `ETH_RPC_URL` is set globally. cc @mds1 for thoughts on this, I know this was not expected behavior when I implemented it the last time

**Comment by mds1** [comment] 2022-04-27 20:59
I'm not sure I totally follow the suggesting aliasing and how it would affect config options/defaults, but:
- Allowing users to specify `fork_url` in the config as an alias for `eth_rpc_url` seems reasonable to me.
- Automatically forking if a `FOUNDRY_FORK_URL` env var is found also seems ok.
- The main thing we want to prevent is: the presence of an `ETH_RPC_URL` env var _should not_ lead to tests forking from that URL. Having a globally defined `ETH_RPC_URL` is common for cast users, so we don't want that to affect tests.

Now that cast supports config files though, I wonder if this alias puts us in a weird spot: I might want tests to not fork, but cast to use e.g. Optimism by specifying an Optimism RPC in the config file's `eth_rpc_url`. AFAIK that is not currently doable because specifying  `eth_rpc_url` will result in tests also forking?

So perhaps we want to decouple the two and have something like this?
- `fork_url` used to determine the network for forge
- `eth_rpc_url` to determine the network for cast, which defaults to `fork_url` if present, and `ETH_RPC_URL` env var if `fork_url` isn't present

**Comment by OliverNChalk** [comment] 2022-05-25 23:21
To second @mds1's comments, the following scenario is currently not supported:

- Specify `eth_rpc_url` in config
- Pass in `--fork-block-number` on command line

In this scenario the following error will be returned:
![image](https://user-images.githubusercontent.com/11343499/170384993-a9cb10f4-1a28-4847-acb0-1d570838cc28.png)

**Comment by onbjerg** [comment] 2022-08-15 18:48
Will close this as this is sort of supported now - you can add RPC URLs in the `[rpc_endpoints]` section of `foundry.toml` and alias one of them to `ETH_RPC_URL`, e.g.:

```toml
[rpc_endpoints]
mainnet = "${ETH_RPC_URL}"
```

I think that should cover this functionality, but please let me know if it didn't quite cover what you were asking for :slightly_smiling_face:

**Closed by onbjerg** 2022-08-15 18:48 UTC
Labels: good first issue, T-feature, C-forge, P-low, D-easy
