### ISSUE TITLE
'Remappings.txt' overlaps with 'Remappings' files in git submodules.

### ISSUE THREAD

**Issue by ESNJS** [foundry-rs/foundry#5054] opened 2023-05-26 16:37 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (33f3fee 2023-05-26T00:03:48.457406188Z)

### What command(s) is the bug in?

forge remappings

### Operating System

Linux

## Description

Note: I installed submodules by using "forge install"
Note: Using VSCode with Docker (Ubuntu)

I have a `remappings.txt` file as follows:

```
src/=src/
ds-test/=lib/forge-std/lib/ds-test/src/
forge-std/=lib/forge-std/src/
v2-core/=lib/v2-core/
v2-periphery/=lib/v2-periphery/
solmate/=lib/solmate/
@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/
@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/
universal-router/=lib/universal-router/
```

When I run the command `forge remappings`, it gives me the following result:

```
@openzeppelin/=lib/universal-router/node_modules/@openzeppelin/
@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/
@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/
@uniswap/=lib/universal-router/node_modules/@uniswap/
ds-test/=lib/forge-std/lib/ds-test/src/
erc4626-tests/=lib/openzeppelin-contracts-upgradeable/lib/erc4626-tests/
forge-std/=lib/forge-std/src/
openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/
openzeppelin-contracts/=lib/openzeppelin-contracts/
openzeppelin/=lib/openzeppelin-contracts-upgradeable/contracts/
permit2/=lib/universal-router/lib/permit2/
solmate/=lib/solmate/
src/=src/
universal-router/=lib/universal-router/
v2-core/=lib/v2-core/
v2-periphery/=lib/v2-periphery/
```

The issue arises because one of the git submodules also contains a `remappings.txt` file and it seems to be being merged with my remappings configuration file. It appears that during compilation it uses the first record that matches the pattern and this is causing my contract to not compile.

Here's the screenshot of the problematic submodule:

![image](https://github.com/foundry-rs/foundry/assets/46317127/2c2a6f6b-697d-47a1-9668-8b1eeced66ae)

and its content:

```
solmate/=lib/solmate/
permit2/=lib/permit2/
forge-std/=lib/forge-std/src/
@openzeppelin/=node_modules/@openzeppelin
@uniswap=node_modules/@uniswap
```

Question: Is there any way to ignore other files that are not in the root folder?

**Comment by mattsse** [comment] 2023-05-26 16:49
what keys are overwritten?
this should just merge them, which I believe it does, looking at the merged list

**Comment by ESNJS** [comment] 2023-05-26 17:20
> what keys are overwritten? this should just merge them, which I believe it does, looking at the merged list

You're correct, the records aren't overwritten, they're merged. I'll modify the error description to reflect this. However, it appears that during compilation it uses the first record that matches the pattern. This was causing my contract to not compile properly.

**Comment by Evalir** [comment] 2023-06-16 05:57
This is intended behavior—this way we can properly resolve all dependencies through merging remappings. Closing for now

**Closed by Evalir** 2023-06-16 05:57 UTC
Labels: T-bug
