### ISSUE TITLE
forge create with constructor args only works if specified before private key

### ISSUE THREAD

**Issue by rayquaza7** [foundry-rs/foundry#770] opened 2022-02-18 23:31 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (590c463 2022-02-18T23:15:29.668765+00:00)

### What command(s) is the bug in?

forge create

### Operating System

macOS (amd)

### Describe the bug

Following the foundry book: [https://onbjerg.github.io/foundry-book/forge/deploying.html?search=forgeup](url)
I tried to deploy a contract to Rinkeby using this command(constructor takes 2 arguments):
`forge create --rpc-url $rpc_url --private-key $pvt_key --constructor-args "x" $admin src/Lootbox.sol:Lootbox` 
and it caused this:
```
error: The following required arguments were not provided:
    <CONTRACT>

USAGE:
    forge create --rpc-url <RPC_URL> --private-key <PRIVATE_KEY> --constructor-args <constructor_args>... <CONTRACT>
```

However, when I do:
`forge create --rpc-url $rpc_url --constructor-args "x" $admin --private-key $pvt_key src/Lootbox.sol:Lootbox` 
i am able to successfully deploy it. 
Interestingly, the forge book specifies to use --private-key after the --constructor-args but `forge create --help` puts it after that.

**Comment by onbjerg** [comment] 2022-02-19 15:22
cc @gakonst this is because of #503 / #473

**Comment by calldata** [comment] 2022-02-26 09:12
This is caused by the `multiple_values = true` dervie attribute for `constructor_args`. As the [doc](https://docs.rs/clap/latest/clap/struct.Arg.html#method.multiple_values) says, there's no more  options allowed to follow `--construct-args`. That is to say the `--contructor-args` option must be the last one for the cmd line.

**Comment by onbjerg** [comment] 2022-08-11 20:09
Closing this since we can't really fix it without requiring people to type `--constructor-args arg1 --constructor-args arg2` which is a lot worse imo

**Closed by onbjerg** 2022-08-11 20:09 UTC
Labels: T-bug, C-forge, P-normal, Cmd-forge-create
