### ISSUE TITLE
A new level of verbosity that shows sstores and sloads in trace

### ISSUE THREAD

**Issue by meetmangukiya** [foundry-rs/foundry#5616] opened 2023-08-12 15:59 UTC
### Component

Forge

### Describe the feature you would like

[openchain](https://openchain.xyz/) style `sstore`s and `sload`s as part of the trace as an additional level of verbosity on traces.
<img width="785" alt="Screenshot" src="https://github.com/foundry-rs/foundry/assets/7620533/127738d3-a248-4a77-8d65-180b4e94f7f5">

**Comment by mds1** [comment] 2023-08-14 03:36
Going to close this as a duplicate of https://github.com/foundry-rs/foundry/issues/3390 which tracks this idea + other trace improvements. Note that you can use the `vm.record` and `vm.accesses` cheats as a partial workaround for now—you lose some ordering info since it returns two separate arrays instead of a single array of both reads+writes, and it doesn't give you values. A good feature request would be to improve `accesses` to return more data if you wanted to open that issue, e.g. return a single array of structs like:

```solidity
struct StorageAccess {
  bool isWrite; // true for SSTORE, false for SLOAD
  bytes32 slot;
  bytes32 previousValue;
  bytes32 newValue; // for SLOAD, this would match previousValue
}
```

**Closed by mds1** 2023-08-14 03:36 UTC
Labels: T-feature
