### ISSUE TITLE
cast send fails when an array is empty

### ISSUE THREAD

**Issue by stephenctw** [foundry-rs/foundry#7209] opened 2024-02-22 09:48 UTC
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (9b73e06 2024-02-22T00:17:39.710060848Z)

### Operating System

None

### Describe the bug

When sending transactions with `cast` where one of the input arguments is empty array, it fails. (The last argument `[]` in the following example)

```
cast send --private-key $PRK --rpc-url "http://127.0.0.1:8545" \
 "0xcafac3dd18ac6c6e92c921884f9e4176737c052c" \ 
 "sealInnerMatchAndCreateInnerTournament((bytes32,bytes32),bytes32,bytes32,bytes32,bytes32[])" \
 '(0x3def69a2d0169048f596c51606ff29055c67cbee528d6eb56dcfec9b93cf3fa0,0x5c67add7c6caf302256adedf7ab114da0acfe870d449a3a489f781d659e8becc)' \
 "0x0000000000000000000000000000000000000000000000000000000000000000" \
 "0x0000000000000000000000000000000000000000000000000000000000000000" \
 "0xee88d4f3801d5299a6b06536f80af3058fc91db68d7f3cfa72f51987f8c08a76" \
 '[]' 2>&1

parser error:
[]
 ^
Invalid string length
```

The same command works with prior version: `forge 0.2.0 (c312c0d 2023-12-22T00:17:24.515645977Z)`

**Comment by zerosnacks** [comment] 2024-07-11 11:24
Unable to reproduce with given setup.

Marking as resolved by https://github.com/alloy-rs/core/pull/548 + https://github.com/alloy-rs/core/pull/547/files

See related comment: https://github.com/foundry-rs/foundry/issues/7280#issuecomment-1971420916

**Closed by zerosnacks** 2024-07-11 11:24 UTC
Labels: T-bug
