### ISSUE TITLE
forge install: Installs development branch and ignores releases

### ISSUE THREAD

**Issue by frangio** [foundry-rs/foundry#401] opened 2022-01-07 21:09 UTC
`forge install openzeppelin/openzeppelin-contracts` installs the master branch of the repository. We consider this a development branch, and request that people use our releases instead. On one hand it's a matter of stability because the master branch may receive breaking changes, but it's also a matter of security. Our release process involves release candidates, an open review period, and a call to participate in the bug bounty, so we discourage using code that hasn't been through this process.

Ideally, for the OpenZeppelin Contracts repository, forge would fetch the tags and install the latest tag (according to semver) that is not a release candidate. This may not be a general enough solution since a git repository is not guaranteed to use tags in this way, and may even only have old tags that don't include the real latest version. There could be a flag to install the latest, but preferably this should be the default behavior for OpenZeppelin Contracts at least.

**Comment by gakonst** [comment] 2022-01-08 10:32
You can install a specific tag by doing `forge install openzeppelin/openzeppelin-contracts@5.0.1`!

**Comment by frangio** [comment] 2022-01-08 22:00
Using git submodules is interesting, and staying close to `git submodule add` is a reasonable design decision, but if people use forge to install their dependencies it becomes a kind of package manager. The concern that I wanted to raise is about the default behavior as a package manager. I don't think the current defaults are good because it potentially installs a development version of the dependency.

How would you feel about forcing users to write a tag or branch name in the argument to `install`?

**Comment by gakonst** [comment] 2022-01-08 22:28
> How would you feel about forcing users to write a tag or branch name in the argument to install?

Definitely not something we want to do 😅

Once we include foundry.toml files we'll explore making our own manifest which allows installing specific versions of libraries! But for now I think we'll stick with the current way it's done

**Comment by onbjerg** [comment] 2022-01-19 21:31
Should we close this given that it is working as intended? Or is there something we need to track in here?

**Comment by mds1** [comment] 2022-01-19 22:09
I do think having `forge install` and `forge update` default to using the latest tag is a good idea, and more in-line with other package managers that users will be familiar with / migrating from. If no tags are found, use the latest main, and have a `--dev` flag to let users choose to use the latest main instead of tags

**Comment by zerosnacks** [comment] 2022-07-20 12:55
I'm having the same issue with the Uniswap V3 repo and the `0.8` branch. 

When I run `forge install` to do the same it does not specify the branch in the `gitmodules` file which causes the clone to fail for others. It also appears to not pick up the branch when running `forge install` when the branch is manually specified in the `gitmodules` file.

**Comment by frangio** [comment] 2022-08-25 20:54
@mattsse Can you clarify if this was implemented? I don't see that this was closed by a PR or commit.

**Comment by frangio** [comment] 2022-11-08 02:27
Folks, I am starting to become concerned by this. Our users are inadvertently using the `master` branch. We do not want people using the development branch, this makes no sense. Please reopen this issue.

**Comment by frangio** [comment] 2022-11-08 17:54
Yeah, that's what I'd like to see:
> defaults to using the latest tag
> --dev flag to choose latest main instead

"Latest" here means among those tags that look like semver (`[v]X.Y.Z`) the one that is highest. There may also be prerelease tags like `vX.Y.Z-beta.0` that should probably be ignored.

**Comment by mattsse** [comment] 2022-11-08 18:08
understood. on it. sorry about the delay.

**Closed** 2022-11-17 06:23 UTC
Labels: T-feature, C-forge, Cmd-forge-pm
