### ISSUE TITLE
Verification exits without warning when importing files from outside of `src` folder

### ISSUE THREAD

**Issue by jordaniza** [foundry-rs/foundry#2808] opened 2022-08-17 07:30 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (ccb9aa5 2022-08-17T00:03:47.513943128Z)

### What command(s) is the bug in?

forge verify

### Operating System

Linux

### Describe the bug

Related to [previous issue on verify](https://github.com/foundry-rs/foundry/issues/2807), it's possible to have a directory setup in foundry using remappings like so:

```
- lib/
- script/
  -- ImportBothContracts.s.sol
- src/
  -- ContractA.sol
- some_other_folder/
  -- ContractB.sol
- remappings.txt
- foundry.toml
```

In our case, we had existing repos, audits, deploy scripts and tests in Brownie but needed access to the contracts, so we have been importing contracts from both our newer repos (written in foundry) and older repos (brownie) into single deploy scripts. This works from a scripting, testing perspective, and works quite nicely using remappings to avoid relative imports, but verification specifically struggles with the setup.

If my script is something like:

```ts
import "../src/MainContractA.sol";
import "../some_other_folder/ContractB.sol";

contract S is Script {
   function run() public {
      new ContractA();
      new ContractB();
   }
}
```
and I run with `forge script .... --verify --etherscan-api-key 1235 --broadcast`

Then I will verify contract A but NOT contract B. 

I am not sure I'd consider this a serious bug, as the forge documentation and foundry.toml ask you to state the source folder. However it is interesting that forge script and forge test work with no problems, and forge verify does not seem to. Instead, it exits verification of Contract B with no messaging. If you ONLY try and deploy Contract B from Script S, you have the issue 2807 where the verification process starts and exits with no indication that it failed to verify.

**Comment by joshieDo** [comment] 2022-08-17 12:26
Unfortunately, I was not able to reproduce this.

I included `some_other_folder/`  inside the project folder: verified ✅ .
I put `some_other_folder/` outside the project folder, and linked it with remappings: verified ✅ .

Did I misunderstand the structure?

Is there a reproducible repo that you can share?

**Comment by jordaniza** [comment] 2022-08-17 12:46
Yeah not a problem, I'll share my old kinda funky setup and see if we can find something interesting, will upload it later today.

**Comment by mds1** [comment] 2023-04-11 21:51
Since (1) @joshieDo was not able to reproduce, (2) we never a repro from @jordaniza, and (3) verification code has changed a lot since to make it more robust, I'm going to close this

**Closed by mds1** 2023-04-11 21:51 UTC
Labels: T-bug, C-forge, Cmd-forge-verify, Cmd-forge-script
