### ISSUE TITLE
Error when using `cast etherscan-source` with `-d` to output souce tree

### ISSUE THREAD

**Issue by wp-lai** [foundry-rs/foundry#2792] opened 2022-08-16 05:31 UTC
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (f817db3 2022-08-16T00:12:12.954668Z)

### What command(s) is the bug in?

cast etherscan-source

### Operating System

macOS (Apple Silicon)

### Describe the bug

Using command
```
cast etherscan-source 0x34d85c9cdeb23fa97cb08333b511ac86e1c4e258 -c mainnet --etherscan-api-key=$ETHERSCAN_API_KEY -d output
```

got error
```
Error:
Read-only file system (os error 30)
```

**Comment by onbjerg** [comment] 2022-08-16 09:28
What directory are you running the command in? The error suggests you are in a folder that is not writeable, e.g. a mounted filesystem or a folder you don't have permission for.

**Comment by joshieDo** [comment] 2022-08-16 09:35
I was able to reproduce it and the error seems to be coming from the `SourceTree`. There's a ... problematic path:

```
        SourceTreeEntry {
            path: "/contracts/main/Land.sol",
            contents: "...
```

**Comment by onbjerg** [comment] 2022-08-16 09:59
Fixed here: https://github.com/gakonst/ethers-rs/pull/1603

**Comment by mattsse** [comment] 2022-08-18 12:48
closing as this will land automatically with next ethers bump

**Closed by mattsse** 2022-08-18 12:48 UTC
Labels: T-bug, C-cast
