### ISSUE TITLE
`cast access-list` throws `intrinsic gas too low` error

### ISSUE THREAD

**Issue by wminshew** [foundry-rs/foundry#3216] opened 2022-09-14 18:30 UTC
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

cast 0.2.0 (a119909 2022-09-14T17:09:21.826942Z)

### What command(s) is the bug in?

cast access-list

### Operating System

macOS (Intel)

### Describe the bug

when I run `cast access-list`, I get an error about intrinsic gas. Should be able to repro w the below command:

```
$ cast access-list --rpc-url mainnet 0x4f509fba9290dbabd0e07bf78cd01d5c7d6814e9 $(cast sig "withdraw()")
Error:(code: -32000, message: failed to apply transaction: 0x53cff0f41c897e189ada4e2a60c284d5ca432b34bf00d873aeb005ac2e75f693 err: intrinsic gas too low: have 0, want 21064, data: None)
```

**Comment by zerosnacks** [comment] 2024-06-26 12:28
Am able to reproduce with `cast access-list --rpc-url $MAINNET_RPC_URL $(cast sig "withdraw()")`, throwing a similar error:

It throws: `server returned an error response: error code -32000: failed to apply transaction: 0xdcf1cd2f26708a35d7686e3367ec8dbb928a93752521f7b4876339770576247f err: intrinsic gas too low: have 21000, want 21064`

**Comment by mattsse** [comment] 2024-06-27 17:00
no, I ran this and this is failing on the eth_createAccessList call itself, looks like a server issue I think

**Comment by zerosnacks** [comment] 2024-08-02 10:56
Looks like an issue with Alchemy, running this with an Infura URL works

```
cast access-list --rpc-url <INFURA_MAINNET_URL> 0x4f509fba9290dbabd0e07bf78cd01d5c7d6814e9 $(cast sig "withdraw()")
```

yields

```
gas used: 41103
access list:
- address: 0xcfBf34d385EA2d5Eb947063b67eA226dcDA3DC38
- address: 0x86d80d18890F694dC75e78703360085140Fa51Fd
- address: 0xF29Ff96aaEa6C9A1fBa851f74737f3c069d4f1a9
- address: 0x2a2C412c440Dfb0E7cae46EFF581e3E26aFd1Cd0
  keys:
    0x0000000000000000000000000000000000000000000000000000000000000000
- address: 0xd9Db270c1B5E3Bd161E8c8503c55cEABeE709552
```

Marking as `resolved` as it is not an issue with `cast`

**Closed by zerosnacks** 2024-08-02 10:56 UTC
Labels: T-bug, C-cast
