### ISSUE TITLE
cast send giving 'eth_sendTransaction.' error  [but works with seth]

### ISSUE THREAD

**Issue by henry-hz** [foundry-rs/foundry#3301] opened 2022-09-21 10:37 UTC
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (074267e 2022-09-21T00:06:00.509051276Z)

### What command(s) is the bug in?

cast send

### Operating System

Linux

### Describe the bug

```
❯ cast send 0x155108834986DA3B498baA5764029598160439cF "addFabs(address,address,address,address)" 0xCA3C09b989682cD5ECbDe4Bd2ED41c49349fA481 0x740836C95C6f3F49CccC65A27331D1f225138c39 0x660428626d4bAc1A7b1c619157e3205dAd540ad1 0xf36F3976f288b2B4903aca8c177efC019b81D88B
Enter keystore password:
Error: 
(code: -32600, message: Unsupported method: eth_sendTransaction. Alchemy does not hold users' private keys. See available methods at https://docs.alchemy.com/alchemy/documentation/apis, data: None)

❯ RUST_LOG=ethers=trace cast send 0x155108834986DA3B498baA5764029598160439cF "addFabs(address,address,address,address)" 0xCA3C09b989682cD5ECbDe4Bd2ED41c49349fA481 0x740836C95C6f3F49CccC65A27331D1f225138c39 0x660428626d4bAc1A7b1c619157e3205dAd540ad1 0xf36F3976f288b2B4903aca8c177efC019b81D88B
2022-09-21T10:28:38.056227Z TRACE rpc{method="eth_chainId" params="null"}: ethers_providers::provider: tx
2022-09-21T10:28:38.792823Z TRACE rpc{method="eth_chainId" params="null"}: ethers_providers::provider: rx="\"0x5\""
Enter keystore password:
2022-09-21T10:28:44.907348Z TRACE rpc{method="eth_getBlockByNumber" params="[\"latest\",false]"}: ethers_providers::provider: tx
2022-09-21T10:28:45.093258Z TRACE rpc{method="eth_getBlockByNumber" params="[\"latest\",false]"}: ethers_providers::provider: rx="{\"hash\":\"0x80bdab8a0bb667350eed668f6ab7831861dd90874a01db184ffb41216ffa5ac8\",\"parentHash\":\"0xf4ca695ec0ce9beb679bc89cb92e548eb43e3874e887358a4f6d413b6a4f6a33\",\"sha3Uncles\":\"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347\",\"miner\":\"0x0000000000000000000000000000000000000000\",\"stateRoot\":\"0x9bc88959cce72df84601ecd42cbc83e3873e2a905b6701726f613c95a245336a\",\"transactionsRoot\":\"0xa746e23f528a9708c8715289df698b8afc9d96aac4c7873ce07c20e697f147c6\",\"receiptsRoot\":\"0xc6a5882af416826a8f9ee4ea2287d1194fa445019cb13bb4e395ffb0297e5990\",\"number\":\"0x7477af\",\"gasUsed\":\"0x4a4d0d\",\"gasLimit\":\"0x1c9c380\",\"extraData\":\"0x\",\"logsBloom\":\"0xc02008040022010421088c00d04202440419e0442210a882d29100020a090110040400424000b22601202040080060090080d840000100404006c2543026f044020864c2c43000000a009048010408620100c0000045100008362380002a01040e02902892008800200800260210482100500820080e26205202803020080000841002a34c9048048055800310117880911081601800040a490048421818620802211000500801408024b4e0008002008124f0000804020012370000103822100a2040060040000000001054000a440418840000010a0313034121024810600c09181102440082008014083000c000300040140200000260800028362e008401\",\"timestamp\":\"0x632ae754\",\"difficulty\":\"0x0\",\"totalDifficulty\":\"0xa4a470\",\"sealFields\":[],\"uncles\":[],\"transactions\":[\"0x1e056096c5b805c2fd145e745fae7e3f29e2db874c1d15d28eeede982608fe12\",\"0x4fd66ef93a5497f44b7eb04a21cfe134886d8de751d31117866c75d3d48c2ae2\",\"0x77a1295e87a451cf9507df6886bce64ccf130f2a9b4eef6e9bb30bb7707acf72\",\"0xe95b3fee58b6d612c53d7e4874753ae8466b788f868f4b76b2883e8b736f61df\",\"0xa7066b60067f6b1e72f11597258713e2b871e9e02ba25deb302b3fc96ea53b47\",\"0x7c94bf0d79aeddf0755a1eb019a1a1ef630304a8db222658945faedde57332c4\",\"0x8b7b7c023e2aa5f9041a2263f6ed03ddf4ae37bd688a8c32b4cf25e3314f9ab3\",\"0x425fb7e4b10c755429418ba755c81180b628a63e0bd8861f78def368c0c05b25\",\"0xfc02644deb643c48b6cc61b534e0510befd90b443144631831f9d6827722db65\",\"0xdbbb26a2f98e1f9518cf0aac2f694cf3bf0efb0144ee3796b99fe28126bc5367\",\"0xd435d1d686e63777985264a64a0bf73f218feba19290470e43f28f119fbdfd0b\",\"0x9c773c760f6a3581fd1f63c6ef66ac872805f66658c7720e0bcd6422dae0ce33\",\"0xe18c967af724e52ddc76ff70249494e1be7d02e34d33ba5b562f822648a84dfd\",\"0xfff7b82cab730326c39fddc9ff91ca9deaa9cf81a7608e657cc9d57f3a90ee19\",\"0xc77c8a8134c4091abed2566592e3461e946f661da291f729ac70eb63ce007130\",\"0x7fa052b9e3be182ed16ad948425c8bd11271a34f9dec998082d2e628846654de\",\"0xde928643e0dd0af36c69a371c608e5ee06b2612befb00481fa093700c793f13f\",\"0x4f1ec6e41da8a5fe3f1af02a68d7922c259861eaa3ab94688c90657dfa64ace4\",\"0x58d95575f41c4f7c6480c5d837f0e0ee40b250d7551245d2f7a0d0eb0c636fd6\",\"0x36fa45440a002e98fe655c4e1162a7e854ad686555ea03d83c2ce7159aac3200\",\"0x3d7bdea67659da970f280d79a57d45d981053c6f7bf6c3ffcde4ef189b9ee04c\",\"0x64a4f9914745d6ec728bd2bbc5c28a70219063dabbfe23304ea16d8062cbe54e\",\"0xdfa67a41c7cbcbf989a9d280c94f533a24a71200612cd3e7d9e8d09c5333ab63\",\"0xd140aa523cabc42451a1e1a1610b74dbccc176f6864a68c60f11f8d1c20fd577\",\"0x9f7e30c9578117334a53ad576e7c585bb8f56224ea2ebcadcbe81a9d7e0b79cf\",\"0x1f8dbf338de95354477feb57ec4fcc31c6cef0d8db4a13bc1f73e0827267feb5\",\"0x7010593d8da3fbe0a15293cc7569834d1efbbb9f22030e910edcbd64c1551012\",\"0x5541887011006acea105aef6c9251427a867487fc01891167b7c8a70a9f61846\",\"0x9592b0b08ecd06a02c4b0d04ccf2240df49a561f9b32a4a451a20efec2706ff1\",\"0x281d8adf330458beedc56ac37cc0cc8871578b27d1eea35bde3687f156e8c4f2\",\"0x25790957840374f7393239354a2e01db0b228a71e4e6a81fc6cdd9f1fd7c4642\",\"0xe9b90900360b875b7fbdee88a7726f2dbc01c28cd8bd253141963c95caf1cecc\",\"0xfde518cb001e8d185e645edefb6063f87de2987f9906115398afdd60a860d8b3\",\"0xe73bcfb841e5e0bcb13728b9c971e93bb323ed1b4e6020f0a79238776b894b02\",\"0x236a8d5e83f58040cf0b0963c341705e8ad5c02cc75f998842c3e840189671b4\",\"0x30339c1a1913392c72fdb281a9b4c13db852f9afbee15a1cc4c25aa6d26aeb0e\",\"0x0c5440ee97c9769292c5769df6dde2df533850134933156738a9f369d141fa17\",\"0xbe45b15e5a011521647de4e87d6f67e852dd88855887eeebccee38d1185c7e23\"],\"size\":\"0x2d48\",\"mixHash\":\"0xa0fd04caf6e848a9915024a22a4fae5408147be62d5cdaf8ae8be287818b7d82\",\"nonce\":\"0x0000000000000000\",\"baseFeePerGas\":\"0x12\"}"
2022-09-21T10:28:45.093579Z TRACE rpc{method="eth_feeHistory" params="[\"0xa\",\"latest\",[5.0]]"}: ethers_providers::provider: tx
2022-09-21T10:28:45.284825Z TRACE rpc{method="eth_feeHistory" params="[\"0xa\",\"latest\",[5.0]]"}: ethers_providers::provider: rx="{\"baseFeePerGas\":[\"0x11\",\"0x12\",\"0x11\",\"0x11\",\"0x10\",\"0x11\",\"0x10\",\"0x10\",\"0x11\",\"0x12\",\"0x11\"],\"gasUsedRatio\":[0.9671262666666668,0.10547376666666666,0.4685046333333333,0.11634546666666666,0.5702652666666667,0.2141802,0.2844761,0.5178748666666667,0.5061598333333334,0.16231296666666667],\"oldestBlock\":\"0x7477a6\",\"reward\":[[\"0x5a0\"],[\"0xb50\"],[\"0x5a1\"],[\"0x5a3\"],[\"0x5f5e100\"],[\"0x787\"],[\"0xb54\"],[\"0x788\"],[\"0x59682f00\"],[\"0x5a0\"]]}"
2022-09-21T10:28:45.284987Z TRACE rpc{method="eth_estimateGas" params="[{\"accessList\":[],\"data\":\"0xc3536e3b000000000000000000000000ca3c09b989682cd5ecbde4bd2ed41c49349fa481000000000000000000000000740836c95c6f3f49cccc65a27331d1f225138c39000000000000000000000000660428626d4bac1a7b1c619157e3205dad540ad1000000000000000000000000f36f3976f288b2b4903aca8c177efc019b81d88b\",\"from\":\"0xcb7d8a80c3d7d3ebd7fbd0fa6b644c8a536c9269\",\"maxFeePerGas\":\"0xb2d05e24\",\"maxPriorityFeePerGas\":\"0xb2d05e00\",\"to\":\"0x155108834986da3b498baa5764029598160439cf\",\"type\":\"0x02\"}]"}: ethers_providers::provider: tx
2022-09-21T10:28:45.521432Z TRACE rpc{method="eth_estimateGas" params="[{\"accessList\":[],\"data\":\"0xc3536e3b000000000000000000000000ca3c09b989682cd5ecbde4bd2ed41c49349fa481000000000000000000000000740836c95c6f3f49cccc65a27331d1f225138c39000000000000000000000000660428626d4bac1a7b1c619157e3205dad540ad1000000000000000000000000f36f3976f288b2b4903aca8c177efc019b81d88b\",\"from\":\"0xcb7d8a80c3d7d3ebd7fbd0fa6b644c8a536c9269\",\"maxFeePerGas\":\"0xb2d05e24\",\"maxPriorityFeePerGas\":\"0xb2d05e00\",\"to\":\"0x155108834986da3b498baa5764029598160439cf\",\"type\":\"0x02\"}]"}: ethers_providers::provider: rx="\"0x1bcfa\""
2022-09-21T10:28:45.521543Z TRACE rpc{method="eth_sendTransaction" params="[{\"type\":\"0x02\",\"from\":\"0xcb7d8a80c3d7d3ebd7fbd0fa6b644c8a536c9269\",\"to\":\"0x155108834986da3b498baa5764029598160439cf\",\"gas\":\"0x1bcfa\",\"data\":\"0xc3536e3b000000000000000000000000ca3c09b989682cd5ecbde4bd2ed41c49349fa481000000000000000000000000740836c95c6f3f49cccc65a27331d1f225138c39000000000000000000000000660428626d4bac1a7b1c619157e3205dad540ad1000000000000000000000000f36f3976f288b2b4903aca8c177efc019b81d88b\",\"accessList\":[],\"maxPriorityFeePerGas\":\"0xb2d05e00\",\"maxFeePerGas\":\"0xb2d05e24\"}]"}: ethers_providers::provider: tx
2022-09-21T10:28:46.019700Z TRACE rpc{method="eth_sendTransaction" params="[{\"type\":\"0x02\",\"from\":\"0xcb7d8a80c3d7d3ebd7fbd0fa6b644c8a536c9269\",\"to\":\"0x155108834986da3b498baa5764029598160439cf\",\"gas\":\"0x1bcfa\",\"data\":\"0xc3536e3b000000000000000000000000ca3c09b989682cd5ecbde4bd2ed41c49349fa481000000000000000000000000740836c95c6f3f49cccc65a27331d1f225138c39000000000000000000000000660428626d4bac1a7b1c619157e3205dad540ad1000000000000000000000000f36f3976f288b2b4903aca8c177efc019b81d88b\",\"accessList\":[],\"maxPriorityFeePerGas\":\"0xb2d05e00\",\"maxFeePerGas\":\"0xb2d05e24\"}]"}: ethers_providers::transports::retry: should not retry err=JsonRpcClientError(JsonRpcError(JsonRpcError { code: -32600, message: "Unsupported method: eth_sendTransaction. Alchemy does not hold users' private keys. See available methods at https://docs.alchemy.com/alchemy/documentation/apis", data: None }))
Error: 
(code: -32600, message: Unsupported method: eth_sendTransaction. Alchemy does not hold users' private keys. See available methods at https://docs.alchemy.com/alchemy/documentation/apis, data: None)

❯ seth send 0x155108834986DA3B498baA5764029598160439cF "addFabs(address,address,address,address)" 0xCA3C09b989682cD5ECbDe4Bd2ED41c49349fA481 0x740836C95C6f3F49CccC65A27331D1f225138c39 0x660428626d4bAc1A7b1c619157e3205dAd540ad1 0xf36F3976f288b2B4903aca8c177efC019b81D88B
seth-send: warning: `ETH_GAS' not set; using default gas amount
seth-send: Published transaction with 132 bytes of calldata.
seth-send: 0xf5437851dde07f63b0d6e2697a591e6a3de9bdd32caddd3a96942b4ed7dd5649
seth-send: Waiting for transaction receipt......................
seth-send: Transaction included in block 7632823.

```

**Comment by mattsse** [comment] 2022-09-21 13:15
you didn't provide a private key or wallet info, in which case cast send falls back to `eth_sendTransaction` and assumes the node has unlocked accounts.

we need to improve the error here and issue a warning in this case

**Comment by EdNoepel** [comment] 2023-06-06 13:42
Note this error might also mean you have entered the wrong password to unlock your keystore.

**Comment by zerosnacks** [comment] 2024-06-26 13:07
Marking as resolved as the implementation is working as intended

**Closed by zerosnacks** 2024-06-26 13:07 UTC
Labels: T-bug, C-cast
