### ISSUE TITLE
Option to remove scientific notation from cast calls

### ISSUE THREAD

**Issue by jordaniza** [foundry-rs/foundry#6982] opened 2024-02-01 07:25 UTC
Up until recently, cast call would return just the return data. Now a separate value is returned if the return type is specified as uint256. 

I can parse this quite happily with shell commands but it's an extra headache and has broken all my scripts. Moreover the behaviour is not consistent, if you don't decode the return data, you get one value. 

It would be great to make this either:

- not the default - developers can parse big numbers themselves
- opt out with a flag - breaking change but otherwise doesn't introduce new parsing logic.

**Comment by mds1** [comment] 2024-02-01 14:14
Closing as duplicate of https://github.com/foundry-rs/foundry/issues/6598, feel free to add any thoughts to that discussion

Also related to https://github.com/foundry-rs/foundry/issues/6600

**Closed by mds1** 2024-02-01 14:14 UTC
