### ISSUE TITLE
Out of Gas Error

### ISSUE THREAD

**Issue by mergd** [foundry-rs/foundry#5785] opened 2023-09-05 22:45 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (0f530f2 2023-09-05T00:25:20.448586000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

The following code with the unchecked iterator runs into an `out of gas` issue, but moving iterator into the for loop causes the execution to be fine.

Another issue is that this loop also causes foundry to run forever if a `--gas-limit` isn't specified. This isn't an infinite loop so it shouldn't be an issue at all.

```Solidity
        for (uint256 i = 0; i < _tokenIds.length;) {
            uint256 _tokenId = _tokenIds[i];
            if (_array[i] == 0) continue; // Skip erroneous slashes
            uint256 _votes = balanceOf[_tokenId].votes;
            // Remove
            if (_votes == 1 || _votes < _slash[i]) {
                delete stakes[_tokenId];
            } else {
                balanceOf[_tokenId].votes -= _slash[i];
            }
            console2.log("gas", i, gasleft());

            unchecked {
                i++;
            }
        }
```
For the log: the last log before it reverts is     │   ├─ [0] console::log(gas1, 25671984 [2.567e7]) [staticcall] – indicating that it still has a great deal of gas before running out of gas.

The change:
```Solidity
        for (uint256 i = 0; i < _tokenIds.length; i++) {
< Contract logic here />
}

```

**Comment by Evalir** [comment] 2023-12-18 18:01
Closing as duplicate of other several out of gas errors which seem to be coming from a different source.

**Closed by Evalir** 2023-12-18 18:01 UTC
Labels: T-bug
