### ISSUE TITLE
feat(`debugger`): should be able to dump buffers (or even entire state) to disk by keypress

### ISSUE THREAD

**Issue by emo-eth** [foundry-rs/foundry#7112] opened 2024-02-13 22:54 UTC
### Component

Forge

### Describe the feature you would like

It's currently not possible to copy or more closely inspect memory/calldata/returndata; it would nice to be able to dump them to disk to inspect more easily for eg formatting errors. It may even be nice to dump the entire EVM state – but dumping buffers seems like a good first step.

**Comment by zerosnacks** [comment] 2024-10-03 12:10
Hi @emo-eth, going to mark this as duplicate of https://github.com/foundry-rs/foundry/pull/7375 

Trying to get the `press-key-to-dump` functionality of https://github.com/foundry-rs/foundry/pull/7135 included in that PR

**Comment by zerosnacks** [comment] 2024-10-04 09:13
Re-opening as it won't be included in #7135

**Closed** 2024-10-23 10:38 UTC
Labels: T-feature, A-debugger
