### ISSUE TITLE
Allow user to disable address-shortening in  `forge test / script` traces

### ISSUE THREAD

**Issue by ckoopmann** [foundry-rs/foundry#2973] opened 2022-08-27 06:52 UTC
### Component

Forge

### Describe the feature you would like

# Current Behaviour
When displaying method calls in the traces of forge tests / scripts currently the contract address is shortened to only show the first / last two bytes with the rest redacted / replaced by three dots:
i.e.  `0xc02a...6cc2:withdraw` instead of `0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2:withdraw`.

Afaik there is no way to avoid this and this happens even at the highest verbosity level `-vvvvv`.
This makes it impossible to copy the addresses and paste it into a blockexplorer for example.

# Proposed Behaviour

When the user specifies the highest verbosity level `-vvvvv` show the full address without redaction. 

Alternatively add an additional argument `--show-full-addresses` to control this behaviour independently of the general verbosity setting.

**Comment by ckoopmann** [comment] 2022-08-27 07:25
Apparently already mentioned / discussed here:
https://github.com/foundry-rs/foundry/pull/2064

**Comment by onbjerg** [comment] 2022-08-27 21:24
Essentially a duplicate of #2674

**Closed by onbjerg** 2022-08-27 21:24 UTC
Labels: T-feature
