### ISSUE TITLE
`forge coverage` fails with `Stack too deep` while build is successful

### ISSUE THREAD

**Issue by Lolshh** [foundry-rs/foundry#3873] opened 2022-12-11 13:36 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e9f274d 2022-12-11T00:04:59.790449Z)

### What command(s) is the bug in?

forge coverage

### Operating System

macOS (Apple Silicon)

### Describe the bug

Hi, I am facing an issue when running forge coverage as it tells me the following "CompilerError: Stack too deep".
I already checked #3527 and doesn't really help this case.
Indeed --via-ir doesn't help because of the AST.

The weird part is that when I run forge build everything works fine.

Does anyone have an idea of how to solve this issue ?

**Comment by AlbertoCentonze** [comment] 2022-12-12 19:34
Same issue here, I would suggest updating the title since it doesn't describe the problem

**Comment by PaulRBerg** [comment] 2023-02-07 14:27
Duplicate of #3357.

**Comment by onbjerg** [comment] 2023-02-25 01:37
Closing as per above

**Closed by onbjerg** 2023-02-25 01:37 UTC
Labels: T-bug, C-forge, Cmd-forge-coverage
