### ISSUE TITLE
failed assertions in `setUp` do not fail the test, even if the test fails

### ISSUE THREAD

**Issue by mds1** [foundry-rs/foundry#1291] opened 2022-04-13 12:56 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (64087b5 2022-04-13T00:05:01.629608+00:00)

### What command(s) is the bug in?

forge test

### Operating System

macOS (amd)

### Describe the bug

The below test should fail for two reasons: First because the assertions in setup fail, and again because the assertion in `testSetUpFailure` fails. However `forge test -m testSetUpFailure` shows this test as passing

```solidity
contract SetUpFailureTest is DSTest {
  function setUp() public {
    assertTrue(false);
  }

  function testSetUpFailure() public {
    assertTrue(false);
  }
}

```

Below is a table of what currently happens for the four combinations you can have above, vs. what I'd expect to happen. You can see the problems are from when assertions in `setUp` fail. 

| setUp             | testSetUpFailure  | Current Test Result | Expected Test Result | Summary |
| ----------------- | ----------------- | ------------------- | -------------------- | ------- |
| `assertTrue(true)`  | `assertTrue(true) ` | PASS                | PASS                 | ✅       |
| `assertTrue(true)`  | `assertTrue(false)` | FAIL                | FAIL                 | ✅       |
| `assertTrue(false)` | `assertTrue(true)`  | PASS                | FAIL                 | ❌       |
| `assertTrue(false)` | `assertTrue(false)` | PASS                | FAIL                 | ❌       |

**Comment by onbjerg** [comment] 2022-04-13 13:56
I don't think this was the behavior pre-REVM as well. The issue is that we don't call `Executor::is_success` after calling `setUp`.

I'm not entirely sure it makes sense to have assertions in `setUp`, but I don't have a strong opinion here - I just wonder if the same should be true for constructors as well, then.

Currently `Executor::is_success` requires a state changeset, but we don't have one since both deploying (which runs the constructor) and calling `setUp` commit that changeset directly to the underlying database. So, two paths forward:

- We can refactor `Executor` such that we only really have the `call_raw/call` variants that return state changesets - `call_committing/call_raw_committing` would then just be very thin wrappers around these that also call `db.commit(changeset)`. This cleans up the executor code a bit, and seems like the right path forward. I think I did attempt this at some point, but there was some annoyances in some other parts of the code so I shelved it to get REVM over the line.
- We can create a new `Executor::is_success` variant that calls the db directly.. This seems like double work and I'd not prefer this solution

**Comment by onbjerg** [comment] 2022-04-13 14:32
>I think a warning or disallowing it would be totally fine, but I agree that seems difficult, given that assertions can have arbitrary function signatures and we won't know they're assertions until they call fail().
>
>One other solution is to lazily warn users: if we detect a call with fail's selector in setUp, only then do we display a warning that says "Assertions in setUp do not behave properly, please move them into a unit test or use require statements instead".

The primary issue with this is that we can only really know if we implement one of the other solutions I outlined *or* require that tests always run with tracing on, so not super nice.

I think your use for assertions in `setUp` makes sense now that you outline it - I guess I would recommend that we go the first route. If we go that route, then we can always return a state changeset, regardless of if we committed it to DB or not, and it also (as a bonus) cleans up the code.

I still think it's worth considering constructors here, since we do support calling cheatcodes in constructors, so at the very least we should consider if a failing assertion in the constructor causes a panic or something :sweat_smile:

**Comment by mds1** [comment] 2022-04-13 14:36
> The primary issue with this is that we can only really know if we implement one of the other solutions I outlined or require that tests always run with tracing on, so not super nice.

Ah, did not realize that, so agreed that does not sound ideal. The first route sounds good to me then, pending the constructor decision below

> I still think it's worth considering constructors here, since we do support calling cheatcodes in constructors, so at the very least we should consider if a failing assertion in the constructor causes a panic or something 😅

I'm not sure I follow this suggestion. Are you saying migrate away from `setUp` entirely and use constructors instead? Or call `setUp()` in your constructor then run the assertions in the constructor?

**Comment by mds1** [comment] 2022-04-13 14:52
I see, yes I agree with that!

**Comment by gakonst** [comment] 2022-08-29 16:43
There's also a world where we just #wontfix this and give a 'best practice' of not including assertions in setUp?

**Comment by mds1** [comment] 2022-08-29 16:52
Yea I'm ok with that, I don't think this is a big issue. 

A bit tangential, but wonder if we should also just get rid of `setUp` for 1.0.0 and just use the constructor directly? Right now both are supported I believe, and afaik the only reason we `setUp` is legacy leftover from dapptools

**Comment by gakonst** [comment] 2022-08-29 17:01
> A bit tangential, but wonder if we should also just get rid of setUp for 1.0.0 and just use the constructor directly? Right now both are supported I believe, and afaik the only reason we setUp is legacy leftover from dapptools

Supportive of this. Probably will simplify our codebase too.

**Comment by mattsse** [comment] 2022-08-30 12:02
supportive of this as well!

**Comment by rkrasiuk** [comment] 2022-09-17 20:28
fyi, picked this up & started refactoring executor today

**Comment by gakonst** [comment] 2022-09-18 01:31
Ugh I think we discussed this separately and decided that it'd be too big of a breaking change for no clear benefit?

**Comment by rkrasiuk** [comment] 2022-09-18 04:09
@gakonst to be clear - i've started refactoring & cleaning up the executor according to @onbjerg's original comment about returning changesets in call_raw/call_raw_committing

**Closed** 2022-09-18 21:30 UTC
Labels: T-bug, A-evm, Cmd-forge-test, C-forge, P-low, D-average
