### ISSUE TITLE
Allow parameterization of tests across a predefined array of values

### ISSUE THREAD

**Issue by ckoopmann** [foundry-rs/foundry#2329] opened 2022-07-15 08:02 UTC
### Component

Forge

### Describe the feature you would like

It'd be great if the user was able to run a test or even a whole collection of tests across a chosen set of input values.
(Note that this is different from fuzz testing across random values).

Example use cases:
- Run tests across different address inputs.  (Different Token Addresses, Contract Owner vs. non-owner, Contract vs. EOA etc)
- Run a set of tests both before and after the upgrade of a contract

The feature would ideally allow the user to:
- [ ] Parameterize a single test
- [ ] Parameterize a whole test collection (contract)
- [ ] Specify multiple parameters in which case the test(-collection) will be run for all combinations
- [ ] Set the values to parameterize  dynamically (for example in the `setUp` method) (optional)
- [ ] Pass filter arguments to `forge test` to only run a subset of the originally specified parameter space (similar to `--match-test`

### Additional context

One testing library that does this fairly well imo is pytest (see [here](https://docs.pytest.org/en/6.2.x/parametrize.html)).

**Comment by onbjerg** [comment] 2022-07-15 21:41
I'd argue this is a duplicate of https://github.com/foundry-rs/foundry/issues/858, so I'm closing this as such - please let me know if the feature outlined in #858 is not the same as this :smile:

**Closed by onbjerg** 2022-07-15 21:41 UTC
Labels: T-feature
