### ISSUE TITLE
Add Alpine support for Foundry binaries

### ISSUE THREAD

**Issue by susruth** [foundry-rs/foundry#8498] opened 2024-07-23 10:17 UTC
### Component

Forge, Cast, Anvil, Chisel

### Describe the feature you would like

When attempting to run a Docker image that got build using **Alpine**, I encounter an error indicating that `anvil` is not found. However, using the same configuration with **Ubuntu** works as expected. Below are the respective Dockerfile configurations for both Alpine and Ubuntu.

**Alpine Dockerfile:**
```dockerfile
FROM alpine:latest AS builder

WORKDIR /app

RUN apk update && apk add --no-cache wget

ARG TARGETARCH
RUN if [ "$TARGETARCH" = "amd64" ]; then \
    wget https://github.com/foundry-rs/foundry/releases/download/nightly-62cdea8ff9e6efef011f77e295823b5f2dbeb3a1/foundry_nightly_linux_amd64.tar.gz && \
    tar -xzf foundry_nightly_linux_amd64.tar.gz; \
    elif [ "$TARGETARCH" = "arm64" ]; then \
    wget https://github.com/foundry-rs/foundry/releases/download/nightly-62cdea8ff9e6efef011f77e295823b5f2dbeb3a1/foundry_nightly_linux_arm64.tar.gz && \
    tar -xzf foundry_nightly_linux_arm64.tar.gz; \
    else \
    echo "Unsupported architecture"; exit 1; \
    fi

FROM alpine:latest

EXPOSE 8545

WORKDIR /app

RUN apk update && apk add --no-cache curl

COPY --from=builder /app/anvil .
COPY ./cmd.sh .
COPY ./ignition/data/ .

CMD ["./cmd.sh"]
```

**Ubuntu Dockerfile:**
```dockerfile
FROM ubuntu:latest AS builder

WORKDIR /app

RUN apt-get update && apt-get install -y wget --fix-missing --fix-broken

ARG TARGETARCH
RUN if [ "$TARGETARCH" = "amd64" ]; then \
    wget https://github.com/foundry-rs/foundry/releases/download/nightly-62cdea8ff9e6efef011f77e295823b5f2dbeb3a1/foundry_nightly_linux_amd64.tar.gz && \
    tar -xzf foundry_nightly_linux_amd64.tar.gz; \
    elif [ "$TARGETARCH" = "arm64" ]; then \
    wget https://github.com/foundry-rs/foundry/releases/download/nightly-62cdea8ff9e6efef011f77e295823b5f2dbeb3a1/foundry_nightly_linux_arm64.tar.gz && \
    tar -xzf foundry_nightly_linux_arm64.tar.gz; \
    else \
    echo "Unsupported architecture"; exit 1; \
    fi

FROM ubuntu:latest

EXPOSE 8545

WORKDIR /app

RUN apt-get update && apt-get install -y curl --fix-missing --fix-broken

COPY --from=builder /app/anvil .
COPY ./cmd.sh .
COPY ./ignition/data/ .

CMD ["./cmd.sh"]
```

External file `cmd.sh` that might be required is:
```bash
#!/bin/sh

./anvil --host 0.0.0.0 --block-time 10 &

sleep 3 

if [ -n "$CHAIN_ID" ]; then
    response=$(curl -s -X POST -H "Content-Type: application/json" --data "{\"jsonrpc\":\"2.0\", \"method\":\"anvil_setChainId\", \"params\":[$CHAIN_ID], \"id\":1}" http://localhost:8545)
    echo "Set chain ID response: $response"
else
    echo "CHAIN_ID is not set, default chain ID is 31337."
fi

if [ "$LIGHT" = "true" ]; then
    state_file="./lightState.json"
else
    state_file="./fullState.json"
fi

response=$(curl -s -X POST -H "Content-Type: application/json" --data-binary @$state_file http://localhost:8545)
echo "Set blockchain state response: $response"

tail -f /dev/null
```

#### Error Output
```
cmd.sh: line 3: ./anvil: not found
```

#### Expected Behavior
The Alpine Docker image should build and run successfully, similar to the Ubuntu image.

#### Additional Information
- **Alpine Version**: `latest`
- **Ubuntu Version**: `latest`
- **Foundry Release**: `nightly-62cdea8ff9e6efef011f77e295823b5f2dbeb3a1`

**Comment by zerosnacks** [comment] 2024-07-23 10:38
I think this is because Alpine uses MUSL whereas Foundry has a dependency on GLIBC

A possible workaround is using the https://hub.docker.com/r/frolvlad/alpine-glibc/ image (see: https://github.com/foundry-rs/foundry/blob/master/Dockerfile)

**Comment by grandizzy** [comment] 2024-10-01 11:23
@susruth @gnapoli23 we have this PR merged https://github.com/foundry-rs/foundry/pull/8964 could you check if solves your issue? thank you

**Comment by gnapoli23** [comment] 2024-10-01 14:31
> @susruth @gnapoli23 we have this PR merged #8964 could you check if solves your issue? thank you

Confirming that it's working for me now. BTW is there a reason why #8964 uses `alpine:3.18` instead of the latest stable `alpine:3.20` version?

**Comment by grandizzy** [comment] 2024-10-01 14:37
> BTW is there a reason why https://github.com/foundry-rs/foundry/pull/8964 uses alpine:3.18 instead of the latest stable alpine:3.20.3 version?

Hm, not sure if any deps on version.  @DrakeEvans can you please chime in?

**Comment by grandizzy** [comment] 2024-10-01 15:32
going to close this one as it is confirmed working, pls open new ticket if other issues. Thank you!

**Closed by grandizzy** 2024-10-01 15:32 UTC
Labels: T-feature, A-releases, A-compatibility

**Comment by DrakeEvans** [comment] 2024-10-07 18:56
> > BTW is there a reason why #8964 uses alpine:3.18 instead of the latest stable alpine:3.20.3 version?
> 
> Hm, not sure if any deps on version. @DrakeEvans can you please chime in?

The initial build step was using alpine:3.18 and I wanted to keep the scope of my changes as small as possible.   If we upgrade to latest we should upgrade both parts.  But I have not tested anything on alpine:3.20
