### ISSUE TITLE
Testing try/catch block with `mockCall` and `mockCallRevert` not behaving as expected

### ISSUE THREAD

**Issue by Bolee95** [foundry-rs/foundry#5434] opened 2023-07-19 14:58 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (c835a3d 2023-07-17T00:21:00.033122754Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

Hi,
I'm trying to test an `ERC-1155` smart contract, which after token transfer checks target implements `IERC1155Receiver` interface. I'm trying to do it without writing a mock contract, but by using `vm.mockCall` or `vm.mockCallRevert` in order to revert or return the magic value that `ERC-1155` checks. 
```solidity
    function _doSafeTransferAcceptanceCheck(
        address operator,
        address from,
        address to,
        uint256 id,
        uint256 amount,
        bytes memory data
    ) private {
        if (to.isContract()) {
            try IERC1155Receiver(to).onERC1155Received(operator, from, id, amount, data) returns (
                bytes4 response
            ) {
                if (response != IERC1155Receiver.onERC1155Received.selector)
                    revert TransferOfERC1155Rejected();
            } catch Error(string memory reason) {
                revert(reason);
            } catch {
                revert TransferToNonERC1155Receiver();
            }
        }
    }
```

The test code is the following:
```solidity
function test_safeTransferFrom_revertsWhenSenderContractRevertsWithReason() public {
        address from = address(1);
        address dummy1155Receiver = address(100);
        vm.etch(dummy1155Receiver, abi.encode(0x01));
        assertTrue(dummy1155Receiver.code.length > 0);

        erc1155d.exposed_mintBatch(from, ArrayUtils._asUint256Array(1, 1), "");
        vm.mockCallRevert(
            dummy1155Receiver,
            abi.encodeWithSelector(
                IERC1155Receiver.onERC1155Received.selector,
                from,
                from,
                1,
                1,
                ""
            ),
            "Error"
        );
        vm.expectRevert("Error");
        vm.prank(from);
        erc1155d.safeTransferFrom(from, dummy1155Receiver, 1, 1, "");
    }

```

The trace for when the test is executed is the following:
```
[FAIL. Reason: Error != expected error: 0xacdfb75a != Error] test_safeTransferFrom_revertsWhenSenderContractRevertsWithReason() (gas: 48141)
Traces:
  [913757] ERC1155DTest::setUp() 
    ├─ [858498] → new ERC1155DExposed@0x5615dEB798BB3E4dFa0139dFa1b3D433Cc23b72f
    │   └─ ← 4288 bytes of code
    └─ ← ()

  [48141] ERC1155DTest::test_safeTransferFrom_revertsWhenSenderContractRevertsWithReason() 
    ├─ [0] VM::etch(0x0000000000000000000000000000000000000064, 0x0000000000000000000000000000000000000000000000000000000000000001) 
    │   └─ ← ()
    ├─ [28418] ERC1155DExposed::exposed_mintBatch(0x0000000000000000000000000000000000000001, [1], 0x) 
    │   ├─ emit TransferBatch(operator: ERC1155DTest: [0x7FA9385bE102ac3EAc297483Dd6233D62b3e1496], from: 0x0000000000000000000000000000000000000000, to: 0x0000000000000000000000000000000000000001, ids: [1], values: [1])
    │   └─ ← ()
    ├─ [0] VM::mockCallRevert(0x0000000000000000000000000000000000000064, 0x, 0x4572726f72) 
    │   └─ ← ()
    ├─ [0] VM::expectRevert(Error) 
    │   └─ ← ()
    ├─ [0] VM::prank(0x0000000000000000000000000000000000000001) 
    │   └─ ← ()
    ├─ [5357] ERC1155DExposed::safeTransferFrom(0x0000000000000000000000000000000000000001, 0x0000000000000000000000000000000000000064, 1, 1, 0x) 
    │   ├─ emit TransferSingle(operator: 0x0000000000000000000000000000000000000001, from: 0x0000000000000000000000000000000000000001, to: 0x0000000000000000000000000000000000000064, id: 1, value: 1)
    │   ├─ [0] 0x0000000000000000000000000000000000000064::onERC1155Received(0x0000000000000000000000000000000000000001, 0x0000000000000000000000000000000000000001, 1, 1, 0x) 
    │   │   └─ ← 0x4572726f72
    │   └─ ← "TransferToNonERC1155Receiver()"
    └─ ← "Error != expected error: 0xacdfb75a != Error"
```

As can be seen in the trace, `dummyERC1155Receiver` did return the "Error" string, as set via `mockCallRevert`, but for some reason, the wrong catch block was invoked (the one when the revert reason is not found).

Whatever the input of `mockCall` or `mockCallRevert`, the execution will revert as the call to the `dummyERC1155Receiver` failed immediately. I even tried using a real contract implementing `IERC1155Receiver` instead of using `etch`, but the result is always the same. Returning the correct magic value also results in a revert.

I haven't found any of the existing issues that may be an answer to this. 
Please let me know if more info is needed.

**Comment by zerosnacks** [comment] 2024-07-03 11:26
Hi @Bolee95, sorry for the delay

Did you manage to resolve this? One thing people frequently run into is not implementing the receiver callbacks on their test contract, causing a revert to happen before you can catch it.

**Comment by zerosnacks** [comment] 2024-07-25 14:40
Tentatively closing this as I'm leaning towards it being a user mistake or a strict limitation due to the way callback call frames work. To future readers or OP: feel free to re-open or leave a comment with details if you are able to reproduce this issue.

**Closed by zerosnacks** 2024-07-25 14:40 UTC
Labels: T-bug, A-cheatcodes, T-to-investigate
