### ISSUE TITLE
Proxy patten failed with sending ether

### ISSUE THREAD

**Issue by qiwihui** [foundry-rs/foundry#3744] opened 2022-11-23 03:45 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (b28119b 2022-11-23T00:17:21.324951Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

I tried to test proxy patten to receive ether but some of the situations failed while they should not. I tested these cases on testnet, they behaves as expected. Here is the test files:

proxy.sol

```solidity
// SPDX-License-Identifier: MIT
// solhint-disable const-name-snakecase
pragma solidity 0.6.10;

/**
 * @title OwnedUpgradeabilityProxy
 * @dev This contract combines an upgradeability proxy with basic authorization control functionalities
 */
contract OwnedUpgradeabilityProxy {

    /**
     * @dev Allows the proxy owner to upgrade the current version of the proxy.
     * @param implementation representing the address of the new implementation to be set.
     */
    function upgradeTo(address implementation) public virtual {
        address currentImplementation;
        bytes32 position = implementationPosition;
        assembly {
            currentImplementation := sload(position)
        }
        require(currentImplementation != implementation);
        assembly {
            sstore(position, implementation)
        }
        emit Upgraded(implementation);
    }

    /**
     * @dev This event will be emitted every time the implementation gets upgraded
     * @param implementation representing the address of the upgraded implementation
     */
    event Upgraded(address indexed implementation);

    // Storage position of the address of the current implementation
    bytes32 private constant implementationPosition = 0x6e41e0fbe643dfdb6043698bf865aada82dc46b953f754a3468eaa272a362dc7;

    function implementation() public view returns (address impl) {
        bytes32 position = implementationPosition;
        assembly {
            impl := sload(position)
        }
    }

    event CallFallback(uint256);
    event CallReceive(uint256);

    /**
     * @dev Fallback functions allowing to perform a delegatecall to the given implementation.
     * This function will return whatever the implementation call returns
     */
    fallback() external {
        emit CallFallback(1);
        proxyCall();
    }

    receive() external payable {
        emit CallReceive(2);
        proxyCall();
    }

    function proxyCall() internal {
        bytes32 position = implementationPosition;

        assembly {
            let ptr := mload(0x40)
            calldatacopy(ptr, 0, calldatasize())
            let result := delegatecall(gas(), sload(position), ptr, calldatasize(), 0, 0)
            let size := returndatasize()
            returndatacopy(ptr, 0, size)

            switch result
            case 0 { revert(ptr, size) }
            default { return(ptr, size) }
        }
    }
}

```

testTransfer.sol

```solidity
// SPDX-License-Identifier: MIT
pragma solidity 0.6.10;

import "forge-std/Test.sol";
import {OwnedUpgradeabilityProxy} from "./proxy.sol";

contract Implementation0 {}

contract Implementation1 {
    event CallFallback();
    event CallReceive();

    fallback() external {
        emit CallFallback();
    }

    receive() external payable {
        emit CallReceive();
    }
}

contract Implementation2 {
    event CallFallback();

    fallback() external {
        emit CallFallback();
    }
}

contract Implementation3 {
    event CallFallback();

    fallback() external payable {
        emit CallFallback();
    }
}

contract Implementation4 {
    event CallFallback();
    event CallReceive();

    fallback() external payable {
        emit CallFallback();
    }

    receive() external payable {
        emit CallReceive();
    }
}

contract ContractTest is Test {
    OwnedUpgradeabilityProxy proxy;
    Implementation0 impl0;
    Implementation1 impl1;
    Implementation2 impl2;
    Implementation3 impl3;
    Implementation4 impl4;

    function setUp() public {
        proxy = new OwnedUpgradeabilityProxy();
        impl0 = new Implementation0();
        impl1 = new Implementation1();
        impl2 = new Implementation2();
        impl3 = new Implementation3();
        impl4 = new Implementation4();
    }

    function proxyUpgradeTo(address impl) internal {
        proxy.upgradeTo(impl);
        assert(proxy.implementation() == impl);
    }

    function testImplNoReceiveNoFallback() public {
        proxyUpgradeTo(address(impl0));

        vm.expectRevert();
        payable(address(proxy)).transfer(1 ether);
    }

    function testImplReceiveFallbackNoPayable() public {
        proxyUpgradeTo(address(impl1));
        
        payable(address(proxy)).transfer(1 ether);
    }

    function testImplNoReceiveFallbackNoPayable() public {
        proxyUpgradeTo(address(impl2));
        
        vm.expectRevert();
        payable(address(proxy)).transfer(1 ether);
    }

    function testImplNoReceiveFallbackWithPayable() public {
        proxyUpgradeTo(address(impl3));
        
        payable(address(proxy)).transfer(1 ether);
    }

    function testImplReceiveFallbackWithPayable() public {
        proxyUpgradeTo(address(impl4));
        
        payable(address(proxy)).transfer(1 ether);
    }
}

```

And here is the result

```shell
$ forge test -vvv
[⠒] Compiling...
No files changed, compilation skipped

Running 5 tests for test/testCallback.sol:ContractTest
[PASS] testImplNoReceiveFallbackNoPayable() (gas: 42840)
[FAIL. Reason: EvmError: Revert] testImplNoReceiveFallbackWithPayable() (gas: 40945)
Traces:
  [40945] ContractTest::testImplNoReceiveFallbackWithPayable() 
    ├─ [23487] OwnedUpgradeabilityProxy::upgradeTo(Implementation3: [0xc7183455a4C133Ae270771860664b6B7ec320bB1]) 
    │   ├─ emit Upgraded(implementation: Implementation3: [0xc7183455a4C133Ae270771860664b6B7ec320bB1])
    │   └─ ← ()
    ├─ [307] OwnedUpgradeabilityProxy::implementation() [staticcall]
    │   └─ ← Implementation3: [0xc7183455a4C133Ae270771860664b6B7ec320bB1]
    ├─ [1269] OwnedUpgradeabilityProxy::receive{value: 1000000000000000000}() 
    │   ├─ emit CallReceive(: 2)
    │   └─ ← "EvmError: OutOfGas"
    └─ ← "EvmError: Revert"

[PASS] testImplNoReceiveNoFallback() (gas: 42817)
[FAIL. Reason: EvmError: Revert] testImplReceiveFallbackNoPayable() (gas: 40945)
Traces:
  [40945] ContractTest::testImplReceiveFallbackNoPayable() 
    ├─ [23487] OwnedUpgradeabilityProxy::upgradeTo(Implementation1: [0xF62849F9A0B5Bf2913b396098F7c7019b51A820a]) 
    │   ├─ emit Upgraded(implementation: Implementation1: [0xF62849F9A0B5Bf2913b396098F7c7019b51A820a])
    │   └─ ← ()
    ├─ [307] OwnedUpgradeabilityProxy::implementation() [staticcall]
    │   └─ ← Implementation1: [0xF62849F9A0B5Bf2913b396098F7c7019b51A820a]
    ├─ [1269] OwnedUpgradeabilityProxy::receive{value: 1000000000000000000}() 
    │   ├─ emit CallReceive(: 2)
    │   └─ ← "EvmError: OutOfGas"
    └─ ← "EvmError: Revert"

[FAIL. Reason: EvmError: Revert] testImplReceiveFallbackWithPayable() (gas: 40967)
Traces:
  [40967] ContractTest::testImplReceiveFallbackWithPayable() 
    ├─ [23487] OwnedUpgradeabilityProxy::upgradeTo(Implementation4: [0xa0Cb889707d426A7A386870A03bc70d1b0697598]) 
    │   ├─ emit Upgraded(implementation: Implementation4: [0xa0Cb889707d426A7A386870A03bc70d1b0697598])
    │   └─ ← ()
    ├─ [307] OwnedUpgradeabilityProxy::implementation() [staticcall]
    │   └─ ← Implementation4: [0xa0Cb889707d426A7A386870A03bc70d1b0697598]
    ├─ [1269] OwnedUpgradeabilityProxy::receive{value: 1000000000000000000}() 
    │   ├─ emit CallReceive(: 2)
    │   └─ ← "EvmError: OutOfGas"
    └─ ← "EvmError: Revert"

Test result: FAILED. 2 passed; 3 failed; finished in 439.17µs

Failing tests:
Encountered 3 failing tests in test/testCallback.sol:ContractTest
[FAIL. Reason: EvmError: Revert] testImplNoReceiveFallbackWithPayable() (gas: 40945)
[FAIL. Reason: EvmError: Revert] testImplReceiveFallbackNoPayable() (gas: 40945)
[FAIL. Reason: EvmError: Revert] testImplReceiveFallbackWithPayable() (gas: 40967)

Encountered a total of 3 failing tests, 2 tests succeeded
```

**Comment by metmirr** [comment] 2023-01-22 16:34
The issue still persists, although I am not testing the proxy patter.

**Comment by burnto** [comment] 2023-02-08 20:21
This came up for me with proxies (specifically OZ Clones) as well.

Specifically, clones could be created in `setup()`, but then when transferring eth with `transfer` in a test function, it reverts with the `OutOfGas` message.

**Comment by onbjerg** [comment] 2023-02-25 01:42
`.transfer` only grants the receiver 2300 gas to compute. You are running out of gas, logs are expensive to emit.

https://docs.soliditylang.org/en/v0.8.19/units-and-global-variables.html#address-related

**Closed by onbjerg** 2023-02-25 01:42 UTC
Labels: T-bug

**Comment by burnto** [comment] 2023-02-25 01:53
> `.transfer` only grants the receiver 2300 gas to compute. You are running out of gas, logs are expensive to emit.
> 
> https://docs.soliditylang.org/en/v0.8.19/units-and-global-variables.html#address-related

Thanks @onbjerg - yes, this was my hunch initially, but a `transfer()` in setup() succeeded, whereas a `transfer()` in the actual test failed. Is there something different about the gas budget in tests?

**Comment by onbjerg** [comment] 2023-02-25 02:05
There should not be, this sounds like some edge case behavior of Solidity. The gas stipend of 2300 is set by Solidity, as far as I know - at the very least, it is not controlled by us.

The gas budget for both set up and the individual tests are the exact same (very high)

**Comment by burnto** [comment] 2023-02-25 03:04
Well, looks I can't isolate the issue I thought I was seeing, so it must have been caused by some error on my part. Thanks for weighing in.

**Comment by burnto** [comment] 2023-03-08 17:51
@onbjerg @qiwihui so looks like I'm still running into (what I think is) this issue, and I've now isolated it:
https://github.com/foundry-rs/foundry/discussions/4508

I'd really appreciate your quick peek, since this is unexpected behavior and I *think* this indicates a `forge test` limitation.
