### ISSUE TITLE
Cheatcodes to write to CSV

### ISSUE THREAD

**Issue by lucas-manuel** [foundry-rs/foundry#1359] opened 2022-04-18 22:33 UTC
### Component

Forge

### Describe the feature you would like

When running mainnet simulations it is often useful to log state to files, specifically CSVs. It would be great to have cheatcodes to do the following actions:

- Add column with label and multiple values
- Write CSV to path
- Append values to column (potentially)

```solidity
for (uint  i; i < 100; i++) {
    inputs.push(i);
    values.push(someFunction(i));
}
vm.csv_add_column("someFunctionInput", inputs);
vm.csv_add_column("someFunctionOutput", values);
vm.write_csv(path);
```

**Comment by onbjerg** [comment] 2022-04-18 22:36
Any reason you can't use FFI for this use case?

I'm generally wary that we're going to end up adding a bunch of cheatcodes that are somewhat niche, not sure what the general stance is on this. The primary issue is that the more cheatcodes we add, the higher the maintenance burden, so imo limiting what cheatcodes we add/don't add or trying to add the more "general" version of the cheatcode is preferred

**Comment by brockelmore** [comment] 2022-04-18 22:42
yea i lean towards a csv writer in solidity + a `write_file` cheatcode actually

**Comment by onbjerg** [comment] 2022-04-18 22:54
I guess a `write_file` makes more sense, but I still wonder if this is not covered by the FFI cheatcode or if we can make it be covered by FFI. I can just already see someone requesting `vm.write_json` :smile:

**Comment by lucas-manuel** [comment] 2022-04-18 23:47
I got it what I needed from ffi here:

```solidity
    function _writeToFile(string memory line, string memory filePath) internal {
        string[] memory inputs = new string[](5);
        inputs[0] = "scripts/write-to-file.sh";
        inputs[1] = "-f";
        inputs[2] = filePath;
        inputs[3] = "-i";
        inputs[4] = line;

        vm.ffi(inputs);
    }

    function _writeToFile(string memory key, uint256 value, string memory filePath) internal {
        string memory line = string(abi.encodePacked(key, _convertUintToString(value)));

        string[] memory inputs = new string[](5);
        inputs[0] = "scripts/write-to-file.sh";
        inputs[1] = "-f";
        inputs[2] = filePath;
        inputs[3] = "-i";
        inputs[4] = line;

        vm.ffi(inputs);
    }
```

write-to-file.sh

```
#!/usr/bin/env bash
set -e

while getopts f:i: flag
do
    case "${flag}" in
        f) file=${OPTARG};;
        i) input=${OPTARG};;
    esac
done

echo $input >> $file

echo "0x"
```

But itd be much harder to handle csv columns this way. Was able to get this output:

```
--------------
Month 1
--------------
Exchange Rate: 25101
Total Supply-: 598449
Total Assets-: 1502219

--------------
Month 2
--------------
Exchange Rate: 25146
Total Supply-: 598449
Total Assets-: 1504891

--------------
Month 3
--------------
Exchange Rate: 25197
Total Supply-: 598449
Total Assets-: 1507920

--------------
Month 4
--------------
Exchange Rate: 25252
Total Supply-: 598449
Total Assets-: 1511246

--------------
Month 5
--------------
Exchange Rate: 25312
Total Supply-: 598449
Total Assets-: 1514832
```

**Comment by transmissions11** [comment] 2022-04-19 00:19
somewhat a dupe of https://github.com/foundry-rs/foundry/issues/1022

**Comment by brockelmore** [comment] 2022-04-19 04:49
> I guess a `write_file` makes more sense, but I still wonder if this is not covered by the FFI cheatcode or if we can make it be covered by FFI? I can already see someone requesting `vm.write_json` :smile: 

the plan is to do any formatting you want in solidity and pass it up to rust. ffi is slow & cumbersome for simply writing a file (having to enable it just to write a file is overkill imo)

**Comment by sambacha** [comment] 2022-05-11 18:56
> Any reason you can't use FFI for this use case? :thinking: 
> 
> 
> 
> I'm generally wary that we're going to end up adding a bunch of cheatcodes that are somewhat niche, not sure what the general stance is on this. The primary issue is that the more cheatcodes we add, the higher the maintenance burden, so imo limiting what cheatcodes we add/don't add or trying to add the more "general" version of the cheatcode is preferred

The riches are in the niches

**Closed** 2022-06-23 00:40 UTC
Labels: T-feature, Cmd-forge-test, C-forge, A-cheatcodes
