### ISSUE TITLE
Is not able to verify deployed contract

### ISSUE THREAD

**Issue by debych** [foundry-rs/foundry#4493] opened 2023-03-07 12:28 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (28b2ae6 2023-03-06T00:04:12.952149891Z)

### What command(s) is the bug in?

forge script

### Operating System

Linux

### Describe the bug

Running this command

```
ETHERSCAN_API_KEY=$POLYGON_ETHERSCAN_API_KEY forge script script/Deploy.s.sol -f polygon -vvvv --json --broadcast 
--skip-simulation --silent --legacy --verify
```

Gives such output after deployment

```
##
Start verification for (0) contracts
All (0) contracts were verified!
```

**Comment by Evalir** [comment] 2023-06-16 06:22
Closing—duplicate of several verification issues. Currently deduping these to just the few ones remaining.

**Closed by Evalir** 2023-06-16 06:22 UTC
Labels: T-bug, C-forge, Cmd-forge-verify

**Comment by tzaffi** [comment] 2024-11-13 20:51
Can you please link to the original when closing for dupes?
