### ISSUE TITLE
Failed to resolve versions ethers_solc

### ISSUE THREAD

**Issue by MeetEatMeat** [foundry-rs/foundry#2234] opened 2022-07-07 13:23 UTC
### Discussed in https://github.com/foundry-rs/foundry/discussions/2232

<div type='discussions-op-text'>

<sup>Originally posted by **MeetEatMeat** July  7, 2022</sup>
I'm trying to build a project which has several pragma versions in it's dependencies list, but then i'm getting an error below:
<img width="761" alt="Снимок экрана 2022-07-07 в 17 16 43" src="https://user-images.githubusercontent.com/34601776/177783386-2e0d4b71-0631-4e3e-a09e-f8183816dba8.png">
 How to resolve it?</div>

**Comment by mattsse** [comment] 2022-07-07 13:41
you have semver incompatible requirements:

NonfungiblePositionManager requires 0.7.6
IAlgebrPool requires 0.8.0 

try upgrading the contracts/pragmas

**Comment by mattsse** [comment] 2022-07-07 13:43
closing this as this is intended behaviour to disallow sember incompatible pragmas

**Closed by mattsse** 2022-07-07 13:43 UTC

**Comment by MeetEatMeat** [comment] 2022-07-07 14:22
> you have semver incompatible requirements:
> 
> NonfungiblePositionManager requires 0.7.6 IAlgebrPool requires 0.8.0
> 
> try upgrading the contracts/pragmas

Since i'm unable to update code of it's dependencies is there nothing to do?
