### ISSUE TITLE
configure or read anvil cache/tmp storage disk location

### ISSUE THREAD

**Issue by alvrs** [foundry-rs/foundry#4989] opened 2023-05-20 08:05 UTC
### Component

Anvil

### Describe the feature you would like

It would be nice if it was possible to configure or read the anvil disk cache location via the CLI
https://github.com/foundry-rs/foundry/blob/c331b5eeee1b4151ef7354a081667e2d770b37f5/anvil/src/config.rs#L1085-L1086 

Use case: we have a dev script internally running anvil and want to clean the cache before every start. Currently we're hardcoding the location to `~/.foundry/anvil/tmp`, but this is brittle and would break if the cache location is changed upstream.

**Comment by holic** [comment] 2023-05-21 17:23
Semi related to https://github.com/foundry-rs/foundry/issues/3623

**Comment by ltfschoen** [comment] 2023-05-23 17:52
if i kept it running it used up 10Gb in 24 hrs 
so i kept having to remember to run the following as i only had about 20Gb free anyway so it was chewing up precious swap disk space, which is especially important on a dual cpu machine with 8gb memory that was always maxed out
```
du -sh /root/.foundry/anvil/
rm -rf /root/.foundry/anvil/tmp/
```

**Comment by Evalir** [comment] 2023-07-24 21:48
Closing—can't reproduce anymore

**Closed by Evalir** 2023-07-24 21:48 UTC
Labels: T-feature
