### ISSUE TITLE
Support creation of contracts with CREATE2 in scripts

### ISSUE THREAD

**Issue by JasoonS** [foundry-rs/foundry#1999] opened 2022-06-16 16:56 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (2457e5f 2022-06-16T00:07:46.767196942Z)

### What command(s) is the bug in?

forge script

### Operating System

(tested on Ubuntu Linux and Mac)

### Describe the bug

When running contract creation with `CREATE2` scripts don't deploy contracts as expected.

Reproducible example:
```solidity
pragma solidity ^0.8.13;

import "forge-std/Script.sol";

contract D {
  uint256 public x;

  constructor(uint256 a) {
    x = a;
  }
}

contract MyScript is Script {
  uint256 create2Salt = 5;

  function run() external {
    vm.startBroadcast();

    uint256 arg = 654654654;

    address predictedAddress = address(
      uint160(
        uint256(
          keccak256(
            abi.encodePacked(
              bytes1(0xff),
              msg.sender,
              create2Salt,
              keccak256(abi.encodePacked(type(D).creationCode, abi.encode(arg)))
            )
          )
        )
      )
    );

    D d = new D{salt: bytes32(create2Salt)}(arg);
    console.log("The below 2 addresses should be the same: <address(d), predictedAddress>");
    console.log(address(d), predictedAddress);

    vm.stopBroadcast();
  }
}
```

When running this script we get this output:
```
$ forge script ./contracts/scripts/Create2.s.sol:MyScript --rpc-url $MUMBAI_RPC_URL  --private-key $PRIVATE_KEY --broadcast --verify --etherscan-api-key $ETHERSCAN_KEY -vvvv
[⠰] Compiling...
[⠊] Compiling 1 files with 0.8.13
[⠒] Solc 0.8.13 finished in 549.83ms
Compiler run successful
Traces:
  [90323] MyScript::run()
    ├─ [0] VM::startBroadcast()
    │   └─ ← ()
    ├─ [47315] → new D@0x3e0dde95fe6889388e7b5202e87a651b5f1a0f4e
    │   └─ ← 125 bytes of code
    ├─ [0] console::log("The below 2 addresses should be the same: <address(d), predictedAddress>") [staticcall]
    │   └─ ← ()
    ├─ [0] console::log(D: [0x3e0dde95fe6889388e7b5202e87a651b5f1a0f4e], 0xfe0e52391686289fc281350bce83bde14d235421) [staticcall]
    │   └─ ← ()
    ├─ [0] VM::stopBroadcast()
    │   └─ ← ()
    └─ ← ()


Script ran successfully.
Gas used: 90323

== Logs ==
  The below 2 addresses should be the same: <address(d), predictedAddress>
  0x3e0dde95fe6889388e7b5202e87a651b5f1a0f4e, 0xfe0e52391686289fc281350bce83bde14d235421
==========================
Simulated On-chain Traces:

  [104072] Create2Deployer::create2()
    ├─ [47315] → new D@0x3e0dde95fe6889388e7b5202e87a651b5f1a0f4e
    │   └─ ← 125 bytes of code
    └─ ← 0x3e0dde95fe6889388e7b5202e87a651b5f1a0f4e


==========================

Estimated total gas used for script: 135293

Amount required: 0.00040587900270586 ETH

==========================

###
Finding wallets for all the necessary addresses...
##
Sending transactions [0 - 0].
⠁ [00:00:00] [################################################################################] 1/1 txes (0.0s)
Transactions saved to: broadcast/Create2.s.sol/80001/run-latest.json

##
Waiting for receipts.
⠉ [00:00:07] [############################################################################] 1/1 receipts (0.0s)
#####
✅ Hash: 0xdb21c3da66739ac53d8a2a06843ebd7964187beecf4fe592a5957afa56a0e967
Block: 26773410
Paid: 0.00031221600104072 ETH (104072 gas * 3.00000001 gwei)


Transactions saved to: broadcast/Create2.s.sol/80001/run-latest.json



==========================

ONCHAIN EXECUTION COMPLETE & SUCCESSFUL. Transaction receipts written to "broadcast/Create2.s.sol/80001/run-latest.json"
##
Start Contract Verification

Transactions saved to: broadcast/Create2.s.sol/80001/run-latest.json
```

And on-chain the transaction that is created is: https://mumbai.polygonscan.com/tx/0xdb21c3da66739ac53d8a2a06843ebd7964187beecf4fe592a5957afa56a0e967 - notice that it doesn't deploy any contract, and it just calls out to [this contract](https://blockscan.com/address/0x4e59b44847b379578588920ca78fbf26c0b4956c).

I notice that the address it calls out to is mentioned in the foundry codebase, eg [here](https://github.com/foundry-rs/foundry/blob/d081b1805d7ed911b6fdde5ae79c71adecf50060/cli/tests/it/script.rs#L255).

**Comment by JasoonS** [comment] 2022-06-16 17:12
Example contract used is taken from here: https://docs.soliditylang.org/en/latest/control-structures.html#salted-contract-creations-create2 , but the same issue happens with other contracts I've tested.

**Comment by mds1** [comment] 2022-06-16 17:28
It does work—I've been predicting/verifying create2 address in scripts. I think the issue is that when you predict the address that `msg.sender` is different than the one broadcasting the transaction

**Comment by mds1** [comment] 2022-06-16 17:29
The 0x4e59b44847b379578588920ca78fbf26c0b4956c address is a create2 deterministic deployer that is deployed across many chains. You need that contract at the same address on all supported chains. Create2 cannot be called by an EOA, so to use it you send the contract bytecode to a deployer contract

**Comment by gakonst** [comment] 2022-06-16 21:26
closing as there is not a bug here

**Closed by gakonst** 2022-06-16 21:26 UTC
Labels: T-bug

**Comment by JasoonS** [comment] 2022-06-17 04:29
> It does work—I've been predicting/verifying create2 address in scripts. I think the issue is that when you predict the address that `msg.sender` is different than the one broadcasting the transaction

Thanks, can you please share what you use instead of msg.sender? Logging msg.sender in the scripts does display the correct address afaik.

I did try very carefully to get this to work. So I would really appreciate it if you could share a snippit from your scripts @mds1

**Comment by mds1** [comment] 2022-06-17 04:35
On mobile right now so can't send a snippet, but looking again it seems I misspoke earlier. When predicting the address, you're using msg.sender as the deployer address, but it should be 0x4e59b44847b379578588920ca78fbf26c0b4956c

**Comment by JasoonS** [comment] 2022-06-17 05:57
Great - that is working, thanks @mds1 .

The contract however isn't being automatically verified by the script currently.

**Comment by gakonst** [comment] 2022-06-17 15:37
Cool! let's follow up on the separate issue

**Comment by 2547881370** [comment] 2022-10-24 09:00
I have a problem at present; When I use ganache to fork, create2 is created successfully. When using anvi fork l, create2 returns 0x00000000000000000000000000000000000000000000000000000000000



ganache -f https://bsc-mainnet.nodereal.io/v1/a9d5920ea85349c298ee543d3d4922ac -e 100
00 --chain.chainId 56 -l 1200000000 -g 2000000000000 --fork.blockNumber 22070910

anvil -f https://bsc-mainnet.nodereal.io/v1/a9d5920ea85349c298ee543d3d4922ac  --chain-id  56 --gas-limit 12000000000000000000 --gas-price 9000000000000000000   --fork-block-number 22070910

`
// SPDX-License-Identifier: Unlicensed
pragma solidity 0.8.15;

contract Deployer {
  bytes32 public salt = keccak256(abi.encodePacked(0x0000000000000000000000000000000000000002));

  function deploy(bytes memory data) public returns(address Addr){
        bytes32 _salt = salt;
        address addr;
        assembly {
          addr := create2(0, add(data, 0x20), mload(data), _salt)
        }
        Addr = address(addr);
        return Addr;
  }
}

`
