### ISSUE TITLE
 Forge Initialization and Compilation Errors on Windows: Submodule Cloning and Import Resolution Issues

### ISSUE THREAD

**Issue by dustij** [foundry-rs/foundry#6769] opened 2024-01-11 23:48 UTC
## Description
Encountered multiple errors while initializing a Foundry project and compiling contracts using `forge` (version 0.2.0) on Windows. The issues include submodule cloning errors with backslashes in paths and unresolved imports during compilation.

## Steps to Reproduce
1. Run `forge init hello-foundry` to initialize a new Foundry project.
2. Observe errors during submodule cloning (path issue with backslashes).
3. Run `forge test` or `forge build` in the initialized project directory.
4. Notice errors related to unresolved imports (`ds-test/test.sol` not found).

## Expected Behavior
The `forge init` command should correctly clone submodules without path issues, and the `forge test` or `forge build` commands should resolve imports correctly.

## Actual Behavior
- During initialization: `error: filename in tree entry contains backslash: '\'` and `fatal: No url found for submodule path 'lib/forge-std' in .gitmodules`.
- During compilation: Import resolution errors like `Error (6275): Source "ds-test/test.sol" not found`.

## Environment Details
- Operating System: Windows (MINGW64)
- Forge Version: 0.2.0

## Possible Solution
- The path issue might be related to Windows file path formats. Investigating how paths are handled during submodule cloning could be a start.
- The import resolution issue might be related to how `forge` handles file paths or project structure on Windows.

## Additional Context
- The issue seems specific to the Windows environment.
- Including command line outputs for reference:
![image](https://github.com/foundry-rs/forge-std/assets/142411963/b8a85055-bcfe-4796-8c2a-72ef7c4c6429)
![image](https://github.com/foundry-rs/forge-std/assets/142411963/e4aef9a7-dd39-475e-bfa8-cdf235932594)
![image](https://github.com/foundry-rs/forge-std/assets/142411963/05200129-e9f5-4dd9-b6e6-32f88a33d22b)

**Comment by Evalir** [comment] 2024-01-12 03:45
Closing as a duplicate of #6770 (please correct me if it's not, although both issues look extremely similar)

**Closed by Evalir** 2024-01-12 03:45 UTC
