### ISSUE TITLE
Error starting foundry on my windows

### ISSUE THREAD

**Issue by prince-joel** [foundry-rs/foundry#4308] opened 2023-02-08 13:10 UTC
### Component

Forge, Foundryup

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (249538f 2023-02-09T00:01:54.1537047Z)

### What command(s) is the bug in?

 forge init hello_foundry

### Operating System

Windows

### Describe the bug

After installing foundry as directed by the documentation, I used the command "  forge init hello_foundry"  to create a project and I got this error.

The target directory is a part of or on its own an already initialized git repository,
and it requires clean working and staging areas, including no untracked files.

Check the current git repository's status with `git status`.
Then, you can track files with `git add ...` and then commit them with `git commit`,
ignore them in the `.gitignore` file, or run this command again with the `--no-commit` flag.

If none of the previous steps worked, please open an issue at:
https://github.com/foundry-rs/foundry/issues/new/choose

**Comment by 0xMcsweeja** [comment] 2023-02-22 11:23
Was experiencing same thing but managed to resolve it in a non-deterministic way unfortunately.
One of the three things fixed it for me:

1. Cleared git tree by committing all my changes
2. manually added the submodule to my .gitignore with ignore=dirty:
```
[submodule "lib/openzeppelin-contracts"]
	path = lib/openzeppelin-contracts
	url = https://github.com/OpenZeppelin/openzeppelin-contracts
	branch = v4.8.1
	ignore = dirty
```

3. and added some incorrect fuzz to the end of the installation command to force it to break for a different error, then running the standard `forge install OpenZeppelin/openzeppelin-contracts` again and it worked.

Curiously i now have a second entry in my .gitignore with funky backslashes:
```
[submodule "lib/forge-std"]
	path = lib/forge-std
	url = https://github.com/foundry-rs/forge-std
	branch = v1.4.0
    ignore = dirty
[submodule "lib/openzeppelin-contracts"]
	path = lib/openzeppelin-contracts
	url = https://github.com/OpenZeppelin/openzeppelin-contracts
	branch = v4.8.1
	ignore = dirty
[submodule "lib\\openzeppelin-contracts"]
	branch = v4.8.1
```

Hope this helps with investigation - will try to reproduce on a fresh build tomorrow but posting this incase anyone stuck

**Comment by Swader** [comment] 2023-05-17 05:11
Can confirm committing everything and/or adding the gitignore helped, but also undeterministically.

**Comment by mattsse** [comment] 2023-05-17 10:05
> The target directory is a part of or on its own an already initialized git repository,

this is also a common cause of problems, just because managing everything via git can be a bit challenging...

The double entry could be an issue with windows' platform path separator which is \\ 

I suspect forge added this:

> [submodule "lib\\openzeppelin-contracts"]

?

**Comment by Swader** [comment] 2023-05-17 11:07
I was doing this on Mac, and the folder I was working in was a regular forge init project, no specific git config done by me.

**Comment by SkyYap** [comment] 2023-05-21 12:06
Referring to [foundry docs](https://book.getfoundry.sh/reference/forge/forge-init), it mentioned:

```
By default, forge init will also initialize a new git repository, install some submodules and create an initial commit message.

If you do not want this behavior, pass --no-git.
```

Just pass in `--no-git`. It works perfectly for me here.

**Comment by Evalir** [comment] 2023-06-16 06:30
Closing—solution provided and behavior documented in docs.

**Closed by Evalir** 2023-06-16 06:30 UTC
Labels: T-bug

**Comment by sardarahmedkhan505** [comment] 2023-07-03 08:38
> Referring to [foundry docs](https://book.getfoundry.sh/reference/forge/forge-init), it mentioned:
> 
> ```
> By default, forge init will also initialize a new git repository, install some submodules and create an initial commit message.
> 
> If you do not want this behavior, pass --no-git.
> ```
> 
> Just pass in `--no-git`. It works perfectly for me here.

Thanks solved my probem

**Comment by pallavi991** [comment] 2023-07-25 10:03
getting this error
'''
Error: 
The target directory is a part of or on its own an already initialized git repository,
and it requires clean working and staging areas, including no untracked files.

Check the current git repository's status with `git status`.
Then, you can track files with `git add ...` and then commit them with `git commit`,
ignore them in the `.gitignore` file, or run this command again with the `--no-commit` flag.

If none of the previous steps worked, please open an issue at:
https://github.com/foundry-rs/foundry/issues/new/choose
'''
the lib/forge-std folder is missing

**Comment by jeffsaremi** [comment] 2024-07-06 19:44
Committing my changes to git fixed the problem as suggested [here](https://github.com/foundry-rs/foundry/issues/4308#issuecomment-1439852977)
