### ISSUE TITLE
Using `assertEq` in unit test reports error: "Invalid data"

### ISSUE THREAD

**Issue by GavinXu520** [foundry-rs/foundry#7748] opened 2024-04-22 02:27 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

0.2.0

### What command(s) is the bug in?

forge test -vvvvv  --via-ir  --mt testAssertEq

### Operating System

Linux

### Describe the bug

I reported an error using `assertEq` in the unit test. The error message was: "Invalid data".
The specific screenshots are as follows:

![1713752795541](https://github.com/foundry-rs/foundry/assets/13655605/a03d1967-eeb1-40cc-905f-969d31f1ea8a)

The solidity code content is as follows:

```sol
pragma solidity ^0.8.12;

import "forge-std/Test.sol";

contract MyTest is Test {
    function testAssertEq() public {
        assertEq(uint256(1), uint256(1));
    }
}
```

**Comment by GavinXu520** [comment] 2024-04-22 02:53
add another point:
The error occurred in forge-std v1.8.1. Currently, I changed it to forge-std v1.5.2 and there is no error anymore.

**Comment by klkvr** [comment] 2024-04-22 11:25
Duplicate of #7402. You need to update to latest nightly

**Closed by klkvr** 2024-04-22 11:25 UTC
Labels: T-bug
