### ISSUE TITLE
bug(`forge-script`): not sending specified amount of gas with transaction.

### ISSUE THREAD

**Issue by mesozoic-technology** [foundry-rs/foundry#6601] opened 2023-12-14 15:48 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

0.2.0

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

I have a script that is invoking a method on a contract on Sepolia. I'm instructing it to use a great deal of gas, but it is not reflecting that amount in the stack trace with the verbose printout.

The offending line looks like this:
`entrypoint.handleOps{gas: 200000}(ops, payable(wallet.addr));`

And the stacktrace looks like this:

```
    ├─ [84018] 0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789::handleOps([UserOperation({ sender: 0xCEf159675026e08e355cA1a00270Ec7d1cb36d00, nonce: 0, initCode: 0xb1d4bddc41d51057587bdf373ebcaf61c76f31c85fbfb9cf00000000000000000000000071d0fc7d1c570b1ed786382b551a09391c91e33d0000000000000000000000000000000000000000000000000000000000000001, callData: 0x, callGasLimit: 7000000 [7e6], verificationGasLimit: 70000 [7e4], preVerificationGas: 50000 [5e4], maxFeePerGas: 1000000000 [1e9], maxPriorityFeePerGas: 1000000000 [1e9], paymasterAndData: 0x40cd4ffc9d4bfc82fdf5fb922d07be8d0032299d00000000000000000000000000000000000000000000000000000000657e303000000000000000000000000000000000000000000000000000000000657b22f076fa0ac4259dbe85c335661e7cd721e789faee324d05bbfc791e64f4a2c79bba61c268f598cbffd3761e0b04c614db051422976bb981c611f9c5c074cb73b4891b, signature: 0x5123633ae014c4f1103c83eb6c77d855e8bc557672f9799e94a436164d59c9754411e9fd4c88ed3b0d0690f932831c397ee42e709e2c30a2a3861a45018fa36b1c })], wallet: [0x71D0Fc7d1C570b1ED786382B551a09391C91E33d])
    │   ├─ [68595] 0x7fc98430eAEdbb6070B35B39D798725049088348::createSender(0xb1d4bddc41d51057587bdf373ebcaf61c76f31c85fbfb9cf00000000000000000000000071d0fc7d1c570b1ed786382b551a09391c91e33d0000000000000000000000000000000000000000000000000000000000000001)
    │   │   ├─ [67816] 0xb1d4bDDc41d51057587bdF373ebcaf61c76f31c8::createAccount(wallet: [0x71D0Fc7d1C570b1ED786382B551a09391C91E33d], 1)
    │   │   │   ├─ [29883] → new <unknown>@0xCEf159675026e08e355cA1a00270Ec7d1cb36d00
    │   │   │   │   ├─ emit Upgraded(implementation: 0x73cFe0Bd6a07B69C908B62216Ce1150E9e86491c)
    │   │   │   │   ├─ [2572] 0x73cFe0Bd6a07B69C908B62216Ce1150E9e86491c::initialize(wallet: [0x71D0Fc7d1C570b1ED786382B551a09391C91E33d]) [delegatecall]
    │   │   │   │   │   └─ ← EvmError: OutOfGas
    │   │   │   │   └─ ← 0 bytes of code
    │   │   │   └─ ← EvmError: Revert
    │   │   └─ ← 0x0000000000000000000000000000000000000000
    │   └─ ← 
    └─ ← 
```
    
You can see this method only has 84018 gas available to it by the time it is invoked in the stack trace. If I increase the gas for the method, it is not reflected. However, I can decrease the amount of gas beneath the 84018 it is reporting and it will be reflected in the stack trace.

**Comment by commercium-sys** [comment] 2023-12-14 15:50
I configured some contracts for easy reproducibility with a Sepolia RPC endpoint. The code is in this repository here and should be very easy to set up and run. 

https://github.com/commercium-sys/foundry-sketches/blob/main/script/EIP4337Gas.s.sol

**Comment by zerosnacks** [comment] 2024-07-05 13:23
Hi @mesozoic-technology I'm not able to open the link you provided. It looks like the repo has been re-initialized. Would you be able to provide a new minimal reproduction of your issue? Thanks

**Comment by zerosnacks** [comment] 2024-07-30 15:15
Marking as `can't reproduce`, feel free to re-open with a minimal reproduction. I'm unfortunately unable to open the linked file.

**Closed by zerosnacks** 2024-07-30 15:15 UTC
Labels: T-bug, C-forge, Cmd-forge-script
