### ISSUE TITLE
feat: getCode for linked contracts

### ISSUE THREAD

**Issue by jparklev** [foundry-rs/foundry#1161] opened 2022-04-01 05:24 UTC
### Component

Forge

### Describe the feature you would like

This is quite a niche feature request, I think. But currently it's not possible to use the `getCode` cheatcode with contracts that have linked libraries, so you can't import a local contract using a different solidity version in your tests if it's using one. 

### Additional context

The specific use case I ran into was importing a Balancer pool (`0.7.6`) that implemented an oracle using Balancer's [query processor library](https://github.com/balancer-labs/balancer-v2-monorepo/blob/bd197c7d80e712dbcbe362a402156c528ab10bd9/pkg/pool-utils/contracts/oracle/QueryProcessor.sol) into a testing suite of a newer project (`0.8.11`).

**Comment by onbjerg** [comment] 2022-04-01 21:38
This adds a lot of complexity to `getCode`. Right now it's a pretty simple "find the artifact, extract the bytecode" which requires close to 0 knowledge of how the project is structured and what was compiled.

This change would require a lot of information about the project, such as what contracts were compiled, which ones are unlinked, what the bytecode is of those libraries and then linking them.

Since this is hard I'm marking it https://github.com/gakonst/foundry/labels/D-hard and since the problem is pretty niche, I'm marking this as https://github.com/gakonst/foundry/labels/P-low

Is there any way you can achieve what you want to achieve *without* using `getCode`? The primary use case for `getCode` (I think, at least) is importing non-Solidity contracts

**Comment by jparklev** [comment] 2022-04-01 21:50
> Since this is hard I'm marking it [D-hard](https://github.com/gakonst/foundry/labels/D-hard) and since the problem is pretty niche, I'm marking this as [P-low](https://github.com/gakonst/foundry/labels/P-low)

Yea, sounds v reasonable to me

> Is there any way you can achieve what you want to achieve without using getCode? 

Since the contract i'm testing against is now live on mainnet, i'm interacting with the deployed code using a mainnet fork, which mostly meets my needs here ~

> The primary use case for getCode (I think, at least) is importing non-Solidity contracts

Ahh I think it was added for different compiler versions as well! https://github.com/gakonst/foundry/issues/326

**Comment by malik672** [comment] 2024-02-13 09:54
@onbjerg assign this to me, btw wthat's the final decision
create a new cheatcode or modify getcode

**Closed** 2024-06-03 11:45 UTC
Labels: T-feature, Cmd-forge-test, C-forge, A-cheatcodes, P-low, D-hard
