### ISSUE TITLE
`forge install` does not show any progress on macOS

### ISSUE THREAD

**Issue by StErMi** [foundry-rs/foundry#4247] opened 2023-02-02 07:15 UTC
### Component

Forge

### Describe the feature you would like

When I try to install forge libs on a cloned repo I get no progress/user feedback on what's happening. 

I would like to know

1) what forge is installing 
2) the overall progress of the installation process

forge v: forge 0.2.0 (cd7850b 2023-02-02T00:05:14.844624Z)

**Comment by zerosnacks** [comment] 2024-07-01 14:40
Marking as `unable to reproduce`

Feel free to re-open if you are still experiencing this issue

**Closed by zerosnacks** 2024-07-01 14:40 UTC
Labels: T-feature
