### ISSUE TITLE
Unexpected behavior when using vm.prank in a Foundry test

### ISSUE THREAD

**Issue by roudra323** [foundry-rs/foundry#8740] opened 2024-08-26 04:52 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (6822860 2024-07-29T00:20:30.057117769Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

# Unexpected Behavior with vm.prank in Foundry Tests

## Issue Description

I've encountered an unexpected behavior when using `vm.prank` in a Foundry test. It appears that the pranked address is only being applied to the first function call after `vm.prank`, even when that call is part of the arguments of a subsequent call.

## Code Snippet

```solidity
vm.prank(COMMUNITY_CREATOR);
artBlockNFT.approve(address(mainEngine), artBlockNFT.getTokenId(userProductID));
```

## Expected Behavior

I expected `vm.prank(COMMUNITY_CREATOR)` to set the caller address to `COMMUNITY_CREATOR` for the entire `approve` call, including the nested `getTokenId` call.

## Actual Behavior

The test output suggests that only `getTokenId` is called with the pranked address, while `approve` is called with a different address:

```
├─ [0] VM::prank(COMMUNITY_CREATOR: [0x3140316e3923d01946617334372A56dc30ecdfbB])
│   └─ ← [Return] 
├─ [670] ArtBlockNFT::getTokenId(0xa750005500000000000000000000000000000000000000000000000000000000) [staticcall]
│   └─ ← [Return] 0
├─ [3311] ArtBlockNFT::approve(MainEngine: [0xbD7A792B8B0943A2f6716974fe1755E7f36aa5b0], 0)
│   └─ ← [Revert] ERC721InvalidApprover(0x7FA9385bE102ac3EAc297483Dd6233D62b3e1496)
└─ ← [Revert] ERC721InvalidApprover(0x7FA9385bE102ac3EAc297483Dd6233D62b3e1496)
```

The `approve` call is reverting with `ERC721InvalidApprover`, suggesting it's not being called by `COMMUNITY_CREATOR`.

## Questions

1. Is this the intended behavior of `vm.prank`? 
2. If not, is this a bug in Foundry?
3. If this is intended, what's the correct way to ensure both `getTokenId` and `approve` are called by the pranked address?

Any insights or clarifications on this behavior would be greatly appreciated. Thank you!

**Comment by yash-atreya** [comment] 2024-08-26 07:50
This is intended behavior for `vm.prank`. 
You can use `vm.startPrank(addr)` for your use-case.

eg. 
```solidity
vm.startPrank(COMMUNITY_CREATOR)
artBlockNFT.approve(address(mainEngine), artBlockNFT.getTokenId(userProductID));
vm.stopPrank()
```

**Comment by zerosnacks** [comment] 2024-08-26 08:25
Marking as resolved by https://github.com/foundry-rs/foundry/issues/8740#issuecomment-2309571665, expected behavior.

**Closed by zerosnacks** 2024-08-26 08:25 UTC
Labels: A-cheatcodes
