### ISSUE TITLE
Line number of failed assert would be very helpful

### ISSUE THREAD

**Issue by georgercarder** [foundry-rs/foundry#8523] opened 2024-07-25 17:07 UTC
### Component

Forge

### Describe the feature you would like

It would be very helpful if the line number of the failed assert were printed in the console.

**Comment by zerosnacks** [comment] 2024-07-26 09:50
Agreed! Marking as duplicate of https://github.com/foundry-rs/foundry/issues/7930, added your request for printing this on failed asserts to the ticket description

**Closed by zerosnacks** 2024-07-26 09:50 UTC
Labels: A-testing, T-feature
