### ISSUE TITLE
`forge install smartcontractkit/ccip@contracts-ccip/v1.2.1` fails with "remote: Not Found" due to tag name containing "/"

### ISSUE THREAD

**Issue by DJViau** [foundry-rs/foundry#5996] opened 2023-10-05 19:40 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (2fc85cb 2023-10-05T00:18:04.223871000Z)

### What command(s) is the bug in?

forge

### Operating System

macOS (Apple Silicon)

### Describe the bug

`forge install transmissions11/solmate@branch/name/with-slashes` fails but `forge install transmissions11/solmate@branch-name-with-dashes` works.

The first outputs the erroneous message:

```
Installing with-slashes in /Users/user/path/project/lib/with-slashes (url: Some("https://github.com/transmissions11/solmate@branch/name/with-slashes"), tag: None)
...
```

The second outputs the expected message:

```
Installing solmate in /Users/user/path/project/lib/solmate (url: Some("https://github.com/transmissions11/solmate"), tag: Some("branch-name-with-dashes"))
...
```

I'm inferring that forge is splitting on `/` naively, which is messing up accessing the repo name and the tag.

Edit:

This was clarified here: https://github.com/foundry-rs/foundry/issues/5996#issuecomment-2010030371

**Comment by jaketimothy** [comment] 2023-12-18 01:27
Would love this. Example: https://github.com/smartcontractkit/ccip/releases/tag/contracts-ccip%2Fv1.2.1

**Comment by Evalir** [comment] 2023-12-18 12:54
Closing, cannot reproduce

**Comment by bayological** [comment] 2024-01-04 17:18
@Evalir 
> Closing, cannot reproduce

This is still an issue, and I'm currently experiencing it, can this be reopened. 
I have two branches, develop & feat/tokenWork, on [this repo](https://github.com/mento-protocol/mento-core) that can be used to reproduce. 

Running the following works fine:
`forge install mento-protocol/mento-core@develop `

But running the install command using the branch that includes a slash I get this:
`forge install mento-protocol/mento-core@feat/tokenWork`

![image](https://github.com/foundry-rs/foundry/assets/6872903/d9578f21-275b-45fd-b6f4-a2251a54971f)

In the error logs you can see it cannot find the repository `https://github.com/mento-protocol/mento-core@feat/tokenWork/` which is correct as that is not the correct URL for the branch. The correct URL is `https://github.com/mento-protocol/mento-core/tree/feat/tokenWork`

Forge version is: `forge 0.2.0 (0f20cc6 2024-01-03T00:16:29.596863086Z)`
Operating System : `Ubuntu 22.04.3 LTS`

**Comment by Evalir** [comment] 2024-01-04 17:22
interesting, thanks for reporting @bayological — will reopen

**Comment by matYang** [comment] 2024-03-20 16:44
+1 here, we've found that if the tag name contains the character "/", forge install is unable to parse it, e.g. for a valid tag name of `contracts-ccip/v1.2.1`
```
forge install smartcontractkit/ccip@contracts-ccip/v1.2.1
```
foundry fails to parse the tag
```
Installing v1.2.1 in /Users/mattyang/Desktop/code/experiments/foundry-learn/foundry-starter-kit/lib/v1.2.1 (url: Some("https://github.com/smartcontractkit/ccip@contracts-ccip/v1.2.1"), tag: None)
```
then git cmd exits with code 128.
This is not a problem if tag name does not contain "/"

**Comment by grandizzy** [comment] 2024-10-28 13:53
I considered adding a `tag=` / `branch=` arg but I think the UX friendly way (and already supported) is to specify the full path, for example

```bash
forge install smartcontractkit/ccip@contracts-ccip/v1.2.1
```

is actually
```
forge install smartcontractkit/ccip@contracts-ccip/v1.2.1
```

and a specific branch can be installed as
```
forge install smartcontractkit/ccip/releases/tag/contracts-ccip/v1.2.1
```

@mattsse @zerosnacks @yash-atreya pls chime in

**Comment by mattsse** [comment] 2024-10-28 16:38
introducing @tag etc makes sense to me

**Closed** 2024-10-28 18:35 UTC
Labels: T-bug, C-forge, Cmd-forge-pm
