### ISSUE TITLE
Arithmetic operation overflow

### ISSUE THREAD

**Issue by cxkoda** [foundry-rs/foundry#4296] opened 2023-02-07 17:36 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (ebe1b45 2023-02-07T00:07:26.750861174Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

Running the following test results in forge crashing with the output shown at the bottom. 
For a reprod see also https://github.com/cxkoda/forge-overflow and the [CI logs](https://github.com/cxkoda/forge-overflow/actions/runs/4116468804/jobs/7106553424) there.

```solidity
pragma solidity ^0.8.15;

import {Test} from "forge-std/Test.sol";
import {Vm} from "forge-std/Vm.sol";

contract Item {}

contract ItemTest is Test {
    function _canReceiveETH(address payable receiver) internal returns (bool) {
        uint256 startReceiverBalance = receiver.balance;

        vm.deal(address(this), 1);
        (bool success,) = receiver.call{value: 1}("");

        vm.deal(receiver, startReceiverBalance);
        return success;
    }

    function testForwardETH(address payable target) public {
        vm.assume(_canReceiveETH(target));

        for (uint256 i; i < 50; ++i) {
            Item item = new Item();
            vm.assume(address(item) != address(target));
        }
    }
}
```

---

```bash
The application panicked (crashed).
Message:  arithmetic operation overflow
Location: /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/primitive-types-0.12.1/src/lib.rs:38

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: start_thread<unknown>
      at ./nptl/pthread_create.c:442
   2: clone3<unknown>
      at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Aborted (core dumped)
```

**Comment by zerosnacks** [comment] 2024-06-28 14:48
Unable to reproduce, marking as duplicate of https://github.com/foundry-rs/foundry/issues/4489

**Closed by zerosnacks** 2024-06-28 14:48 UTC
Labels: T-bug, Cmd-forge-test, T-to-reproduce
