### ISSUE TITLE
Forge script -- verify failing on polygon

### ISSUE THREAD

**Issue by FabienCoutant** [foundry-rs/foundry#5379] opened 2023-07-13 13:44 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e488e2b 2023-07-10T15:17:42.605282000Z)

### What command(s) is the bug in?

forge script script/01_ImplementationManager.s.sol --rpc-url ${NETWORK} --broadcast --verify --optimize

### Operating System

macOS (Apple Silicon)

### Describe the bug

Trying to deploy my contract and verify it using forge script on polygon but the verification failing every times (I had deployed on sepolia without any issue)

Here my `foundry.toml` setup :
```
[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/${INFURA_KEY}"
sepolia = "https://sepolia.infura.io/v3/${INFURA_KEY}"
polygon = "https://polygon-mainnet.infura.io/v3/${INFURA_KEY}"

[etherscan]
mainnet = {key = "${ETHERSCAN_API_KEY}" }
sepolia = {key = "${ETHERSCAN_API_KEY}" }
polygon = {key = "${POLYGONSCAN_API_KEY}", chain = 137, url = "https://api.polygonscan.com/api/" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
```

and here the cmd run and the result:
```
> cross-env && forge script script/01_ImplementationManager.s.sol --rpc-url ${NETWORK} --broadcast --verify --optimize

[⠰] Compiling...
No files changed, compilation skipped
Script ran successfully.

EIP-3855 is not supported in one or more of the RPCs used.
Unsupported Chain IDs: 137.
Contracts deployed with a Solidity version equal or higher than 0.8.20 might not work properly.
For more information, please see https://eips.ethereum.org/EIPS/eip-3855

## Setting up (1) EVMs.

==========================

Chain 137

Estimated gas price: 164.981681361 gwei

Estimated total gas used for script: 323286

Estimated amount required: 0.053336267840472246 ETH

==========================

###
Finding wallets for all the necessary addresses...
##
Sending transactions [0 - 0].
⠁ [00:00:00] [##########################################################################################################################################################################################] 1/1 txes (0.0s)
Transactions saved to: /Users/xutyr/Dev/Cloover/Contracts/broadcast/01_ImplementationManager.s.sol/137/run-latest.json

Sensitive values saved to: /Users/xutyr/Dev/Cloover/Contracts/cache/01_ImplementationManager.s.sol/137/run-latest.json

##
Waiting for receipts.
⠉ [00:00:06] [######################################################################################################################################################################################] 1/1 receipts (0.0s)
##### polygon
✅ Hash: 0x06897546e6d8cbd24d50924bfdde831ac633a30909f25a27a4db84337f5fc26a
Contract Address: 0x4840f5a6d73E5841ec99Db9a221B447cF0375407
Block: 45030705
Paid: 0.037706475225533604 ETH (248682 gas * 151.625269322 gwei)


Transactions saved to: /Users/xutyr/Dev/Cloover/Contracts/broadcast/01_ImplementationManager.s.sol/137/run-latest.json

Sensitive values saved to: /Users/xutyr/Dev/Cloover/Contracts/cache/01_ImplementationManager.s.sol/137/run-latest.json



==========================

ONCHAIN EXECUTION COMPLETE & SUCCESSFUL.
Total Paid: 0.037706475225533604 ETH (248682 gas * avg 151.625269322 gwei)
##
Start verification for (1) contracts
Start verifying contract `0x4840f5a6d73e5841ec99db9a221b447cf0375407` deployed on polygon

Transactions saved to: /Users/xutyr/Dev/Cloover/Contracts/broadcast/01_ImplementationManager.s.sol/137/run-latest.json

Sensitive values saved to: /Users/xutyr/Dev/Cloover/Contracts/cache/01_ImplementationManager.s.sol/137/run-latest.json

Error: 
expected value at line 1 column 1
 ELIFECYCLE  Command failed with exit code 1.
```

But it's working using `verify-contract`
```
╰─ forge verify-contract \                        
    --chain-id 137 \
    --num-of-optimizations 200 \
    --watch \
    --constructor-args $(cast abi-encode "constructor(address)" "0x6273393d54d7133b5b24500f7bd85152b3bd5d71") \
    --etherscan-api-key "MyKey" \
    --compiler-version v0.8.19+commit.7dd6d404 \
    0x4840f5a6d73E5841ec99Db9a221B447cF0375407 \
    src/core/ImplementationManager.sol:ImplementationManager
Start verifying contract `0x4840f5a6d73E5841ec99Db9a221B447cF0375407` deployed on polygon

Submitting verification for [src/core/ImplementationManager.sol:ImplementationManager] "0x4840f5a6d73E5841ec99Db9a221B447cF0375407".

Submitted contract for verification:
        Response: `OK`
        GUID: `1icrqdpjdzvwh4mgzbfejwcwqnpfjcxi8mrmw2nxhmykrejppv`
        URL:
        https://polygonscan.com/address/0x4840f5a6d73E5841ec99Db9a221B447cF0375407
Contract verification status:
Response: `NOTOK`
Details: `Pending in queue`
Contract verification status:
Response: `OK`
Details: `Pass - Verified`
Contract successfully verified
```

**Comment by FabienCoutant** [comment] 2023-07-13 14:10
Closing the issue found the solution

**Comment by kevinstubbs** [comment] 2023-07-16 06:43
Just had this happen to me, however it was because I was using an etherscan API key rather than polygonscan API key. I see it might not be the case for you (having a separate env variable for that), but I would double-check that you really have the correct key from polygonscan in there.

**Comment by Evalir** [comment] 2023-08-18 14:48
Closing as duplicate of https://github.com/foundry-rs/foundry/issues/5251

**Closed by Evalir** 2023-08-18 14:48 UTC
Labels: T-bug
