### ISSUE TITLE
The application panicked (crash) -- forge script

### ISSUE THREAD

**Issue by aiwowo1** [foundry-rs/foundry#3646] opened 2022-11-08 20:43 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (28312e7 2022-10-13T00:10:05.477412592Z)

### What command(s) is the bug in?

new ContractName()

### Operating System

Linux

### Describe the bug

I'm trying to use forge script to test deploying a contract with an external library. The script I use is: 
` forge script ForkDeploy.s.sol --broadcast -vvvv`

I got the error message:

```
The application panicked (crashed).
Message:  You must provide an RPC URL (see --fork-url) when broadcasting.
Location: cli/src/cmd/forge/script/cmd.rs:202

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Aborted
```

I have tried using the same script but given the RPC_URL as the error message suggested and it worked:
forge script ForkDeploy.s.sol --broadcast -vvvv --fork-url $MAINNET_RPC_URL

I would like to use the fork simulator instead of explicitly giving the RPC_URL. 

Also the same `forge script ` would work if I don't use the external library. 

The script:
```
        string memory MAINNET_RPC_URL = vm.envString('MAINNET_RPC_URL');
        uint256 mainnetFork = vm.createFork(MAINNET_RPC_URL);
        vm.selectFork(mainnetFork);
        string memory mnemonic = vm.envString('MNEMONIC');
        uint256 privateKey = vm.deriveKey(mnemonic, 0);
        address deployer = vm.addr(privateKey);

        vm.startBroadcast(deployer);
     
        AmmalgamFactory factory = new AmmalgamFactory(deployer);  <-- problem line
        
        vm.stopBroadcast();

```

**Comment by mattsse** [comment] 2022-11-11 15:29
you're forge version appears to be outdated

does this also happen with the newest build?

**Comment by aiwowo1** [comment] 2022-11-11 18:11
Yes still broken with the latest forge version: 
foundryup: installed - forge 0.2.0 (c5791f5 2022-11-11T00:07:57.448068674Z)
forge 0.2.0 (c5791f5 2022-11-11T00:07:57.448068674Z)

Here are my full script and command:

```
// SPDX-License-Identifier: GPL-3.0-only
pragma solidity ^0.8.13;

import 'forge-std/Script.sol';
import {AmmalgamFactory} from '../contracts/AmmalgamFactory.sol';

contract ForkDeploy is Script {
    function run() external {
        string memory MAINNET_RPC_URL = vm.envString('MAINNET_RPC_URL');
        uint256 mainnetFork = vm.createFork(MAINNET_RPC_URL);
        vm.selectFork(mainnetFork);
        string memory mnemonic = vm.envString('MNEMONIC');
        uint256 privateKey = vm.deriveKey(mnemonic, 0);
        address deployer = vm.addr(privateKey);

        vm.startBroadcast(deployer);

        AmmalgamFactory factory = new AmmalgamFactory(deployer);
        factory.setFeeTo(deployer);

        vm.stopBroadcast();

        console2.log('Factory Address:', address(factory));
    }
}
```

Run command in WSL (* Ubuntu-20.04  ):
`  forge script ForkDeploy.s.sol -vvvv `

**Comment by aiwowo1** [comment] 2022-11-11 18:12
update the crashing message: 
```
[⠑] Compiling...
[⠒] Compiling 20 files with 0.8.13
[⠆] Solc 0.8.13 finished in 5.36s
Compiler run successful
The application panicked (crashed).
Message:  You must provide an RPC URL (see --fork-url) when broadcasting.
Location: cli/src/cmd/forge/script/cmd.rs:302

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Aborted
```

**Comment by aiwowo1** [comment] 2022-11-11 19:29
Do you have a working example with external library I can test on my end?

**Comment by mattsse** [comment] 2022-11-11 20:17
oh there's a panic due to a massing fork URL.

@joshieDo I'm not entirely sure what effect multifork should have here when broadcasting, given that there's no --fork-url set here

**Comment by aiwowo1** [comment] 2022-11-11 23:29
By providing the --fork-url $MAIN_RPC_URL I got different error:
`Transaction failed when running the on-chain simulation. Check the trace above for more information.`

Looked into the trace, it seems it using the external library (Validations) instead of the factory contract (AmmalgamFactory) to call the setFee() method. and the actual AmmalgamFactory contract is market as Unknown. 

```

  [737795] → new Validations@0x415b2Cf4aB5E84DC60c2dc50295dCEFE91DBFd09
    └─ ← 3170 bytes of code

  [4430496] → new <Unknown>@0x28a7AAEE9b65f00c69548403C6C56058aEBfF87f
    └─ ← 20216 bytes of code

  [21608] Validations::setFeeTo(0x7A153e26cc8ecDF57902c220481ea1c3636108c5)
```

The full trace is here:

```
Traces:
  [4687282] ForkDeploy::run()
    ├─ [0] console::log(Deploying AmmalgamFactory...) [staticcall]
    │   └─ ← ()
    ├─ [0] VM::envString(MAINNET_RPC_URL)
    │   └─ ← <env var value>
    ├─ [0] console::log(MAINNET_RPC_URL, https://mainnet.infura.io/v3/[my-project-key]) [staticcall]
    │   └─ ← ()
    ├─ [0] VM::createFork(https://mainnet.infura.io/v3/5e51c1a70be24721a44796530ec3a0b6)
    │   └─ ← 1
    ├─ [0] VM::selectFork(1)
    │   └─ ← ()
    ├─ [0] VM::envString(MNEMONIC)
    │   └─ ← <env var value>
    ├─ [0] VM::deriveKey(<pk>)
    │   └─ ← <pk>
    ├─ [0] VM::addr(<pk>)
    │   └─ ← 0x7A153e26cc8ecDF57902c220481ea1c3636108c5
    ├─ [0] VM::startBroadcast(0x7A153e26cc8ecDF57902c220481ea1c3636108c5)
    │   └─ ← ()
    ├─ [4070172] → new Validations@0x415b2Cf4aB5E84DC60c2dc50295dCEFE91DBFd09
    │   └─ ← 20216 bytes of code
    ├─ [22699] Validations::setFeeTo(0x7A153e26cc8ecDF57902c220481ea1c3636108c5)
    │   └─ ← ()
    ├─ [0] VM::stopBroadcast()
    │   └─ ← ()
    ├─ [0] console::log(Factory Address:, Validations: [0x415b2Cf4aB5E84DC60c2dc50295dCEFE91DBFd09]) [staticcall]
    │   └─ ← ()
    └─ ← ()


Script ran successfully.

== Logs ==
  Deploying AmmalgamFactory...
  MAINNET_RPC_URL https://mainnet.infura.io/v3/[my-project-key]
  Factory Address: 0x415b2Cf4aB5E84DC60c2dc50295dCEFE91DBFd09

## Setting up (1) EVMs.
==========================
Simulated On-chain Traces:

  [737795] → new Validations@0x415b2Cf4aB5E84DC60c2dc50295dCEFE91DBFd09
    └─ ← 3170 bytes of code

  [4430496] → new <Unknown>@0x28a7AAEE9b65f00c69548403C6C56058aEBfF87f
    └─ ← 20216 bytes of code

  [21608] Validations::setFeeTo(0x7A153e26cc8ecDF57902c220481ea1c3636108c5)
    └─ ← "EvmError: Revert"

Error:

Transaction failed when running the on-chain simulation. Check the trace above for more information.

```

**Comment by aiwowo1** [comment] 2022-11-11 23:31
Just for comparison, this is the successful trace when I did not have the external library 'Validations.sol' added. You can see the setFeeTo is called by the AmmalgamFactory.

```

== Logs ==
  Factory Address: 0x415b2Cf4aB5E84DC60c2dc50295dCEFE91DBFd09

## Setting up (1) EVMs.
==========================
Simulated On-chain Traces:

  [4842299] → new AmmalgamFactory@0x415b2Cf4aB5E84DC60c2dc50295dCEFE91DBFd09
    └─ ← 22122 bytes of code

  [51897] AmmalgamFactory::setFeeTo(0x7A153e26cc8ecDF57902c220481ea1c3636108c5)
    └─ ← ()


==========================
```

**Comment by mds1** [comment] 2023-04-11 23:01
@aiwowo1 it's not clear to me if this is still an issue, and how to reproduce it—I'm going to optimistically close this, but if you are still having this issue, can you provide a repo with steps to reproduce and we can reopen? Thanks!

**Closed by mds1** 2023-04-11 23:01 UTC
Labels: T-bug, C-forge, Cmd-forge-script
