### ISSUE TITLE
"salt" is not accepted in the typed data file for "cast wallet sign"

### ISSUE THREAD

**Issue by akolotov** [foundry-rs/foundry#5912] opened 2023-09-26 08:01 UTC
### Component

Cast

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (2885b0d 2023-09-13T00:28:05.459976172Z)

### What command(s) is the bug in?

cast wallet sign

### Operating System

macOS (Apple Silicon)

### Describe the bug

Try to sign the typed data with the following command `cast wallet sign --interactive --data --from-file ./out/MetaTransaction1.json`. It will out put the following error:
```
Error: 
failed to parse json file: "./out/MetaTransaction1.json": data did not match any variant of untagged enum Type

Context:
- data did not match any variant of untagged enum Type
```
`./out/MetaTransaction1.json`:
```
{
  "domain": {
    "name": "RootChainManager",
    "salt": "0x0000000000000000000000000000000000000000000000000000000000000001",
    "verifyingContract": "0xA0c68C638235ee32657e8f720a23ceC1bFc77C77",
    "version": "1"
  },
  "message": {
    "from": "0x95Ba4cF87D6723ad9C0Db21737D862bE80e93911",
    "functionSignature": "0xe3dec8fb00000000000000000000000095ba4cf87d6723ad9c0db21737d862be80e93911000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb480000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000002dc6c0",
    "nonce": 0
  },
  "primaryType": "MetaTransaction",
  "types": {
    "EIP712Domain": [
      {
        "name": "name",
        "type": "string"
      },
      {
        "name": "version",
        "type": "string"
      },
      {
        "name": "verifyingContract",
        "type": "address"
      },
      {
        "name": "salt",
        "type": "bytes32"
      }
    ],
    "MetaTransaction": [
      {
        "name": "nonce",
        "type": "uint256"
      },
      {
        "name": "from",
        "type": "address"
      },
      {
        "name": "functionSignature",
        "type": "bytes"
      }
    ]
  }
}
```

At the same time if `salt` is replaced by any other sequence everything works as expected:
`./out/MetaTransaction2.json`:
```
{
  "domain": {
    "name": "RootChainManager",
    "z": "0x0000000000000000000000000000000000000000000000000000000000000001",
    "verifyingContract": "0xA0c68C638235ee32657e8f720a23ceC1bFc77C77",
    "version": "1"
  },
  "message": {
    "from": "0x95Ba4cF87D6723ad9C0Db21737D862bE80e93911",
    "functionSignature": "0xe3dec8fb00000000000000000000000095ba4cf87d6723ad9c0db21737d862be80e93911000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb480000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000002dc6c0",
    "nonce": 0
  },
  "primaryType": "MetaTransaction",
  "types": {
    "EIP712Domain": [
      {
        "name": "name",
        "type": "string"
      },
      {
        "name": "version",
        "type": "string"
      },
      {
        "name": "verifyingContract",
        "type": "address"
      },
      {
        "name": "z",
        "type": "bytes32"
      }
    ],
    "MetaTransaction": [
      {
        "name": "nonce",
        "type": "uint256"
      },
      {
        "name": "from",
        "type": "address"
      },
      {
        "name": "functionSignature",
        "type": "bytes"
      }
    ]
  }
}
```

```
cast wallet sign --interactive --data --from-file ./out/MetaTransaction2.json
Enter private key: 
0x2e7452c91f55802475bc4cd921f8f12d016d026e89f5444940004f7ccd73fc407b8fce966d2c683532c222cde2b388d60222e1bdcb9ee5beeffb8a790de1218c1b
```

**Comment by zerosnacks** [comment] 2024-07-04 11:25
Unable to reproduce with given setup:

In `foo.json`

```json
{
  "domain": {
    "name": "RootChainManager",
    "salt": "0x0000000000000000000000000000000000000000000000000000000000000001",
    "verifyingContract": "0xA0c68C638235ee32657e8f720a23ceC1bFc77C77",
    "version": "1"
  },
  "message": {
    "from": "0x95Ba4cF87D6723ad9C0Db21737D862bE80e93911",
    "functionSignature": "0xe3dec8fb00000000000000000000000095ba4cf87d6723ad9c0db21737d862be80e93911000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb480000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000002dc6c0",
    "nonce": 0
  },
  "primaryType": "MetaTransaction",
  "types": {
    "EIP712Domain": [
      {
        "name": "name",
        "type": "string"
      },
      {
        "name": "version",
        "type": "string"
      },
      {
        "name": "verifyingContract",
        "type": "address"
      },
      {
        "name": "salt",
        "type": "bytes32"
      }
    ],
    "MetaTransaction": [
      {
        "name": "nonce",
        "type": "uint256"
      },
      {
        "name": "from",
        "type": "address"
      },
      {
        "name": "functionSignature",
        "type": "bytes"
      }
    ]
  }
}
```

```
cast wallet sign --interactive --data --from-file foo.json
Enter private key:
0x99639e1358ab52aa60ec508b0b4c84e0b0cc202b468510353f06b0cf7a64b8460c918f4f3f7e750b34e2e7b5b03252d3930225f7f2110c1cee405f46eb14e7f11b
```

Marking as resolved

**Closed by zerosnacks** 2024-07-04 11:25 UTC
Labels: T-bug

**Comment by Joselinosko** [comment] 2024-09-20 07:54
0x95ba4cf87d6723ad9c0db21737d862be80e93911
