### ISSUE TITLE
Limit for contacts cloning

### ISSUE THREAD

**Issue by 0xmikko** [foundry-rs/foundry#5796] opened 2023-09-07 08:35 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (dbfd8d9 2023-09-06T12:58:39.679860620Z)

### What command(s) is the bug in?

forge t 

### Operating System

Linux

### Describe the bug

In testing contracts, we have a function, which clones contracts:
```
 function takeCreditAccount(uint256, uint256) external override returns (address creditAccount) {
        FactoryParams storage fp = _factoryParams[msg.sender];

        address masterCreditAccount = fp.masterCreditAccount;
        if (masterCreditAccount == address(0)) {
            revert CallerNotCreditManagerException(); // U:[AF-1]
        }

        uint256 head = fp.head;
        if (head == fp.tail || block.timestamp < _queuedAccounts[msg.sender][head].reusableAfter) {
            creditAccount = Clones.clone(masterCreditAccount); // U:[AF-2A]
            emit DeployCreditAccount({creditAccount: creditAccount, creditManager: msg.sender}); // U:[AF-2A]
        } else {
            creditAccount = _queuedAccounts[msg.sender][head].creditAccount; // U:[AF-2B]
            delete _queuedAccounts[msg.sender][head]; // U:[AF-2B]
            unchecked {
                ++fp.head; // U:[AF-2B]
            }
        }

        emit TakeCreditAccount({creditAccount: creditAccount, creditManager: msg.sender}); // U:[AF-2A,2B]
    }
```

As you can see, it calls ```Clones.clone``` method for cloning a contract. It works perfect, until the depth < ~25 (for testing purposes, I have only one function which creates accounts). Then, it provides the following error:

```new <Unknown>@0xA14a1b426bdA7ca0F83450dBd2DF61dA907D7ee7
    │   │   │   │   └─ ← 0 bytes of code
    │   │   │   └─ ← "ERC1167: create failed"
    │   │   └─ ← "ERC1167: create failed"
    │   └─ ← "ERC1167: create failed"
    └─ ← "ERC1167: create failed"
 ```
 
It seems that the problem related to `factory contract nonce`, when it's not updated on time

**Comment by 0xmikko** [comment] 2023-11-28 22:08
Sure, you can:

1. `git clone https://github.com/Gearbox-protocol/core-v3.git`
2. `git checkout invariant-bug`
3. `yarn`
4. `forge t --mt invariant`

**Comment by zerosnacks** [comment] 2024-07-03 14:32
Hi @0xmikko 

I'm (un)fortunately unable to reproduce the bug. Following the instructions yields:

```
$ forge t --mt invariant
Ran 1 test for contracts/test/invaritants/OpenInvariants.t.sol:InvariantGearboxTest
[PASS] invariant_credit_accounts() (runs: 200, calls: 10000, reverts: 0)
Suite result: ok. 1 passed; 0 failed; 0 skipped; finished in 42.34s (42.32s CPU time)

Ran 1 test suite in 42.34s (42.34s CPU time): 1 tests passed, 0 failed, 0 skipped (1 total tests)
```

For good measure I ran it twice, no different result

Marking as `resolved`, feel free to re-open if you are able to reproduce it or run into the issue again

**Closed by zerosnacks** 2024-07-03 14:32 UTC
Labels: T-bug
