### ISSUE TITLE
`create` reverts once a contract gets past a certain nonce while invariant testing

### ISSUE THREAD

**Issue by haydenshively** [foundry-rs/foundry#6074] opened 2023-10-20 22:55 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (619f3c5 2023-10-20T00:17:29.281153000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

After a given contract deploys ~200 other contracts via `create`, further deployments fail.

**Steps to reproduce**

- Create a test file like so:
```Solidity
contract Anything {
    function foo() external pure returns (string memory) {
        return "Hello World";
    }
}

contract Deployer {
    function deploy() external {
        new Anything();
    }
}

contract DeploymentTest is Test {
    Deployer deployer;

    function setUp() public {
        deployer = new Deployer();
    }

    function invariantDoesDeploy() public {
        assertTrue(true);
    }
}
```
- Run with `fail_on_revert = true`

Somewhere around the 200th run, you'll get this:
```bash
[98417310] Deployer::deploy() 
    ├─ [0] → new <Unknown>@0x5B471abaEa413c31a900Bbcde4FBb01d4Ce4C669
    │   └─ ← 0 bytes of code
    └─ ← "EvmError: Revert"
```

This only affects `create`, not `create2`.

**Comment by gtg2619** [comment] 2024-03-26 17:10
Encountered a similar problem. If this issue has been resolved now?

**Comment by vovikhangcdv** [comment] 2024-03-28 05:07
Same here 👍🏼

**Comment by DaniPopes** [comment] 2024-06-27 10:20
I cannot reproduce on the latest build. cc @grandizzy

**Comment by grandizzy** [comment] 2024-06-27 13:33
yep, cannot reproduce either, going to close this one for now, @vovikhangcdv @gtg2619 @haydenshively pls reopen if you still hit such. thank you!

**Closed by grandizzy** 2024-06-27 13:33 UTC
Labels: T-bug
