### ISSUE TITLE
`forge fmt` removes newline from the end of each file

### ISSUE THREAD

**Issue by CodeSandwich** [foundry-rs/foundry#2667] opened 2022-08-09 13:06 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (63ed109 2022-08-09T00:03:50.892098571Z)

### What command(s) is the bug in?

forge fmt

### Operating System

Linux

### Describe the bug

`forge fmt` leaves all `.sol` files without the newline at the end. This makes them non-conformant with POSIX definition of lines of text. It also conflicts with many tools like text editors, which automatically insert the newline at the end of each file. Various code displaying tools like `gitk` also treat lack of the newline as an anomaly which needs to be explicitly highlighted, which generates noise.

**Comment by gakonst** [comment] 2022-08-09 17:08
interesting - cc @rkrasiuk

**Comment by rkrasiuk** [comment] 2022-08-10 07:36
hmm, this looks like a regression. it was addressed in #2177

**Comment by gakonst** [comment] 2022-08-10 22:06
fixed in #2690

**Closed** 2022-08-10 22:06 UTC
Labels: T-bug, C-forge, Cmd-forge-fmt
