### ISSUE TITLE
vm.roll can result in panic on L2 network

### ISSUE THREAD

**Issue by RiccardoBiosas** [foundry-rs/foundry#1649] opened 2022-05-17 22:42 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

As described in [this issue](https://github.com/foundry-rs/foundry/issues/748), forge does not currently handle the idiosyncrasies of each EVM-compatible L2 network. In the context of testing contracts which rely on a block.number delta against an Arbitrum fork pinned at a certain block, using `vm.roll` as a workaround would suffice until now.

However, after upgrading to foundry 2.0, forking an Arbitrum live network pinned at a certain block (i.e.: `forge test --fork-url ARBITRUM_RPC --fork-block-number 1337`) and then using `vm.roll` to set the test contract's `block.number` to an L1 value results in a panic. This prevents me from testing some logic where the L2 contract calculates the difference between a `lastBlockNumber` variable and the current block.number (both L1 values).

I think that the change responsible for this behavior is [this commit](https://github.com/foundry-rs/foundry/commit/ceaecc660caada579b28f3f4967e6fb40c594e66#diff-61de971a1475be0209ee9896ce71d6b3424904b26eb2ea0227d1ff23ee4e6e6bR309). In fact, after downgrading foundry to the [previous commit](https://github.com/foundry-rs/foundry/commit/4415ff47cc03c9f9657dd2959f57de411a4e67b2) ( `foundryup -C 4415ff47cc03c9f9657dd2959f57de411a4e67b2`), the test/`vm.roll` worked again as expected

**Comment by mattsse** [comment] 2022-05-22 10:44
thanks for raising this, 

> using vm.roll to set the test contract's block.number to an L1 value results in a panic. 

this is the expected behavior, because the fork is bound to a specific chain.

#ceaecc660 introduced panics because that's the only safe behavior when we failed to look up data on the fork.

this is good feedback and we're working on making forking support more flexible for different L2s: https://github.com/foundry-rs/foundry/issues/834

so you can easily switch the context from within your test and the use case you're describing should be possible.

**Comment by mattsse** [comment] 2022-08-01 19:50
it's not handled automatically yet, a workaround is described here https://github.com/foundry-rs/foundry/issues/748#issuecomment-1178906548

we decided to hold off on this until the major L2 upgrades are rolled out before baking in chain agnostic stuff.

but I think we can close this in favor of #748 ?

**Comment by onbjerg** [comment] 2022-08-01 19:51
Yeah, agreed :+1:

**Closed by onbjerg** 2022-08-01 19:51 UTC
Labels: T-bug, Cmd-forge-test, C-forge, A-cheatcodes, P-high
