### ISSUE TITLE
Publish Crates To Crates.IO For All Foundry Related Crates

### ISSUE THREAD

**Issue by bonedaddy** [foundry-rs/foundry#2107] opened 2022-06-24 07:22 UTC
### Component

Other (please describe)

### Describe the feature you would like

Published crates on https://crates.io for all foundry related crates (`cast`, `forge`, `foundry` ,etc..)

**Comment by onbjerg** [comment] 2022-06-24 22:08
Duplicate of https://github.com/foundry-rs/foundry/issues/665

**Closed by onbjerg** 2022-06-24 22:08 UTC
Labels: T-feature
