### ISSUE TITLE
Go back to lazy-loading fields in [etherscan] config section

### ISSUE THREAD

**Issue by adhusson** [foundry-rs/foundry#4550] opened 2023-03-14 00:45 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [x] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (a1f41be 2023-03-14T00:15:36.156534Z)

### What command(s) is the bug in?

`forge script`

### Operating System

macOS (Apple Silicon)

### Describe the bug

Since 93aa2d071b635a838030aa29ad85b52d361f5728 any env variable used in [etherscan] must be present or forge will fail. For instance with:

```toml
[etherscan]
mumbai={key="${POLYGON_API_KEY}"}
```

if you run `forge script` locally without verification (and without broadcast) you will get:

```
Failed to resolve env var `POLYGON_API_KEY` in `${POLYGON_API_KEY}`: environment variable not found
```

That was not the case before 93aa2d071b635a838030aa29ad85b52d361f5728. And it makes sense to lazy-load, you can have scripts in a project that will only be run on a local node (and some people will only use it this way). Those will not use some sections of the config file.

**Comment by mattsse** [comment] 2023-03-14 09:18
@DaniPopes looks like a regression.
do you have bandwidth to investigate?

**Comment by DaniPopes** [comment] 2023-03-14 10:23
This is already the case: environment variables are only resolved when `Config::get_etherscan...` is called, so on-demand.
I could only reproduce this with a fork url, and the error happens here, when trying to decode Etherscan traces:

https://github.com/foundry-rs/foundry/blob/1e0b628d47a7fc18f4fbe0b0b84581fe6a9ad3b3/cli/src/cmd/forge/script/mod.rs#L202-L212

Previously the variable wasn't even getting resolved in the first place, so that's why this error never showed up.

**Comment by adhusson** [comment] 2023-03-14 10:25
I'm confused, if I start a `forge script` without verify, without broadcast (but with a fork-url indeed), the script doesn't start and the error pops up immediately.

**Comment by DaniPopes** [comment] 2023-03-14 10:47
Yes. Since you're using a fork URL, we assume the possibility that you're calling external contracts, which we need to decode the traces of. This uses the config's Etherscan API key when / if available, which cannot be done if there's a bad config

**Comment by adhusson** [comment] 2023-03-14 11:07
Ah yes this makes sense. Is it possible to only decode the field that corresponds to the current chainId? The fork-url (in our case) is a vanilla anvil node.

**Comment by grandizzy** [comment] 2024-10-29 13:53
we're not planning to add possibility to decode field for current chain ids, going to close this as not planned. thank you!

**Closed by grandizzy** 2024-10-29 13:53 UTC
Labels: T-bug, Cmd-forge-test, C-forge, Cmd-forge-script, A-config
