### ISSUE TITLE
forge test --gas-report is generating gas report only relevant to test written

### ISSUE THREAD

**Issue by web3dopamine** [foundry-rs/foundry#4486] opened 2023-03-06 16:02 UTC
After running default foundry template and trying to get gas reports with `forge test --gas-report`
i am only able to get reports only if the test is written as shown in the image 
![image](https://user-images.githubusercontent.com/14943387/223163710-e6a8bb39-1205-431d-8ec0-4f1cb46a41c3.png).

But when i comment out the test file no report is generated as shown in the image
![image](https://user-images.githubusercontent.com/14943387/223164085-beac82ce-b295-41ef-aa14-348d58c44761.png)

**Comment by mattsse** [comment] 2023-03-06 16:09
hmm, since there's nothing being executed I think this would be the expected behaviour?

**Comment by web3dopamine** [comment] 2023-03-06 16:13
> hmm, since there's nothing being executed I think this would be the expected behaviour?

Isnt `forge test --gas-report` suppose to report gas whether test are written or not?

**Comment by mattsse** [comment] 2023-03-06 16:24
I'm not sure I understand.

the functions have to be called in order to get the gas

**Comment by web3dopamine** [comment] 2023-03-06 16:29
So test like the following must be written to generate gas report??

i cannot generate a report without having a test?




`    // SPDX-License-Identifier: UNLICENSED`
             

     import "forge-std/Test.sol";
     import "../src/Counter.sol";

      contract CounterTest is Test {
        Counter public counter;

        function setUp() public {
          counter = new Counter();
          counter.setNumber(0);
      }

    function testIncrement() public {
        counter.increment();
        assertEq(counter.number(), 1);
    }

    function testSetNumber(uint256 x) public {
        counter.setNumber(x);
        assertEq(counter.number(), x);
    }

**Comment by mattsse** [comment] 2023-03-06 16:31
forge test does not execute anything if there's no test.
so you don't know how much gas a function would consume.
which is required by --gas-report

**Comment by web3dopamine** [comment] 2023-03-06 16:37
ok, foundry does not have that.

sorry to take your time, the docs does not mention that explicitly

**Comment by mattsse** [comment] 2023-03-06 16:43
> we can calculate the gas consumed without executing the function

yes and no, because only using opcodes only gets you so far until there are conditions.

**Comment by mattsse** [comment] 2023-03-06 17:05
I believe you're just missing some addtional settings:

https://book.getfoundry.sh/config/vscode?highlight=vscode#integrating-with-vscode

**Comment by web3dopamine** [comment] 2023-03-06 17:09
i added those settings and the issue still persist  :)

**Comment by mattsse** [comment] 2023-03-06 17:49
hmm what extension are you using,
perhaps it's time to finally integrate this properly. can take a look.

**Comment by web3dopamine** [comment] 2023-03-06 18:33
Name: solidity
Id: JuanBlanco.solidity
Description: Ethereum Solidity Language for Visual Studio Code
Version: 0.0.141
Publisher: Juan Blanco
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=JuanBlanco.solidity

This is how my `settings.json` looks like
![image](https://user-images.githubusercontent.com/14943387/223199549-5c1146fb-9fba-4eec-83c3-9a65cab8cf1f.png)

**Comment by mds1** [comment] 2023-03-07 18:36
I'd recommend using the Hardhat VSCode extension instead, I've found it's a lot more reliable with foundry projects and you don't need a remappings file

**Comment by alxs** [comment] 2023-04-27 12:29
Agree that this is not the expected behaviour. One should be able to generate a gas report without writing any tests beforehand.

**Comment by Kali-Decoder** [comment] 2023-06-18 19:20
to find the gas report for single file from many sol files in src ??? what is command for that

**Comment by Mr-Beast-bpsr** [comment] 2023-12-08 12:31
> to find the gas report for single file from many sol files in src ??? what is command for that

--match-test  For particular test.
--match-path For particular file.

**Comment by Evalir** [comment] 2023-12-10 20:25
It seems the issue was solved—although we know gas reports can be improved and we'll put in bandwith on this once the alloy migration is complete. I'll close this for now.

**Closed by Evalir** 2023-12-10 20:25 UTC
Labels: T-bug, Cmd-forge-test
