### ISSUE TITLE
Unable to verify contract created by another contract

### ISSUE THREAD

**Issue by Nemusonaneko** [foundry-rs/foundry#3358] opened 2022-09-26 04:48 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (906ba37 2022-09-25T00:04:37.878963958Z)

### What command(s) is the bug in?

forge verify-contract

### Operating System

Linux

### Describe the bug

Was able to verify the factory contract but when I try to verify a contract created through the factory, it fails.

Using this command to verify:
`forge verify-contract --chain-id CHAINID --num-of-optimizations 1000000 --watch --compiler-version 0.8.17+commit.8df45f5f CONTRACT_ADDRESS LlamaPayV2Payer API_KEY`

it fails with the response "NOTOK" and the details "Fail - Unable to verify"

Tried it with multiple testnets and I am having the same issue

[Contract created from](https://github.com/LlamaPay/llamapay-v2/blob/master/src/LlamaPayV2Factory.sol)
[Contract I'm trying to verify](https://github.com/LlamaPay/llamapay-v2/blob/master/src/LlamaPayV2Payer.sol)

**Comment by zerosnacks** [comment] 2024-08-02 11:38
Marking as duplicate of https://github.com/foundry-rs/foundry/issues/6023

It is possible that this case has also been resolved over time as this is quite a common pattern

**Closed by zerosnacks** 2024-08-02 11:38 UTC
Labels: T-bug, C-forge, Cmd-forge-verify
