### ISSUE TITLE
`anvil_setBalance` does not work on Arbitrum fork

### ISSUE THREAD

**Issue by ivelin** [foundry-rs/foundry#4786] opened 2023-04-20 19:56 UTC
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (8307d6d 2023-04-20T00:07:51.981402795Z)

### What command(s) is the bug in?

anvil_setBalance

### Operating System

Linux

### Describe the bug

`anvil_setBalance` works fine on forks of Chain Id 1 (mainnet) and Chain Id 5 (Goerli), however it does not seem to work on Arbitrum forks.

To reproduce:

```bash
$ anvil --chain-id 42161 --fork-url https://arb-mainnet.g.alchemy.com/v2/.....


                             _   _
                            (_) | |
      __ _   _ __   __   __  _  | |
     / _` | | '_ \  \ \ / / | | | |
    | (_| | | | | |  \ V /  | | | |
     \__,_| |_| |_|   \_/   |_| |_|

    0.1.0 (8307d6d 2023-04-20T00:08:07.042011665Z)
    https://github.com/foundry-rs/foundry

Available Accounts
==================

(0) "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266" (10000 ETH)
(1) "0x70997970C51812dc3A010C7d01b50e0d17dc79C8" (10000 ETH)
(2) "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC" (10000 ETH)
(3) "0x90F79bf6EB2c4f870365E785982E1f101E93b906" (10000 ETH)
(4) "0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65" (10000 ETH)
(5) "0x9965507D1a55bcC2695C58ba16FB37d819B0A4dc" (10000 ETH)
(6) "0x976EA74026E726554dB657fA54763abd0C3a0aa9" (10000 ETH)
(7) "0x14dC79964da2C08b23698B3D3cc7Ca32193d9955" (10000 ETH)
(8) "0x23618e81E3f5cdF7f54C3d65f7FBc0aBf5B21E8f" (10000 ETH)
(9) "0xa0Ee7A142d267C1f36714E4a8F75612F20a79720" (10000 ETH)

Private Keys
==================

(0) 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
(1) 0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d
(2) 0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a
(3) 0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6
(4) 0x47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926a
(5) 0x8b3a350cf5c34c9194ca85829a2df0ec3153be0318b5e2d3348e872092edffba
(6) 0x92db14e403b83dfe3df233f83dfa3a0d7096f21ca9b0d6d6b8d88b2b4ec1564e
(7) 0x4bbbf85ce3377467afe5d46f804f221813b2bb87f24d81f60f1fcdbf7cbf4356
(8) 0xdbda1821b80551c9d65939329250298aa3472ba22feea921c0cf5d620ea67b97
(9) 0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6

Wallet
==================
Mnemonic:          test test test test test test test test test test test junk
Derivation path:   m/44'/60'/0'/0/


Base Fee
==================

100000000

Gas Limit
==================

30000000

Genesis Timestamp
==================

1682019745

Fork
==================
Endpoint:       https://arb-mainnet.g.alchemy.com/v2/Kjt13n8OuVVCBqxIGMGYuwgbnLzfh1U6
Block number:   82536691
Block hash:     0x396dbeb8b8f2be3bec050aa53c61e898e3fa7acfd19ba1c81a45fc6a6bad6700
Chain ID:       42161


Listening on 127.0.0.1:8545
```

Then in a another terminal on the same host:
```sh
$ cast balance 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
56311877858242
$ cast balance 0x70997970C51812dc3A010C7d01b50e0d17dc79C8
0
$ cast balance 0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC
0
$ curl http://localhost:8545 -X POST -H "Content-Type: application/json"   --data '{"method":"anvil_setBalance","params":["0xE7616f8F030A611be722A7787Ce183FD78B941C9", "0x021e19e0c9bab2400000"],"id":1,"jsonrpc":"2.0"}'
{"jsonrpc":"2.0","id":1,"result":null} 
$ 
$ 
 $ cast balance 0xE7616f8F030A611be722A7787Ce183FD78B941C9
0
 $ cast balance 0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC
0
 $ cast balance 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
56311877858242
 $ curl http://localhost:8545 -X POST -H "Content-Type: application/json"   --data '{"method":"anvil_setBalance","params":["0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266", "1"],"id":1,"jsonrpc":"2.0"}'
 $ yast balance 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
56311877858242
 $ 
 $ cast balance 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
56311877858242
 $ forge --version
forge 0.2.0 (8307d6d 2023-04-20T00:07:51.981402795Z)
 $ 
```

Notice that the balance of the default anvil wallet accounts is also incorrect. Anvil reports 10000 at startup, but `cast` shows balances of 0 for all except for the first account `0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266`.

**Comment by mattsse** [comment] 2023-04-20 20:48
I was not able to reproduce this:

```
 cast balance 0xE7616f8F030A611be722A7787Ce183FD78B941C9                                        
0

❯ curl http://localhost:8545 -X POST -H "Content-Type: application/json" --data '{"method":"anvil_setBalance","params":["0xE7616f8F030A611be722A7787Ce183FD78B941C9", "0x021e19e0c9bab2400000"],"id":1,"jsonrpc":"2.0"}'
{"jsonrpc":"2.0","id":1,"result":null}%                                                                                   
❯ cast balance 0xE7616f8F030A611be722A7787Ce183FD78B941C9                                        
10000000000000000000000
```

and yes the dev account are always pre funded

**Comment by mattsse** [comment] 2023-04-21 17:39
I used your provider endpoint from above, 

just tested it again, same result 0-> 10000000000000000000000

**Comment by ivelin** [comment] 2023-04-21 20:23
Thank you for the clarification. That's great to hear.
Which anvil version did you use? I should switch to it.

**Comment by Evalir** [comment] 2023-06-27 20:50
Also tested, could not reproduce. Closing!

**Closed by Evalir** 2023-06-27 20:50 UTC
Labels: T-bug

**Comment by Jin-K-Yang** [comment] 2023-07-25 09:18
I have this bug too, I don't know why but I change `chain-id` parameter to 1 and it solves the problem.
Hope Foundry can solve this bug.
