### ISSUE TITLE
Transaction is not packed/executed

### ISSUE THREAD

**Issue by GopherJ** [foundry-rs/foundry#5234] opened 2023-06-27 17:34 UTC
### Component

Anvil

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e918c81 2023-06-27T00:04:31.801932823Z)

### What command(s) is the bug in?

anvil --fork-url ...

### Operating System

Linux

### Describe the bug

Anvil stop mining new blocks and after receiving transactions, it just keep printing:

```
eth_chainId
eth_blockNumber
eth_chainId
eth_blockNumber
eth_chainId
eth_blockNumber
eth_chainId
eth_blockNumber
eth_chainId
eth_blockNumber
eth_chainId
eth_blockNumber
eth_chainId
eth_blockNumber
eth_chainId
eth_blockNumber
eth_chainId
eth_blockNumber
eth_chainId
```

without executing transactions

**Comment by GopherJ** [comment] 2023-06-28 00:12
hi @mattsse but I've disabled the rate limit

```
.PHONY: anvil
anvil:
        @anvil \
                $(if $(FORK),--fork-url https://eth-$(FORK).alchemyapi.io/v2/$(ALCHEMY_KEY) --no-rate-limit,) \
                $(if $(FORK_BLOCK_NUMBER),--fork-block-number $(FORK_BLOCK_NUMBER),) \
                $(if $(FORK),--chain-id 522,--chain-id 31337) \
                $(if $(DEPLOYER_MNEMONIC),--mnemonic "${DEPLOYER_MNEMONIC}",--mnemonic "test test test test test test test test test test test junk") \
                --host 0.0.0.0 \
                --disable-block-gas-limit \
                --code-size-limit 100000 \
```

**Comment by GopherJ** [comment] 2023-06-28 01:15
If I set auto mine, 1 transaction go through:

```
evm_setAutomine
evm_setIntervalMining
eth_blockNumber
eth_chainId

    Transaction: 0x9bab9a54ecf30153a43e912566a25d6cc2b4968afac2ad24ff4e8a32067c2439
    Gas used: 21000

    Block Number: 17557114
    Block Hash: 0x834e16d07854815e8fa7e9f220ba27932c2e6537ddda6d7417a9d19d34f6d915
    Block Time: "Sun, 25 Jun 2023 13:48:55 +0000"

eth_blockNumber
eth_chainId
eth_chainId
eth_getTransactionReceipt
eth_chainId
eth_chainId
eth_call
eth_chainId
eth_call
whale USDT balance: 2143157755246000
supply 10000000 USDT from 0xF977814e90dA44bFA03b6295A0616a897441aceC to 0x018281853eCC543Aa251732e8FDaa7323247eBeB

```

**Comment by GopherJ** [comment] 2023-06-28 01:26
I also tried to manually mine a block, but my transaction is not included

**Comment by GopherJ** [comment] 2023-06-28 06:07
I changed the make target to be:

```
.PHONY: anvil
anvil:
	anvil \
		$(if $(FORK),--fork-url https://eth-$(FORK).alchemyapi.io/v2/$(ALCHEMY_KEY) --chain-id 522 --no-rate-limit,--chain-id 31337) \
		$(if $(FORK_BLOCK_NUMBER),--fork-block-number $(FORK_BLOCK_NUMBER),) \
		$(if $(DEPLOYER_MNEMONIC),--mnemonic "${DEPLOYER_MNEMONIC}",--mnemonic "test test test test test test test test test test test junk") \
		--host 0.0.0.0 \
		--state-interval 60 \
		--dump-state state.json \
		$(if $(wildcard state.json),--load-state state.json,) \
		--disable-block-gas-limit \
		--code-size-limit 100000 \
```
and it looks a little bit better, but I still have one of my transaction blocked there

![image](https://github.com/foundry-rs/foundry/assets/33961674/da9359f0-c106-4557-b3d7-dd388fe18036)

**Comment by GopherJ** [comment] 2023-06-28 06:52
seems this happened after enabling interval mining

**Comment by mattsse** [comment] 2023-06-28 17:24
tbh I'm having some difficulties interpreting all of this.

>  but I still have a big transaction blocked there

not sure what this means

is the tx you're waiting for still in the pool? see `txpool` rpc namespace

**Comment by GopherJ** [comment] 2023-06-30 11:24
hi @mattsse I think the issue is solved on my side, there are multiple things:

- vpn issue (sometimes the vpn is not so good so I image anvil has difficulties to fetch data)
- anvil commands can be optimized by removing `--tracing` and add `--timeout`
- after upgrades anvil looks better
- interval mining was accidently turned on

Now it's fine on my end and feel free to close this issue

**Comment by GopherJ** [comment] 2023-06-30 11:24
I'll try again some big transactions to see if it passes

**Comment by Evalir** [comment] 2023-06-30 21:01
Closing for now—seems the issue was caused by quite a few combination of things. 

@GopherJ def do report back if you keep having issues! Thanks

**Closed by Evalir** 2023-06-30 21:01 UTC
Labels: T-bug
