### ISSUE TITLE
Forge test runs get killed

### ISSUE THREAD

**Issue by pcaversaccio** [foundry-rs/foundry#3070] opened 2022-09-03 10:12 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (4b9cca1 2022-09-03T00:07:00.132143504Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

When I run my tests with the latest Foundry version, my tests get killed locally as well as for GH actions. You can reproduce the bug by cloning my repo [here](https://github.com/pcaversaccio/snekmate) and run `forge test`.

An example failed action: https://github.com/pcaversaccio/snekmate/runs/8168667052?check_suite_focus=true
![image](https://user-images.githubusercontent.com/25297591/188266009-e773c7ae-978e-443b-b74b-da5c0246aa16.png)

Locally it looks like that:
![image](https://user-images.githubusercontent.com/25297591/188266068-2f894df3-7d1d-4ca0-a651-6f87ad3ac625.png)

Seems to be related to a memory allocation issue, but not an expert.

As comparison, I used an older foundry version (`forge 0.2.0 (fb1f0aa 2022-08-29T19:50:24.7749584Z)`) for which the tests worked. So there has been a bug introduced in the meantime I guess.

**Comment by rkrasiuk** [comment] 2022-09-03 10:21
137 is OOM. looks like a duplicate of #3067, is that right @shekhirin?

**Comment by shekhirin** [comment] 2022-09-03 10:31
@rkrasiuk yep, looks like that

**Comment by rkrasiuk** [comment] 2022-09-03 10:32
closing as duplicate. @pcaversaccio will free to follow up in #3067

**Closed by rkrasiuk** 2022-09-03 10:32 UTC
Labels: T-bug, Cmd-forge-test, C-forge

**Comment by adhusson** [comment] 2022-09-03 14:33
having same issue with exit code 129
