### ISSUE TITLE
It seems i can't use `cast wallet sign` to sign rawTx ? 

### ISSUE THREAD

**Issue by nzhl** [foundry-rs/foundry#4897] opened 2023-05-08 12:07 UTC
### Component

Cast

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

cast 0.2.0 (de47eb8 2023-05-08T11:42:26.063038000Z)

### What command(s) is the bug in?

cast wallet sign

### Operating System

macOS (Apple Silicon)

### Describe the bug

I am trying to generate the signature (say y, r, s) for a tx using `cast wallet sign` which will be needed when i undertake rpc call `eth_sendRawTransaction`.

So basically, i have the following tx:

```js
  let transaction = {
    to: '0x7ae1e913465d81ad32d682cceae5c14599456c63',
    value: ethers.utils.parseEther('0'),
    gasLimit: 0x02f287,
    maxPriorityFeePerGas: 0x0121152080,
    maxFeePerGas: 0x0a0e7b58821f,
    data: '0x617ba037000000000000000000000000328507dc29c95c170b56a1b3a758eb7a9e73455c0000000000000000000000000000000000000000000000000de0b6b3a7640000000000000000000000000000bf0135be6a39257c659fd1955324dc3cdb342f290000000000000000000000000000000000000000000000000000000000000000',
    nonce: 0x0315,
    type: 2,
    chainId: 0x05 
  };

```

And after rlp encoding and sha256 i get the following hash:

```
❯ cast --to-rlp '[
  "0x05",
  "0x0315",
  "0x0121152080",
  "0x0a0e7b58821f",
  "0x02f287",
  "0x7ae1e913465d81ad32d682cceae5c14599456c63",
  "0x",
  "0x617ba037000000000000000000000000328507dc29c95c170b56a1b3a758eb7a9e73455c0000000000000000000000000000000000000000000000000de0b6b3a7640000000000000000000000000000bf0135be6a39257c659fd1955324dc3cdb342f290000000000000000000000000000000000000000000000000000000000000000",
  []]'
0xf8b205820315850121152080860a0e7b58821f8302f287947ae1e913465d81ad32d682cceae5c14599456c6380b884617ba037000000000000000000000000328507dc29c95c170b56a1b3a758eb7a9e73455c0000000000000000000000000000000000000000000000000de0b6b3a7640000000000000000000000000000bf0135be6a39257c659fd1955324dc3cdb342f290000000000000000000000000000000000000000000000000000000000000000c0
❯ cast k 0x02f8b205820315850121152080860a0e7b58821f8302f287947ae1e913465d81ad32d682cceae5c14599456c6380b884617ba037000000000000000000000000328507dc29c95c170b56a1b3a758eb7a9e73455c0000000000000000000000000000000000000000000000000de0b6b3a7640000000000000000000000000000bf0135be6a39257c659fd1955324dc3cdb342f290000000000000000000000000000000000000000000000000000000000000000c0
0x3b5dd528fe510056ae401cb9d83ed148df68c310a89da516d13e8a7166a97166
```

`0x3b5dd528fe510056ae401cb9d83ed148df68c310a89da516d13e8a7166a97166` is perfect correct which i have verified with result calculated from etherjs script.

*~~~Here comes the problem~~~*

After i signed the hash with my secret, i got the following signature 

```
> cast wallet  sign --mnemonic $TEST 0x3b5dd528fe510056ae401cb9d83ed148df68c310a89da516d13e8a7166a97166

>0x06ad1ca9425fa04e73b54e9d558568ebb6ab539552b4b125bd844a971e7f875f496482cbfc480b53eafd6c6bd3bbe505b4faea02d66a0e52554bc4f4ef3319ad1b
```

`0x06ad1ca9425fa04e73b54e9d558568ebb6ab539552b4b125bd844a971e7f875f496482cbfc480b53eafd6c6bd3bbe505b4faea02d66a0e52554bc4f4ef3319ad1b` can not be true because either Metamask or my etherjs script gives me the following r, s:

```
❯ cast --from-rlp 0xf8f505820315850121152080860a0e7b58821f8302f287947ae1e913465d81ad32d682cceae5c14599456c6380b884617ba037000000000000000000000000328507dc29c95c170b56a1b3a758eb7a9e73455c0000000000000000000000000000000000000000000000000de0b6b3a7640000000000000000000000000000bf0135be6a39257c659fd1955324dc3cdb342f290000000000000000000000000000000000000000000000000000000000000000c001a09e52033d31027d31f3b1acfcbcf933ff24a643ab1c64f45d4d0a2d3d38639da1a07dd2129b139723fd7951d5313f40c567024ef8069cec6b7f7ce714c0c2a9ce31 | jq
[
  "0x05",
  "0x0315",
  "0x0121152080",
  "0x0a0e7b58821f",
  "0x02f287",
  "0x7ae1e913465d81ad32d682cceae5c14599456c63",
  "0x",
  "0x617ba037000000000000000000000000328507dc29c95c170b56a1b3a758eb7a9e73455c0000000000000000000000000000000000000000000000000de0b6b3a7640000000000000000000000000000bf0135be6a39257c659fd1955324dc3cdb342f290000000000000000000000000000000000000000000000000000000000000000",
  [],
  "0x01",              => y
  "0x9e52033d31027d31f3b1acfcbcf933ff24a643ab1c64f45d4d0a2d3d38639da1",      =>  r
  "0x7dd2129b139723fd7951d5313f40c567024ef8069cec6b7f7ce714c0c2a9ce31"        => s
]
```

**Comment by nzhl** [comment] 2023-05-08 12:19
To make it complete. This is the ethersjs script i used:

```js
const ethers = require('ethers');
const { computeAddress, recoverAddress, serialize, UnsignedTransaction } = require("@ethersproject/transactions");

async function main() {

  let privatekey = '';
  let wallet = new ethers.Wallet(privatekey);

  console.log('Using wallet address ' + wallet.address);

  let transaction = {
    to: '0x7ae1e913465d81ad32d682cceae5c14599456c63',
    value: ethers.utils.parseEther('0'),
    gasLimit: 0x02f287,
    maxPriorityFeePerGas: 0x0121152080,
    maxFeePerGas: 0x0a0e7b58821f,
    data: '0x617ba037000000000000000000000000328507dc29c95c170b56a1b3a758eb7a9e73455c0000000000000000000000000000000000000000000000000de0b6b3a7640000000000000000000000000000bf0135be6a39257c659fd1955324dc3cdb342f290000000000000000000000000000000000000000000000000000000000000000',
    nonce: 0x0315,
    type: 2,
    chainId: 0x05 
  };


  // sign and serialize the transaction 
  let rawTransaction =  serialize(transaction)
  let rawTxHash = ethers.utils.keccak256(rawTransaction);
  let signedRawTransaction = await wallet.signTransaction(transaction)
    // .then(ethers.utils.serializeTransaction(transaction));
  
  // print the raw transaction hash
  console.log('rawTx: ' + rawTransaction);
  console.log();
  console.log('rawTxHash: ' + rawTxHash);
  console.log();
  console.log('signedRawTransaction: ' + signedRawTransaction);
}

main();

```

The output
```
rawTx: 0x02f8b205820315850121152080860a0e7b58821f8302f287947ae1e913465d81ad32d682cceae5c14599456c6380b884617ba037000000000000000000000000328507dc29c95c170b56a1b3a758eb7a9e73455c0000000000000000000000000000000000000000000000000de0b6b3a7640000000000000000000000000000bf0135be6a39257c659fd1955324dc3cdb342f290000000000000000000000000000000000000000000000000000000000000000c0

rawTxHash: 0x3b5dd528fe510056ae401cb9d83ed148df68c310a89da516d13e8a7166a97166

signedRawTransaction: 0x02f8f505820315850121152080860a0e7b58821f8302f287947ae1e913465d81ad32d682cceae5c14599456c6380b884617ba037000000000000000000000000328507dc29c95c170b56a1b3a758eb7a9e73455c0000000000000000000000000000000000000000000000000de0b6b3a7640000000000000000000000000000bf0135be6a39257c659fd1955324dc3cdb342f290000000000000000000000000000000000000000000000000000000000000000c001a09e52033d31027d31f3b1acfcbcf933ff24a643ab1c64f45d4d0a2d3d38639da1a07dd2129b139723fd7951d5313f40c567024ef8069cec6b7f7ce714c0c2a9ce31
```

```
❯ cast --from-rlp f8f505820315850121152080860a0e7b58821f8302f287947ae1e913465d81ad32d682cceae5c14599456c6380b884617ba037000000000000000000000000328507dc29c95c170b56a1b3a758eb7a9e73455c0000000000000000000000000000000000000000000000000de0b6b3a7640000000000000000000000000000bf0135be6a39257c659fd1955324dc3cdb342f290000000000000000000000000000000000000000000000000000000000000000c001a09e52033d31027d31f3b1acfcbcf933ff24a643ab1c64f45d4d0a2d3d38639da1a07dd2129b139723fd7951d5313f40c567024ef8069cec6b7f7ce714c0c2a9ce31 | jq


❯ [
  "0x05",
  "0x0315",
  "0x0121152080",
  "0x0a0e7b58821f",
  "0x02f287",
  "0x7ae1e913465d81ad32d682cceae5c14599456c63",
  "0x",
  "0x617ba037000000000000000000000000328507dc29c95c170b56a1b3a758eb7a9e73455c0000000000000000000000000000000000000000000000000de0b6b3a7640000000000000000000000000000bf0135be6a39257c659fd1955324dc3cdb342f290000000000000000000000000000000000000000000000000000000000000000",
  [],
  "0x01",
  "0x9e52033d31027d31f3b1acfcbcf933ff24a643ab1c64f45d4d0a2d3d38639da1",
  "0x7dd2129b139723fd7951d5313f40c567024ef8069cec6b7f7ce714c0c2a9ce31"
]

```

**Comment by Evalir** [comment] 2023-06-27 20:41
Closing as this is not a bug.

I think we could support this, yes! feel free to file a separate issue.

**Closed by Evalir** 2023-06-27 20:41 UTC
Labels: T-bug

**Comment by radeksvarz** [comment] 2023-12-14 11:55
> Closing as this is not a bug.
> 
> I think we could support this, yes! feel free to file a separate issue.

Seams to be open / related here: #1273
