### ISSUE TITLE
`forge debug` does not have source view

### ISSUE THREAD

**Issue by llllvvuu** [foundry-rs/foundry#5569] opened 2023-08-09 09:57 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (1a110a5 2023-08-08T16:26:20.836709000Z)

### What command(s) is the bug in?

forge debug

### Operating System

macOS (Apple Silicon)

### Describe the bug

Create file `contracts/Counter.sol`: https://solidity-by-example.org/first-app/

Run: `forge debug --debug contracts/Counter.sol --sig "inc()"`

Result:

<img width="1440" alt="Screenshot 2023-08-09 at 2 57 17 AM" src="https://github.com/foundry-rs/foundry/assets/5601392/6a6fe25d-2fe9-4088-8bb5-63089c76bda7">

**Comment by Evalir** [comment] 2023-08-09 16:06
Yep @jameswenzel — I'll try to make time between tomorrow and friday to look into this so we can unblock u and more ppl on the support channel!

Let's close this issue and keep tracking on #5435

**Closed by Evalir** 2023-08-09 16:06 UTC
Labels: T-bug

**Comment by iFrostizz** [comment] 2023-08-09 18:44
@Evalir please note that this very much may be fixed after that https://github.com/foundry-rs/foundry/pull/5547 is merged. We could also do this step by step if better !

**Comment by Evalir** [comment] 2023-08-09 18:54
Right @iFrostizz ! That'd be awesome if the refactor fixed it. A quick fix for this would also be appreciated for this if you know the cause!

**Comment by llllvvuu** [comment] 2023-08-09 22:30
If there's a refactor y'all might find [Debug Adapter Protocol](https://microsoft.github.io/debug-adapter-protocol//) interesting; lets people use VSCode/Vim/whatever as the frontend. I don't think the VSCode UI is necessarily that much better, if at all, but idk, using standard framework could turn out to be easier to build/maintain

Example, rust-analyzer has a pretty nifty CodeLens (although [they may switch to VSCode-specific API](https://github.com/rust-lang/rust-analyzer/issues/3601)) for debug test which I believe passes off to DAP:
![146777918-e3274bf6-200a-4254-96aa-b5b38fa3eda5.png](https://github.com/foundry-rs/foundry/assets/5601392/197d71d8-805a-4cea-95fd-a639492faee3)

**Comment by iFrostizz** [comment] 2023-08-13 19:53
You might wanna try my branch https://github.com/foundry-rs/foundry/pull/5547 tho the source mapping *may* be incorrect
