### ISSUE TITLE
Allow loading environment variables from given path

### ISSUE THREAD

**Issue by altugbakan** [foundry-rs/foundry#5723] opened 2023-08-25 06:46 UTC
### Component

Forge, Cast, Chisel

### Describe the feature you would like

Now, the `.env` file is only loaded from the project root. A CLI flag can be added to load the `.env` file from another directory. This will be helpful if Foundry is used within a monorepo that uses a single `.env` file.

The lines that load the `.env` file can be seen here:
https://github.com/foundry-rs/foundry/blob/8dd7ad2b22a8d7aca13f2e9d73c121a41da28baf/crates/cli/src/utils/mod.rs#L181-L203

I would also like to work on this.

### Additional context

The code can be seen below:

```rust
pub fn load_dotenv() {
    let load = |p: &Path| {
        dotenvy::from_path(p.join(".env")).ok();
    };

    // we only want the .env file of the cwd and project root
    // `find_project_root_path` calls `current_dir` internally so both paths are either both `Ok` or
    // both `Err`
    if let (Ok(cwd), Ok(prj_root)) = (std::env::current_dir(), find_project_root_path(None)) {
        load(&prj_root);
        if cwd != prj_root {
            // prj root and cwd can be identical
            load(&cwd);
        }
    };
}
```

**Comment by pikonha** [comment] 2024-02-26 22:48
I'm interested in this solution because I have a monorepo structure with the `.env` file placed in the root folder. Is there any workaround until this is released?

**Comment by zerosnacks** [comment] 2024-07-03 14:12
Hi @altugbakan thanks for your suggestion! Would you still be willing to work on this?

**Comment by altugbakan** [comment] 2024-07-03 14:42
Hey, I would like to!

**Comment by zerosnacks** [comment] 2024-07-03 14:49
Awesome! Assigning to you

**Comment by altugbakan** [comment] 2024-07-03 15:26
Opened #8346 for this

**Comment by altugbakan** [comment] 2024-07-10 22:03
Hey, I tried my hand, but don’t currently have the capacity to work on this. Anyone who wants to solve this can check this out.

**Comment by zerosnacks** [comment] 2024-07-11 04:32
No problem @altugbakan, thanks for your time and effort

**Comment by grandizzy** [comment] 2024-10-08 12:05
marking as dupe of https://github.com/foundry-rs/foundry/issues/3711 and closing it, will keep track of request there. thank you

**Closed by grandizzy** 2024-10-08 12:05 UTC
Labels: T-feature, C-cast, C-forge, C-anvil, A-config
