### ISSUE TITLE
Configuration with libraries will affect all contracts' creationCode

### ISSUE THREAD

**Issue by ZhimaoL** [foundry-rs/foundry#3201] opened 2022-09-13 23:04 UTC
### Component

Forge

### Describe the feature you would like

Add more descriptions on README to illustrate the expected behavior of "libraries" setting.

When deploying our contracts using create2, we couldn't produce deterministic addresses across different networks.

Eventually found out it was caused by [libraries](https://book.getfoundry.sh/reference/config/solidity-compiler#libraries) which will change the result for all
`type(somecontract).creationCode.`

Not sure if this is the expected behavior, maybe add more description on the handbook will be better?

**Comment by onbjerg** [comment] 2022-09-18 23:59
This is expected. When you link a library it replaces placeholder segments of the bytecode with concrete addresses. If the libraries are not deployed to the same address across all networks, then the bytecode will also change, resulting in a different address for your contracts. I'm closing this since it's not a bug, but if you think it would be helpful to clarify, feel free to open an issue in the book repository

**Closed by onbjerg** 2022-09-18 23:59 UTC
Labels: A-docs, T-feature, C-forge
