### ISSUE TITLE
Allow confirming/prompting before broadcast

### ISSUE THREAD

**Issue by rpedroni** [foundry-rs/foundry#5188] opened 2023-06-20 16:53 UTC
### Component

Forge

### Describe the feature you would like

Here at Endaoment we leverage `forge script` for multiple processes and on-chain interactions. Given the relevance and care of what we do, it'd be great if before broadcasting the picked-up transactions from a script, forge offered an option of adding a prompt/confirmation that requires the user to see the output (if any) of the script and confirm they want to go ahead with the broadcast.

I imagine this as a feature similar to `console`, whilst not being an original language construct, could be placed somewhere in code and pinpoint the spot you want the prompt/confirmation to happen.
If this proves to be too hard, a simple `"confirm: y/n"` after doing all the simulations would also be appreciated.

Hopefully this is useful for others likewise and props on this great project! ;)

**Comment by mds1** [comment] 2023-06-21 10:58
I think this be closed as a duplicate of https://github.com/foundry-rs/foundry/issues/2399? Give that convo a read and feel free to share any thoughts there, as we came to a decision around UX in that issue

**Closed by mds1** 2023-06-21 10:58 UTC
Labels: T-feature
