### ISSUE TITLE
Not enough ether reverts

### ISSUE THREAD

**Issue by 0xBeans** [foundry-rs/foundry#1748] opened 2022-05-27 07:57 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (4fcd7e0 2022-05-27T00:04:39.67082Z)

### What command(s) is the bug in?

forge test --gas-report -vvv

### Operating System

macOS (Apple Silicon)

### Describe the bug

This is not necessarily a bug but was prompted by @gakonst to submit an issue.

This is regarding the ambiguous revert() that happens when not enough ether is sent to a function.

Contract function:
```
    function mint(uint256 quantity) external payable   {
        require(msg.value == quantity * mintPrice)
        _mint()
    }
```

Test Function
```
    function testMint() public {
        // forget to vm.deal()

        vm.startPrank(user1, user1);
        contract.mint{value: 0.05 ether}(1);

        // assert statements here
    }
```

Failed test logs 
```
[FAIL. Reason: Revert] mint() (gas: 55015)
Traces:
[0] ContractTest::testMint()
  ├─ [55015] contract::mint{value: 50000000000000000}(1)
   │   └─ ← ()
└─ ← ()
```

I forgot to `vm.deal()` which reverted the mint due to not having enough ether. Im aware of `hoax()` in forge-std (and I shouldve dealed anyway) but the "issue" is that the revert string is quite unhelpful. My initial assumption was that something was wrong with my function or test, not that I forgot to `vm.deal()`. 

@gakonst asked what the ideal error string would be - something like "Not enough ether" or the likes. ERC20s error out with `arithmetic underflow/overflow` which could work in this instance as well.

Thanks :)

**Comment by mattsse** [comment] 2022-05-27 10:59
ref #275

**Comment by onbjerg** [comment] 2022-05-27 16:16
Duplicate of https://github.com/foundry-rs/foundry/issues/476?

**Comment by 0xBeans** [comment] 2022-05-27 19:25
@onbjerg yep seems like a duplicate xD

**Closed** 2022-05-29 02:15 UTC
Labels: T-bug, T-feature, Cmd-forge-test, C-forge, A-tracing
