### ISSUE TITLE
Cannot check negative expectCall assertion with any other expectCall assertion. 

### ISSUE THREAD

**Issue by simplyoptimistic** [foundry-rs/foundry#5655] opened 2023-08-18 06:02 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (11b08e9 2023-08-16T00:24:01.780465000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

`count` was added to `expectCall` here: https://github.com/foundry-rs/foundry/pull/4833

It allows for the ability to check that a function isn't called, by checking `count == 0`. Because of the way negative assertions have been implemented, it is not possible to combine them with other assertions around whether a function has been called or not, as you will receive this error:

`[FAIL. Reason: Counted expected calls can only bet set once.]` < also notice the typo

Whereas it would be possible to check in a test that different functions are being called by doing something like this:

```
vm.expectCall(where, data);
f.X();

vm.expectCall(where, data);
f.Y();
```

Where, `where` and `data` can be the same in both cases, and `X()` and `Y()` can be the same in both cases. It fails even if you do the following:

`vm.expectCall(where, data)`
`vm.expectCall(where, data, count=0)` 

with the same error as above.

**Comment by Evalir** [comment] 2023-08-18 21:38
note that this is not a bug, an intended behavior—this is actually a duplicate of https://github.com/foundry-rs/foundry/issues/509

closing to consolidate issues

**Closed by Evalir** 2023-08-18 21:38 UTC
Labels: T-bug
