### ISSUE TITLE
Anvil node stops mining blocks and working after simulating reverted tx

### ISSUE THREAD

**Issue by devanonon** [foundry-rs/foundry#1661] opened 2022-05-18 20:59 UTC
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (c0667c5 2022-05-18T00:16:34.701816Z)

### Operating System

macOS (Intel)

### Describe the bug

All latest, ran `foundryup` about 20 minutes ago:
```
forge 0.2.0 (c0667c5 2022-05-18T00:16:34.701816Z)
cast 0.2.0 (c0667c5 2022-05-18T00:16:34.701816Z)
anvil 0.1.0 (c0667c5 2022-05-18T00:16:35.035292Z)
```

I have some bash scripts which orchestrate a lot of this, but if I call them in the wrong order, anvil seems to break / not let me submit txs / not mine blocks anymore.

Essentially, my workflow which works is:
```
./scripts/node.sh
./scripts/deploy.sh local
./scripts/enable.sh local
```

Apart from reading in env vars and some checks, these scripts basically amount to:
```
anvil -f $MAIN_RPC --chain-id 1
forge create ./src/Contract.sol:Contract i --rpc-url http://localhost:8545 --constructor-args $ARGS --private-key $PRIV_KEY
cast send -i --rpc-url http://localhost:8545 $LOCAL_CONTRACT_ADDRESS "enable()" --private-key $PRIV_KEY
```

Called in this order, they work fine. If I accidentally call them in the order: `node` `enable` `deploy` the entire anvil node breaks and does not accept more requests. Actually, the deploy script does not even work.

Of course, I should not be able to call `enable` on the contract before it is deployed, but still it should not break the node entirely.

It seems that something in anvil gets hung up on the reverting TX `enable`. In the logs I don't even see a reverting TX, I just see
```
eth_sendRawTransaction
```
But of course no output that the tx was successful or unsuccessful.

Trying to deploy then afterwards, nothing shows up in the anvil logs. They just stop but the `anvil` process is still running and `forge create` just hangs.

**Comment by mattsse** [comment] 2022-05-18 21:37
can't reproduce this with

```
 anvil -f $RPC --chain-id 1
```

```console
cast send --rpc-url http://localhost:8545 $ACCOUNT "enable()" --private-key $PRIV_KEY 
```

succeeds repeatedly

**Comment by devanonon** [comment] 2022-05-19 00:34
Okay, I actually just reproduced it again. So, I ran `./scripts/node.sh` and my cast command never got called.

The anvil output is:
```
Listening on 127.0.0.1:8545
eth_blockNumber
eth_blockNumber
eth_getBlockByNumber
eth_chainId
eth_getTransactionCount
eth_getBlockByNumber
eth_call
eth_feeHistory
eth_feeHistory
eth_estimateGas
eth_createAccessList
eth_chainId
eth_sendRawTransaction
eth_getTransactionReceipt
eth_blockNumber
```
Then the anvil node doesn't work anymore. It seems to accept RPC requests but never process them.


Without the frontend running right now (but MM still connected to anvil), I get this:
```
eth_blockNumber
eth_chainId
eth_getTransactionCount
eth_getBlockByNumber
eth_blockNumber
eth_getBlockByNumber
eth_feeHistory
eth_feeHistory
eth_estimateGas
eth_createAccessList
eth_call
eth_sendRawTransaction
eth_getTransactionReceipt

    Transaction: x
    Gas used: 21000
    Block Number: 14801917
    Block Hash: x
    Block Time: "Thu, 19 May 2022 00:29:47 +0000"

eth_blockNumber
eth_getTransactionByHash
eth_getTransactionReceipt

blockHash               x
blockNumber             14801917
contractAddress
cumulativeGasUsed       0
effectiveGasPrice       4000000000
gasUsed                 21000
logs                    []
logsBloom               0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
root
status                  1
transactionHash         x
transactionIndex        0
type
eth_blockNumber
eth_getBlockByNumber
eth_call
eth_blockNumber
```
So, as we can see the cast command works.

Then, with nothing connecting to the anvil node (i.e. no frontend nor MM) I get this:
```
eth_chainId
eth_getTransactionCount
eth_getBlockByNumber
eth_feeHistory
eth_feeHistory
eth_estimateGas
eth_createAccessList
eth_sendRawTransaction
eth_getTransactionReceipt

    Transaction: x
    Gas used: 21000
    Block Number: 14801928
    Block Hash: x
    Block Time: "Thu, 19 May 2022 00:31:46 +0000"


blockHash               x
blockNumber             14801928
contractAddress
cumulativeGasUsed       0
effectiveGasPrice       4000000000
gasUsed                 21000
logs                    []
logsBloom               0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
root
status                  1
transactionHash         x
transactionIndex        0
type
```
All working as expected.

I hope this helps! Let me know if you can think of anything else for me to check.

**Comment by mattsse** [comment] 2022-05-19 08:31
nice!

closing this, feel free to open it again if you discover something weird

**Closed by mattsse** 2022-05-19 08:31 UTC
Labels: T-bug
