### ISSUE TITLE
coverage: both branches lines taken but only half branch coverage

### ISSUE THREAD

**Issue by hellwolf** [foundry-rs/foundry#5623] opened 2023-08-14 13:42 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (ca67d15 2023-08-02T00:16:51.291393754Z)

### What command(s) is the bug in?

forge coverage --hardhat --report lcov

### Operating System

Linux

### Describe the bug

We found sporadically some cases that the lcov reporting from foundry did not make sense to us, since the branch should in all cases be hit, here are some examples:

- https://app.codecov.io/gh/superfluid-finance/protocol-monorepo/blob/dev/packages%2Fethereum-contracts%2Fcontracts%2Fagreements%2FConstantFlowAgreementV1.sol#L776 (in normal non-branching code path).

- https://app.codecov.io/gh/superfluid-finance/protocol-monorepo/blob/dev/packages%2Fethereum-contracts%2Fcontracts%2Futils%2FBatchLiquidator.sol#L67 (in normal code block)

- https://app.codecov.io/gh/superfluid-finance/protocol-monorepo/blob/dev/packages%2Fethereum-contracts%2Fcontracts%2Futils%2FCFAv1Forwarder.sol#L411 (abi.encodeCall)

- https://app.codecov.io/gh/superfluid-finance/protocol-monorepo/blob/dev/packages%2Fethereum-contracts%2Fcontracts%2Futils%2FIDAv1Forwarder.sol#L21 (normal code paths in a constructor)

... etc.

Is there something we could help with to give more diagnostics information about those?

**Comment by dcposch** [comment] 2023-09-07 08:39
### False negatives in branch coverage

Here's a clear example. (Ignore the nonsensical  else, I added it to confirm this issue:)

<img width="642" alt="image" src="https://github.com/foundry-rs/foundry/assets/169280/704e2714-457e-45bb-bd85-c23467d798a9">

**`forge coverage` correctly shows both branches taken (line coverage in both if and else), but incorrectly reports 1/2 branch coverage for the if**

**Comment by Evalir** [comment] 2023-12-18 18:07
Closing as duplicate, but ack coverage needs more work. Will revisit during next year

**Comment by DaniPopes** [comment] 2024-11-30 06:09
What is this a duplicate of? I can't determine if this was ever fixed, so re-opening. CC @grandizzy do you recall if you've fixed a similar issue?

**Comment by grandizzy** [comment] 2024-11-30 07:13
> What is this a duplicate of? I can't determine if this was ever fixed, so re-opening. CC @grandizzy do you recall if you've fixed a similar issue?

hm,  nope, wasn't aware of this one, though didn't see any issue like this lately, worth double checking

**Comment by grandizzy** [comment] 2024-11-30 07:17
@DaniPopes ah, actually yes, thrre were several fixes re branch report incorrectly, I added unit tests for 
https://github.com/foundry-rs/foundry/pull/8413
https://github.com/foundry-rs/foundry/pull/8414
https://github.com/foundry-rs/foundry/pull/8433

**Closed** 2024-11-30 07:21 UTC
Labels: T-bug
