### ISSUE TITLE
Unable to use `Contract.Event` syntax - compiler fails

### ISSUE THREAD

**Issue by hexcowboy** [foundry-rs/foundry#6206] opened 2023-11-03 16:17 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (1c7bf46 2023-11-03T13:18:06.065760000Z)

### What command(s) is the bug in?

forge compile

### Operating System

macOS (Apple Silicon)

### Describe the bug

Minimal repro:

`Counter.sol`
```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

contract Counter {
    event Created(
        address indexed creator
    );

    constructor() {
        emit Created(msg.sender);
    }
}
```

`Counter.t.sol`
```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import {Test, console2} from "forge-std/Test.sol";
import {Counter} from "../src/Counter.sol";

contract CounterTest is Test {
    Counter public counter;

    function setUp() public {
        vm.expectEmit();
        emit Counter.Created(msg.sender); // <--the perp
        counter = new Counter();
    }
}
```

When building:

```bash
➜ forge compile
[⠒] Compiling...
[⠒] Compiling 22 files with 0.8.21
[⠑] Solc 0.8.21 finished in 1.46s
Error: 
Compiler run failed:
Error: Internal exception in StandardCompiler::compile: /solidity/libsolidity/interface/Natspec.cpp(89): Throw in function static Json::Value solidity::frontend::Natspec::userDocumentation(const solidity::frontend::ContractDefinition &)
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: Solidity assertion failed
[solidity::util::tag_comment*] = Solidity assertion failed

Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: Solidity assertion failed
[solidity::util::tag_comment*] = Solidity assertion failed
```

I can only reproduce this error when using `Counter.Created` syntax

**Comment by mattsse** [comment] 2023-11-03 18:25
this is a solc error, can reproduce with 0.8.21

works with 0.8.22 though, so seems to be fixed.

there's nothing we can do here I'm afraid, so closing

**Closed by mattsse** 2023-11-03 18:25 UTC
Labels: T-bug
