### ISSUE TITLE
Feature: Cheatcodes for VM state checkpointing to facilitate differential tests

### ISSUE THREAD

**Issue by jameswenzel** [foundry-rs/foundry#1652] opened 2022-05-18 03:31 UTC
# Motivation 
Sometimes it is necessary to test implementation logic between a refactor and existing code, or an optimized, low-level assembly implementation versus a human-readable "reference" implementation.

When testing against two different implementations of the same logic, it would be very useful to be able to roll back VM state between runs of test logic against different implementations. In practice, this would would function similarly to how VM state is rolled back to the state after calling `setUp()` between individual tests.

# Solution

1. Implement a `vm.checkpoint` cheatcode to create a state that can be revisited (possibly with tagging to allow multiple checkpoints - though certainly not a requirement)
2. Implement a `vm.rollback` cheatcode to roll back to a previous state (possibly taking a tag as a parameter to roll back to)

**Comment by onbjerg** [comment] 2022-05-19 16:33
Duplicate of #1162

**Closed by onbjerg** 2022-05-19 16:33 UTC
Labels: T-feature
