### ISSUE TITLE
`forge build`: select contracts to compile

### ISSUE THREAD

**Issue by Jeiwan** [foundry-rs/foundry#1595] opened 2022-05-13 06:08 UTC
### Component

Forge

### Describe the feature you would like

I'd like to select contracts when running `forge build`. This would allow to apply different compiler options to different contracts. Specifically, I'd like to selectively apply `--via-ir` and `--optimization` to contracts that would benefit from this most, and I don't want to optimize test contracts. Implementing this feature would also mean that `forge test` doesn't re-compile the contracts that were compiled with different settings.

Without this feature, it's not possible to run `forge build --via-ir` in a project that has contracts compiled with an old Solc version (one that doesn't support Yul IR).

Also, it might be a good idea to add per-contract optimization settings to the TOML config.

**Comment by gakonst** [comment] 2022-05-13 23:15
@mattsse think this is a dupe of providing configs on a per contract/path basis?

**Comment by onbjerg** [comment] 2022-05-14 01:23
I don't think it's currently possible to compile a subset of contracts that are imported in another set of contracts that do not have these optimizations. Specifically, if you have a contract Foo imported into FooTest it isn't possible to optimize Foo but not FooTest, or the other way around. This is tracked in https://github.com/ethereum/solidity/issues/1540 and https://github.com/ethereum/solidity/issues/11787

**Comment by gakonst** [comment] 2022-05-14 02:13
Yep let's consolidate to #317

**Closed by gakonst** 2022-05-14 02:13 UTC
Labels: T-feature, C-forge, D-hard, Cmd-forge-build
