### ISSUE TITLE
massive gas estimation when running `forge script` on base

### ISSUE THREAD

**Issue by colinnielsen** [foundry-rs/foundry#7400] opened 2024-03-14 01:58 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (545cd0b 2024-03-14T00:20:00.210934000Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

Blob storage was released today on Base, and I am using `forge script` to run a transaction through a new contract.

- [The forge-based tx](https://basescan.org/tx/0x607518b4a7ff312c17160e23a554aed3ee6920619e4e7009b7a571c54df7ad28)
- [What the tx should've cost](https://basescan.org/tx/0x879ed42f97027a78ad789be0d6bb02b455f370a95a6f4093209b303d6d891d59)

## Repro steps:
1. clone the repo off this pr / branch https://github.com/0xmetropolis/erc20/pull/3
2. run `export OWNER=rando_addr`
3. run `forge script script/DeployToken.s.sol --rpc-url https://mainnet.base.org`

**Comment by 0xAndoroid** [comment] 2024-03-16 16:48
Adding --legacy flag solves the issue, but you are right, priority fees are overestimated. I'm going to try to spot the issue and submit a pr.

**Comment by 0xAndoroid** [comment] 2024-03-16 17:43
This is a duplicate of #5709 

@Evalir why aren't you considering implementing custom estimator function in foundry? ethers' accepts
```rust
fn estimator(base_fee: U256, history: Vec<Vec<U256>>) -> (U256, U256)
```
in `estimate_eip1559_fees(estimator)`

**Closed** 2024-04-09 20:52 UTC
Labels: T-bug
