### ISSUE TITLE
Set private key env vars in CI for tests

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#1457] opened 2022-04-29 09:47 UTC
### Component

Forge, Cast

### Describe the feature you would like

we recently added tests that only run if private key, rpc URL and etherscan API key are set in ci, the integration tests check:
* `forge verify*`
* `forge create`

and are only run if the env vars are present.

It'd be nice to also run them in CI to catch issues.

this would require:
* secure env setup (so no one steals our PK)
* feature gating these tests and run them separately because they can be flaky (network/endpoint etc..)

**Comment by StErMi** [comment] 2022-06-06 12:45
Hi there, I'm trying to have a common way to launch both local and CI tests scripts and I was wondering if it's possible make `forge test` (and other commands) to automatically pick up `.env` files based on the profile.

In my scenario we have two different use case:

1) GitHub actions CI tests
2) Local test to be run before commit/push

I would like to be able to define the same `scripts` in `package.json` and be able to run them equally both locally with `npm run test:whatever` and by GitHub CI.

## GitHub actions

I can easily define `env` variables in the `yml` with constant values or getting the value of them from GitHub secrets.
After that I can easily call the tests scripts via `npm run test` and `npm run test:fork` (this one is using the setupping the env variable `FOUNDRY_ETH_RPC_URL`

Everything is good here.

## Local tests

I would like to use the same scripts that I'm using for the CI also locally to have only one source to lunch my tests. The problem is that as far as I get it's not possible to do it currently.

So I was thinking that foundry could enhance the way it loads `env` variables from `.env` file based on `profiles`.

You would have `foundry.toml` where you define all you "public" env variables and profiles but also `.env` file where you can define "secret" value for some env variables. 

If no profile is specified when the command is launched the `default` profile is used so it will try to load `.env` file if it exists.
In case where a `profile` is specified it will try to load that specific env file. For example if you specify that the profile is `prod` it will try to load `.env.prod` env file.

It would work like `foundry.toml` work so if a more specific profile is used it will laod first the `.env` and then will merge the `.env.$profile_name` config.

In this way we would be able to have the same scripts for both Github CI and local testing. 

Here's the repo I'm currently testing on: https://github.com/StErMi/forge-sol-challenge

**Comment by onbjerg** [comment] 2022-06-09 14:18
@StErMi check out https://github.com/foundry-rs/foundry/issues/1034

**Comment by StErMi** [comment] 2022-06-10 09:20
> @StErMi check out #1034

That's precisely what I was looking for!

**Comment by onbjerg** [comment] 2022-06-10 09:53
Closing this issue in that case :)

**Closed by onbjerg** 2022-06-10 09:53 UTC
Labels: T-question, T-meta
