### ISSUE TITLE
`forge script`: directly broadcast from account address when using `--account`

### ISSUE THREAD

**Issue by cairoeth** [foundry-rs/foundry#6604] opened 2023-12-14 20:33 UTC
### Component

Forge

### Describe the feature you would like

When using `forge script`, it's possible to add `--account` to a use a keystore account. However, `vm.startBroadcast` in the script won't use the address from the account. To fix this, you need to pass `--froms` with the address of the account, resulting in something like: `forge script script/Deploy.s.sol --account wallet --froms <ADDRESS>`

It would be great if `forge script` fetches the address from the account and passes it to `vm.startBroadcast` automatically. Otherwise, it's quite annoying to keep getting the account's address manually.

### Additional context

This feature will create the experience of using keytore accounts easier, which is a much safer option than using the private key from `.env`.

**Comment by ernestognw** [comment] 2023-12-14 20:42
I recognize there might be an edge case where automatically setting `--froms` to the account address may be breaking, so I was thinking a workaround might be getting the account address with `cast`. However, `--froms $(cast wallet address --account <ACCOUNT>)` asks for the password twice.

Perhaps we can have a single `--fromAccount` that fills both `--account` and `--froms $(cast wallet address --account <ACCOUNT>)`?

**Comment by klkvr** [comment] 2023-12-16 23:55
This is a duplicate of #6034 which already has discussion regarding why implementing this is not trivial without changes to the current script design.

**Comment by Evalir** [comment] 2023-12-18 17:29
Hey all — ack we can do better around wallet management UX. I'm currently consolidating the issue tracker, so let's move the discussion to #6034 — I'll make sure to leave a comment there on what we can do. Thanks!

**Closed by Evalir** 2023-12-18 17:29 UTC
Labels: T-feature
