### ISSUE TITLE
bug(`cast`): unknown contract at address 0x

### ISSUE THREAD

**Issue by miketamis** [foundry-rs/foundry#8146] opened 2024-06-13 07:11 UTC
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (8801156 2024-06-13T00:22:06.739865000Z)

### What command(s) is the bug in?

cast run --debug 0xcc... --rpc-url http://...

### Operating System

macOS (Apple Silicon)

### Describe the bug

When running cast run --debug on a transaction on a live chain, I get Unknown Contract at address, even thou the contract was deployed using the binaries that are in the project. (the contract wasn't deployed using Forge but the build output from forge was used)

**Comment by zerosnacks** [comment] 2024-10-22 11:26
Hi @miketamis, is this related to Besu Chain specifically or are you able to reproduce this against other networks / RPCs?

Related: https://github.com/foundry-rs/foundry/issues/8147

**Comment by grandizzy** [comment] 2024-11-14 13:45
dupe of https://github.com/foundry-rs/foundry/issues/8606 going to provide a way to load artifacts from local dir when using cast run / send. thank you!

**Closed by grandizzy** 2024-11-14 13:45 UTC
Labels: T-bug, C-cast, P-low, T-to-investigate
