### ISSUE TITLE
bug(`cast run`): local execution of transaction on BSC fails even though transaction originally succeeded on-chain

### ISSUE THREAD

**Issue by wp-lai** [foundry-rs/foundry#2997] opened 2022-08-29 03:13 UTC
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (307576d 2022-08-29T00:05:05.72678Z)

### What command(s) is the bug in?

cast run

### Describe the bug

Regarding this [tx](https://bscscan.com/tx/0xaa081672f7ad60e49000cb3520df1dce395d55d59ea31918adca41408f7fe28f) in bsc chain,

command
```
cast run 0xaa081672f7ad60e49000cb3520df1dce395d55d59ea31918adca41408f7fe28f --rpc-url https://rpc.ankr.com/bsc
```
produced an unexpected result
```
Executing previous transactions from the block.
Traces:
  [0] 0x0000…0000::fallback()
    └─ ← ()


Transaction failed.
Gas used: 0
```

while both `cast tx 0xaa081672f7ad60e49000cb3520df1dce395d55d59ea31918adca41408f7fe28f --rpc-url https://rpc.ankr.com/bsc` and `cast receipt 0xaa081672f7ad60e49000cb3520df1dce395d55d59ea31918adca41408f7fe28f --rpc-url https://rpc.ankr.com/bsc` produced expected result.

**Comment by minaminao** [comment] 2022-09-07 07:18
In my environment, a more detailed trace is shown, but it is weird because the transaction is successful but shows OutOfGas. The RPC used is Quicknode.

```
$ cast run 0xaa081672f7ad60e49000cb3520df1dce395d55d59ea31918adca41408f7fe28f
Executing previous transactions from the block.
Traces:
  [28142] BEP20USDT::transfer(0x085747a5b761ab8682be10f2597674e8aa688c66, 22000000000000000000) 
    └─ ← "EvmError: OutOfGas"


Transaction failed.
Gas used: 51115
```

**Comment by zerosnacks** [comment] 2024-06-26 11:46
> In my environment, a more detailed trace is shown, but it is weird because the transaction is successful but shows OutOfGas. The RPC used is Quicknode.
> 
> ```
> $ cast run 0xaa081672f7ad60e49000cb3520df1dce395d55d59ea31918adca41408f7fe28f
> Executing previous transactions from the block.
> Traces:
>   [28142] BEP20USDT::transfer(0x085747a5b761ab8682be10f2597674e8aa688c66, 22000000000000000000) 
>     └─ ← "EvmError: OutOfGas"
> 
> 
> Transaction failed.
> Gas used: 51115
> ```

able to reproduce this result

https://bscscan.com/tx/0xaa081672f7ad60e49000cb3520df1dce395d55d59ea31918adca41408f7fe28f indeed shows the transaction was succesful

requires further investigation

**Comment by zerosnacks** [comment] 2024-08-02 12:30
As a sanity check, was able to run a random recent transaction on BSC `cast run 0xf9450d2831320782ca16bf3afa3e6c9bc3812ae9532f074a2ce6015f2355d4bf --rpc-url https://bsc-dataseed.bnbchain.org` without issue.

**Comment by alexanderhawl** [comment] 2024-10-01 08:38
Today, I also met this problem. I wanna transfer token ,but it report outofgas.
IERC20(0xf3100086E52180b31fE39EF4a09e5BEE4E7D62EF).transfer(0x72AdEBF8F20d144c60db0677F20D19f0Ce89e11A, 0.01 ether);
fork rpc is https://rpc.ankr.com/bsc
foundry version : forge 0.2.0 (3ff3d05 2024-10-01T00:25:45.808130533Z)

**Comment by grandizzy** [comment] 2024-10-25 12:20
the problem here is that we're simulating tx with a different EVM version than chain's at the time tx happened, if passing `--evm-version istanbul` option then it shows proper result
```bash
cast run 0xaa081672f7ad60e49000cb3520df1dce395d55d59ea31918adca41408f7fe28f --rpc-url https://rpc.ankr.com/bsc --evm-version istanbul

Traces:
  [29471] 0x55d398326f99059fF775485246999027B3197955::transfer(0x085747A5B761AB8682Be10F2597674e8AA688C66, 22000000000000000000 [2.2e19])
    ├─ emit Transfer(param0: 0xd9fcDa91103C9D082518350c1d2a437DA8C4f7d4, param1: 0x085747A5B761AB8682Be10F2597674e8AA688C66, param2: 22000000000000000000 [2.2e19])
    └─ ← [Return] 0x0000000000000000000000000000000000000000000000000000000000000001

```

This is a broader issue (and affects test/script executions too) which we're going to address by autodetecting EVM version.

Ref:
https://github.com/foundry-rs/foundry/issues/6228
https://github.com/foundry-rs/foundry/issues/8614

**Comment by grandizzy** [comment] 2024-10-25 13:57
same as https://github.com/foundry-rs/foundry/issues/8446 we're going to close this one as dupe and track fix in 8446. thank you!

**Closed by grandizzy** 2024-10-25 13:57 UTC
Labels: T-bug, C-cast
