### ISSUE TITLE
Option to automatically update remappings when installing dependencies

### ISSUE THREAD

**Issue by aviggiano** [foundry-rs/foundry#2257] opened 2022-07-10 15:37 UTC
### Component

Forge

### Describe the feature you would like

Installing dependencies through `forge` currently requires more manual steps than, e.g., through `npm` on hardhat. This is because `remappings.txt` is not automatically updated when a new library is included.

This proposal suggests including an option on `forge install` that would automatically update `remappings.txt`

### Additional context

It is possible to install and automatically search for `.sol` files, and based on that add the corresponding remapping. Another idea is to have a directory of commonly used libraries and default remappings for that (e.g. `@openzeppelin/=lib/openzeppelin-contracts/`), but it requires more maintenance and is not very scalable.

**Comment by onbjerg** [comment] 2022-07-10 20:02
Duplicate of #883

**Closed by onbjerg** 2022-07-10 20:02 UTC
Labels: T-feature
