### ISSUE TITLE
feat(forge): `vm.startDebug` - start the debugger at the current test location

### ISSUE THREAD

**Issue by 0xPhaze** [foundry-rs/foundry#4282] opened 2023-02-06 08:06 UTC
### Component

Forge

### Describe the feature you would like

The biggest pain point of the debugger is stepping through the functions to arrive at the exact code location that you are interested in. Being able to start the debugger at the exact code location could be really helpful. To make things easier on building this feature, this could only be activated/in-use if `forge test --debug` is being called.

**Comment by mds1** [comment] 2023-02-06 16:28
Seems like a duplicate of https://github.com/foundry-rs/foundry/issues/3430#issuecomment-1267457660?

**Comment by 0xPhaze** [comment] 2023-02-06 17:09
yes, `vm.breakpoint` would also be great. Can close this if it's already being tracked there then.

**Comment by simpledefi** [comment] 2023-03-05 14:37
I would second this... It would be extremely helpful to be able to debug the last transaction.

I'm working on a test case where it's running 200 random  transactions. Based on the return value, I would love to be able to start the debugger and say "debug the last transaction"..

Right now code looks like:
                uint amountOut = st.withdrawStake();
                require(amountOut > 0,"0 amount out");

idt would be usefull IF possible:
                uint amountOut = st.withdrawStake();
                if (amountOut ==  0) vm.debugLastTransaction();

**Comment by mds1** [comment] 2023-03-05 16:27
Thanks @0xPhaze, going to close this in favor of #3430 since there's more discussion there, and we'll be tracking all debugger improvements as part of #4440.

@simpledefi IIUC that basically just sounds like a breakpoint, but if not and it's something different feel free to open a separate issue

**Closed by mds1** 2023-03-05 16:27 UTC
Labels: T-feature
