### ISSUE TITLE
"Unknown Contract at address <address>" inside the debugger

### ISSUE THREAD

**Issue by HrikB** [foundry-rs/foundry#2348] opened 2022-07-16 11:46 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (153ae19 2022-06-26T00:04:15.775569508Z)

### What command(s) is the bug in?

forge test --debug

### Operating System

Windows

### Describe the bug

I am unable to get the contract solidity code to show up in the debugger:
![image](https://user-images.githubusercontent.com/23041116/179353508-99683b18-83cd-45cd-a2d9-7b42e8eb5596.png)

**Comment by onbjerg** [comment] 2022-07-16 18:39
Can you provide more context? What contract do you expect this to be?

**Comment by HrikB** [comment] 2022-07-16 22:55
This is the contract I am testing:
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import {ClonesUpgradeable} from "@openzeppelin/contracts-upgradeable/proxy/ClonesUpgradeable.sol";
import {ContextUpgradeable} from "@openzeppelin/contracts-upgradeable/utils/ContextUpgradeable.sol";
import "@openzeppelin/contracts-upgradeable/utils/AddressUpgradeable.sol";

/**
 * @dev ERC1167 Minimal Proxy Factory
 */
contract ERC1167Factory is ContextUpgradeable {
    using AddressUpgradeable for address;

    event NewClone(address instance, address implementation, bytes32 salt);

    function clone(address implementation, bytes memory data)
        public
        returns (address instance)
    {
        instance = ClonesUpgradeable.clone(implementation);

        //data is optional
        if (data.length > 0)
            instance.functionCall(
                data,
                "ERC1167Factory: Failed to call the proxy"
            );

        emit NewClone(instance, implementation, bytes32(0));
    }

    function cloneDeterministic(
        address implementation,
        bytes32 salt,
        bytes memory data
    ) public returns (address instance) {
        //Salt init data
        salt = keccak256(abi.encodePacked(salt, _msgSender(), data));
        instance = ClonesUpgradeable.cloneDeterministic(implementation, salt);

        //data is optional
        if (data.length > 0)
            instance.functionCall(
                data,
                "ERC1167Factory: Failed to call the proxy"
            );

        emit NewClone(instance, implementation, salt);
    }

    function predictDeterministicAddress(
        address implementation,
        bytes32 salt,
        bytes memory data
    ) public view returns (address predicted) {
        //Salt init data
        salt = keccak256(abi.encodePacked(salt, _msgSender(), data));
        predicted = ClonesUpgradeable.predictDeterministicAddress(
            implementation,
            salt
        );
    }
}
```

This is the test contract: 
```
//SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "forge-std/Test.sol";
import "forge-std/console.sol";

import "../../contracts/proxy/ERC1167/ERC1167Factory.sol";
import "../../contracts/assets/ERC721/ERC721Owl.sol";

contract ERC1167FactoryTest is Test {
    uint256 constant allE =
        108072616621495115728666252674775380663051985687931193103493745074052254330606;

    ERC1167Factory c;
    ERC721Owl impl;

    function setUp() public {
        c = new ERC1167Factory();
        impl = new ERC721Owl();
    }

    function testCloneDeterministic() public {
        c.cloneDeterministic(
            address(impl),
            bytes32(abi.encode(0)),
            abi.encodeWithSignature(
                "initialize(address,string,string,string,address)",
                address(0),
                "name",
                "symbol",
                "uri",
                address(0)
            )
        );
    }
}
```
The command I am running is: `forge test --debug "testCloneDeterministic()"`

**Comment by onbjerg** [comment] 2022-07-16 23:00
You are not at PC 0, so this is later during execution. I need to know what contract you expect to be in at that point in the program

**Comment by HrikB** [comment] 2022-07-16 23:10
This is PC 0
![image](https://user-images.githubusercontent.com/23041116/179374610-ef04edc8-49f0-4ea4-8ada-45a80b78f952.png)

**Comment by HrikB** [comment] 2022-07-16 23:11
I've never had that part show up correctly... always says unknown contract

**Comment by onbjerg** [comment] 2022-07-16 23:12
Does any part of the debugger show correct contracts? If you run the test with `-vvvvv` does the trace show the contracts as well?

**Comment by HrikB** [comment] 2022-07-16 23:16
Yes `-vvvvv` does show contracts but they are at different addresses than what the debugger is trying to display
![image](https://user-images.githubusercontent.com/23041116/179374721-73ec5d93-9206-4def-801f-9ca3652efb4d.png)

**Comment by HrikB** [comment] 2022-07-16 23:16
Debugger trying to display `0x5b73c549...` for some reason... this doesn't change

**Comment by onbjerg** [comment] 2022-07-16 23:17
`0x5b73c549` is probably the test contract itself which you don't see in traces

**Comment by onbjerg** [comment] 2022-08-23 17:01
Closing this since I can't reproduce it, but feel free to reopen if this is still the case with some more context :smile:

**Closed by onbjerg** 2022-08-23 17:01 UTC
Labels: T-bug, C-forge, Cmd-forge-debug
