### ISSUE TITLE
Top level objects in files without contracts are not included in the compilation artifacts

### ISSUE THREAD

**Issue by montyly** [foundry-rs/foundry#1646] opened 2022-05-17 17:08 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### Describe the bug

Hey,

If a foundry codebase has a file that contains only top-level objects without contract, foundry does not generate their compilation artifacts. 

For example: (after `foundry init`):
```
$ cat src/top_level.sol 
function test() {

}
$ cat src/Contract.sol 
// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.10;

import "./top_level.sol";

contract Contract {
    function a() public{
        test();
    }
}
```
Running `forge build` will not generate a json file in `out/free.sol/`. 

However by adding an empty contract to `top_level.sol`:
```
function test() {

}
contract T{}
```

Running `forge build` will generate a json file in `out/free.sol/T.json`. 

This prevent third-party tools (such as Slither) to work on such codebase.

Related: https://github.com/crytic/slither/issues/1208

**Comment by onbjerg** [comment] 2022-05-19 16:36
I think this is expected behavior - if there is no library and no contract, then what do you want from the compilation artifacts? Free standing functions are not included in the ABI.

**Comment by mattsse** [comment] 2022-05-19 16:58
> I think this is expected behavior - if there is no library and no contract.

exactly, solc only emits a `SourceFile` for files that don't contain any contracts/interfaces. 

I've though about this after @mds1 brought it up, we could generate an empty artifact with only the AST set for files like this, but I'm not a fan of that tbh. it's potentially unsound because the general assumption is `contract = artifact`, however, we already handle these edge cases in ethers-solc and never check for outputs to be present (like bytecode), so generating an empty artifact for a file that does not contain any source units should generally just work.

I'm not sure why slither expects a file to begin with, judging from the logs, it parses the ast and maps that to a file structure: `parse_top_level_from_loaded_json`?

I will investigate this

**Comment by montyly** [comment] 2022-05-20 08:54
The issue is that with forge's compilation artifacts structure the data associated with top-level objects are missing. 

In this example, when I run `forge build --extra-output userdoc --extra-output devdoc`, in `cache/solidity-files-cache.json`, I see:
```json
    "/tmp/tests_foundry/src/top_level.sol": {
      "lastModificationDate": 1653035419629,
      "contentHash": "6e6c34f5c3278ef99f3777de8ddf2601",
      "sourceName": "src/top_level.sol",
      "solcConfig": {
        "settings": {
          "optimizer": {
            "enabled": true,
            "runs": 200
          },
          "metadata": {
            "bytecodeHash": "ipfs"
          },
          "outputSelection": {
            "*": {
              "": [
                "ast"
              ],
              "*": [
                "evm.bytecode",
                "evm.deployedBytecode",
                "devdoc",
                "userdoc"
              ]
            }
          },
          "evmVersion": "london"
        }
      },
      "imports": [],
      "versionRequirement": null,
      "artifacts": {}
    },
```

So I would expect to have access to the ast/devdoc/userdoc of the content in `top_level.sol`, but it's not available. It's the same with other top-level objects (i.e. if there is a top-level structure, I would expect to see its ast). The lack of AST for top-level objects will prevent Slither from working.

I think that anything that can generate Solidity artifacts (ast/doc/etc ..) should be available in some format in the compilation artifacts.

**Comment by montyly** [comment] 2022-05-20 08:58
For info, the way hardhat handles it, is that it will create, per compilation unit, a `artifacts/build-info/<random_id>.json` with all the compilation artifacts (but there is probably a better way to structure this)

**Comment by mattsse** [comment] 2022-05-20 09:40
get it now, thanks.

this should be an easy fix and I'm on it now.

**Comment by gakonst** [comment] 2022-05-23 21:24
@montyly can you check if this works now on latest `foundryup -b master`?

**Comment by pedrommaiaa** [comment] 2022-05-25 13:27
I'm not sure about @montyly but I was having a very similar problem that was caused when running `slither` and now its working @gakonst.

**Comment by mattsse** [comment] 2022-06-08 19:37
closing this as we emit artifacts for sol files without contract definitions now

**Closed by mattsse** 2022-06-08 19:37 UTC
Labels: T-bug, C-forge, Cmd-forge-build
