### ISSUE TITLE
Contract with the same filename in src will overwrite output

### ISSUE THREAD

**Issue by jpopesculian** [foundry-rs/foundry#2239] opened 2022-07-07 19:26 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (dd7c88f 2022-07-07T19:03:57.366945167Z)

### What command(s) is the bug in?

forge build

### Operating System

Linux

### Describe the bug

If you have the following project structure

```
src/
  Contract.sol
  other/
    Contract.sol
```

where each source file contains

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.0;

contract Contract {}
```

the output JSON in `out/Contract.sol/Contract.json` will look like

```JavaScript
{
  "ast": {
    "absolutePath": "src/other/Contract.sol",
    ...
  },
  ...
}
```

I would expect there to be two files or for the build to fail

**Comment by onbjerg** [comment] 2022-07-08 15:41
Dupe of #1488

**Closed by onbjerg** 2022-07-08 15:41 UTC
Labels: T-bug, C-forge, Cmd-forge-build
