### ISSUE TITLE
coverage support cmdline based file filters

### ISSUE THREAD

**Issue by kkx** [foundry-rs/foundry#3000] opened 2022-08-29 10:34 UTC
### Component

Forge

### Describe the feature you would like

Hi, 
is there a way to filter out some contracts from coverage report? 
Currently, the report is showing the coverage for contracts inside of "test" and "src/mocks" (used for testing) folders, and there is no way for users to hide them, if this is not available right now, is there any chance to create something similar to filtering in the test?
```
TEST FILTERING:
    -m, --match <PATTERN>
            Only run test functions matching the specified regex pattern.
            
            Deprecated: See --match-test

        --match-test <REGEX>
            Only run test functions matching the specified regex pattern
            
            [aliases: mt]

        --no-match-test <REGEX>
            Only run test functions that do not match the specified regex pattern
            
            [aliases: nmt]

        --match-contract <REGEX>
            Only run tests in contracts matching the specified regex pattern
            
            [aliases: mc]

        --no-match-contract <REGEX>
            Only run tests in contracts that do not match the specified regex pattern
            
            [aliases: nmc]

        --match-path <GLOB>
            Only run tests in source files matching the specified glob pattern
            
            [aliases: mp]

        --no-match-path <GLOB>
            Only run tests in source files that do not match the specified glob pattern
            
            [aliases: nmp]
```

**Comment by onbjerg** [comment] 2022-09-01 10:38
There is not currently

**Comment by onbjerg** [comment] 2022-09-01 10:39
Duplicate of https://github.com/foundry-rs/foundry/issues/2988

**Closed by onbjerg** 2022-09-01 10:39 UTC
Labels: T-feature, C-forge, Cmd-forge-coverage
