### ISSUE TITLE
Remove feature that makes inclusion of "fail" in test name cause the test to always fail.

### ISSUE THREAD

**Issue by mgiagante** [foundry-rs/foundry#9218] opened 2024-10-28 20:36 UTC
### Component

Forge

### Describe the feature you would like

Currently, including the word "fail" in the name of a test makes the test always expect a revert. This is counter intuitive as some users might add this word in the test name to describe the intent of the case or the scenario under test.

Unless there is a strong case for keeping this, its removal would make `forge test` more intuitive.

**Comment by mgiagante** [comment] 2024-10-28 20:37
I want to volunteer to fix this.
Feel free to assign it to me if you want. Thanks!

**Comment by zerosnacks** [comment] 2024-10-29 08:43
This is a breaking change with DappTools compatibility that we are intending to make after the V1 release

**Comment by grandizzy** [comment] 2024-10-30 06:12
Closing this one as dupe of https://github.com/foundry-rs/foundry/issues/4437

**Closed by grandizzy** 2024-10-30 06:12 UTC
Labels: T-feature, T-to-discuss, T-post-V1
