### ISSUE TITLE
ewasm in extraoutput config throw a InternalCompilerError error

### ISSUE THREAD

**Issue by StErMi** [foundry-rs/foundry#2044] opened 2022-06-21 05:55 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (9010e8b 2022-06-21T00:10:16.127085Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

When I try to build/test with the `foundry.toml` config 

```
[default]
optimizer_runs = 200
extra_output_files = [ "ewasm"]
```

I get this console error

```bash
[⠑] Compiling...
[⠘] Compiling 4 files with 0.5.17
[⠃] Compiling 87 files with 0.6.4
[⠰] Solc 0.5.17 finished in 52.21ms
[⠒] Solc 0.6.4 finished in 1.50s
Error: 
   0: Compiler run failed
      InternalCompilerError: 
      

      UnimplementedFeatureError: 
      
   0: 

Location:
   cli/src/compile.rs:151

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

**Comment by onbjerg** [comment] 2022-06-21 07:32
This is an internal compiler error. My best guess is that eWASM wasn't really fully supported in the versions you are using (which are quite old). Looking at the v0.5.13 solc docs the compiler input description (that we use) does seem to suggest that it is unsupported.

@mattsse any ideas?

**Comment by StErMi** [comment] 2022-06-21 07:33
> This is an internal compiler error. My best guess is that eWASM wasn't really fully supported in the versions you are using (which are quite old). Looking at the v0.5.13 solc docs the compiler input description (that we use) does seem to suggest that it is unsupported.
> 
> @mattsse any ideas?

I can try on a new code, this one is old because I'm doing a `foundry-ethernaut-ctf` migration ;)

**Comment by mattsse** [comment] 2022-06-21 10:52
let me check when ewasm was added and add this to the existing ethers-solc backwards compatible check

**Comment by mattsse** [comment] 2022-06-21 10:57
it shipped with 0.5.13 but

> (EWasm) binary output (not fully working yet, though)

not sure what we should do here, since it's possible to pass this to solc but may result in errors so I think we still keep it even if it not working

**Comment by onbjerg** [comment] 2022-06-22 00:34
I don't think there's much we can do - if it's not fully supported on the compiler at that version and would require special handling I don't think we should put much time into it given that 0.5.13 is so old. I would recommend upgrading if you want eWASM support @StErMi.

I'm closing this issue but feel free to let me know if you think this does not make sense :)

**Closed by onbjerg** 2022-06-22 00:34 UTC
Labels: T-bug, C-forge, Cmd-forge-build

**Comment by StErMi** [comment] 2022-06-22 05:34
> I don't think there's much we can do - if it's not fully supported on the compiler at that version and would require special handling I don't think we should put much time into it given that 0.5.13 is so old. I would recommend upgrading if you want eWASM support @StErMi.
> 
> I'm closing this issue but feel free to let me know if you think this does not make sense :)

Makes totally sense. I will not upgrade for my use case because being a CTF there's a reason why I'm using those "old" version, but you are right. 

When I created the issue I thought it was a general issue not bound to a specific problem of old sold version!
Thanks for the support!

**Comment by StErMi** [comment] 2022-06-22 05:44
I'm still having a problem but by using `Solidity v0.8.13`.

How to reproduce it: 

1) `forge init --template https://github.com/StErMi/forge-template forge-test`
2) Update `foundry.toml` to add

```
[default]
optimizer_runs = 200
extra_output_files = [ "ewasm"]
```

3) run `forge test` and now I get this error 

```bash
Error:
   0: Compiler run failed
      YulException: Invalid code generated after EVM to wasm translation.
      Note that the source locations in the errors below will reference the original, not the translated code.
      Translated code: [.... continue ]
```
Full error log: https://gist.github.com/StErMi/e8e93ea70d9a955389404abeb84891a2

**Comment by shekhirin** [comment] 2022-06-22 16:20
I think it's related to immutables not being supported for `ewasm` target yet: https://github.com/ethereum/solidity/issues/10148.

This is how you can reproduce it:
```solidity
pragma solidity >=0.4.22 <0.9.0;

contract C {
  address immutable private owner;
  constructor() {
    owner = msg.sender;
  }
}
```

```bash
Uncaught exception:
/solidity/libyul/backends/wasm/EVMToEwasmTranslator.cpp(112): Throw in function solidity::yul::Object solidity::yul::EVMToEwasmTranslator::run(const solidity::yul::Object &)
Dynamic exception type: boost::wrapexcept<solidity::yul::YulAssertion>
std::exception::what: Invalid code generated after EVM to wasm translation.
Note that the source locations in the errors below will reference the original, not the translated code.
Translated code:
----------------------------------
...
}----------------------------------
Error: Function "setimmutable" not found.

```
