### ISSUE TITLE
feat(cheatcodes): add negative assertions for `expectEmit` and `expectRevert` using `count` syntax

### ISSUE THREAD

**Issue by fubhy** [foundry-rs/foundry#509] opened 2022-01-19 10:28 UTC
Negative assertions, e.g. asserting that a certain `call` was not performed or a certain event was not `emit`ed are not very useful on their own (because they might pass for the wrong reasons, e.g. a negative assertion always passes if you simply don't do anything of course).

However, when paired with positive assertions (e.g. asserting that the tested functionality actually performed the desired state mutation), they can be very useful to assert that a certain code path was skipped in doing so. This can be useful to test e.g. that a certain conditional was skipped.

I realize that this can already be achieved at the test level with the `testFail` prefix, but that comes with different ergonomics vs. negating individual assertions.

**Comment by gakonst** [comment] 2022-01-19 11:29
Good idea. Does any other project do it, so that we can have some example? What would be your ideal syntax?

(cc @brockelmore @mds1 @transmissions11)

**Comment by mds1** [comment] 2022-01-19 14:43
I like this idea, agreed it'd be useful, but I don't have any examples offhand. It's easy to extend DSTest to add an `assertNeq` method so I think we can ignore that for the scope of this issue. Then we have `expectEmit`, `expectCall`, and `expectRevert`. Inverting `expectRevert` isn't necessary, so we're down to just calls and events, but let me know if there's anything we might be missing here.

It would also be useful to test that you don't jump to a certain function within your contract (and similarly have an `expectJump`), though I'd guess this is currently difficult for the same reasons as #432 

Some syntax ideas:
1. a `vm.expectInverse()` cheat code that watches for the next `vm.expect*()` and inverts it. With an approach like this I worry we're cluttering up tests a bit, e.g. you now need 4 lines to test an event is not emitted, and because of the order required you can't wrap these into a helper method
2. similar to 1 but instead called as `vm.expectInverse(vm.expect*())`, which saves a line, but I think we'd have to abi encode this without a preprocessor—also this then becomes the only cheatcode that takes another cheat code as input, but maybe that's ok

There's probably another question of how topics should be considered when expecting an event not to be emitted. I'd guess most or all use cases only are really interested in only ensuring that topic0 is not found, as opposed to ensuring topic0 is emitted but that topic1/data does not have some value. The easiest behavior is to just invert the result of `expectEmit`, but then everyone would be calling `vm.expectEmit()` with 4 unused input args every time they want to assert an event isn't emitted which feels a bit gross

**Comment by fubhy** [comment] 2022-01-19 15:08
@mds1 Agreed wrt `1` being a bit verbose / cluttered. I like `2`, but maybe we can make that a bit shorter: What about `vm.not(vm.expectCall(...))` ?

Slightly off topic, but for events in particular, wouldn't it make sense to also have a more ergonomic version that just tests for topic0 via `vm.expectEmit("Transfer(address, address, uint)")`.

**Comment by mds1** [comment] 2022-01-19 15:16
> Slightly off topic, but for events in particular, wouldn't it make sense to also have a more ergonomic version that just tests for topic0 via vm.expectEmit("Transfer(address, address, uint)")

That'd be a useful overload here, because then we can shorten it to s single line `vm.not(vm.expectEmit("Transfer(address, address, uint)"))`. IIRC we discussed an `expectEmit` syntax like that but didn't implement it since it doesn't extend nicely to taking input args of the expected params, though I may be misremembering / @brockelmore might recall

**Comment by odyslam** [comment] 2022-09-29 13:00
+1 for vm.not before expectNotEmit. For some protocols (like Nomad), where the functionality is heavily based on event emission, some times there are no other signals (or variables to be read) that can verify that something did NOT happen, except the NOT emission of an event.

**Comment by mattsse** [comment] 2022-09-29 13:20
this is definitely useful and we should add this imo.

otherwise, you can't test the inverse of expectEmit.

flipping the impl and adding `expectNotEmit` should be easy.

will try to squeeze this in

**Comment by ChainsightLabs** [comment] 2022-09-29 16:25
+1

**Comment by DanTheDev-il** [comment] 2022-11-03 07:50
def a +1 from my side for this change, too.

Hardhat has a similar functionality that I found really easy and handy to use:

expect(<call).to.not.emit(<contract>, <eventName>).withArgs(....)

the ".withArgs" part is optional. So either I check only if an event was emitted or not or I can also check if the args match (or dont).

**Comment by reubenr0d** [comment] 2023-03-21 23:21
+1

Another way to go about this would be with cheatcodes that count the number of times a function is called or event emitted. That way we can not only assert that call/emit was made multiple times, but also if it was not made at all using the same cheat.

There is an issue for `expectCallCount` (https://github.com/foundry-rs/foundry/issues/4513), but we could also do something similar for events as well.
Eg. `expectEmit(bool,bool,bool,bool, uint256 count)`

**Comment by mds1** [comment] 2023-03-29 16:17
I'm supportive of adding overloads with a `count` arg for both the `expectEmit` and `expectCall` cheats, since that accomplishes both this issue and #4513 with the same UX/set of cheats. I saw in the support telegram that you'd be interested in working on this, should I assign to you?

Also if anyone has objections to that syntax and has a reason to prefer e.g. `expectNoEmit` please share 🙂

**Comment by reubenr0d** [comment] 2023-03-30 04:08
Yep, you can assign it to me @mds1

**Comment by Evalir** [comment] 2023-05-08 20:51
cc @mds1 i guess we went for the `count` syntax arg (which needs to be fixed)—do we still wanna implement negative assertions?

**Comment by grandizzy** [comment] 2024-09-11 14:01
> cc @grandizzy possibly relevant to recent cheatcode additions

yep, is on my cheatcode expect* list to tackle

**Closed** 2024-12-17 15:26 UTC
Labels: T-feature, Cmd-forge-test, C-forge, A-cheatcodes, P-normal

**Comment by avniculae** [comment] 2025-04-24 14:50
`expectEmit` with `count: 0` does not seem to work as intended

```
forge Version: 1.0.0-stable
Build Timestamp: 2025-02-13T20:02:34.979686000Z (1739476954)
```

Here's a POC
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import {Test} from "forge-std/Test.sol";

contract A {
    event Event1();
    event Event2();

    function foo() public {
        emit Event1();
    }

    function bar() public {
        emit Event2();
    }
}

contract B is Test {
    A a;

    function setUp() public {
        a = new A();
    }

    function test_foo_Event1() public {
        vm.expectEmit(address(a));
        emit A.Event1();
        
        a.foo();
    }

    function test_foo_Event2() public {
        vm.expectEmit({emitter: address(a), count: 0});
        emit A.Event2();

        a.foo();
    }
}
```

Trace shows that `Event2` is not emitted, but the test fails with `[FAIL: log != expected log]`

Do you experience the same?

**Comment by grandizzy** [comment] 2025-04-25 08:05
@avniculae this fails because you expect no event emitted from address a (`vm.expectEmit({emitter: address(a), count: 0});`) but there's one `Event1` emitted through `a.foo();` call. If you change expect to `vm.expectEmit({emitter: address(a), count: 1});` then test pass, hope this makes sense.

**Comment by avniculae** [comment] 2025-04-25 14:53
@grandizzy I don't see how `count: 0` serves the initial purpose in this case then: that is, to assert that a particular event is not emitter. Also, `vm.expectEmit({emitter: address(a), count: 1});` will not make the test pass, as now it expects that `Event2` is emitted once, but only `Event1` is emitted.

**Comment by grandizzy** [comment] 2025-04-25 14:57
@avniculae the expect emit with emitter and country 0 should be read as: this particular emitter / address should not emit any event, which is not the case in your test (a.foo() emits an event).
`vm.expectEmit({emitter: address(a), count: 1});` means that emitter a should emit exactly one event, which it does and test passes locally here. Do you get different result?

**Comment by avniculae** [comment] 2025-04-25 15:48
@grandizzy I see, so this is different than the initial intention mentioned here I guess https://github.com/foundry-rs/foundry/issues/509#issuecomment-1488912530

This one fails for me locally
```
function test_foo_Event2() public {
        vm.expectEmit({emitter: address(a), count: 1});
        emit A.Event2();

        a.foo();
    }
```

**Comment by grandizzy** [comment] 2025-04-25 15:58
> [@grandizzy](https://github.com/grandizzy) I see, so this is different than the initial intention mentioned here I guess [#509 (comment)](https://github.com/foundry-rs/foundry/issues/509#issuecomment-1488912530)
> 
> This one fails for me locally
> 
> ```
> function test_foo_Event2() public {
>         vm.expectEmit({emitter: address(a), count: 1});
>         emit A.Event2();
> 
>         a.foo();
>     }
> ```

yeah, should be `a.bar()` instead `a.foo();` as in emitter with address a emits one `Event2` event. If you use `a.foo` that emits `Event1`

**Comment by avniculae** [comment] 2025-04-25 16:15
@grandizzy but if `count:1` applies only on the event emitted in the test (ie in this case applies to Event2), why is the behaviour of `count:0` different?

**Comment by deluca-mike** [comment] 2025-05-14 08:16
Can confirm, the current implementation of `function expectEmit(address emitter, uint64 count) external;` is both limiting and also seems broken.

**Comment by grandizzy** [comment] 2025-05-14 08:33
> Can confirm, the current implementation of `function expectEmit(address emitter, uint64 count) external;` is both limiting and also seems broken, at least when trying to specify a count of 0.

please detail what you find off, can turn it into a gh issue after. thank you

**Comment by avniculae** [comment] 2025-05-15 11:14
@grandizzy As I detailed above, I personally think the `expectEmit(count)` implementation is
1. not serving its initial purpose: that is, to assert a particular event is not emitted (similar to `expectCall(count)`). Rather, `expectEmit(count)` when `count=0` applies generally, for all events
2. is inconsistent: when `count > 0` it applies for a single event (the one you emit just after `expectEmit`), while `count=0` applies for all events (as highlighted in point 1)
