### ISSUE TITLE
是否可以想remix直接部署proxy？

### ISSUE THREAD

**Issue by xf8259980** [foundry-rs/foundry#5257] opened 2023-06-30 05:23 UTC
### Component

Other (please describe)

### Describe the feature you would like

remix 可以在引入uups后自动化部署Deploy with Proxy 。
用户只需要勾选 Deploy with Proxy 就可以了。
但是在foundry中使用 create 部署。能否新增一个参数自动化部署 proxy ？

**Comment by Evalir** [comment] 2023-06-30 20:59
Closing due to:
- Please use english for filling issues
- This is a duplicate of a few proxy management issues we've gotten, and currently there is no appetite to include these natively into foundry.

**Closed by Evalir** 2023-06-30 20:59 UTC
Labels: T-feature
