### ISSUE TITLE
forge coverage does not use same settings as forge build

### ISSUE THREAD

**Issue by comunidadio** [foundry-rs/foundry#4921] opened 2023-05-11 02:06 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (db96393 2023-05-11T00:10:51.773583000Z)

### What command(s) is the bug in?

forge coverage

### Operating System

macOS (Apple Silicon)

### Describe the bug

➜  forge git:(master) ✗ forge build                 
[⠆] Compiling...
[⠒] Compiling 26 files with 0.8.19
[⠰] Solc 0.8.19 finished in 10.18s
Compiler run successful!
➜  forge git:(master) ✗ forge coverage
[⠢] Compiling...
[⠒] Compiling 26 files with 0.8.19
[⠑] Solc 0.8.19 finished in 1.37s
Error: 
Compiler run failed:
Error: Unimplemented feature (/solidity/libsolidity/codegen/ArrayUtils.cpp:228):Copying of type struct MyStruct memory[] memory to storage not yet supported.

---

Expected behavior: same successful compilation as with "forge build" as "forge coverage" should use the same settings (like "forge test" who does run fine).
Actual behavior: getting an "unimplemented feature" error.

Note that I do the get the same compilation error with "forge build" if I remove "via_ir = true" from my foundry.toml file, so I guess some build settings are not passed consistently to coverage build.

**Comment by PaulRBerg** [comment] 2023-05-16 20:16
Duplicate of https://github.com/foundry-rs/foundry/issues/3527#issuecomment-1366189327.

Also, see the discussion in https://github.com/foundry-rs/foundry/issues/3978.

**Comment by PaulRBerg** [comment] 2023-05-16 20:17
If you want `forge coverage` to work, you will need to make your code compile even without `--via-ir`. [See my tweet](https://twitter.com/PaulRBerg/status/1612043506545033218).

**Closed as completed** 2023-05-17 06:26 UTC
Labels: T-bug
