### ISSUE TITLE
bug(`forge script`): `Text file busy (os error 26)` due to race condition in SVM when doing multiple installations

### ISSUE THREAD

**Issue by kahuang** [foundry-rs/foundry#8508] opened 2024-07-24 03:07 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (ef62fdb 2024-07-12T00:22:06.894449000Z)

### What command(s) is the bug in?

forge script

### Operating System

Linux

### Describe the bug

Compiling 1 files with Solc 0.8.15
Compiling 38 files with Solc 0.8.25
Compiling 4 files with Solc 0.8.19
installing solc version "0.8.15"
installing solc version "0.8.19"
installing solc version "0.8.25"
Successfully installed solc 0.8.19
Successfully installed solc 0.8.25
Solc 0.8.19 finished in 607.39ms
Successfully installed solc 0.8.15
Solc 0.8.15 finished in 769.38ms
Error:
"/root/.svm/0.8.25/solc-0.8.25": Text file busy (os error 26)
Error: Command '['forge', 'script', '-vvv', 'scripts/deploy/Deploy.s.sol:Deploy', '--rpc-url'...

**Comment by zerosnacks** [comment] 2024-07-24 08:45
Running into the same issue in a CI test here: https://github.com/alloy-rs/svm-rs/actions/runs/10073396814/job/27847343682#step:5:337

Possibly related

**Comment by grandizzy** [comment] 2024-10-17 12:58
this is dupe of https://github.com/foundry-rs/foundry/issues/4736 we're going to track issue there as more context available. thank you!

**Closed by grandizzy** 2024-10-17 12:58 UTC
Labels: T-bug, C-forge, P-low, Cmd-forge-script, A-compiler, T-to-investigate
