### ISSUE TITLE
Error forking binance mainnet with block number

### ISSUE THREAD

**Issue by bzpassersby** [foundry-rs/foundry#4962] opened 2023-05-17 16:18 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (6defdce 2023-05-17T00:12:17.009064000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Intel)

### Describe the bug

When creating a binance mainnet fork in my test file, if I specify a block number with `vm.createFork`, the following error message appears:
```
2023-05-17T16:09:17.302491Z ERROR sharedbackend: Failed to send/recv `basic` err=GetAccount(0x5615deb798bb3e4dfa0139dfa1b3d433cc23b72f, 
(code: -32000, message: missing trie node b7416b956ad63992bbcd79fce8a5a2272fe012db291728210ea033abdd44e21c (path ), data: None)) address=0x5615deb798bb3e4dfa0139dfa1b3d433cc23b72f
2023-05-17T16:09:17.385844Z ERROR sharedbackend: Failed to send/recv `basic` err=GetAccount(0x5615deb798bb3e4dfa0139dfa1b3d433cc23b72f, 
(code: -32000, message: missing trie node b7416b956ad63992bbcd79fce8a5a2272fe012db291728210ea033abdd44e21c (path ), data: None)) address=0x5615deb798bb3e4dfa0139dfa1b3d433cc23b72f
The application panicked (crashed).
Message:  called `Option::unwrap()` on a `None` value
Location: /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/revm-3.1.1/src/journaled_state.rs:133

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```
Note that, If no block number is specified in `vm.createFork`, no error message appears and fork is created and run successfully. So the issue seems to only arise when a block number is input. My json-rpc url is provided by ChainStack.

**Comment by agostbiro** [comment] 2023-06-10 17:59
Hi @bzpassersby , thanks for reporting this! I've managed to reproduce the error. 

The root cause of the issue is that the ChainStack RPC service doesn't provide [archive nodes](https://ethereum.org/en/developers/docs/nodes-and-clients/archive-nodes/) for their free tier, but forking from older blocks is only supported with archive nodes. If you need to fork from a specific block, you could try try to upgrade your ChainStack plan or use a different provider such as Alchemy, Ankr or Infura that provide archive nodes for free for development.

I'm working on a PR to improve error reporting when a user tries to fork from an older block with a non-archive node.

**Comment by Evalir** [comment] 2023-07-01 01:18
Closing—this was improved recently and is an RPC issue fundamentally.

**Closed by Evalir** 2023-07-01 01:18 UTC
Labels: T-bug
