### ISSUE TITLE
Contract constructor is not returning any values when forcing to return data via assembly

### ISSUE THREAD

**Issue by 0xRaccoon** [foundry-rs/foundry#4568] opened 2023-03-15 17:48 UTC
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

0.2.0

### Operating System

macOS (Intel)

### Describe the bug

We are currently using a contract constructor to batch RPC transactions and force it to return data via assembly, as explained in [RPC Batching](https://defi-wonderland.notion.site/RPC-Request-Batching-Easily-10x-your-requests-performance-7ac7704cdd53473fb132f66d36211edd). However, we are facing an issue when trying to test with a local fork using `anvil`. Specifically, the constructor is not returning any data, unlike other RPCs.

To simplify the example we can use the following contract:

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.13;

contract ConstructorReturnData {
  constructor() {
    uint256[] memory _returnData = new uint256[](1);
    _returnData[0] = 1;
    bytes memory _data = abi.encode(_returnData);

    assembly {
      let _dataStart := add(_data, 32)
      let _dataEnd := sub(msize(), _dataStart)
      return(_dataStart, _dataEnd)
    }
  }
}
```

**Steps to Reproduce**
1. Start a local mainnet fork using `anvil`.
2. Use the contract constructor to return data via assembly.
eg.
``` 
    const constructorReturnDataFactory = (await ethers.getContractFactory('ConstructorReturnData')) as ConstructorReturnData__factory;
    const contractCreationCode = constructorReturnDataFactory.bytecode;
    const returnedData = await provider.call({ data: contractCreationCode });
    console.log(returnedData);
```
4. Observe that the constructor does not return any data.

**Expected Behavior**
-The constructor should return data, as it does when using other RPCs, in the case of the example `0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001`.

Actual Behavior
-The constructor does not return any data when using a local fork with anvil (`0x`).

**Comment by mattsse** [comment] 2023-03-15 21:51
I believe this is a bug in revm, which should be addressed by #4356

**Comment by nzhl** [comment] 2023-04-17 14:46
+1 same issue, any progress ?

**Comment by klkvr** [comment] 2024-07-12 11:27
Can't reproduce this anymore, assuming fixed by mentioned revm update
```
cast call --create 0x608060405234801561001057600080fd5b506000600167ffffffffffffffff81111561002e5761002d6100b0565b5b60405190808252806020026020018201604052801561005c5781602001602082028036833780820191505090505b509050600181600081518110610075576100746100df565b5b60200260200101818152505060008160405160200161009491906101d6565b6040516020818303038152906040529050602081018059038082f35b7f4e487b7100000000000000000000000000000000000000000000000000000000600052604160045260246000fd5b7f4e487b7100000000000000000000000000000000000000000000000000000000600052603260045260246000fd5b600081519050919050565b600082825260208201905092915050565b6000819050602082019050919050565b6000819050919050565b61014d8161013a565b82525050565b600061015f8383610144565b60208301905092915050565b6000602082019050919050565b60006101838261010e565b61018d8185610119565b93506101988361012a565b8060005b838110156101c95781516101b08882610153565b97506101bb8361016b565b92505060018101905061019c565b5085935050505092915050565b600060208201905081810360008301526101f08184610178565b90509291505056fe
0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001
```

**Closed by klkvr** 2024-07-12 11:27 UTC
Labels: T-bug, C-anvil, T-to-investigate
