### ISSUE TITLE
Crashed while testing transferFrom: called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by x1250** [foundry-rs/foundry#5860] opened 2023-09-20 04:22 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (135ee3e 2022-12-29T00:04:02.850095146Z)

### What command(s) is the bug in?

forge test -vvv --fork-url https://bsc-dataseed.binance.org/ --fork-block-number 31596150 --debug testTransferFromWithoutTax

### Operating System

Linux

### Describe the bug

This test fails:

  function testTransferFromWithoutTax() public {
    uint256 allowanceAmount = 500 * 10**18;
    uint256 transferAmount = 200 * 10**18;

    // Bob aprueba un allowance para carol
    token.approve(carol, allowanceAmount);

    uint256 initialBalanceBob = token.balanceOf(bob);
    uint256 initialBalanceCarol = token.balanceOf(carol);

    vm.stopPrank();
    vm.startPrank(carol);
    // Carol transfers from Bob
    token.transferFrom(bob, carol, transferAmount);
    vm.stopPrank();

    uint256 finalBalanceBob = token.balanceOf(bob);
    uint256 finalBalanceCarol = token.balanceOf(carol);

    require(finalBalanceBob == initialBalanceBob - transferAmount, "BOB_WRONG_FINAL_BALANCE");
    require(finalBalanceCarol == initialBalanceCarol + transferAmount, "CAROL_WRONG_FINAL_BALANCE");
  }

$ RUST_BACKTRACE=1 forge test -vvv --fork-url https://bsc-dataseed.binance.org/ --fork-block-number 31596150 --debug testTransferFromWithoutTax
[⠢] Compiling...
No files changed, compilation skipped
2023-09-20T04:18:36.536211Z ERROR sharedbackend: Failed to send/recv `basic` err=GetAccount(0x1804c8ab1f12e6bbf3894d4083f33e07309d1f38, 
(code: -32000, message: missing trie node, data: None)) address=0x1804c8ab1f12e6bbf3894d4083f33e07309d1f38
2023-09-20T04:18:36.536272Z ERROR forge::multi_runner: error=Failed to get account for 0x1804c8ab1f12e6bbf3894d4083f33e07309d1f38: 0x1804c8ab1f12e6bbf3894d4083f33e07309d1f38
The application panicked (crashed).
Message:  called `Option::unwrap()` on a `None` value
Location: cli/src/cmd/forge/test/mod.rs:185

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: __libc_start_call_main<unknown>
      at ./csu/../sysdeps/nptl/libc_start_call_main.h:58
   2: __libc_start_main_impl<unknown>
      at ./csu/../csu/libc-start.c:392

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.

**Comment by Evalir** [comment] 2023-09-20 04:28
Hi! Thanks for reporting. Sadly though, this is an RPC issue and somewhat common when using bsc endpoints—we'd recommend using more reliable ones.

Closing as not a bug, but a common chain-specific quirk.

**Closed by Evalir** 2023-09-20 04:28 UTC
Labels: T-bug
