### ISSUE TITLE
Broken pipe, failed printing to stdout

### ISSUE THREAD

**Issue by Gypsaman** [foundry-rs/foundry#9191] opened 2024-10-24 14:05 UTC
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e903484 2024-07-19T00:35:00.583275743Z)

### What command(s) is the bug in?

cast call ... | cast abi_decode

### Operating System

Linux

### Describe the bug

I am trying to pipe the output of a cast call to a cast abi-decode.
`cast call 0x5FbDB2315678afecb367f032d93F642f64180aa3 "get_car()" --rpc-url=$LOCAL_PROVIDER | cast abi-decode "(string,uint256,uint256)" `

```
error: the following required arguments were not provided:
  <CALLDATA>

Usage: cast abi-decode <SIG> <CALLDATA>

For more information, try '--help'.
The application panicked (crashed).
Message:  failed printing to stdout: Broken pipe (os error 32)
Location: library/std/src/io/stdio.rs:1118

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: __libc_start_call_main<unknown>
      at ./csu/../sysdeps/nptl/libc_start_call_main.h:58
   2: __libc_start_main_impl<unknown>
      at ./csu/../csu/libc-start.c:360
```

**Comment by grandizzy** [comment] 2024-10-24 14:18
looks similar with https://github.com/foundry-rs/foundry/issues/7055 which we're working to get a fix for soon
CC @zerosnacks

**Comment by zerosnacks** [comment] 2024-10-24 15:22
@grandizzy doesn't appear this is a regression of https://github.com/foundry-rs/foundry/pull/9109 which is fortunate but https://github.com/foundry-rs/foundry/pull/9174 does not appear to fix this either. Going to investigate this further.

**Comment by zerosnacks** [comment] 2024-10-24 15:40
Hi @Gypsaman, thanks for your report

Marking as a duplicate of https://github.com/foundry-rs/foundry/issues/7055 as it is the same underlying issue that will be resolved soon.

**Closed by zerosnacks** 2024-10-24 15:40 UTC
Labels: T-bug, T-needs-triage
