### ISSUE TITLE
Refactor `foundry_utils::link_with_nonce_or_address`

### ISSUE THREAD

**Issue by joshieDo** [foundry-rs/foundry#1843] opened 2022-06-05 11:16 UTC
### Component

Forge

### Describe the feature you would like

This function is becoming too much. Should be heavily refactored.

**Comment by onbjerg** [comment] 2022-06-05 12:39
Duplicate of #975?

**Comment by mattsse** [comment] 2022-06-06 11:46
yeh I think that's a dup 

let's close this one since #975 has more info and discussion

**Closed by mattsse** 2022-06-06 11:46 UTC
Labels: T-debt
