### ISSUE TITLE
Cross Chain Testing

### ISSUE THREAD

**Issue by hexonaut** [foundry-rs/foundry#1558] opened 2022-05-08 17:34 UTC
### Component

Forge

### Describe the feature you would like

It would be nice to be able to coordinate integration tests across multiple chains. MakerDAO is actively expanding to other chains. Currently we do integration testing with hardhat because you can connect to multiple forks at once. It would be nice if we have some cheatcode to switch between chains.

For example you could configure:

mainnet: https://ethereumendpoint
optimism: https://optimismendpoint

We could then toggle between the networks:

```
vm.switchContext("mainnet");
// do something on mainnet
vm.switchContext("optimism")
// do something on optimism
```

**Comment by odyslam** [comment] 2022-05-08 18:52
This is also very interesting to us ! (Nomad.xyz). 

How do you handle it now @hexonaut ? I was thinking to use `--ffi` to input/output data between different `forge test` that use different forks

**Comment by onbjerg** [comment] 2022-05-08 19:03
Duplicate of https://github.com/foundry-rs/foundry/issues/834?

**Comment by odyslam** [comment] 2022-05-08 19:40
@onbjerg I think so

**Comment by onbjerg** [comment] 2022-05-08 22:50
Let me know if it's not a duplicate and I will reopen @hexonaut  :blush:

**Closed** 2022-05-08 22:49 UTC
Labels: T-feature

**Comment by hexonaut** [comment] 2022-05-09 12:38
Ah yes it's a duplicate.
