### ISSUE TITLE
debugger: out of bounds crash

### ISSUE THREAD

**Issue by Ainevsia** [foundry-rs/foundry#7292] opened 2024-03-02 06:33 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (4f00ec6 2024-02-17T00:16:39.754919679Z)

### What command(s) is the bug in?

forge test --debug test_Challenge

### Operating System

Linux

### Describe the bug

`alloc::vec::Vec<T,A>::swap_remove::assert_failed::h5090f444fc1dfa89`

![image](https://github.com/foundry-rs/foundry/assets/31178818/a0daf218-b08b-4e1c-9995-07041ecfa862)

when I was about to proceed debugging in this command, the debbuger trashed

![image](https://github.com/foundry-rs/foundry/assets/31178818/f8a975c9-6fdc-495b-855b-f6ba9489a4ff)

```bash
The application panicked (crashed).
Message:  swap_remove index (is 8) should be < len (is 6)
Location: /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/vec/mod.rs:1460

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 8 frames hidden ⋮                               
   9: alloc::vec::Vec<T,A>::swap_remove::assert_failed::h5090f444fc1dfa89
      at <unknown source file>:<unknown line>
  10: foundry_debugger::tui::draw::<impl foundry_debugger::tui::context::DebuggerContext>::draw_src::h708aaf46d88ea8c0
      at <unknown source file>:<unknown line>
  11: foundry_debugger::tui::draw::<impl foundry_debugger::tui::context::DebuggerContext>::draw::hbfb71a38efc8877e
      at <unknown source file>:<unknown line>
  12: foundry_debugger::tui::TerminalGuard<B>::with::h17e17004297486f5
      at <unknown source file>:<unknown line>
  13: foundry_debugger::tui::Debugger::try_run::hb1836f3405ec111c
      at <unknown source file>:<unknown line>
  14: forge::cmd::test::TestArgs::execute_tests::{{closure}}::h53b2154b561e44d4
      at <unknown source file>:<unknown line>
  15: forge::cmd::test::TestArgs::run::{{closure}}::hb3dc4877be496e8d
      at <unknown source file>:<unknown line>
  16: foundry_cli::utils::block_on::h7a01a85b3f5b3642
      at <unknown source file>:<unknown line>
  17: forge::main::h551766c42bc2efd1
      at <unknown source file>:<unknown line>
  18: std::sys_common::backtrace::__rust_begin_short_backtrace::hdfc3c8eba44a89b5
      at <unknown source file>:<unknown line>
  19: main<unknown>
      at <unknown source file>:<unknown line>
  20: __libc_start_main<unknown>
      at /build/glibc-wuryBv/glibc-2.31/csu/../csu/libc-start.c:308
  21: _start<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
[1]    1468374 abort (core dumped)  forge test --debug test_Challenge
```

**Comment by piohei** [comment] 2024-03-19 19:03
Hi all! I came to same error when doing my testing. It can be reproduced by running debug with single file and two contracts in it. It is caused by wrong mapping in the code. Here https://github.com/foundry-rs/foundry/blob/master/crates/debugger/src/tui/draw.rs#L350 is a mapping with file_id -> bytecode. It should be (file_id, contract_name) -> bytecode. Now wrong bytecode is used for source when getting IC based on PC and then looking for source.

**Comment by mattsse** [comment] 2024-03-19 19:06
nice, thanks for looking into this, this sounds fixable

**Comment by piohei** [comment] 2024-03-22 10:39
I guess this is same issue https://github.com/foundry-rs/foundry/issues/7216.
This one **potentially** can also be caused by same problem https://github.com/foundry-rs/foundry/issues/7111.

**Comment by DaniPopes** [comment] 2024-05-24 20:45
Panic fixed with https://github.com/foundry-rs/foundry/pull/7991

**Closed by DaniPopes** 2024-05-24 20:45 UTC
Labels: T-bug
