### ISSUE TITLE
Publish `anvil` node to crates.io as crate

### ISSUE THREAD

**Issue by shekohex** [foundry-rs/foundry#2441] opened 2022-07-22 14:41 UTC
### Component

Anvil

### Feature Request

Hello, I would like to have `anvil` crate published to crates.io as a crate (not just the binary) and that we can be able to use it from normal rust projects.

### Context and use cases

It would be super useful to have a fully running local EVM node from our Rust projects and be able to interact with them using ethers-rs for example, and here is specifically what are our use case:

As a developer, I would like to be able to spawn a local EVM node, deploy some contracts on it (using ethers-rs), run a few tests on it, then at the end tear down everything. 

Talking more specific, we are building General Purpose Oracles, in Rust using ethers-rs, and we built a general `EventWatcher` module that watches for contract events and then calls `handle_event` to a set of preconfigured event handlers. We want to test this and make sure it works under different scenarios.

**What we did consider before?** we did fallback to use and write all of our tests in Typescript with ganache and ethers.js and run our oracle as a child process with JSON logging, man, it is a crazy process to just test a few things. What we hope for is that, with everything being in Rust using `anvil` it will be super simple as we can use Rust's built-in test framework to do all these things in much simpler way so that we test each part in more isolated way.  

### Additional context

Here is a link to our Oracle code of the [`EventWatcher`](https://github.com/webb-tools/relayer/blob/cb25b3ed5428795158a8e76173bd877f0122d3d8/src/events_watcher/mod.rs#L95-L259) that I was talking about above.

**Comment by onbjerg** [comment] 2022-07-22 16:39
Duplicate of #665

**Closed by onbjerg** 2022-07-22 16:39 UTC
Labels: T-feature

**Comment by shekohex** [comment] 2022-07-22 16:49
Thank you.
