### ISSUE TITLE
Using a script to send transactions deploying contracts and sending ether Not Working on goerli arbitrum

### ISSUE THREAD

**Issue by mesozoic-technology** [foundry-rs/foundry#4566] opened 2023-03-15 16:07 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (df8ab09 2023-03-14T09:58:14.632506Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Intel)

### Describe the bug

When I use a script that deploys a contract that uses an external library, forge should be deploying this library ahead of my contract and linking it to my contract before deploying my contract.

This can work. It occasionally does.

But 95% of the time or more, I receive an error about gas estimation or an error about mismatched nonces from the provider.

When it is an error about gas estimation, it can be before it sends any transactions. Or, it can deploy the library first, continuing onto the transactions defined in my script, and error about gas estimation when it reaches the transaction that will deploy my contract - the second out of three script defined transactions. 

Right now, I am deploying to Arbitrum Goerli and it is constantly failing although it has occasionally succeeded in the past.

**Comment by Valentin-Seehausen** [comment] 2023-03-17 18:29
+1

**Comment by realisation** [comment] 2023-03-22 16:31
I'm having an impossible time deploying onto Arbitrum Goerli again.

(code: -32000, message: err: max fee per gas less than block base fee: address 0xA600AdFzCB8C750482a828q128495e026446cA96, maxFeePerGas: 101070000 baseFee: 101340000 (supplied gas 309316493),

**Comment by realisation** [comment] 2023-03-24 15:58
Still having this awful experience with Arbitrum Goerli. Seems like it is on their side as it works sometimes and does not work at all other times.

**Comment by gzeoneth** [comment] 2023-03-24 16:06
@realisation Do you have a deployment repo and script that we can try to reproduce?

**Comment by mattsse** [comment] 2023-03-24 16:20
I'd appreciate a minimal example that I can use to debug this.

**Comment by realisation** [comment] 2023-03-24 16:39
All my stuff is private. It happens when I try to do multiple interactions with Arbitrum Goerli. Potentially even one interaction. It can be for deploying a contract or just calling a contract. The flow that it messes up on mostly for me is interacting with a contract, deploying a contract, then sending ether to that contract with .call(). The contract has an external library so this generates four transactions, with the deployment of the external library prepending before the other three.

**Comment by realisation** [comment] 2023-03-24 16:40
When I try to do this flow, a great deal of the time it does not send any transactions, complaining about the gas fee. Maybe about as often it gets the first transaction through, deploying the external library. Very occasionally it gets the second transaction through. Never does it get to the third or fourth transactions.

**Comment by realisation** [comment] 2023-03-24 16:49
Make a simple script. Use an arbitrum RPC. Interact with a few contracts in the script with vm.broadcast(). You will see the problem.

**Comment by mattsse** [comment] 2023-03-24 18:11
It would save me time if I had a minimal repro that I could debug directly

**Comment by realisation** [comment] 2023-03-28 21:37
> It would save me time if I had a minimal repro that I could debug directly

It's that simple, you can make one. There are no complications. Interact multiple times in a standard foundry script and you will see. I am experiencing the problem again.

**Comment by gakonst** [comment] 2023-03-30 15:54
Hey @realisation :)

While we could try to make a repro, we are juggling a few different projects and it's hard to prioritize. If you want to get the best service out of us, you can help us by making the EXACT problem you're encountering as simple as "clone this repo, run forge test, the problem is there". 

Otherwise, Matt or I might spend a bunch of time trying to reproduce it, then come back to you with a fix, and you may say "oh this didn't fix my issue". So it is important that you have exact steps for reproducing, or we won't be able to prioritize it.

Appreciate the understanding, it is part of our culture to have repros and would like everyone to respect that :)

**Comment by zerosnacks** [comment] 2024-07-01 15:29
Marking as `requires reproduction`

Please re-open with a minimal reproduction if you are still facing this issue @mesozoic-technology

**Closed by zerosnacks** 2024-07-01 15:29 UTC
Labels: T-bug, C-forge, Cmd-forge-script, T-to-reproduce
