### ISSUE TITLE
tokio panic on debug

### ISSUE THREAD

**Issue by thedavidmeister** [foundry-rs/foundry#5271] opened 2023-07-02 12:19 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (d369d24 2023-07-02T00:05:10.773939000Z)

### What command(s) is the bug in?

forge test -vvv --debug <test>

### Operating System

macOS (Apple Silicon)

### Describe the bug

This is all i get for a debug

```
thedavidmeister@davids-iMac rain.interpreter % RUST_BACKTRACE=full forge test -vvv --debug testParseTwoFullLinesSingleRHSEach
[⠒] Compiling...
No files changed, compilation skipped
The application panicked (crashed).
Message:  Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.
Location: /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/mod.rs:65

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   2: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   3: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   4: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   5: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   6: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   7: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   8: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   9: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  10: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  11: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  12: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  13: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  14: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  15: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  16: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
zsh: abort      RUST_BACKTRACE=full forge test -vvv --debug testParseTwoFullLinesSingleRHSEac
```

**Comment by mattsse** [comment] 2023-07-02 12:59
@DaniPopes looks like a regression of https://github.com/foundry-rs/foundry/pull/5263

**Comment by mattsse** [comment] 2023-07-02 13:05
think I found it @DaniPopes 

fixing

https://github.com/foundry-rs/foundry/blob/ffefeeb257dc9776d69f105e37aac35b3f692909/cli/src/cmd/forge/test/mod.rs#L232-L232

**Comment by mattsse** [comment] 2023-07-02 13:09
@thedavidmeister thanks for flagging, triggering new release once merged

**Closed** 2023-07-02 13:10 UTC
Labels: T-bug

**Comment by thedavidmeister** [comment] 2023-07-02 13:57
> @DaniPopes looks like a regression of #5263
> 
> @thedavidmeister is the repo public?

it is yeah https://github.com/rainprotocol/rain.interpreter
