### ISSUE TITLE
`cheatcodes`: `expectRevert` mangles return data on low level calls

### ISSUE THREAD

**Issue by Evalir** [foundry-rs/foundry#5159] opened 2023-06-14 21:08 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### Operating System

None

### Describe the bug

When doing low level calls, it's expected that you can match the calldata returned with `vm.expectRevert`, but this is not possible—somewhere when reverting on low level calls, the calldata is being lost.

**Comment by mds1** [comment] 2023-06-14 21:15
Reproduction:

```solidity
contract A {
    function foo() public {
        revert("error message");
    }
}

contract MyTest is Test {
    A a;

    function setUp() public {
        a = new A();
    }

    // Passes, which makes sense
    function test1() public {
        vm.expectRevert("error message");
        a.foo();
    }

    // This test fails, and the return data is 512 bytes of zeros
    function test2() public {
        vm.expectRevert("error message"); // <-- We use expectRevert
        (bool ok, bytes memory data) = address(a).call(abi.encodeCall(A.foo, ()));
        assertTrue(ok, "call should fail"); //  <-- `ok` flipped from false to true by `vm.expectRevert`

        bytes memory expectedErr = abi.encodeWithSignature("Error(string)", ("error message"));
        console2.logBytes(data);
        console2.logBytes(expectedErr);
        assertEq(data, expectedErr);
    }

    // This test passes
    function test3() public {
        // No expectRevert here
        (bool ok, bytes memory data) = address(a).call(abi.encodeCall(A.foo, ()));
        assertFalse(ok, "call should fail"); <-- therefore `ok` is false here

        bytes memory expectedErr = abi.encodeWithSignature("Error(string)", ("error message"));
        console2.logBytes(data);
        console2.logBytes(expectedErr);
        assertEq(data, expectedErr);
    }
}
```

**Comment by mds1** [comment] 2023-06-15 20:57
Closing since this is expected behavior. TLDR is that when you flip the return value, it changes what data solc expects, so dummy data of zeroes is intentionally returned. The book will be updated with more info to clarify things

**Closed by mds1** 2023-06-15 20:57 UTC
Labels: T-bug
