### ISSUE TITLE
Issue with Forge Coverage

### ISSUE THREAD

**Issue by shikhar229169** [foundry-rs/foundry#5457] opened 2023-07-24 04:38 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (6e09b4e 2023-07-24T00:18:14.641174497Z)

### What command(s) is the bug in?

forge coverage

### Operating System

Linux

### Describe the bug

I have a contract, it contains of various functions. After writing certain functions I ran forge coverage, it was showing the contract in the coverage reports. And after that I added another function like below:
```solidity
function testing() public {
        
}
```
And after adding this function which actually does nothing, so at this point when I ran forge coverage, the contract was gone from the coverage reports. So, if we write any empty function in the contract, foundry doesn't consider that contract in the coverage reports.

**Comment by klkvr** [comment] 2024-04-02 20:38
The issue is that function starts with `test` which results in contract being recognized as a test contract and excluded from coverage report.

We will consider and implement opt-in/default tests inclusion into gas reports, closing this issue for now

**Closed by klkvr** 2024-04-02 20:38 UTC
Labels: T-bug
