### ISSUE TITLE
Add `checkEmit` cheatcode to test past log emission

### ISSUE THREAD

**Issue by adhusson** [foundry-rs/foundry#1906] opened 2022-06-10 14:29 UTC
### Component

Forge

### Describe the feature you would like

Sometimes the argument of an event is easy to figure out _after_ the call that triggered the `emit`, but not before. It may even be part of the return value of the call. In that case, rather than
```solidity
uint importantNumber = <figure out important number in a complicated way>
expectEmit(true,true,true,true,address(contract));
emit Event(importantNumber);
contract.doThing();
```

it would be much easier to write:
```solidity
T memory ret = contract.doThing();
checkEmit(true,true,true,true,address(contract));
emit Event(ret.importantNumber);
```

since the purpose of a test like this is just to check that the important number does get emitted, it makes sense to grab it from the call's return value.

**Comment by mds1** [comment] 2022-06-10 15:24
I agree this would be a better default, but it'd also be a breaking change so I don't think this will be updated soon. This is also being tracked in item 2 of https://github.com/foundry-rs/foundry/issues/876

**Comment by adhusson** [comment] 2022-06-10 16:06
Is there a reason to not have both (expect-before and check-after)?

**Comment by onbjerg** [comment] 2022-06-13 09:28
Is this not a duplicate of https://github.com/foundry-rs/foundry/issues/543 sort of? At least, they would be able to serve the same purpose.

**Comment by onbjerg** [comment] 2022-07-01 18:36
Closing this as a dupe of #543 keeping in mind that similar functionality is being worked on in #2161

**Closed by onbjerg** 2022-07-01 18:36 UTC
Labels: T-feature, Cmd-forge-test, C-forge, A-cheatcodes
