### ISSUE TITLE
`forge install` fails when repo contains both the same branch and tag names

### ISSUE THREAD

**Issue by sambacha** [foundry-rs/foundry#1828] opened 2022-06-03 07:48 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### Describe the bug

```shell
$ forge install https://github.com/sambacha/zen-foundry-template@v1 --no-commit
Installing zen-foundry-template in "/Users/sbacha/lib/zen-foundry-template" (url: Some("https://github.com/sambacha/zen-foundry-template"), tag: Some("v1"))
    Installed zen-foundry-template
00:46:37 sbacha Sams-MacBook-Pro /Users/sbacha/forge-t
$ ls
.  ..
```

```shell
$ forge install https://github.com/sambacha/zen-foundry-template@v1
Installing zen-foundry-template in "/Users/sbacha/lib/zen-foundry-template" (url: Some("https://github.com/sambacha/zen-foundry-template"), tag: Some("v1"))
Error:
   0: There are changes in your working/staging area. Commit them first or add the `--no-commit` option.

Location:
   cli/src/cmd/forge/install.rs:119

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets
```

**Comment by sambacha** [comment] 2022-06-03 07:48
this is from this issue which was closed https://github.com/foundry-rs/foundry/issues/1810

**Comment by 0xYYY** [comment] 2022-06-03 16:54
i can't reproduce the error, are you on the latest forge version?
```bash
❯ foundryup
foundryup: installing foundry (version nightly, tag nightly-0342bc24b7d248d3049ca7cf78caf6df59a81e52)
foundryup: downloading latest forge and cast
############################################################################################################################################################################## 100.0%
foundryup: downloading manpages
############################################################################################################################################################################## 100.0%
foundryup: installed - forge 0.2.0 (0342bc2 2022-06-03T00:07:22.397795526Z)
foundryup: installed - cast 0.2.0 (0342bc2 2022-06-03T00:07:22.397795526Z)
foundryup: done

❯ mkdir test && cd test && git init
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint:   git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint:   git branch -m <name>
Initialized empty Git repository in /home/haotongye/Repos/test/.git/

❯ forge install https://github.com/sambacha/zen-foundry-template@v1 --no-commit
Installing zen-foundry-template in "/home/haotongye/Repos/test/lib/zen-foundry-template" (url: Some("https://github.com/sambacha/zen-foundry-template"), tag: Some("v1"))
    Installed zen-foundry-template

❯ ls lib/zen-foundry-template
foundry.toml  justfile  package.json  README.md  scripts  src  test
```

additional context for discussion:
as for the name confict, if there is a tag with the same name as the branch, afaik, tags have precedence over branches (reference: `<refname>` section of `git help  revisions`)
since `forge install` uses `git checkout <ref>`, the installed package will checkout to the tag and not the branch (which is the expected outcome)

**Comment by onbjerg** [comment] 2022-06-05 09:31
The failure is because you have not committed the changes yet - the error says:

>There are changes in your working/staging area. Commit them first or add the `--no-commit` option.

So this is the expected behavior - let me know if that makes sense.

**Comment by sambacha** [comment] 2022-06-10 05:34
This is in a clean repo but i will double check

**Comment by onbjerg** [comment] 2022-07-03 12:50
Ping @sambacha here as well :slightly_smiling_face:

**Comment by sambacha** [comment] 2022-07-03 17:29
I believe you were in fact correct ya, can close this.

**Closed** 2022-07-03 17:29 UTC
Labels: T-bug, C-forge, Cmd-forge-pm
