### ISSUE TITLE
`forge coverage` does not work for if statements within for loops

### ISSUE THREAD

**Issue by KittyFu307** [foundry-rs/foundry#3600] opened 2022-11-03 07:23 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (70f4fb5 2022-11-03T00:06:25.653195Z)

### What command(s) is the bug in?

forge coverage

### Operating System

macOS (Apple Silicon)

### Describe the bug

When I run `forge coverage` to test the coverage for my code, I found that I have written the code to match the all branches but the result seems not. If I call the external function, it will not cover this branch.
<img width="1400" alt="截屏2022-11-03 下午5 00 14" src="https://user-images.githubusercontent.com/61280608/199681927-e6b79bef-0f44-434c-96a9-7fb2993f783d.png">

The coverage result is 
<img width="1481" alt="截屏2022-11-03 下午5 03 07" src="https://user-images.githubusercontent.com/61280608/199682048-a97f6741-9e30-4e9e-a0cf-4ddfeb0ca289.png">

But I think my test function have covered all situations, and the result is not

**Comment by chrismin** [comment] 2022-12-06 19:58
I'm unfortunately seeing the same issue. It seems to be related to coverage of "if" statements. Is there any update on this bug?

**Comment by KittyFu307** [comment] 2022-12-08 02:33
> I'm unfortunately seeing the same issue. It seems to be related to coverage of "if" statements. Is there any update on this bug?

unfortunately not, maybe you can @their-developers in this issue to see if there any updates

**Comment by KittyFu307** [comment] 2023-02-08 02:53
Hi @rkrasiuk any update for this issue? Thank you for your time

**Comment by PaulRBerg** [comment] 2023-02-08 08:48
@KittyFu307 it may be useful to rename the title of this issue to include a reference to for loops so that other users who bump into the same problem can reach us here.

**Comment by KittyFu307** [comment] 2023-02-08 09:22
> @KittyFu307 it may be useful to rename the title of this issue to include a reference to for loops so that other users who bump into the same problem can reach us here.

Sure~ have already done

**Comment by PaulRBerg** [comment] 2023-02-08 15:59
Actually, as per the code you shared above @KittyFu307, and per @chrismin's comment, this issue may be about if statements more broadly, not just some cases within for loops.

I've recently bumped into another nasty bug in the coverage command, which may be related (though this is based on a gut feeling):

https://github.com/foundry-rs/foundry/issues/4309

**Comment by PaulRBerg** [comment] 2023-02-08 16:00
I can't quite manage to pin down what this bug is about, exactly.

**Comment by PaulRBerg** [comment] 2023-02-08 16:49
**Update**: I have managed to get to the bottom of this, opened an issue here:

https://github.com/foundry-rs/foundry/issues/4310

@KittyFu307 this is definitely the same issue you encountered in  your `loopChoose` function, though the issue you had in `branchChoose` may be something completely unrelated.

**Comment by PaulRBerg** [comment] 2023-02-08 20:57
I think that I have figured it out - @KittyFu307, your original issue was actually reporting on two bugs in Foundry. One I documented myself in #4310; the other has been documented and discussed in #3497.

If someone else could confirm my guess, then I suggest we close this issue in favor of #4310 and #3497, which are more targeted.

**Comment by KittyFu307** [comment] 2023-02-09 07:06
> I think that I have figured it out - @KittyFu307, your original issue was actually reporting on two bugs in Foundry. One I documented myself in #4310; the other has been documented and discussed in #3497.
> 
> If someone else could confirm my guess, then I suggest we close this issue in favor of #4310 and #3497, which are more targeted.

Oh @PaulRBerg Thank you for taking the time to debug this error. I am pretty sure that the problem of the `loopChoose` function is the same as that of #4310. This has troubled me for a long time. I hope foundry team can solve it.

**Comment by PaulRBerg** [comment] 2023-02-09 07:39
No worries, @KittyFu307. Pinging @onbjerg in case he could take a quick look? Seems like an easy fix.

**Comment by onbjerg** [comment] 2023-02-09 08:43
I am completely out of the loop on Foundry so I do not have the context necessary to figure out if this is an easy fix or not. My best guess is that the common denominator for all of these complexly linked issues is that we detect branches by detecting sequences of bytecode, and it is possible that detection is not strict enough for overlapping cases.

For the other isssues (array access, calls) there are hidden reverts, so essentially all of the issues boil down to this one

**Comment by PaulRBerg** [comment] 2023-02-09 09:59
Thank you for taking the time to respond, @onbjerg.

> For the other isssues (array access, calls) there are hidden reverts

There are cases when there are clearly no hidden reverts, e.g. the one I documented in #4310:

```solidity
function isOdd(uint256 number) external view returns (bool odd) {
    uint256[] memory arr = new uint256[](1);
    arr[0] = block.timestamp;

    if (number % 2 == 1) {
        odd = true;
        arr[0];
    } else {
        odd = false;
    }
}
```

The `arr` array is initialized with a size of 1, so `arr[0]` cannot revert in this function.

Regarding calls - it may be the case that a hidden revert is what generates partial coverage for certain calls. However, as I suggested [here](https://github.com/foundry-rs/foundry/issues/3497#issuecomment-1423220193), there should definitely be a way to opt-out of the default revert-covering requirements with a comment (e.g. `// forgecov: ignore-next-line-revert`).

**Comment by mds1** [comment] 2023-02-09 13:52
That `isOdd` function is not payable, so there is a revert in the case where `msg.value > 0`. One tip is using `forge inspect MyContract ir-optimized` and checking out what solidity generates to see what it's doing under the hood (you may already know this)

**Comment by PaulRBerg** [comment] 2023-02-09 14:53
Interesting point, @mds1, but unfortunately, no, this wasn't the issue. After adding the `payable` modifier, the 50% branch coverage stayed put:

```text
| File        | % Lines       | % Statements  | % Branches   | % Funcs       |
|-------------|---------------|---------------|--------------|---------------|
| src/Foo.sol | 100.00% (5/5) | 100.00% (6/6) | 50.00% (1/2) | 100.00% (1/1) |
| Total       | 100.00% (5/5) | 100.00% (6/6) | 50.00% (1/2) | 100.00% (1/1) |
```

However, if Forge did actually report partial coverage for non-payable functions, that would be a bad user experience IMO.

1. This is not something obvious, not at all.
2. Developers are interested in testing the business logic of their protocol - not that a standard compiler feature works.

**Comment by deboguer-jng** [comment] 2023-05-10 13:39
I've same issues on our project. @PaulRBerg any update on this issue?

**Comment by PaulRBerg** [comment] 2023-05-10 15:21
No, @deboguer-jng. Also, I have never been involved in the development of the `forge coverage` command - I am just a user like you.

**Comment by grandizzy** [comment] 2024-07-14 21:11
confirmed fixed with https://github.com/foundry-rs/foundry/pull/8414 please reopen if you hit any similar issue

**Closed by grandizzy** 2024-07-14 21:11 UTC
Labels: T-bug, C-forge, Cmd-forge-coverage, T-to-reproduce
