### ISSUE TITLE
Failed to parse chain: 420

### ISSUE THREAD

**Issue by lokyse** [foundry-rs/foundry#5699] opened 2023-08-22 17:36 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0

### What command(s) is the bug in?

forge verify-contract  --chain-id 420  --compiler-version 0.8.16+commit.07a7930e  --watch

### Operating System

macOS (Intel)

### Describe the bug

Error: 
Failed to parse chain: 420

**Comment by Evalir** [comment] 2023-08-22 18:11
@lokyse what chain is this? Doesn't appear on chainlist.org nor is on ethers-rs.

**Comment by lokyse** [comment] 2023-08-23 02:54
> @lokyse what chain is this? Doesn't appear on chainlist.org nor is on ethers-rs.

It's chain Id number of Optimism

**Comment by mds1** [comment] 2023-08-23 15:34
> Doesn't appear on chainlist.org

It does if you check "include testnets", it's Optimism Goerli: https://community.optimism.io/docs/useful-tools/networks/#parameters-for-node-operators

**Comment by Evalir** [comment] 2023-08-23 18:38
@lokyse how old is your forge version? try using `foundryup`? This is working well for me.

**Comment by lokyse** [comment] 2023-08-24 00:50
> @lokyse how old is your forge version? try using `foundryup`? This is working well for me.

 It works by using latest forge version

**Comment by Evalir** [comment] 2023-08-24 00:51
Awesome, closing then unless this is caused by a different issue!

**Closed by Evalir** 2023-08-24 00:51 UTC
Labels: T-bug
