### ISSUE TITLE
cast call failing with panic when attempting to debug

### ISSUE THREAD

**Issue by coffeexcoin** [foundry-rs/foundry#6541] opened 2023-12-07 20:56 UTC
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (54b3695 2023-12-07T00:29:49.682799000Z)

### What command(s) is the bug in?

cast call

### Operating System

macOS (Apple Silicon)

### Describe the bug

I was attempting to simulate some transactions via `cast call` to demonstrate the debugging functionality and the application is crashing with "Message:  there should be a contract with bytecode":

```
cast call 0x4d224452801ACEd8B2F0aebE155379bb5D594381 \
`cast calldata "transfer(address,uint256)" "0xF977814e90dA44bFA03b6295A0616a897441aceC" "1"` \
-f 0x5954aB967Bc958940b7EB73ee84797Dc8a2AFbb9 \
--rpc-url $HOME_NODE_URL \
--trace \
--debug \
--etherscan-api-key $ETHERSCAN_KEY

Compiling: SimpleToken 0x4d224452801ACEd8B2F0aebE155379bb5D594381
The application panicked (crashed).
Message:  there should be a contract with bytecode
Location: /Users/runner/work/foundry/foundry/crates/common/src/compile.rs:456

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
[1]    15483 abort      cast call 0x4d224452801ACEd8B2F0aebE155379bb5D594381  -f  --rpc-url  --trace
```

**Comment by mattsse** [comment] 2023-12-08 12:29
thanks!

this is indeed a bug caused by how we prepare the sources retrieved from etherscan
will be fixed by https://github.com/foundry-rs/block-explorers/pull/19

**Closed** 2023-12-08 13:43 UTC
Labels: T-bug
