### ISSUE TITLE
feat(forge): `vm.startChisel` - start chisel at current test location

### ISSUE THREAD

**Issue by 0xPhaze** [foundry-rs/foundry#4281] opened 2023-02-06 08:01 UTC
### Component

Forge

### Describe the feature you would like

It would be great for debugging purposes if an existing test could be used to create a chisel-environment to play around with. I know it might be a bit ugly in terms of not be so well-defined when multiple tests are being run and potentially multiple calls to `vm.startChisel` are being made, but I think this would make a great additional feature for debugging. It could also only be activated if a single test match is found.

**Comment by mds1** [comment] 2023-02-06 16:29
Duplicate of https://github.com/foundry-rs/foundry/issues/4171

**Closed** 2023-02-06 17:10 UTC
Labels: T-feature
