### ISSUE TITLE
Flashloan test wrong: all runs well, but EVM revert in the end

### ISSUE THREAD

**Issue by chen4903** [foundry-rs/foundry#5763] opened 2023-08-31 16:13 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (56adbe4 2023-07-16T07:03:29.896803000Z)

### What command(s) is the bug in?

forge test --match-path test/09.NewFreeDAO/a.sol -vvv --offline

### Operating System

Windows

### Describe the bug

I try a simple flashloan. All runs well, the flashloan() and DVMFlashLoanCall() return true, but the result is an EVM revert. I never meet this situation before, I think maybe there is somthing I doesn't notice...

This is the code.

    // SPDX-License-Identifier: UNLICENSED
    pragma solidity ^0.8.10;

    import "forge-std/Test.sol";

    contract Attacker is Test {
        address constant wbnb = 0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c;
        address constant dodo = 0xD534fAE679f7F02364D177E9D44F1D15963c0Dd7;

        function setUp() public {
            vm.createSelectFork("bsc", 21_140_434);
        }

        function test_flashloan() public {
            bytes memory data = abi.encode(dodo, wbnb, 250 * 1e18);
            IDVM(dodo).flashLoan(0, 250 * 1e18, address(this), data);
        }

        function DVMFlashLoanCall(address sender, uint256 baseAmount, uint256 quoteAmount, bytes calldata data) external {
            IERC20(wbnb).transfer(msg.sender, 250 * 1e18);
        }
    }
    interface IDVM{
      function flashLoan(uint256,uint256,address,bytes memory) external returns(bool);
    }
    interface IERC20 {
      function transfer(address to, uint256 value) external returns (bool);
    }

I run this command: forge test --match-path test/09.NewFreeDAO/a.sol -vvv --offline. And the output is that: 

> Running 1 test for test/09.NewFreeDAO/a.sol:Attacker
[FAIL. Reason: EvmError: Revert] test_flashloan() (gas: 69569)
Traces:
  [55656] Attacker::test_flashloan()
    ├─ [52674] 0xD534fAE679f7F02364D177E9D44F1D15963c0Dd7::d0a494e4(000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000d8d726b7177a800000000000000000000000000007fa9385be102ac3eac297483dd6233d62b3e149600000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000060000000000000000000000000d534fae679f7f02364d177e9d44f1d15963c0dd7000000000000000000000000bb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c00000000000000000000000000000000000000000000000d8d726b7177a80000)
    │   ├─ [50505] 0x409E377A7AfFB1FD3369cfc24880aD58895D1dD9::d0a494e4(000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000d8d726b7177a800000000000000000000000000007fa9385be102ac3eac297483dd6233d62b3e149600000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000060000000000000000000000000d534fae679f7f02364d177e9d44f1d15963c0dd7000000000000000000000000bb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c00000000000000000000000000000000000000000000000d8d726b7177a80000) [delegatecall]
    │   │   ├─ [29962] 0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c::a9059cbb(0000000000000000000000007fa9385be102ac3eac297483dd6233d62b3e149600000000000000000000000000000000000000000000000d8d726b7177a80000)
    │   │   │   ├─ emit Transfer(from: 0xD534fAE679f7F02364D177E9D44F1D15963c0Dd7, to: Attacker: [0x7FA9385bE102ac3EAc297483Dd6233D62b3e1496], value: 250000000000000000000 [2.5e20])
    │   │   │   └─ ← 0x0000000000000000000000000000000000000000000000000000000000000001
    │   │   ├─ [3398] Attacker::DVMFlashLoanCall(Attacker: [0x7FA9385bE102ac3EAc297483Dd6233D62b3e1496], 0, 250000000000000000000 [2.5e20], 0x000000000000000000000000d534fae679f7f02364d177e9d44f1d15963c0dd7000000000000000000000000bb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c00000000000000000000000000000000000000000000000d8d726b7177a80000)
    │   │   │   ├─ [2610] 0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c::a9059cbb(000000000000000000000000d534fae679f7f02364d177e9d44f1d15963c0dd700000000000000000000000000000000000000000000000d8d726b7177a80000)
    │   │   │   │   ├─ emit Transfer(from: Attacker: [0x7FA9385bE102ac3EAc297483Dd6233D62b3e1496], to: 0xD534fAE679f7F02364D177E9D44F1D15963c0Dd7, value: 250000000000000000000 [2.5e20])
    │   │   │   │   └─ ← 0x0000000000000000000000000000000000000000000000000000000000000001
    │   │   │   └─ ← ()
    │   │   ├─ [2487] 0x67ee3Cb086F8a16f34beE3ca72FAD36F7Db929e2::70a08231(000000000000000000000000d534fae679f7f02364d177e9d44f1d15963c0dd7) [staticcall]
    │   │   │   └─ ← 0x000000000000000000000000000000000000000000008acc9a6bb5189c407f6f
    │   │   ├─ [534] 0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c::70a08231(000000000000000000000000d534fae679f7f02364d177e9d44f1d15963c0dd7) [staticcall]
    │   │   │   └─ ← 0x00000000000000000000000000000000000000000000000f6f6d2fb1d1c839e3
    │   │   ├─ [487] 0x67ee3Cb086F8a16f34beE3ca72FAD36F7Db929e2::70a08231(000000000000000000000000d534fae679f7f02364d177e9d44f1d15963c0dd7) [staticcall]
    │   │   │   └─ ← 0x000000000000000000000000000000000000000000008acc9a6bb5189c407f6f
    │   │   ├─ [534] 0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c::70a08231(000000000000000000000000d534fae679f7f02364d177e9d44f1d15963c0dd7) [staticcall]
    │   │   │   └─ ← 0x00000000000000000000000000000000000000000000000f6f6d2fb1d1c839e3
    │   │   ├─  emit topic 0: 0x0b82e93068db15abd9fbb2682c65462ea8a0a10582dce93a5664818e296f54eb
    │   │   │           data: 0x0000000000000000000000007fa9385be102ac3eac297483dd6233d62b3e14960000000000000000000000007fa9385be102ac3eac297483dd6233d62b3e1496000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000d8d726b7177a80000
    │   │   └─ ← ()
    │   └─ ← ()
    └─ ← "EvmError: Revert"
Test result: FAILED. 0 passed; 1 failed; 0 skipped; finished in 1.10s
Ran 1 test suites: 0 tests passed, 1 failed, 0 skipped (1 total tests)
Failing tests:
Encountered 1 failing test in test/09.NewFreeDAO/a.sol:Attacker
[FAIL. Reason: EvmError: Revert] test_flashloan() (gas: 69569)
Encountered a total of 1 failing tests, 0 tests succeeded

**Comment by Evalir** [comment] 2023-09-01 00:00
This is probably because the token you're using might not handle transfers like you might be using it—I'd try slimming down the code and seeing where the issue is, but this does not look like a foundry issue and bnb can be pretty iffy with tokens.

I'd say let's take this to foundry support—will close this unless we gather more evidence that this is a foundry issue.

**Closed by Evalir** 2023-09-01 00:00 UTC
Labels: T-bug
