### ISSUE TITLE
Cannot pass in Libraries

### ISSUE THREAD

**Issue by mostarz93** [foundry-rs/foundry#3012] opened 2022-08-30 02:12 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### Describe the bug

Trying to pass in pre deployed libraries but am getting an error saying invalid input string, expected map

**Comment by mattsse** [comment] 2022-08-30 15:48
could you please elaborate on that

what command are you running?

**Comment by mostarz93** [comment] 2022-08-30 15:50
> could you please elaborate on that
> 
> what command are you running?

forge create contracts/utils/SpigotLib.sol:SpigotLib --rpc-url $GORLI_ETH_RPC  --private-key $GORLI_ETH_PRIVATE_KEY --libraries contracts/utils/LineLib.sol:LineLib:0x610858ec92822FCC78d0EF51e3434E5F4968ae66  --verify  --etherscan-api-key $GORLII_ETHERSCAN_API_KEY

**Comment by naszam** [comment] 2022-08-30 16:23
Hi @mattsse,

We're getting a similar issue that might be related when rpc testing via forge with linked library.

```
➜  spells-goerli git:(PE-1045) ✗ make test-forge
./scripts/test-dssspell-forge.sh match="" block=""
Using DssExecLib at: 0x122F6c0Dcd898b4a07310E92c3eAE5D7Ce0c8bb6
[⠊] Compiling...
[⠑] Compiling 76 files with 0.6.12
Error: 
invalid type: string "0x122f6c0dcd898b4a07310e92c3eae5d7ce0c8bb6", expected a map at line 1 column 355
make: *** [Makefile:7: test-forge] Error 1
```
Steps to reproduce:

- Clone: https://github.com/makerdao/spells-goerli
- Switch to branch https://github.com/makerdao/spells-goerli/pull/102
- `dapp update`
- set goerli rpc via `export ETH_RPC_URL`
- `make test-forge`

Any idea?

Thanks!

**Comment by mattsse** [comment] 2022-08-30 16:43
this looks like an issue with how the lib address input affects the compiler output on 0.6.12

and I think the current compiler output fails to parse this, checking rn

**Comment by mattsse** [comment] 2022-08-30 17:02
@naszam fixed here https://github.com/gakonst/ethers-rs/pull/1648 will bump once merged

sorry about that -.-

**Closed** 2022-08-30 17:36 UTC
Labels: T-bug, C-forge
