### ISSUE TITLE
`anvil_reset` does not work without forking

### ISSUE THREAD

**Issue by MOZGIII** [foundry-rs/foundry#6018] opened 2023-10-10 10:04 UTC
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e0722a1 2023-10-10T00:28:23.851012000Z)

### What command(s) is the bug in?

anvil

### Operating System

macOS (Apple Silicon)

### Describe the bug

This is a regression, fixed previously at #2351.

The code in question is this:

https://github.com/foundry-rs/foundry/blob/e0722a10b45859892ec3b998df958a9edc77c202/crates/anvil/src/eth/api.rs#L1520-L1532

This `Err(BlockchainError::RpcUnimplemented)` branch is what is getting executed, and, obviously, this does not work as expected.

It breaks when the forking is not enabled, but it is perfectly valid to reset the node state, for instance in the `beforeEach` hook of the RPC E2E tests.

How it is supposed to work:

1. Node receives `{ "jsonrpc": "2.0", "method": "anvil_reset", "params": [] }`
2. Node resets the internal state to genesis
3. Node responds with success

**Comment by MOZGIII** [comment] 2023-10-11 23:32
Actually, blame shows this was never implemented in the first place, so not a regression. I was confused because the issue that would be implementing this is closed as done.

**Comment by Evalir** [comment] 2023-12-14 15:22
Closing, works as intended

**Closed by Evalir** 2023-12-14 15:22 UTC
Labels: T-bug

**Comment by MOZGIII** [comment] 2023-12-14 16:06
> as intended

Which is? Please elaborate

**Comment by germankuber** [comment] 2023-12-22 03:47
Is it feasible to reposition the operational blockchain fork to a designated block?
