### ISSUE TITLE
Broken build/remappings with nested dependencies

### ISSUE THREAD

**Issue by cxkoda** [foundry-rs/foundry#2693] opened 2022-08-10 13:15 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (63ed109 2022-08-09T00:03:50.892098571Z)

### What command(s) is the bug in?

forge build

### Operating System

Linux

### Describe the bug

Builds break if a project and it's dependency both depend on a third project but at different major version (with breaking changes).
For example having a structure like
```
Consumer2
|- lib
  |- Dependency @ v2.0
  |- Consumer1
    |- lib
      |- Dependency @ v1.0
  ```
see also https://github.com/cxkoda/forge-example-consumer2
 
Compiling the example fails with 
```
Compiler run failed
error[9582]: TypeError: Member "MY_CONST" not found or not visible after argument-dependent lookup in contract Dependency.
 --> lib/forge-example-consumer1/src/Consumer1.sol:9:9:
  |
9 |         dep.MY_CONST();
  |         ^^^^^^^^^^^^
```
because `Dependency @ v2.0` no longer has this function.

I guess the behavior comes from forge not considering the remappings of dependencies, or overriding them with the parent config. Did I overlook a way to configure this? Or is this a bug / expected behavior?

**Comment by onbjerg** [comment] 2022-08-11 17:55
Duplicate of https://github.com/foundry-rs/foundry/issues/1855

**Closed by onbjerg** 2022-08-11 17:55 UTC
Labels: T-bug
