### ISSUE TITLE
Getting an issue while creating contract in Foundry

### ISSUE THREAD

**Issue by devansh3008** [foundry-rs/foundry#4802] opened 2023-04-22 10:23 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (8d0099b 2023-04-19T00:08:21.764755505Z)

### What command(s) is the bug in?

forge create

### Operating System

Linux

### Describe the bug

Foundry Error while compiling contract:
[⠆] Compiling...
No files changed, compilation skipped
Error:
(code: -32000, message: gas required exceeds allowance (0), data: None)

**Comment by hdahme** [comment] 2023-05-05 23:41
I'm also sadly getting this error now

**Comment by miohtama** [comment] 2023-05-22 19:07
I can confirm a duplicate. Trying to deploy a contract on Polygon.

Check that your account has MATIC, or native token for the gas fees.

Maybe this could be promoted to "confusing error message" bug.

**Comment by Evalir** [comment] 2023-06-24 20:57
Closing, duplicate of a recently closed issue.

**Closed by Evalir** 2023-06-24 20:57 UTC
Labels: T-bug, C-forge, Cmd-forge-create

**Comment by EdNoepel** [comment] 2023-08-03 03:49
> Closing, duplicate of a recently closed issue.

Could you link to the "recently closed issue"?

**Comment by Keref** [comment] 2023-11-08 04:58
Same "gas required exceeds allowance", cant deploy on Arbitrum despite having 20 times the gas estimates + successful run on anvil fork. After a year if the pb isnt identified maybe there should be an option to ignore the error and follow thru the broadcast?
