### ISSUE TITLE
when using cast send with --private-key, it keep looking to the ETH_KEYSTORE and asking the keystore password

### ISSUE THREAD

**Issue by henry-hz** [foundry-rs/foundry#2691] opened 2022-08-10 11:42 UTC
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (63ed109 2022-08-09T00:03:50.892098571Z)

### What command(s) is the bug in?

cast send --json private-key $PRIV_KEY $to $func

### Describe the bug

```
cast send --json private-key $PRIV_KEY $to $func
forge create --private-key $PRIV_KEY  $what
```
When running the commands above, the expected behaviour is to have it running straight and bypassing the "asking password" phase of the keystore, once the private key is an explicitly argument, but, even with the --private-key active, it looks for the ETH_KEYSTORE variable, and if it's present, it will activate the dialoge "Insert keystore password:" that is irrelevant for this command.

**Comment by iainnash** [comment] 2022-08-20 04:35
I can take a stab at this.

**Comment by iainnash** [comment] 2022-08-20 15:55
I tried to re-create this on `main`:
`./target/debug/cast send --json --private-key $PRIVATE_KEY $TARGET '$FUNCTION'`

with the `ETH_KEYSTORE` env set to a keystore file and it processed the txn with the private key and no prompts.

I ran `forge create --private-key $PRIVATE_KEY ./src/Counter.sol:Counter` and that works when `ETH_KEYSTORE` was set to a keystore.

The password for the keystore prompt would come up only when removing the `--private-key` arg, as expected.

This is with a slightly newer version:
`forge 0.2.0 (f817db3 2022-08-16T00:12:12.954668Z)`

@henry-hz can you try upgrading and try again? Perhaps other env variables are set that I've missed?

**Comment by henry-hz** [comment] 2022-08-21 13:17
@iainnash  you are right, using the last version it just sent the transaction, both [forge and cast] are now working, thank you!

**Comment by mattsse** [comment] 2022-09-06 15:38
closing as this appears to be fixed, please reopen if you're still facing this

**Comment by henry-hz** [comment] 2022-09-07 12:44
```
ETH_KEYSTORE=/home/henry/.ethereum/keystore
forge create --json --nonce $NONCE --keystore $ETH_KEYSTORE --password $PASS "$@"
```
still getting:

```
Deploying Mock
Error: 
IO: Is a directory (os error 21)
```
using forge 0.2.0 (fb78b6b 2022-09-07T00:03:44.688975211Z)

**Comment by mattsse** [comment] 2022-09-07 12:49
thx for flagging and the command, will debug and fix

**Comment by zerosnacks** [comment] 2024-08-02 11:24
Unable to reproduce the issue with:

```
forge create --json --private-key $PRIVATE_KEY Counter --rpc-url <ALCHEMY_URL>
```

or

```
forge create --json --keystore <KEYSTORE> Counter --rpc-url <ALCHEMY_URL>
```

Marking as `resolved`

**Closed by zerosnacks** 2024-08-02 11:24 UTC
Labels: T-bug, good first issue, C-cast, T-to-reproduce
