### ISSUE TITLE
bug(`anvil`): `anvil_reset`: RPCError Not implemented whilst using `--fork-url`

### ISSUE THREAD

**Issue by geekberryonekey** [foundry-rs/foundry#9156] opened 2024-10-22 10:25 UTC
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

anvil 0.2.0 (2044fae 2024-10-22T00:22:08.742229268Z)

### What command(s) is the bug in?

anvil

### Operating System

None

### Describe the bug

[anvil_reset](https://book.getfoundry.sh/reference/anvil/)

anvil_reset returned  RPCError Not implemented (using --fork-url)

**Comment by zerosnacks** [comment] 2024-10-22 10:32
Looks like it somehow falls through

```rust
        if let Some(forking) = forking {
            // if we're resetting the fork we need to reset the instance id
            self.reset_instance_id();
            self.backend.reset_fork(forking).await
        } else {
            Err(BlockchainError::RpcUnimplemented)
        }
```      

Would you mind listing the full command you started Anvil with?

**Comment by grandizzy** [comment] 2024-11-07 12:23
this is dupe of feature request https://github.com/foundry-rs/foundry/issues/7472 going to close it and track impl there. thanks!

**Closed by grandizzy** 2024-11-07 12:23 UTC
Labels: T-bug
