### ISSUE TITLE
Incorrect gas estimation in foundry EVM

### ISSUE THREAD

**Issue by spencer-xyz** [foundry-rs/foundry#6761] opened 2024-01-11 15:34 UTC
### Component

Other (please describe)

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### Operating System

macOS (Apple Silicon)

### Describe the bug

I am using foundry EVM to simulate transactions locally and I noticed that there seems to be a difference of 2000-3000 gas between the estimated gas used when running locally and the actual gas used. I created a minimal example to reproduce the issue which I have provided below. It simulates a simple transfer, which I also executed on chain (see [here](https://goerli.etherscan.io/tx/0x623674fe5575d86df79d4d33c7341ed5f033829a4ba54f861dcfa704317d79f7)). You can see that there is a difference of 2300 gas.

[gas-usage-test.zip](https://github.com/foundry-rs/foundry/files/13905227/gas-usage-test.zip)

**Comment by mattsse** [comment] 2024-01-11 15:45
hmm not sure,

though I noticed that you set an accesslist during simulation, does the tx on chain have an accesslist?

**Comment by spencer-xyz** [comment] 2024-01-11 15:46
I sent the tx with metamask so if I had to guess, no access list

**Comment by spencer-xyz** [comment] 2024-01-11 15:55
I commented out the part where I set the access list and tried the experiment twice more. Seems like it has resolved the issue.

**Comment by Evalir** [comment] 2024-01-11 16:15
Alright! Seems the issue is fixed, so closing.

**Closed by Evalir** 2024-01-11 16:15 UTC
Labels: T-bug
