### ISSUE TITLE
Bad Checksum solc 0.8.15

### ISSUE THREAD

**Issue by varunsrin** [foundry-rs/foundry#2003] opened 2022-06-16 22:34 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (2457e5f 2022-06-16T00:04:27.032663Z)

### What command(s) is the bug in?

forge build

### Operating System

macOS (Intel)

### Describe the bug

Same issue as #1648, I believe [svm-rs](https://github.com/roynalnaruto/svm-rs) is missing a checksum.

cc @roynalnaruto 

```
 forge build
[⠊] Compiling...
[⠃] installing solc version "0.8.15"The application panicked (crashed).
Message:  checksum not available: "0.8.15"
Location: /Users/runner/.cargo/git/checkouts/svm-rs-cd2fa967df1e48a1/70fe9d9/src/lib.rs:197

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
[1]    41261 abort      forge build
```

Workaround is to add `solc_version = "0.8.14"` to foundry.toml

**Comment by mattsse** [comment] 2022-06-16 22:43
will be fixed by https://github.com/gakonst/ethers-rs/pull/1387 and an ethers bump here

**Comment by onbjerg** [comment] 2022-06-18 22:36
Duplicate of https://github.com/foundry-rs/foundry/issues/1991

**Closed by onbjerg** 2022-06-18 22:36 UTC
Labels: T-bug
