### ISSUE TITLE
forge install error

### ISSUE THREAD

**Issue by lusiwei** [foundry-rs/foundry#2300] opened 2022-07-13 16:30 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (16b4ef6 2022-07-13T00:15:34.493056Z)

### What command(s) is the bug in?

forge install Openzeppelin/openzeppelin-contracts

### Operating System

macOS (Apple Silicon)

### Describe the bug

Installing openzeppelin-contracts in "/Users/ackoo/foundry_demo1/lib/openzeppelin-contracts" (url: Some("https://github.com/Openzeppelin/openzeppelin-contracts"), tag: None)
Error: 
There are changes in your working/staging area. Commit them first or add the `--no-commit` option.

**Comment by mattsse** [comment] 2022-07-13 18:21
install is only allowed if there are no changes in the staging area,

> There are changes in your working/staging area. Commit them first or add the --no-commit option.

this is expected behaviour.

does adding the `--no-commit` flag work?

**Comment by onbjerg** [comment] 2022-07-14 06:29
Yeah, closing this since this is the expected behavior and the workaround is provided (using `--no-commit`, or alternatively committing/stashing your changes). Will reopen if `--no-commit` doesn't work for you :)

**Closed by onbjerg** 2022-07-14 06:29 UTC
Labels: T-bug

**Comment by MwendwaM** [comment] 2023-10-27 07:04
> Yeah, closing this since this is the expected behavior and the workaround is provided (using `--no-commit`, or alternatively committing/stashing your changes). Will reopen if `--no-commit` doesn't work for you :)

Doesn't work for me on windows
