### ISSUE TITLE
Getting an error when running forge test

### ISSUE THREAD

**Issue by vhawk19** [foundry-rs/foundry#5292] opened 2023-07-04 14:46 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (43974b0 2023-05-09T00:17:51.920839000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

When running a test from a forkt, I am encountering this error from `forge` looks like an error from the storage. Is this conclusive of anything?:
```2023-07-04T14:38:13.493498Z ERROR sharedbackend: Failed to send/recv `basic` err=GetAccount(0xb64e280e9d1b5dbec4accedb2257a87b400db149,
(code: -32000, message: missing trie node c9d3e0f8bda4532a36686f260b763beac7a2b1686946ced6cbe300d9cb9d4221 (path ) <nil>, data: None)) address=0xb64e280e9d1b5dbec4accedb2257a87b400db149
2023-07-04T14:38:13.493759Z ERROR forge::runner: err=Eyre(
backend: failed while inspecting: Database(GetAccount(0xb64e280e9d1b5dbec4accedb2257a87b400db149,
(code: -32000, message: missing trie node c9d3e0f8bda4532a36686f260b763beac7a2b1686946ced6cbe300d9cb9d4221 (path ) <nil>, data: None))))
2023-07-04T14:38:13.826844Z ERROR sharedbackend: Failed to send/recv `storage` err=GetStorage(0x0180dee5df18ebf76642e50faaef426f7b2874f7, 24104238192154634397086764757107460916121686968778083312312813627901926985726,
(code: -32000, message: missing trie node c9d3e0f8bda4532a36686f260b763beac7a2b1686946ced6cbe300d9cb9d4221 (path ) <nil>, data: None)) address=0x0180dee5df18ebf76642e50faaef426f7b2874f7 index=0x354a83ed9988f79f6038d4c7a7dadbad8af32f4ad6df893e0e5807a1b1944ffe_U256
2023-07-04T14:38:13.827326Z ERROR forge::runner: err=Eyre(
backend: failed while inspecting: Database(GetStorage(0x0180dee5df18ebf76642e50faaef426f7b2874f7, 24104238192154634397086764757107460916121686968778083312312813627901926985726,
(code: -32000, message: missing trie node c9d3e0f8bda4532a36686f260b763beac7a2b1686946ced6cbe300d9cb9d4221 (path ) <nil>, data: None))))```

**Comment by klkvr** [comment] 2023-07-04 15:38
This error is coming from an rpc provider and caused by querying data too far in past. This may happen in case when you are querying non-archive node and your tests are running so long that the block at which you forked the chain has already been pruned after some time. One of possible solutions could be to change RPC-provider to infura or alchemy rpc, or some another archive data provider

**Comment by Evalir** [comment] 2023-07-04 15:48
Indeed, as @klkvr commented this is due to your RPC provider. If you're forking from old blocks, you'll need archive functionality—if not, it will fail as the node won't have the data needed.

Closing, as not related to foundry.

**Closed by Evalir** 2023-07-04 15:48 UTC
Labels: T-bug

**Comment by vhawk19** [comment] 2023-07-05 06:38
Thanks for pointing the same, that indeed resolved the issue. Is it possible to have an error message which points to the RPC failure?

**Comment by klkvr** [comment] 2023-07-05 09:58
If you see something like (code: -32000, message: "whatever"), it's usually an RPC response indicating some error
