### ISSUE TITLE
feat(`forge script`): display logs during the execution progress

### ISSUE THREAD

**Issue by Q1ngYing** [foundry-rs/foundry#8596] opened 2024-08-03 08:40 UTC
### Component

Forge

### Describe the feature you would like

When I use forge script, I will write some `console` in my script contract, but the current forge script will output the log information after execution. In the future version of foundry, can we add a new parameter like the recent forge test to print out the situation during the execution of forge script, instead of waiting until the entire script is executed and finally printing it out in the terminal? Because when I execute the script, I want to observe my call information in real time, so that I can make better modifications to my script.

**Comment by zerosnacks** [comment] 2024-10-10 11:59
Marking as duplicate of https://github.com/foundry-rs/foundry/issues/5352

**Closed by zerosnacks** 2024-10-10 11:59 UTC
Labels: T-feature, C-forge, Cmd-forge-script, T-to-investigate
