### ISSUE TITLE
bug(forge): coverage takes a very long time when invariant tests are included

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/foundry#4952] opened 2023-05-16 21:37 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (58a2729 2023-05-16T00:06:18.519004000Z)

### What command(s) is the bug in?

forge coverage --match-path "test/invariant/**/*.sol"

### Operating System

macOS (Apple Silicon)

### Describe the bug

The `forge coverage` command is unusable with invariant tests. Here's how long my invariant tests take to run normally:

https://app.warp.dev/block/FObNIsh7boJJYzRFqLwS1Y

And here's what happens when I run `forge coverage` (the command does not finish running even after 10 minutes):

https://app.warp.dev/block/iM1hbmlzW9hPCwbmnUgce2

My hunch is that `forge coverage` recompiles the contracts on every invariant run, and this is what causes the slow execution. However, I can't know for sure because there's no progress reported for invariants (ref https://github.com/foundry-rs/foundry/issues/3277).

I can put together a dedicated repo for reproducing the bug, but doing so should be pretty easy to do in any Foundry project with invariants.

**Update**: my most recent CI run (which used the same settings as I did locally in the permalink above) just finished, and it took 37 minutes to run the coverage command over a set of invariant tests that take ~28 seconds to run directly.

**Comment by PierrickGT** [comment] 2023-12-14 22:33
Any update regarding this issue?
I've noticed that the issue is not present on this older version: `nightly-e15e33a07c0920189fc336391f538c3dad53da73`
May be a good starting point to figure out which changes introduced longer test coverage time.

**Comment by grandizzy** [comment] 2024-05-22 09:02
@PaulRBerg @PierrickGT can you recheck and report back, I wasn't able to recreate the issue locally with latest build. thank you

**Comment by PaulRBerg** [comment] 2024-05-22 10:34
Tagging @smol-ninja and @andreivladbrg

**Comment by Aboudjem** [comment] 2024-05-23 13:22
Same issue here! All tests work, but once it starts testing the invariant, it gets blocked.

**Comment by grandizzy** [comment] 2024-05-23 13:24
> Same issue here! All tests work, but once it starts testing the invariant, it gets blocked.

@Aboudjem Mind to share a test to reproduce and debug locally?  Make sure you're using latest build and try running with trace to see where it hangs.

**Comment by Aboudjem** [comment] 2024-05-23 13:52
Thanks @grandizzy for your quick reply.

As I mentioned, I am experiencing the same issue with invariant test (coverage or not). All tests run correctly, but the process gets blocked once it starts testing the invariants

#### Details:
- **Command Used:**
  ```sh
  forge test -vvvvv --mt invariant_Deposits
  ```
- **Version:**
  `forge 0.2.0 (3e9385b 2024-05-23T00:21:21.770618000Z)`
  - Also tested with the latest nightly build, but the issue persists.

#### Trace Information:
The trace provides no information as the tests do not even start.

#### Repository:
You can find the branch where the problem occurs here:
[feat/clean-refactor](https://github.com/bcnmy/nexus/tree/feat/clean-refactor)

#### CI Logs:
- [CI Run 1](https://github.com/bcnmy/nexus/actions/runs/9206584244/job/25324757547)
- [CI Run 2](https://github.com/bcnmy/nexus/actions/runs/9206584244/job/25324758004)

Feel free to check out the linked repository and CI logs for more details.

**Comment by grandizzy** [comment] 2024-05-23 15:52
@Aboudjem I checked and it looks like you have an infinite loop in code, I run `forge test --mc ExecutorInvariantTest` and it hanged looping and executing the same sequence of opcodes, I encourage you to review the loops within invariant tests. Also it's not too clear from the code what's the target contract of this invariant test, I will have a closer look, but don't think that's the same problem as reported in this issue. Feel free to open a new one if you don't figure out what's wrong. thank you!

**Comment by smol-ninja** [comment] 2024-05-23 16:04
Hi @grandizzy, I am speaking on behalf of @PaulRBerg.

I just checked it with the most recent version of foundry and this issue no longer exists. We can close this issue.

**Comment by grandizzy** [comment] 2024-05-23 18:19
closing per above comment. thank you!

**Closed by grandizzy** 2024-05-23 18:19 UTC
Labels: T-bug
