### ISSUE TITLE
Compilation error is missing the contract (file)name

### ISSUE THREAD

**Issue by 0xalfalfa** [foundry-rs/foundry#1406] opened 2022-04-24 14:55 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (475bc10 2022-04-09T00:03:37.422299507+00:00)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

I decided to try the IR compilation path through the "via_ir" flag and I ran into a "stack too deep" error. Obviously, not foundrys fault, but it would help to see with which sol file/contract the problem happens.

```
$ forge test -vvvvv
[⠢] Compiling...
[⠃] Compiling 41 files with 0.8.13
[⠢] Solc finished in 19.70s
Error: 
   0: Compiler run failed
      YulException: Variable _2 is 1 too deep in the stack [ _2 expr_mpos_3 _6 _18 _1 _16 expr_component_mpos_1 _10 RET var_ins_mpos _4 _7 _3 _14 var_i expr_1 _29 ]
      No memoryguard was present. Consider using memory-safe assembly only and annotating it via 'assembly ("memory-safe") { ... }'.

      
   0: 

Location:
   cli/src/compile.rs:88

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

**Comment by onbjerg** [comment] 2022-04-24 15:29
Dupe of https://github.com/foundry-rs/foundry/issues/559

**Closed by onbjerg** 2022-04-24 15:29 UTC
Labels: T-bug
