### ISSUE TITLE
bug(`anvil`): mining mode does not respect interval for the first block

### ISSUE THREAD

**Issue by sosoxuc** [foundry-rs/foundry#8962] opened 2024-09-26 08:15 UTC
### Component

Anvil

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

Latest

### What command(s) is the bug in?

anvil_mine

### Operating System

macOS (Apple Silicon)

### Describe the bug

```
await getBlockData()
await (provider as JsonRpcApiProvider)._send({ id: 1 , jsonrpc: "2.0" , method: "anvil_mine" , params:["0x1", "0x15180"]});
await getBlockData()
await (provider as JsonRpcApiProvider)._send({ id: 1 , jsonrpc: "2.0" , method: "anvil_mine" , params:["0x1", "0x15180"]});
await getBlockData()
```
Result:
```
20830003: Thu Sep 26 2024 00:27:50
20830004: Thu Sep 26 2024 00:27:51
20830005: Fri Sep 27 2024 00:27:48
```

**Comment by grandizzy** [comment] 2024-09-26 09:37
@sosoxuc could you please detail what's expected behavior, I don't understand where the problem is: I see first 2 blocks mined at 1 sec interval and then a big jump of  ~ 1 day for the 3rd one. Please provide also steps to reproduce the issue as the anvil start command. thank you

**Comment by PatrickAlphaC** [comment] 2024-10-03 15:00
Looks like this goes a bit deeper. If you save a state and it ends on like block 8 for example, when you restart the node, it'll say the block number is 0, causing issues with making RPC calls.

```bash
anvil --dump-state state.json -b 10

# wait 20 seconds for 2 blocks to go, then kill it
```

Then, restart:

```
anvil --load-state state.json
```

And then call the latest block:

```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest", false],"id":1}' http://localhost:8545
```

And you'll see the starting number is `0x0`, which is incorrect.

**Comment by mattsse** [comment] 2024-10-03 15:05
@yash-atreya is is probably because we update the tracked block number incorrectly after reloading the state

**Comment by adraffy** [comment] 2024-10-27 01:35
It also seems true that `anvil_mine [0x1, sec]` uses sec = 1 regardless of whats provided

**Comment by grandizzy** [comment] 2024-10-30 14:59
@adraffy I cannot reproduce the `anvil_mine` issue, mining 2 blocks at 10 seconds interval by using
```curl
curl http://127.0.0.1:8545 -X POST -H "Content-Type: application/json"  --data '{"method":"anvil_mine","params":["0x2", "10"],"id":1,"jsonrpc":"2.0"}'
```

shows 2 blocks with block time at 10 seconds difference

```
    Block Number: 14
    Block Hash: 0x45b19dbb9b3b8b4d55a7189e7aabfa18883acaacf8d0e2c999e8de6bb574c0a4
    Block Time: "Wed, 30 Oct 2024 14:58:37 +0000"


    Block Number: 15
    Block Hash: 0xb49d7253fd47d7e1c678fda34aac7cb980b423f381fa2c079343dfcb3e55830f
    Block Time: "Wed, 30 Oct 2024 14:58:47 +0000"
```

@yash-atreya looks like the issue reported by @PatrickAlphaC is now solved, would it be OK to close this ticket?

**Comment by yash-atreya** [comment] 2024-10-30 15:02
Yeah this can be closed. 
Fixed by https://github.com/foundry-rs/foundry/pull/9021

**Comment by adraffy** [comment] 2024-10-31 19:23
> @adraffy I cannot reproduce the `anvil_mine` issue, mining 2 blocks at 10 seconds interval by using

wait, you supplied `"10"` for 10 sec? not `0xA`?

https://hardhat.org/hardhat-network/docs/reference#hardhat_mine

![image](https://github.com/user-attachments/assets/50441b94-7ae3-4f09-a314-e2b899ff9159)

nm&mdash;that wasn't the issue.

---

Okay, I see why my test was failing

* on block 1 of a fresh anvil, if I call `anvil_mine [0x1, 10]` it does nothing.
* on block 2+, it works as expected

In your example, you're on block 14.

**Comment by adraffy** [comment] 2024-10-31 19:44
```
2024-10-31T19:43:40.484808Z  INFO node::user: eth_blockNumber
2024-10-31T19:43:40.485543Z  INFO node::user:
2024-10-31T19:43:40.485573Z  INFO node::user:     Transaction: 0xbafd3e2039d7f748af71cb12e94e3f49bee2f2b8e812a06b061b2dca92458e66
2024-10-31T19:43:40.485581Z  INFO node::user:     Contract created: 0x3Ede3eCa2a72B3aeCC820E955B36f38437D01395
2024-10-31T19:43:40.485587Z  INFO node::user:     Gas used: 67072
2024-10-31T19:43:40.485594Z  INFO node::user:
2024-10-31T19:43:40.485606Z  INFO node::user:     Block Number: 1
2024-10-31T19:43:40.485614Z  INFO node::user:     Block Hash: 0xda83e6466c372bbf59cb457d8a120baed4bc946c1a451d5023928ecc2cf69b68
2024-10-31T19:43:40.485621Z  INFO node::user:     Block Time: "Thu, 31 Oct 2024 19:43:40 +0000"

2024-10-31T19:43:40.491941Z  INFO node::user: eth_getTransactionReceipt
2024-10-31T19:43:40.494189Z  INFO node::user: eth_blockNumber
2024-10-31T19:43:40.495624Z  INFO node::user: eth_getCode
2024-10-31T19:43:40.497756Z  INFO node::user: eth_getBlockByNumber
anvil_mine [ '0x01', '5' ]
2024-10-31T19:43:40.500065Z  INFO node::user: anvil_mine
2024-10-31T19:43:40.500178Z  INFO node::user:
2024-10-31T19:43:40.500184Z  INFO node::user:     Block Number: 2
2024-10-31T19:43:40.500190Z  INFO node::user:     Block Hash: 0x1b9d8e50e91710145f83794f2a42b9ed68ac5abf83022ec60047a8e96366bb9a
2024-10-31T19:43:40.500197Z  INFO node::user:     Block Time: "Thu, 31 Oct 2024 19:43:40 +0000"
```

```
Block Time: "Thu, 31 Oct 2024 19:43:40 +0000"
Block Time: "Thu, 31 Oct 2024 19:43:40 +0000"
```

**Comment by grandizzy** [comment] 2024-10-31 19:48
reopen per above comment, thanks @adraffy

**Closed** 2024-11-01 09:05 UTC
Labels: T-bug, C-anvil, T-to-reproduce
