### ISSUE TITLE
bug(`remappings`): unable to import Solidity file using auto-remappings, missing `src/` suffix

### ISSUE THREAD

**Issue by acuarica** [foundry-rs/foundry#9247] opened 2024-11-01 16:47 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (17e0981 2024-11-01T00:27:49.655450000Z)

### What command(s) is the bug in?

forge remappings, forge build

### Operating System

macOS (Apple Silicon)

### Describe the bug

When installing some dependencies, the auto-remappings (and `build` command) do not resolve the `import` path properly.

### Steps to reproduce

Create an empty Foundry project and install the [Surl](https://github.com/memester-xyz/surl) library

```sh
forge init foundry-example
cd foundry-example
forge install memester-xyz/surl
```
then

```console
$ forge remappings
ds-test/=lib/surl/lib/forge-std/lib/ds-test/src/
forge-std/=lib/forge-std/src/
solidity-stringutils/=lib/surl/lib/solidity-stringutils/
surl/=lib/surl/
```

The last remapping `surl/=lib/surl/` seems to be missing the `src/` suffix (according to how the library is configured).

If I add the following `import` into, for example, `test/Counter.t.sol`

```solidity
import {Surl} from "surl/Surl.sol";
```

I get an error when running `build` (which is consistent with the `remappings` mentioned above)

```console
$ forge build
[⠃] Compiling...2024-11-01T16:30:19.505013Z ERROR foundry_compilers_artifacts_solc::sources: error="/<path>/foundry-example/lib/surl/Surl.sol": No such file or directory (os error 2)
[⠊] Compiling...
Error: failed to resolve file: "/<path>/foundry-example/lib/surl/Surl.sol": No such file or directory (os error 2); check configured remappings
	--> /<path>/foundry-example/test/Counter.t.sol
	surl/Surl.sol
```

Using the `foundry.toml` provided by the template project

```toml
[profile.default]
src = "src"
out = "out"
libs = ["lib"]
```

### Workaround

By changing the `import` as shown below solves this problem

```solidity
import {Surl} from "surl/src/Surl.sol";
```

### Additional context

_However_, if I use a `..` in the `lib` path resolving to the same folder as above, both `forge remappings` (and `forge build`) commands work as expected

```toml
[profile.default]
src = "src"
out = "out"
libs = ["lib/../lib"]
```

```console
$ forge remappings
ds-test/=lib/surl/lib/forge-std/lib/ds-test/src/
forge-std/=lib/forge-std/src/
solidity-stringutils/=lib/surl/lib/solidity-stringutils/src/
surl/=lib/surl/src/
```

### Related issues

As mentioned in some of the issues below, this does not happen for every dependency (for example installing `solmate` works fine).

- https://github.com/foundry-rs/foundry/issues/4717
- https://github.com/foundry-rs/foundry/issues/3440
- https://github.com/foundry-rs/foundry/issues/6431#issuecomment-2210510486

**Comment by grandizzy** [comment] 2024-11-01 19:14
@acuarica I don't think there's anything wrong here, we're inheriting remappings of module, so the right way to do is to import as
```Solidity
import {Surl} from "surl/src/Surl.sol";
```
or add a remapping `surl/=lib/surl/src` in root project to be able to imports as
```
import {Surl} from "surl/Surl.sol";
```

Can you clarify why would you expect "surl/Surl.sol" import to work out of the box? thank you!

**Comment by acuarica** [comment] 2024-11-01 20:53
@grandizzy thanks for your reply. Sure.

The [Surl documentation](https://github.com/memester-xyz/surl?tab=readme-ov-file#usage) mentions how to import their contract and it's without the `src/` part. So I assumed the import `"surl/Surl.sol"` worked at some point.

Moreover, if we replace `Surl` by `solmate`  (for example) as a dependency, the `remappings` output is different. But there is no specific remapping configuration (why are they different?)

```console
$ forge init foundry-example-solmate && cd foundry-example-solmate
$ forge install transmissions11/solmate
$ forge remappings
ds-test/=lib/solmate/lib/ds-test/src/
forge-std/=lib/forge-std/src/
solmate/=lib/solmate/src
```

Finally, whether I set my project using `libs = ["lib"]`, or `libs = ["lib/../lib"]` should lead to the same `remappings`. Or at least I assumed that. Of course, provided both paths resolve to the same actual folder. But the former results in a `remapping` without the `src/` and the latter with `src/` suffix. I assume there is a problem here, because whatever the right answer should it be, the fact of having different results looks like a problem.

Hope it's a bit more clear now. Thanks for the support.

**Comment by grandizzy** [comment] 2024-11-01 21:03
yeah, but solmate doesn't have test nor scripts in root so you could only import from src. Surl has both so if remappings to src then there'll be no way to import and use something from test or script.

**Comment by grandizzy** [comment] 2024-11-04 09:25
checked the code and that's the intended behavior, if you want to make it solmate like and have remappings to `src` directly then remove `test` and `script` dirs from root lib project. pls reopen this if you still think it's an issue, thank you!

**Comment by acuarica** [comment] 2024-11-04 13:31
Thanks for taking a look at this and for clarifying what the intended behavior should be. However, the only thing that hints something is not working properly is the following

> ### Additional context
> However, if I use a `..` in the `lib` path resolving to the same folder as above, both `forge remappings` (and `forge build`) commands work as expected
> 
> ```toml
> [profile.default]
> src = "src"
> out = "out"
> libs = ["lib/../lib"]
> ```
> 
> ```console
> $ forge remappings
> ds-test/=lib/surl/lib/forge-std/lib/ds-test/src/
> forge-std/=lib/forge-std/src/
> solidity-stringutils/=lib/surl/lib/solidity-stringutils/src/
> surl/=lib/surl/src/
> ```

**Comment by grandizzy** [comment] 2024-11-04 15:45
ah, yes, aworth checking some more, reopening

**Comment by grandizzy** [comment] 2024-11-04 15:58
similar behavior to investigate https://github.com/StackOverflowExcept1on/frost-secp256k1-evm

**Comment by grandizzy** [comment] 2024-11-05 08:31
@acuarica ack this is an issue, similar with https://github.com/foundry-rs/foundry/issues/4717#issuecomment-1502288851 going to close this one as a dupe and track fix there. thank you!

**Closed by grandizzy** 2024-11-05 08:31 UTC
Labels: T-bug, T-to-investigate, A-remappings

**Comment by acuarica** [comment] 2024-11-05 14:53
That's great, thanks for confirming this.
