### ISSUE TITLE
`forge test` started to fail with `EvmError`

### ISSUE THREAD

**Issue by grandizzy** [foundry-rs/foundry#5190] opened 2023-06-21 08:26 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (794f831 2023-06-21T00:07:14.025384268Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

GH actions and local tests started to fail with `[FAIL. Reason: EvmError: Revert]` on the latest nightly build but works OK with `foundryup -v nightly-6d6f854679a7f16e157ff1f05491163ec9bd27d9` (`forge 0.2.0 (6d6f854 2023-06-19T00:07:11.657015827Z)`)
Suspect due to ethers update in https://github.com/foundry-rs/foundry/commit/977a194fcc91cc64217dfc2267a91d8cff1a248a

**Comment by davidbrai** [comment] 2023-06-21 08:56
I'm having the same issue. Example test failure can be seen here: https://github.com/nounsDAO/nouns-monorepo/actions/runs/5325622264/jobs/9646548630

**Comment by DaniPopes** [comment] 2023-06-21 09:23
Manually reverting #5164 (12ea9f61a344087989f884d2ab735893c77ea576) makes the tests pass. cc @onbjerg 😢

```sh
gcl git@github.com:nounsDAO/nouns-monorepo.git
```

**Comment by onbjerg** [comment] 2023-06-21 09:24
alright go ahead and revert

**Comment by cassette06** [comment] 2023-06-21 10:11
encountered the same situation. before foundryup, every test can pass. after foundryup test failed due to evm error

**Comment by storojs72** [comment] 2023-06-21 14:10
Confirming same issue. With newest foundry toolchain, some of tests started accidentally failing on actions, however locally they are passed. Failed [build](https://github.com/lurk-lab/solidity-verifier/actions/runs/5334964224/jobs/9667498832) example output: 
 
 ```
 Running 2 tests for test/nova-verifier-tests.t.sol:NovaVerifierContractTest
[PASS] testVerificationStep1() (gas: 24971)
[FAIL. Reason: EvmError: Revert] testVerificationStep2() (gas: 10747)
Logs:
  [testVerificationStep2] 1
  [getCompressedSnarkStep2Primary] 1

Traces:
  [10747] NovaVerifierContractTest::testVerificationStep2() 
    ├─ [0] console::log([testVerificationStep2] 1) [staticcall]
    │   └─ ← ()
    ├─ [4337] NovaVerifierStep2DataLib::getCompressedSnarkStep2Primary() [delegatecall]
    │   ├─ [0] console::log([getCompressedSnarkStep2Primary] 1) [staticcall]
    │   │   └─ ← ()
    │   ├─ [154] NovaVerifierStep1DataLib::loadCommitment(22736428987877128050193954830529271830158920103255622987789977417941046638334 [2.273e76], 3082432275501042532597777706266404404014741612820025958426178420668529681374 [3.082e75], 0) [delegatecall]
    │   │   └─ ← "EvmError: Revert"
    │   └─ ← "EvmError: Revert"
    └─ ← "EvmError: Revert"

Test result: FAILED. 1 passed; 1 failed; finished in 5.99ms
 ```
 
 Using previous `nightly-6d6f854679a7f16e157ff1f05491163ec9bd27d9` version of toolchain makes tests [working](https://github.com/lurk-lab/solidity-verifier/actions/runs/5335070800/jobs/9667770614).

**Comment by grandizzy** [comment] 2023-06-22 04:48
I confirm all works OK with `forge 0.2.0 (a81d36f 2023-06-22T00:07:17.454867523Z)` Thanks!

**Comment by Evalir** [comment] 2023-06-27 00:03
Hey all—we just merged a fix regarding this—should let us solve the linking bug without tests randomly reverting. We'd love if you tried the latest nightly again once it's released! (in around an hour)

**Comment by grandizzy** [comment] 2023-06-27 04:39
> Hey all—we just merged a fix regarding this—should let us solve the linking bug without tests randomly reverting. We'd love if you tried the latest nightly again once it's released! (in around an hour)

I confirmed tests works OK with `forge 0.2.0 (e918c81 2023-06-27T00:04:31.801932823Z)`

**Comment by Evalir** [comment] 2023-06-27 12:14
Alright—dapper also confirmed via another channel.

Will close this issue later once the workday is done, just in case we get similar reports here.

**Comment by Evalir** [comment] 2023-06-28 15:05
Closing! no related reports so far.

**Closed by Evalir** 2023-06-28 15:05 UTC
Labels: T-bug
