### ISSUE TITLE
expectEmit of an emit that emits an empty string fails

### ISSUE THREAD

**Issue by lucadonnoh** [foundry-rs/foundry#1027] opened 2022-03-23 17:27 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (22323e2 2022-03-23T00:09:43.397848305+00:00)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

This contract
```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.13;

contract HelloWorld {

    event Message(string message);

    string public message = "Hello world";
    string[] public messages = [message];

    function hello() public returns (string memory) {
        emit Message(message);
        return message;
    }

    function updateMessage(string calldata _message) public {
        message = _message;
        messages.push(_message);
    }
}
```
with this test
```solidity
...
function testUpdateMessage(string memory _message) public {
        //cheats.assume(keccak256(abi.encodePacked(_message)) != keccak256(abi.encodePacked("")));
        hw.updateMessage(_message);
        cheats.expectEmit(false, false, false, true);
        emit Message(_message);
        string memory message = hw.hello();
        assertEq(_message, message);
        
        assertEq(_message, hw.messages(1));
    }
...
```
fails when `_message` is `""`.

Trace:
```bash
  [357484] HelloWorldTest::setUp()
    ├─ → new HelloWorld@0xce71…c246
    │   └─ ← 1280 bytes of code
    └─ ← ()
  [12158] HelloWorldTest::testUpdateMessage("")
    ├─ [4784] HelloWorld::updateMessage("")
    │   └─ ← ()
    ├─ [0] VM::expectEmit(false, false, false, true)
    │   └─ ← ()
    ├─ emit Message(message: "")
    ├─ [2850] HelloWorld::hello()
    │   ├─ emit Message(message: "")
    │   └─ ← ""
    └─ ← "Log != expected log"
```

**Comment by onbjerg** [comment] 2022-03-23 21:37
Can you try the current build on `master`? You can do that now by running `foundryup -b master`, or alternatively getting the nightly built tonight

**Comment by lucadonnoh** [comment] 2022-03-23 22:07
tested with forge 0.2.0 (33f1df0 2022-03-23T21:58:00.302498045+00:00) and it still fails in the same way

**Comment by onbjerg** [comment] 2022-03-27 08:18
I've tried resolving this (will try again later), but for others willing to try and pick this up:

When we emit in the test, `data` of the log is:

```
00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000000
```

However, when wwe emit from the `HelloWorld` contract, `data` of the log is:

```
000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```

Interestingly, when using Solidity 0.7.0, this is not the case, and `data` of both logs match. This seems like an obscure Solidity regression?

**Comment by hrkrshnn** [comment] 2022-03-31 10:57
To give an update, this indeed seems to be a compiler bug. When encoding the value from storage, the ABI routine is using `64` bytes (length (0) + 32-byte value (0)). Whereas for memory it is using 32 bytes: length (0). Made https://github.com/ethereum/solidity/issues/12880 to track this.

**Comment by onbjerg** [comment] 2022-08-15 18:49
Closing this since it has been fixed in solc and there isn't anything to do on our end :smile: Thanks for the report again!

**Closed by onbjerg** 2022-08-15 18:49 UTC
Labels: T-bug, Cmd-forge-test, C-forge, A-cheatcodes
