### ISSUE TITLE
`forge coverage` is also generating reports on contracts inside node_modules

### ISSUE THREAD

**Issue by HrikB** [foundry-rs/foundry#2689] opened 2022-08-10 08:10 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (9b0575e 2022-08-04T00:04:01.463358166Z)

### What command(s) is the bug in?

forge coverage

### Operating System

Linux

### Describe the bug

`forge coverage` is also generating reports on contracts inside node_modules. Is there any way to exclude certain directories from being inside the coverage report?

![image](https://user-images.githubusercontent.com/23041116/183850050-61b4604d-ce2a-4531-88f5-8cc18ca37476.png)

**Comment by onbjerg** [comment] 2022-08-10 20:42
These should be excluded if `node_modules` is part of `libs` in `foundry.toml`. Please ensure that is the case, otherwise please provide a minimal reproducible example.

**Comment by HrikB** [comment] 2022-08-10 20:55
![image](https://user-images.githubusercontent.com/23041116/184018194-3cb208d3-dd3b-4f1e-93a8-df9ba8121bd4.png)
My node_modules is in a different directory as it is inside a monorepo. Perhaps using a route like this is causing the error?

**Comment by onbjerg** [comment] 2022-08-10 20:57
Can you try updating Forge as well? It is 6 days out of date

**Comment by HrikB** [comment] 2022-08-10 20:59
Done: forge 0.2.0 (49558db 2022-08-10T00:11:55.304734589Z)

The issue still persists though

**Comment by zerosnacks** [comment] 2024-08-01 14:31
Tentatively marking as `resolved` as I'm unable to reproduce it

Feel free to re-open with a minimal reproduction example / reproduction steps

**Closed by zerosnacks** 2024-08-01 14:31 UTC
Labels: T-bug, C-forge, Cmd-forge-coverage, T-to-reproduce
