### ISSUE TITLE
Coverage not catching functions that are called from another test. 

### ISSUE THREAD

**Issue by Genysys** [foundry-rs/foundry#2278] opened 2022-07-12 12:22 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (7bc3e60 2022-07-12T00:09:54.024092Z)

### What command(s) is the bug in?

forge coverage --report debug

### Operating System

macOS (Intel)

### Describe the bug

I have a function `mint` that calls `getAmountOutMin`. 

In my tests , I call mint , but when I run `forge coverage --report debug`, it shows it as uncoverred.

```
 Function "LandNFT.getAmountOutMin" (location: L264, C8787-9088, anchor: LandNFT:3242, hits: 0)
```

**Comment by onbjerg** [comment] 2022-07-14 06:44
Can you provide more context on your functions? Are they inherited? Are they static? Public/internal? How are they called?

**Comment by onbjerg** [comment] 2022-07-28 17:02
Ping - any chance you could give me a reproduction?

**Comment by onbjerg** [comment] 2022-08-04 16:11
Closing since I have not been able to reproduce. Let me know if this is still an issue for you.

**Closed by onbjerg** 2022-08-04 16:11 UTC
Labels: T-bug, C-forge, Cmd-forge-coverage
