### ISSUE TITLE
Bug: forge install creates lib directory even when error is reported due to dirty git workspace. 

### ISSUE THREAD

**Issue by sambacha** [foundry-rs/foundry#6599] opened 2023-12-14 05:32 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### Operating System

None

### Describe the bug

```console
$ forge install https://github.com/OpenZeppelin/openzeppelin-contracts
Installing openzeppelin-contracts in /Users/janitor/op/lib/openzeppelin-contracts (url: Some("https://github.com/OpenZeppelin/openzeppelin-contracts"), tag: None)
Error:
The target directory is a part of or on its own an already initialized git repository,
and it requires clean working and staging areas, including no untracked files.

Check the current git repository's status with `git status`.
Then, you can track files with `git add ...` and then commit them with `git commit`,
ignore them in the `.gitignore` file, or run this command again with the `--no-commit` flag.

If none of the previous steps worked, please open an issue at:
https://github.com/foundry-rs/foundry/issues/new/choose
21:29:40 Wed Dec 13 2023 janitor macbook /Users/janitor/op master
$ forge install https://github.com/OpenZeppelin/openzeppelin-contracts --no-commit
Installing openzeppelin-contracts in /Users/janitor/op/lib/openzeppelin-contracts (url: Some("https://github.com/OpenZeppelin/openzeppelin-contracts"), tag: None)
fatal: 'lib/openzeppelin-contracts' already exists and is not a valid git repo
Error:
git submodule exited with code 128
21:29:53 Wed Dec 13 2023 janitor macbook /Users/janitor/op master
```

**Comment by Shantaramm** [comment] 2023-12-17 14:08
I have the same error

**Comment by EasonWW** [comment] 2024-01-29 14:26
I also have the same error

**Comment by 0xVitalii** [comment] 2024-03-21 20:07
I have this error. How to fix it?

**Comment by abhi3700** [comment] 2024-03-25 13:32
Same error when installing OZ contracts:
```
forge install https://github.com/OpenZeppelin/openzeppelin-contracts/
```

**Comment by onbjerg** [comment] 2024-03-25 13:49
I can't reproduce this at all, how did you arrive at a state where `lib` is a git repository in itself? Creating a new project and running

```
forge install https://github.com/OpenZeppelin/openzeppelin-contracts
```

works as intended, it installs the dependency.

**Comment by onbjerg** [comment] 2024-03-25 13:52
Creating a new project, editing some file so the workspace is dirty and running

```
forge install https://github.com/OpenZeppelin/openzeppelin-contracts
```

Errors as intended. If I do

```
forge install https://github.com/OpenZeppelin/openzeppelin-contracts --no-commit
```

It does not error, and instead installs the dependency as expected. I cannot reproduce this.

**Comment by zerosnacks** [comment] 2024-07-05 13:21
I'm also unable to reproduce the error, reproduction yields the same results as stated by @onbjerg 

Tentatively closing this as `resolved`

Feel free to re-open or leave a comment if this is still an issue with a minimal reproduction or additional details

**Closed by zerosnacks** 2024-07-05 13:21 UTC
Labels: T-bug

**Comment by Mort3nd** [comment] 2025-05-30 04:54
I have the same problem , and it related to git . I try to clone a random project , but not work . as my solution the git configuration have some problem (TLS handshake error --> fix with changing git proxy setup) and after fix this , the `forge install  https://github.com/OpenZeppelin/openzeppelin-contracts` working
