### ISSUE TITLE
Feature Request: Convenient method to test internal functions and read internal variables

### ISSUE THREAD

**Issue by drop19** [foundry-rs/foundry#1705] opened 2022-05-23 12:51 UTC
### Component

Forge

### Describe the feature you would like

Writing unit tests for internal function function requires boilerplate codes. It is appreciated if there could be convenient methods for testing internal functions and reading internal variables

**Comment by gakonst** [comment] 2022-05-24 06:26
Can you describe your ideal UX? Your test contract can inherit the contract being tested, 

e.g.

```solidity
contract Foo {
       function foo() internal { ... }
}
contract FooTest is Test, Foo {
       function testFoo() {
            require(foo() == ..., "error");
       }
}
```

**Comment by onbjerg** [comment] 2022-05-27 16:48
It's possible to read private variables using `vm.load`: https://book.getfoundry.sh/cheatcodes/load.html

Otherwhise this is a duplicate of #1040

**Closed by onbjerg** 2022-05-27 16:48 UTC
Labels: T-feature

**Comment by pmespresso** [comment] 2022-09-21 04:56
> It's possible to read private variables using `vm.load`: https://book.getfoundry.sh/cheatcodes/load.html

@onbjerg If I'm not mistaken `stdstore` requires a function selector signature in order to read from storage however no getter function is generated for internal/private variables. I stumbled on this thread because I'm trying to do exactly this but getting `"stdStorage find(StdStorage): No storage use detected for target.` when reading private variables. Am I mistaken here?
