### ISSUE TITLE
Improving Speed in Simulations

### ISSUE THREAD

**Issue by JONEmoad** [foundry-rs/foundry#6292] opened 2023-11-12 04:31 UTC
### Component

evm

### Describe the feature you would like

I'd like to suggest an enhancement for evm sim, focusing on the eth_getStorageAt call functionality. Currently, the approach of individually sending requests for each storage slot can be quite inefficient, especially when dealing with numerous slots for a single address.

A potential improvement could be the implementation of batch or parallel request processing. By allowing multiple eth_getStorageAt requests to be sent in a single call or concurrently, the efficiency and processing time could be significantly improved. This feature would be particularly impactful in simulation environments, offering a substantial boost in performance and a noticeable difference in overall efficiency.

This enhancement could dramatically speed up simulations

**Comment by mds1** [comment] 2023-11-12 17:19
Closing as a duplicate of https://github.com/foundry-rs/foundry/issues/5363

However I do agree this would be a significant performance improvement for fork tests, so cc’ing @mattsse @Evalir for visibility

**Closed by mds1** 2023-11-12 17:19 UTC
Labels: T-feature

**Comment by BABA3344** [comment] 2024-05-24 02:46
In all this time, the issue has not been taken seriously. This is disappointing  @mattsse @Evalir @gakonst @DaniPopes @onbjerg @klkvr
