### ISSUE TITLE
Library Deploys Bug

### ISSUE THREAD

**Issue by CornersOfTheCity** [foundry-rs/foundry#6013] opened 2023-10-09 08:33 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (fcae63a 2023-10-08T00:31:37.838144000Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

Library Deploys Twice error still exists.

forge version :  forge 0.2.0 (fcae63a 2023-10-08T00:31:37.838144000Z)

source code:

```
// SPDX-License-Identifier: GPL-3.0
pragma solidity 0.8.14;

library Add{
    function addOne(uint256 num) public pure returns(uint256 outNum){
        outNum = num+1;
    }
} 
```
```
// SPDX-License-Identifier: GPL-3.0
pragma solidity 0.8.14;

library Reduce{
    function reduceOne(uint256 num) public pure returns(uint256 outNum){
        outNum = num-1;
    }
} 
```
```
pragma solidity 0.8.14;
import "./libraries/add.sol";
import "./libraries/reduce.sol";

contract EthereumTest{
    function test(uint256 input) public pure returns(uint256 output){
        uint256 result = Add.addOne(input);
        output = Reduce.reduceOne(result);
    } 
}
```
script:

```
pragma solidity ^0.8.0;

import "forge-std/Script.sol";
import "../src/ethereum/EthereumTest.sol";

contract DeployTest is Script {
    function run() external {
        uint256 deployerPrivateKey = vm.envUint("PRIVATE_KEY");
        vm.startBroadcast(deployerPrivateKey);

        new EthereumTest();

        vm.stopBroadcast();
    }
}

```

output:

```
###
Finding wallets for all the necessary addresses...
##
Sending transactions [0 - 2].
⠙ [00:00:00] [##########################################################################] 3/3 txes (0.0s)
Transactions saved to: /Users/zyq/Contract/Tusima/zkBridge-lightClient/contracts/broadcast/EthereumTest.s.sol/5/run-latest.json

Sensitive values saved to: /Users/zyq/Contract/Tusima/zkBridge-lightClient/contracts/cache/EthereumTest.s.sol/5/run-latest.json

##
Waiting for receipts.
⠚ [00:00:19] [######################################################################] 3/3 receipts (0.0s)
##### goerli
✅  [Success]Hash: 0x318a78911515c3e0a31fb243590bc95f9fb927b275c97294ee1c1a70fcbebe74
Contract Address: 0x22a54684a72A098c8bF475361255B185FCA37390
Block: 9835454
Paid: 0.00030402900202686 ETH (101343 gas * 3.00000002 gwei)


##### goerli
✅  [Success]Hash: 0x7e8e67bffd4c5b0877035baffc5c24d2750b38ac5b5e5b44b3a63fe326fccae3
Contract Address: 0x0755517A344160deC513193Dc75D21d25134eeB9
Block: 9835454
Paid: 0.00030338100202254 ETH (101127 gas * 3.00000002 gwei)


##### goerli
✅  [Success]Hash: 0x6f51b3f65caffdbed7f4a855d976a57784d71bc1bbac45879998ff770df76c20
Contract Address: 0x371180E01b412606A5749C70534614Eb9Ccb3347
Block: 9835454
Paid: 0.00044258700295058 ETH (147529 gas * 3.00000002 gwei)
```
three contract deployed, Two of them are library, details in goerli:

library Add:[0x318a78911515c3e0a31fb243590bc95f9fb927b275c97294ee1c1a70fcbebe74](https://goerli.etherscan.io/tx/0x318a78911515c3e0a31fb243590bc95f9fb927b275c97294ee1c1a70fcbebe74)

library Reduce: [0x7e8e67bffd4c5b0877035baffc5c24d2750b38ac5b5e5b44b3a63fe326fccae3](https://goerli.etherscan.io/tx/0x7e8e67bffd4c5b0877035baffc5c24d2750b38ac5b5e5b44b3a63fe326fccae3)

The only contract that should be deployed：[0x6f51b3f65caffdbed7f4a855d976a57784d71bc1bbac45879998ff770df76c20](https://goerli.etherscan.io/tx/0x6f51b3f65caffdbed7f4a855d976a57784d71bc1bbac45879998ff770df76c20)

**Comment by bernard-wagner** [comment] 2023-10-10 08:08
See the library functions are marked as `public` and not `internal`. Does it still deploy the libraries if they are marked as `internal`?

**Comment by bernard-wagner** [comment] 2023-10-19 07:55
It supports `public` types. The issue is that with `public` types is that even if all functions are inlined by the linker (same as with `internal`), `forge` still sees the `external` functions and assumes it needs to deploy the library (`public` means `internal` and `external`). 

This is further complicated by libraries first needing to get deployed before linking. Only way I can think of resolving this at the moment, would be to do a dry run on the linking stage and determine whether linking has any effect. If it has no effect, then we can assume the library is not needed. This is unnecessarily complex for something that can be avoided by just using `internal`.

**Closed** 2023-11-06 07:06 UTC
Labels: T-bug
