### ISSUE TITLE
Assembly error after `expectEmit`

### ISSUE THREAD

**Issue by Pythonberg1997** [foundry-rs/foundry#2949] opened 2022-08-26 05:59 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (56dc746 2022-08-26T00:05:24.870934Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

Assembly operation will fail if they are put after `expectEmit` while before `expectEmit` will succeed.

Failed example:
```
    ...
    vm.expectEmit(true, true, false, true, address(CONTRACT));
    emit myEvent(param1, parm2, parm3);
    CONTRACT.foo();

    // del is a address
    bytes memory b;
    assembly {
      let m := mload(0x40)
      mstore(add(m, 20), xor(0x140000000000000000000000000000000000000000, del))
      mstore(0x40, add(m, 52))
      b := m
    }
    emit log_bytes(b);
    ...
```
outout:
```
[FAIL. Reason: EvmError: OutOfGas] testAssembly() (gas: 9223372036854754743)
```

Success example
```
    ...
    // del is a address
    bytes memory b;
    assembly {
      let m := mload(0x40)
      mstore(add(m, 20), xor(0x140000000000000000000000000000000000000000, del))
      mstore(0x40, add(m, 52))
      b := m
    }
    emit log_bytes(b);

    vm.expectEmit(true, true, false, true, address(CONTRACT));
    emit myEvent(param1, parm2, parm3);
    CONTRACT.foo();
    ...
```

**Comment by Loverush** [comment] 2022-08-26 05:59
I'm using `solidity 0.6.4`

**Comment by onbjerg** [comment] 2022-08-26 06:06
Technically it is also before/after `CONTRACT.foo()` - can you please try removing `vm.expectEmit` alltogether without moving the assembly block, such that the code is roughly

```
CONTRACT.foo();
<assembly block>
```

`vm.expectEmit` does not modify the bytecode or anything about the EVM in particular, so it is unlikely to be the cause.

**Comment by Loverush** [comment] 2022-08-28 07:26
> Technically it is also before/after `CONTRACT.foo()` - can you please try removing `vm.expectEmit` alltogether without moving the assembly block, such that the code is roughly
> 
> ```
> CONTRACT.foo();
> <assembly block>
> ```
> 
> `vm.expectEmit` does not modify the bytecode or anything about the EVM in particular, so it is unlikely to be the cause.

No. I deleted `vm.expectEmit` and the test passed

**Comment by onbjerg** [comment] 2022-09-01 10:41
Can you provide a minimally runable example? I cannot reproduce this with other assembly blocks, so my guess is still that the assembly block/call is at fault

**Comment by Loverush** [comment] 2022-09-01 11:45
Hello @onbjerg. I tried to give you a minimally example. But I find when I change the test target contract, this error doesn't show up. I will do more test and reply to you later.

**Comment by Pythonberg1997** [comment] 2022-09-19 09:52
```
pragma solidity ^0.8.10;

import "forge-std/Test.sol";

contract AssemblyTest is Test {
  address public constant SOME_CONTRACT_ADDR = 0x0000000000000000000000000000000000002001;

  function setUp() public {}

  function testAssembly() public {
    address deployAddr = deployCode("MyContract.sol");
    vm.etch(SOME_CONTRACT_ADDR, deployAddr.code);

    address addr = address(this);
    bytes memory b;
    assembly {
      let m := mload(0x40)
      mstore(add(m, 20), xor(0x140000000000000000000000000000000000000000, addr))
      mstore(0x40, add(m, 52))
      b := m
    }
    emit log_bytes(b);
  }
}
```

@onbjerg I got the wrong case here

**Comment by Pythonberg1997** [comment] 2022-09-19 10:01
And my foundry version is `forge 0.2.0 (084ef3d 2022-09-19T00:04:35.98318Z)`

**Comment by onbjerg** [comment] 2022-09-19 16:45
Can you post a call trace/what the error is? That code snippet does not use `expectEmit`, so my best guess is that it's still something in the assembly block at fault, but it's not immediately clear what you are trying to do.

**Comment by Pythonberg1997** [comment] 2022-09-19 17:40
The error is:
```
[FAIL. Reason: EvmError: OutOfGas] testAssembly() (gas: 9223372036854754743)
```
Yes there's no `expectEmit`. I misunderstand what cause the error at first. 
I'm tying to do here is RLP encoding a address type variable.
Now I think the error is, (maybe) operate the address type in assembly will cause this error(not always, but above is a example).

**Comment by Pythonberg1997** [comment] 2022-09-21 04:00
@onbjerg any idea?><

**Comment by Pythonberg1997** [comment] 2022-09-21 08:35
Now I'm sure the problem lies in `vm.etch()`. After `vm.etch()`, the assembly code will fail.

**Comment by onbjerg** [comment] 2022-09-21 12:31
It's not, it's still your assembly block. Commenting out `b := m` also makes the test pass. The error is that you are assigning to a variable with type `bytes`, but the layout in memory for this type is `[len, item a, item b, ...]`, and since you are just setting a single slot in memory, it reads the result of your `xor` as the length of the `bytes` type. This works:

```solidity
pragma solidity ^0.8.10;

import "forge-std/Test.sol";

contract AssemblyTest is Test {
  address public constant SOME_CONTRACT_ADDR = 0x0000000000000000000000000000000000002001;

  function setUp() public {}

  function testAssembly() public {
    address deployAddr = deployCode("MyContract.sol");
    vm.etch(SOME_CONTRACT_ADDR, deployAddr.code);

    address addr = address(this);
    bytes memory b;
    assembly {
      // Retrieve memory pointer, assign to `b`
      b := mload(0x40)
      // Store the size in memory of `b` (32 bytes)
      mstore(b, 0x20)
      // Store value
      mstore(add(b, 0x20), xor(0x140000000000000000000000000000000000000000, addr))
      // Increase free memory pointer
      mstore(0x40, add(b, 0x40))
    }
    emit log_bytes(b);
  }
}
```

**Closed by onbjerg** 2022-09-21 12:31 UTC
Labels: T-bug, Cmd-forge-test, C-forge, A-cheatcodes
