### ISSUE TITLE
bug(`anvil`): memory / storage leak in long running test against Anvil

### ISSUE THREAD

**Issue by kubmichael** [foundry-rs/foundry#3478] opened 2022-10-12 06:06 UTC
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### Operating System

Linux

### Describe the bug

Hey, I run a long test with 10K blocks on anvil.
After some time I saw that memory and and storage usage of anvil has increased drastically.
I found that anvil is keeping mined blocks at file system as json files, also after digging in code, I think that blocks also kept in memory.
Is it intentional? Can I limit in some way number of blocks that kept in memory or at file system ?
Can I configure where to keep those files?

Thanks

**Comment by mattsse** [comment] 2022-10-12 10:16
we keep the entire state in memory but cache history states on disk, however, there's still overhead.

there are currently no options to configure this, but this could be added very easily, including whether to keep the historic state at all, which should decrease memory footprint.

**Comment by kubmichael** [comment] 2022-10-12 13:20
configuration option will be very helpful.

**Comment by yhayun** [comment] 2022-10-12 14:02
+1 on adding an option to configure this option - the memory/storage footprint is significant

**Comment by wminshew** [comment] 2022-10-12 22:30
I think this might be related but I've noticed the tests in https://github.com/0xSplits/splits-liquid slow down significantly after  a few runs & eventually just start intermittently failing `[FAIL. Reason: EvmError: FatalExternalError] testCan_distributeToMaxUniqueHolders() (gas: 9223372036854754743)` (normal success case is ~110m gas?)

**Comment by Arieg419** [comment] 2022-10-13 13:56
+1 on adding this - this would be super impactful and significantly improve performance on long-running simulations.

**Comment by gakonst** [comment] 2022-10-14 15:15
Can folks check if running tests with #3488 fixes it?

**Comment by paco0x** [comment] 2022-10-17 04:50
> Can folks check if running tests with #3488 fixes it?

Hi @gakonst, this issue still exists. I tested with the'-prune-history` flag on,  memory usage is still increasing with txs running. It consumes 12G with 55k txs executed on my end:

<img width="1322" alt="CleanShot 2022-10-17 at 12 31 25@2x" src="https://user-images.githubusercontent.com/6123425/196091741-6c50ec2d-c9be-49fb-9427-450f200f3d7a.png">

**Comment by gakonst** [comment] 2022-10-17 14:04
@mattsse can u take a look here?

**Comment by mattsse** [comment] 2022-10-17 14:09
@paco0x how can I reproduce this?

**Comment by paco0x** [comment] 2022-10-17 16:37
> @paco0x how can I reproduce this?

I'm running a simulation tool that replays thousands of historical txs on Uniswap V3 in a forked network. Sorry, the code cannot share here but I assume the issue is not related to any specified contract.

With the transactions being executed in this forked network, the memory footprint of `anvil` also grows. And finally, the system got OOM.

As aforementioned, `anvil` is started with `--prune-history` and the memory usage is about 12.7G after 55k tx executed.

I also tried to call `anvil_reset` to this high-memory usage anvil instance. The memory usage didn't reduce after the call, which is also unexpected.

**Comment by gakonst** [comment] 2023-01-04 16:44
Would like to see a repro please, hard to debug otherwise! Thanks and appreciate the help/understanding.

**Comment by marshall2112** [comment] 2023-01-06 13:29
> Would like to see a repro please, hard to debug otherwise! Thanks and appreciate the help/understanding.
> 
> Did you use the fix from #3836?

## Pre-requisites

- Docker installed (In case of docker for mac, cannot be version 4.15)
- Anvil installed
- Clone this repo
- In repo directory, run `yarn`

## Run anvil, forking eth mainnet

- anvil --fork-url https://eth-mainnet.g.alchemy.com/v2/XYZ --chain-id 1337

## Create local graph-node instance

- cd projects/dev-graph-node
- `yarn node setup`
- `yarn node start`

## Deploy subgraph to local node

- cd ../../subgraph-bean
- `yarn codegen`
- `yarn build`
- `yarn create-local`
- `yarn deploy-local`

This will begin a long process where the graph-node indexes the new subgraph.

## Behavior

Expected:
- anvil gracefully handles the graph indexing process

Actual behavior:
- anvil develops a memory leak and gradually uses _gigabytes_ of memory, eventually causing transactions/requests to not respond. You can see memory start to increase pretty quickly, within a few minutes (<15).

**Comment by marshall-bean** [comment] 2023-01-06 13:36
> Got it - will investigate, ty for the repro.
> 
> What paremeter did you set for `transaction-block-keeper`?

I tried `--transaction-block-keeper 100` just as a SWAG. If there's something more appropriate I can try a different value.

**Comment by 0xalecks** [comment] 2023-01-18 16:13
Any updates on this? We're on hold waiting to see if this is something that might be fixed in Anvil or if we have to switch to a completely different solution. 🙏

**Comment by gakonst** [comment] 2023-01-18 22:59
We'll take a pass this week - thanks! 

Was hoping somebody would've given some more debug information by now vs assuming we'll do all the debugging end to end^^

**Comment by mattsse** [comment] 2023-01-19 11:03
@marshall-bean sorry for the wait.

I tried to replicate this but the `add-dev-graph-node` seems to be gone:

> fatal: Remote branch add-dev-graph-node not found in upstream origin

does this also happen on master?

**Comment by marshall-bean** [comment] 2023-01-19 17:20
> @marshall-bean sorry for the wait.
> 
> I tried to replicate this but the `add-dev-graph-node` seems to be gone:
> 
> > fatal: Remote branch add-dev-graph-node not found in upstream origin
> 
> does this also happen on master?
> 
> could you perhaps please also try with the `--prune-history` flag

Yes is also happens on master, apologies. Please let me know if you have any further issues reproducing.

I can try again with `--prune-history` if you think that will help.

**Comment by gakonst** [comment] 2023-01-19 20:00
Yeah pls give it a shot @marshall-bean

**Comment by mattsse** [comment] 2023-01-19 20:29
I failed to get it working on first try, start timed out...

can try again in a bit

**Comment by marshall-bean** [comment] 2023-01-20 16:06
> Yeah pls give it a shot @marshall-bean

We tested this out yesterday and found that `--prune-history` seems to have solved the memory issue for us. We can consider this resolved from our POV.

**Comment by mattsse** [comment] 2023-01-20 16:10
great, so this seems to be an issue with the default limits for historic state that we keep in memory.

I guess we can make this smarter and auto adjust best on some estimation

**Comment by gakonst** [comment] 2023-01-20 18:36
I guess we could turn prune history and max transaction keeper on by default with some reasonable bounds?

**Comment by sabotagebeats** [comment] 2023-05-26 20:44
> Any updates on this? We're on hold waiting to see if this is something that might be fixed in Anvil or if we have to switch to a completely different solution. 🙏

+1

**Comment by wakamex** [comment] 2023-06-14 20:01
> I guess we could turn prune history and max transaction keeper on by default with some reasonable bounds?

has this been turned on?

I wonder if it could be the source of this error:

```
ValueError: {'code': -32602, 'message': 'BlockOutOfRangeError: block height is 9331 but requested was 5700'}
```

**Comment by grandizzy** [comment] 2024-09-26 06:09
this should be solved now with https://github.com/foundry-rs/foundry/pull/8412, please retest and reopen if still an issue. thank you

**Closed by grandizzy** 2024-09-26 06:09 UTC
Labels: T-bug, A-testing, C-anvil
