### ISSUE TITLE
`rollFork` fails to clean up "hot" storage variables

### ISSUE THREAD

**Issue by amusingaxl** [foundry-rs/foundry#5739] opened 2023-08-28 17:32 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (bff4ed9 2023-08-28T00:24:09.226668296Z)

### What command(s) is the bug in?

forge test --fork-url <RPC_ENDPOINT>

### Operating System

Linux

### Describe the bug

I just spotted this bug in the wild while running MakerDAO's [Spell Test suite](https://github.com/makerdao/spells-goerli/blob/0bc45005e3afe60bfda47121c4337fbb85b40653/src/DssSpell.t.base.sol#L283-L302).

Relevant part of the code:

```solidity
    function setUp() public {
        setValues(address(chief));

        spellValues.deployed_spell_created = spellValues.deployed_spell != address(0) ? spellValues.deployed_spell_created : block.timestamp;
        _castPreviousSpell();

        // ------------- From here ----------------------
        spell = spellValues.deployed_spell != address(0) ?
            DssSpell(spellValues.deployed_spell) : new DssSpell();

        if (spellValues.deployed_spell_block != 0 && spell.eta() != 0) {
            // if we have a deployed spell in the config
            // we want to roll our fork to the block where it was deployed
            // this means the test suite will continue to accurately pass/fail
            // even if mainnet has already scheduled/cast the spell
            vm.makePersistent(address(this));
            vm.makePersistent(address(rates));
            vm.makePersistent(address(addr));
            vm.makePersistent(address(deployers));
            vm.rollFork(spellValues.deployed_spell_block);
        }
    }
```

Spells have an `eta` and a `done` storage variables.

Apparently, any "hot" storage variable is not reset after `rollFork`, like if we had called `vm.makePersistent()` on it.

If I log both variables _before_ and _after_ `rollFork`, they have the same value:

```solidity
        if (spellValues.deployed_spell_block != 0 && spell.eta() != 0) {
            console2.log("Before `rollFork`: eta = %d, done = %b", spell.eta(), spell.done());

            // if we have a deployed spell in the config
            // we want to roll our fork to the block where it was deployed
            // this means the test suite will continue to accurately pass/fail
            // even if mainnet has already scheduled/cast the spell
            vm.makePersistent(address(this));
            vm.makePersistent(address(rates));
            vm.makePersistent(address(addr));
            vm.makePersistent(address(deployers));
            vm.rollFork(spellValues.deployed_spell_block);

            console2.log("After `rollFork`: eta = %d, done = %b", spell.eta(), spell.done());
        }
```

Result shows both wrong:

```
Logs:
  Before `rollFork`: eta = 1693238220, done = b true
  After `rollFork`: eta = 1693238220, done = b true
```

If I remove the log from _before_, `done` is now correct (it has not been accessed), however `eta` is still incorrect, because it was accessed in the conditional:

```solidity
        //                                                  +---- `eta` accessed here:
        //                                                  v
        if (spellValues.deployed_spell_block != 0 && spell.eta() != 0) {
            // if we have a deployed spell in the config
            // we want to roll our fork to the block where it was deployed
            // this means the test suite will continue to accurately pass/fail
            // even if mainnet has already scheduled/cast the spell
            vm.makePersistent(address(this));
            vm.makePersistent(address(rates));
            vm.makePersistent(address(addr));
            vm.makePersistent(address(deployers));
            vm.rollFork(spellValues.deployed_spell_block);

            console2.log("After `rollFork`: eta = %d, done = %b", spell.eta(), spell.done());
        }
```

Result shows `done` correct and `eta` wrong:

```
Logs:
  eta = 1693238220, done = b false
```

If I remove `eta` from the conditional and log it only after `rollFork`, it works as expected:

```solidity
        if (spellValues.deployed_spell_block != 0) {
            // if we have a deployed spell in the config
            // we want to roll our fork to the block where it was deployed
            // this means the test suite will continue to accurately pass/fail
            // even if mainnet has already scheduled/cast the spell
            vm.makePersistent(address(this));
            vm.makePersistent(address(rates));
            vm.makePersistent(address(addr));
            vm.makePersistent(address(deployers));
            vm.rollFork(spellValues.deployed_spell_block);

            console2.log("After `rollFork`: eta = %d, done = %b", spell.eta(), spell.done());
        }
```

Result with both correct:
```
Logs:
  eta = 0, done = b false
```

This looks like an unexpected behavior.

Please reach out to me if you need help running that test suite, but after setting `ETH_RPC_URL`, you can just call `make test match="testOnTime"`.

**Comment by nhtyy** [comment] 2023-08-29 01:13
hi you can see the behavior arise in the code snippet below, at first i also thought this was bug but

https://github.com/foundry-rs/foundry/blob/bff4ed912bb023d7bf9b20eda581aa4867a1cf70/crates/evm/src/executor/backend/mod.rs#L1098-L1111
 
I think this is more of a semantics issue; when you run the command `forge test --fork-url <RPC_ENDPOINT>` yore not specifying the block number, therefore using the current, if you load some state while the fork is at the block number it is essentially cached to memory

Now imagine you instantiate a fork at some `block=T`, and you explicitly override some value (storing it in memory), i think it makes sense that rolling the block number to `block=T+n` forward wouldn't dump all the storage and try to get the new storage at the current block (assuming its lower than the actual chains block height).

However I see where you're coming from when rolling the chain **back**. You could definitely make an argument that the state should be dumped in favor of the older state, since in practice the chain can never go backwards.

on the other hand this could be breaking change, So you should probably just use a different pattern to achieve this. But maybe the core team will have other thoughts.

A fix could be checking that if `new_block_number < current_block` dont copy over the state like in the snippet above.

**Comment by amusingaxl** [comment] 2023-08-29 11:25
If I can roll back in time, I would expect that the chain state would be rolled back, otherwise, there is no point.

All memory cache should be flushed out (or at least not be accessible by the fork) when we're in the context of a rollback. This is the expected behavior. Anything else is just too hard to reason about.

> I think this is more of a semantics issue; when you run the command forge test --fork-url <RPC_ENDPOINT> yore not specifying the block number

Yes, that is correct. By not using the `--fork-block-number` option, we can programmatically choose to fork. This approach is way more CI friendly, without the need to create wrapper scripts to conditionally spin up a fork.

> on the other hand this could be breaking change [...]

I cannot think about a use case where the current behavior would be desirable. Maybe there is someone relying on it out there, however they are relying on an arguably broken behavior.

**Comment by mds1** [comment] 2023-08-29 13:01
First to confirm my understanding of the issue: 

1. Forking from a chain ID at block `X`
2. Make state changes
3. `vm.rollFork` on the same chain to a new block `Y` where `Y < X`
4. State changes from step 2 are currently persisted, but should be reverted

Is that correct? If so, I'm not sure if that's a bug or intentional—will defer to @mattsse for that. 

Assuming that understanding is correct, potential solutions:
1. Leave as-is and document: This feels like a footgun, and is non-intuitive, for the reasons @amusingaxl mentions.
2. If going back in time on a fork, reset state to the fork state at that time: Going back in time isn't realistic, so if you're doing this, it resets all state (storage, code, nonce, block properties). But this would only apply when going back in time via a fork, and this is not applicable for a `vm.roll`
3. Don't allow this and revert: Even (2) is arguably a footgun, because most users won't need to go back in time so this might be user error. The workaround would be to first `rollFork` to the earlier block and `vm.snapshot()` it, and later you can `vm.revertTo()` instead. However, this is semantically different since RPC queries wouldn't query the old fork state, so I guess that is an argument for (2). 
4. A combination of (2) and (3) where by default it reverts but you can override this (either via a config param or a new cheatcode with a boolean config value or a similar cheat named e.g. `forceRollFork` 

I could be convinced of (2) if I better understood the use case here, but allowing you to go backwards by default feels like it could be a footgun that we should prevent.

One last thought: IMO this should all also apply to the case where `Y == X`, since that similarly should not be needed and is likely a user-error.

**Comment by amusingaxl** [comment] 2023-08-29 14:37
> Is that correct?

No, in my example, no state changes are being made. State is only being **read**.

**Comment by mds1** [comment] 2023-08-30 15:24
I see. I'd be curious if this applies to state changes also. If so, all above options are still applicable. If not, option (1) gets removed and the rest are applicable

**Comment by nhtyy** [comment] 2023-08-30 17:40
@mds1 yea it also applies to state changes, since it updates the journaled state. and then it all gets copied over by the code snipped i linked above

**Comment by nhtyy** [comment] 2023-08-30 20:05
@mds1 I was able to test this with writing to a slot at Block `T` (in another account) and then rolling to `T-100` and in both cases the state persisted when i rolled back.

```solidity
     function setUp() public {
        // deploys at current fork block
        // using `--rpc-url` 
        counter = new Counter();
        counter.increment();
    }

    function testRoll() public {
        assertEq(counter.number(), 100);

        counter.setNumber(100);

        assertEq(counter.number(), 100);

        vm.rollFork(block.number - 100);

        assertEq(counter.number(), 100);
    }

```

I think this makes sense because all state changes (reads or writes) end up in the `journaled_state` and would then be copied over for subsequent calls in the function. I believe REVM trys to load state from there first.

And since this in ops case this is the `setup` function all of this would then get written to the CacheDb since it commits its state, meaning it would persist across tests. (the journaled state is thrown away between tests/setup).

I think i like option 4, and i agree snapshot/revert seems like the right call here

**Comment by nhtyy** [comment] 2023-08-30 20:08
this also means rolling forward wont read newer slots if the slot has already been loaded

**Comment by mattsse** [comment] 2023-08-30 20:26
just catching up here 

> However I see where you're coming from when rolling the chain back.

I see.

so what should we change for roll back?

**Comment by nhtyy** [comment] 2023-08-30 20:33
@mattsse 

hi at first I thought it made sense to roll the state back just to some block the user chose, but I dont think users will intend that their state that they explicitly sets gets dumped aswell.

imo a bigger issue could be that if you read `address(n).value()` at `block=t` in the `setup` function, and then roll **forward** to `block=t+n < current` in a subsequent call/test it will still be the old value

**Comment by nhtyy** [comment] 2023-08-30 21:40
maybe we can purge the journal of all entries that are not marked as touched?

dont think this hits the edge case where a contract has an sload and a sstore (making it touched) if the goal is to do a "future" sload

i think im on the side of making it forward only and just clearing the semantics in the docs as revert/snapshot is probably the functionality people are thinking of when wanting to a do a "roll back"

**Comment by amusingaxl** [comment] 2023-08-31 16:14
> i think im on the side of making it forward only and just clearing the semantics in the docs

What would be the difference between `rollFork` and `skip`/`warp` then?

Also, the overload `function rollFork(uint256 forkId, bytes32 transaction) external;` would become very hard to use, given that you would need to calculate the hash of a future transaction yourself.

---

BTW I was going through the docs for `rollFork` and there's no indication it does what we expect it to do:

> [Description](https://book.getfoundry.sh/cheatcodes/roll-fork?highlight=rollfork#description)
>
> Sets block.number. If a fork identifier is passed as an argument, it will update that fork, otherwise it will update the currently active fork.
>
> If a transaction hash is provided, it will roll the fork to the block the transaction was mined in and replays all previously executed transactions.

If it's just changing `block.number` but the state should remain the same, I believe this is a foot gun. This could potentially break constraints in contracts, generating false positive or false negative results in tests.

How hard would it be to simply re-fetch data at the selected block height from the RPC URL?

**Comment by amusingaxl** [comment] 2023-08-31 17:04
It's a conditional:

If there is a spell on `spellValues.deployed_spell`, it uses whatever address is there, otherwise it deploys a fresh one:

```solidity
 // ------------- From here ----------------------
        spell = spellValues.deployed_spell != address(0)
            ? DssSpell(spellValues.deployed_spell) 
            : new DssSpell();
```

When it's a fresh instance, it's fine, because `eta` was not set, so it's `0` regardless.

If it's an existing contract, but it has not being scheduled yet, `eta` is still `0`, so it's still fine. However, after it's being schedule, since `eta` is not zero, so the condition `spellValues.deployed_spell_block != 0 && spell.eta() != 0` is `true`, activating the branch on that calls `rollFork`.

However, the weird part is that if I don't **read** `eta`, it works just fine:

```solidity
        if (spellValues.deployed_spell_block != 0 /*&& spell.eta() != 0*/) {
            // if we have a deployed spell in the config
            // we want to roll our fork to the block where it was deployed
            // this means the test suite will continue to accurately pass/fail
            // even if mainnet has already scheduled/cast the spell
            vm.makePersistent(address(rates));
            vm.makePersistent(address(addr));
            vm.makePersistent(address(deployers));
            vm.rollFork(spellValues.deployed_spell_block);
        }
```

When tests are being executed, `eta = 0`, even though the value stored in the actual instance is not `0`.

I would expect both scenarios to pass or both to fail.

**Comment by nhtyy** [comment] 2023-08-31 17:16
i see that, but i just mean that as an example.

Imagine you just had a state variable in your testContract maybe a `uint256 a`. Imagine you then set `a = 1` (at `block=t`), then you roll back (`block < t`). 

That uint is "apart of the fork state", so if you roll back would you expect that to be persisted even though it technically it wouldnt have been set at the previous block?

**Comment by amusingaxl** [comment] 2023-08-31 17:36
> That uint is "apart of the fork state", so if you roll back would you expect that to be persisted even though it technically it wouldnt have been set at the previous block?

Hmmm, that's a good question.

Honestly, I would expect any changes made **before** `rollFork` to be discarded. In my interpretation, `rollFork(<N>)` would have the same semantics as `--fork-block-number=<N>`, meaning it would start with the exact state the chain had on block `N`.

**Comment by amusingaxl** [comment] 2023-08-31 17:41
> I think `persistSlot `i mentioned in the comment above is a good middleground. Gives you expected behavior out of the box but also allows you to have granular control over state if you want

Notice that in the use case I mentioned, I don't need a `persistentSlot`. On the contrary, I want `eta` to be reverted to the value it had at block `N`.

**Comment by nhtyy** [comment] 2023-08-31 17:48
yes im saying introduce persistSlot and by default dump all state between rolls s.t that it fetches from remote if not persisted. Which would give you expected behavior.

**Closed** 2024-05-24 10:03 UTC
Labels: T-bug
