### ISSUE TITLE
Cannot install OpenZeppelin dependency via `forge install`

### ISSUE THREAD

**Issue by StErMi** [foundry-rs/foundry#4096] opened 2023-01-15 17:12 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (b2baca3 2023-01-15T00:04:32.877705Z)

### What command(s) is the bug in?

forge install

### Operating System

macOS (Apple Silicon)

### Describe the bug

I'm trying to install a specific tag/release of open zeppelin contract by executing the command ` forge install OpenZeppelin/openzeppelin-contracts@v4.7.1 --no-commit`

Error → `Tag: "v4.7.1" not found for repo: "https://github.com/OpenZeppelin/openzeppelin-contracts"!`

Both the tag and release are available, but I get the same error even if I try to install by using the tag/release commit hash.

**Comment by rkrasiuk** [comment] 2023-01-31 14:42
@StErMi are you still experiencing this issue? ran the command above and the installation succeeded

**Comment by DevABDee** [comment] 2023-02-20 12:42
I'm facing the same problem. Solmate got installed but can't install OZ contracts.

**Comment by Evalir** [comment] 2023-06-16 06:33
Closing—cannot reproduce and related issue was closed.

**Closed by Evalir** 2023-06-16 06:33 UTC
Labels: T-bug, C-forge, Cmd-forge-pm

**Comment by IAm0xAxe** [comment] 2023-07-15 08:36
@StErMi  The problem can be solved with this command: `forge install openzeppelin-contracts-06=OpenZeppelin/openzeppelin-contracts@v3.4.0 --no-commit`

**Comment by acemasterjb** [comment] 2023-09-07 15:40
I am still getting this issue, e.g.

```console
$ forge init derpy
# ...
remote: Total 313 (delta 90), reused 135 (delta 75), pack-reused 142
Receiving objects: 100% (313/313), 71.98 KiB | 1.18 MiB/s, done.
Resolving deltas: 100% (129/129), done.
$ forge install --no-commit --shallow OpenZeppelin/openzeppelin-contracts@v4.9.2
Installing openzeppelin-contracts in /path/to/derpy/lib/openzeppelin-contracts (url: Some("https://github.com/OpenZeppelin/openzeppelin-contracts"), tag: Some("v4.9.2"))
Error:
Tag: "v4.9.2" not found for repo "https://github.com/OpenZeppelin/openzeppelin-contracts"! 
```
---
Notes
* Forge version: 0.2.0
* System: Windows 11, WSL2

**Comment by acemasterjb** [comment] 2023-09-07 15:43
And for some reason doing @IAm0xAxe's solution fixed it... but I have no idea why. Can someone explain, and is this expected behaviour?

**Comment by Phenzic** [comment] 2024-01-21 11:12
I've been having the same issue so I simply `cd` into the `lib` directory, installed the dependencies with `git` instead, and then updated my `foundry.toml` file to recognize the installed submodules.

Just an alternative solution though, and probably not the right one but it does the work just fine...
