### ISSUE TITLE
`forge coverage` reports are inaccurate

### ISSUE THREAD

**Issue by HrikB** [foundry-rs/foundry#2759] opened 2022-08-13 13:07 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (49558db 2022-08-10T00:11:55.304734589Z)

### What command(s) is the bug in?

forge coverage

### Operating System

Linux

### Describe the bug

After writing my tests for a contract, I ran coverage and was surprised to see that contract had full line and functions coverage. When I opened the lcov report and read through which lines it was saying I had covered, I knew it something was wrong because there were some function considered covered despite me never writing a test for it. 

I commented out all my tests expect one function call to see if it still gave my 100% line and function coverage and it did. For some reason, one call to a contract gives me full Line, Function, and Statements coverage. However, the branch coverage result seems to be accurate.

**Comment by HrikB** [comment] 2022-08-13 13:07
I can provide source code, if needed.

**Comment by KittyFu307** [comment] 2022-08-15 09:26
Hi ~ I also have the same question, Have you already fixed this?

**Comment by onbjerg** [comment] 2022-08-15 09:42
Duplicate of #2668, please include context in there.

**Comment by KittyFu307** [comment] 2022-08-15 09:42
您好，我是付诗琨，您的邮件我已收到，我会尽快查看并给您回复，谢谢。

**Closed by onbjerg** 2022-08-15 09:42 UTC
Labels: T-bug, C-forge, Cmd-forge-coverage
