### ISSUE TITLE
Error when trying to compile new rust project from scratch 

### ISSUE THREAD

**Issue by Toeplitz** [foundry-rs/foundry#8979] opened 2024-09-28 20:10 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

master

### Operating System

None

### Describe the bug

In a new rust project I have this Cargo.toml
```

[package]
name = "test"
version = "0.1.0"
edition = "2021"
rust-version = "1.80"

[dependencies]
foundry-evm = { git = "https://github.com/foundry-rs/foundry" }
```

With this I get the following compile error:

> 
>    Compiling foundry-fork-db v0.3.1
>    Compiling revm-inspectors v0.7.7
> error[E0308]: mismatched types
>    --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/foundry-fork-db-0.3.1/src/cache.rs:459:39
>     |
> 459 |                 accounts: RwLock::new(accounts),
>     |                           ----------- ^^^^^^^^ expected `HashMap<Address, ..., ...>`, found `HashMap<Address, AccountInfo>`
>     |                           |
>     |                           arguments to this function are incorrect
>     |
>     = note: expected struct `HashMap<_, _, FxBuildHasherInner>`
>                found struct `HashMap<_, _, RandomState>`
> note: associated function defined here
>    --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lock_api-0.4.12/src/rwlock.rs:371:18
>     |
> 371 |     pub const fn new(val: T) -> RwLock<R, T> {
>     |                  ^^^
> 
> error[E0308]: mismatched types
>    --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/foundry-fork-db-0.3.1/src/cache.rs:460:38
>     |
> 460 |                 storage: RwLock::new(storage),
>     |                          ----------- ^^^^^^^ expected `HashMap<Address, ..., ...>`, found `HashMap<Address, ...>`
>     |                          |
>     |                          arguments to this function are incorrect
>     |
>     = note: expected struct `HashMap<_, HashMap<_, _, FxBuildHasherInner>, FxBuildHasherInner>`
>                found struct `HashMap<_, HashMap<_, _, RandomState>, RandomState>`
> note: associated function defined here
>    --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lock_api-0.4.12/src/rwlock.rs:371:18
>     |
> 371 |     pub const fn new(val: T) -> RwLock<R, T> {
>     |                  ^^^
> 
> error[E0308]: mismatched types
>    --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/foundry-fork-db-0.3.1/src/cache.rs:461:43
>     |
> 461 |                 block_hashes: RwLock::new(block_hashes),
>     |                               ----------- ^^^^^^^^^^^^ expected `HashMap<Uint<256, 4>, ..., ...>`, found `HashMap<Uint<256, 4>, ...>`
>     |                               |
>     |                               arguments to this function are incorrect
>     |
>     = note: expected struct `HashMap<_, _, FxBuildHasherInner>`
>                found struct `HashMap<_, _, RandomState>`
> note: associated function defined here
>    --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lock_api-0.4.12/src/rwlock.rs:371:18
>     |
> 371 |     pub const fn new(val: T) -> RwLock<R, T> {
>     |                  ^^^
> 
> For more information about this error, try `rustc --explain E0308`.
> error: could not compile `foundry-fork-db` (lib) due to 3 previous errors
> warning: build failed, waiting for other jobs to finish...

Trying to compile foundry itself works fine.
What am I missing for this compilation to work with the foundry-evm in my project?

**Comment by zerosnacks** [comment] 2024-09-30 09:59
Hi @Toeplitz, could you re-run your test setup against latest master? I'm unable to reproduce your error. Sometimes there is a short period of time we have mismatching versions when the different crates along our dependency chain are being updated.

Tip: have a look at https://github.com/alloy-rs/examples/pull/145/files + https://github.com/foundry-rs/foundry-fork-db if you would like to use EVM forking without pulling in the entirety of Foundry

**Comment by mattsse** [comment] 2024-09-30 10:03
@yash-atreya fyi, this should be fixed with wip alloy-prim bump

**Comment by Toeplitz** [comment] 2024-09-30 10:25
@zerosnacks as I understand when I have this line:
`foundry-evm = { git = "https://github.com/foundry-rs/foundry" }`
it should pull from latest master?

I tried to just do a cargo clean and cargo build in my dummy project again and I have same error.

You should be able reproduce by just making a new rust project and then run:
cargo init
.... then add the foundary-evm crate and run 
cargo build

**Comment by zerosnacks** [comment] 2024-09-30 10:36
Thanks @Toeplitz, this should be fixed by https://github.com/foundry-rs/foundry/pull/8988

**Comment by Toeplitz** [comment] 2024-09-30 12:24
Ok, it builds with foundry-evm = { git = "https://github.com/foundry-rs/foundry", branch="yash/bump-alloy-prim"}

**Closed** 2024-09-30 13:35 UTC
Labels: T-bug, T-to-reproduce, A-dependencies
