### ISSUE TITLE
Console log doesn't have string support

### ISSUE THREAD

**Issue by jonathanjmak** [foundry-rs/foundry#1480] opened 2022-05-03 21:45 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (dda0189 2022-04-30T00:15:17.990347+00:00)

### What command(s) is the bug in?

console.log("insert me here: %s", "hi");

### Operating System

macOS (amd)

### Describe the bug

Output should be ```insert me here: hi``` but instead we get ```insert me here: %s, hi```

**Comment by onbjerg** [comment] 2022-05-03 22:55
Duplicate of #1429

**Closed by onbjerg** 2022-05-03 22:55 UTC
Labels: T-bug
