### ISSUE TITLE
bug: base Docker image for Foundry on ARM (Mac M2) fails to build

### ISSUE THREAD

**Issue by rkdud007** [foundry-rs/foundry#8511] opened 2024-07-24 15:27 UTC
### Component

Other (please describe)

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### Operating System

macOS (Apple Silicon)

### Describe the bug

trying to follow basic script for add base image of foundry ( i also tried just put foundry:nightly also but same error ) 
```
# Use the latest foundry image
FROM ghcr.io/foundry-rs/foundry:nightly-5af9d16ecb620192d4fe5ae61d33e429b7f5aff3

# Copy our source code into the container
WORKDIR /app

# Build and test the source code
COPY . .
RUN forge build
RUN forge test
```

<img width="1060" alt="Screenshot 2024-07-24 at 5 26 07 PM" src="https://github.com/user-attachments/assets/8629ef5a-0eef-474e-afa8-2a9081e565f0">

**Comment by zerosnacks** [comment] 2024-07-24 15:53
Unable to reproduce the issue with Linux with the same nightly

Created a basic repro repo here: https://github.com/zerosnacks/foundry-bug-8511-repro

**Comment by grandizzy** [comment] 2024-07-24 17:03
> Unable to reproduce the issue on Linux with the same nightly
> 
> Created a basic repro repo here: https://github.com/zerosnacks/foundry-bug-8511-repro for others to try

yeah, that's macos related, similar with https://github.com/foundry-rs/foundry/issues/8039 There's a PR in works for supporting arm64 https://github.com/foundry-rs/foundry/pull/7512

**Comment by grandizzy** [comment] 2024-10-04 11:43
going to track progress in https://github.com/foundry-rs/foundry/issues/8039 (there's already a PR in works for it) and close this one as dupe.

**Closed by grandizzy** 2024-10-04 11:43 UTC
Labels: T-bug, A-releases, A-compatibility
