### ISSUE TITLE
fix(forge): vm.getNonce() returns max(nonce, 1) in scripts

### ISSUE THREAD

**Issue by OliverNChalk** [foundry-rs/foundry#2129] opened 2022-06-27 01:04 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (153ae19 2022-06-26T00:04:15.775569508Z)

### What command(s) is the bug in?

forge

### Operating System

Linux

### Describe the bug

The nonce inside of scripts starts at 1, remains at 1 for the first broadcast, and then correctly increments for subsequent broadcasts. This means scripts cannot tell if an address has sent 0 or 1 txs which naturally causes issues.

Minimal reproduction:

https://github.com/proximacapital/forge-nonce-issue

**Comment by onbjerg** [comment] 2022-06-27 06:18
Duplicate of 2110

**Closed by onbjerg** 2022-06-27 06:18 UTC
Labels: T-bug
