### ISSUE TITLE
Foundry versioning and changelog

### ISSUE THREAD

**Issue by Magicking** [foundry-rs/foundry#7506] opened 2024-03-27 12:25 UTC
### Component

Forge, Foundryup

### Describe the feature you would like

Have the possibility to have versioning for the software in order for:
 - Package manager to maintain the distribution of Foundry
 - Dependencies to specify version requirement
 - Developer who use the software to understand what are the changes in-between releaseuses

### Additional context

I already spent too many hours of my life trying to figure stuff out just to guess randomly that it was a Foundry forge not up-to-date issue and I know many which is the case as well, I think having a way to propose a version will help reduce this poor developer experience.

**Comment by zerosnacks** [comment] 2024-07-12 14:14
Hi @Magicking, thanks for your notes

We are working towards a process of versioned releases post-`1.0` including changelogs

In an effort to limit open tickets I'm marking this ticket as duplicate of https://github.com/foundry-rs/foundry/issues/3895

Feel free to leave additional sugesstions / requirements on tickets tagged here: https://github.com/foundry-rs/foundry/issues?q=is%3Aissue+is%3Aopen+releases+label%3AA-releases

**Closed by zerosnacks** 2024-07-12 14:14 UTC
Labels: T-feature
