### ISSUE TITLE
Bug: Failed to get account for 0x001b…23d4, ProviderError Too Many Requests

### ISSUE THREAD

**Issue by sambacha** [foundry-rs/foundry#2122] opened 2022-06-25 21:36 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### Describe the bug

This is happening against a private RPC Node

```log
2022-06-25T21:08:35.5138870Z Test result: [31mFAILED[0m. 1 passed; 1 failed; finished in 7.66s
2022-06-25T21:08:40.2607237Z [31mThe application panicked (crashed).[0m
2022-06-25T21:08:40.2608481Z Message:  [36mFailed to get account for 0x001b…23d4
2022-06-25T21:08:40.2609512Z ProviderError(SerdeJson { err: Error("expected value", line: 1, column: 1), text: "Too Many Requests, [code:OVER_LIMIT current_limit:{requests_per_unit:1500 unit:MINUTE}]" })[0m
2022-06-25T21:08:40.2610537Z Location: [35m/home/runner/work/foundry/foundry/evm/src/executor/fork/backend.rs[0m:[35m265[0m
2022-06-25T21:08:40.2610919Z 
2022-06-25T21:08:40.2611947Z This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry
2022-06-25T21:08:40.2612224Z 
2022-06-25T21:08:40.2612582Z Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
2022-06-25T21:08:40.2613068Z Run with RUST_BACKTRACE=full to include source snippets.
2022-06-25T21:08:40.5068356Z /home/runner/work/_temp/6c7b5394-3a6e-4a73-b1f3-aa5844bf928f.sh: line 1:  1935 Aborted                 (core dumped) forge snapshot --check -f "$ETH_RPC_URL" -vvv --fork-block-number 15025356 --allow-failure
```

Can provide more details (logs etc) if needed

**Comment by mattsse** [comment] 2022-06-25 21:49
> 2022-06-25T21:08:40.2609512Z ProviderError(SerdeJson { err: Error("expected value", line: 1, column: 1), text: "Too Many Requests, [code:OVER_LIMIT current_limit:{requests_per_unit:1500 unit:MINUTE}]" })�[0m

can you provide relevant headers + status code for the rate limited response? so we can identify this as RL error and retry after backing off

**Comment by onbjerg** [comment] 2022-07-03 12:27
Ping @sambacha

**Comment by sambacha** [comment] 2022-07-03 12:30
> > 2022-06-25T21:08:40.2609512Z ProviderError(SerdeJson { err: Error("expected value", line: 1, column: 1), text: "Too Many Requests, [code:OVER_LIMIT current_limit:{requests_per_unit:1500 unit:MINUTE}]" })�[0m
> 
> 
> 
> can you provide relevant headers + status code for the rate limited response? so we can identify this as RL error and retry after backing off

How you want em? HAR? raw? sunny side up?

**Comment by sambacha** [comment] 2022-07-03 12:31
There is no rate limit, this was against my own personal node.

**Comment by onbjerg** [comment] 2022-07-03 12:39
What node? Geth? Erigon?

**Comment by sambacha** [comment] 2022-07-03 12:41
> What node? Geth? Erigon?

Nethermind. I will look for the logs I must have them some where or maybe I can reproduce it again.

**Comment by onbjerg** [comment] 2022-07-03 12:43
And it wasn't behind a proxy of any kind like nginx?

**Comment by sambacha** [comment] 2022-07-03 12:44
> And it wasn't behind a proxy of any kind like nginx?

Local. Raw dog. Not even a container between us.

**Comment by onbjerg** [comment] 2022-07-03 12:46
Any chance you used a remote node by accident? I'm asking because the error message is not from ethers, but it doesn't seem to be present in Nethermind either. Since you didn't post any RPC URL and you didn't provide a Forge version it's going to be really hard to reproduce, unless you can reproduce it yourself. Would it be OK to close the issue if you can't?

**Comment by sambacha** [comment] 2022-07-04 01:30
> Any chance you used a remote node by accident? I'm asking because the error message is not from ethers, but it doesn't seem to be present in Nethermind either. Since you didn't post any RPC URL and you didn't provide a Forge version it's going to be really hard to reproduce, unless you can reproduce it yourself. Would it be OK to close the issue if you can't?

I remember now, this was during the GitHub CI outage. We can close this, aa I also had issues with a few actions at the time (not all at once).

**Closed** 2022-07-04 01:30 UTC
Labels: T-bug, C-forge
