### ISSUE TITLE
Forge commands such as `forge script` & `forge verify-contract` are not working for chains with smaller block times.

### ISSUE THREAD

**Issue by HareemSaad** [foundry-rs/foundry#8352] opened 2024-07-04 08:55 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (0dceb53 2024-07-04T00:18:10.333518000Z)

### What command(s) is the bug in?

forge script, forge verify-contract

### Operating System

macOS (Apple Silicon)

### Describe the bug

When running on chain operations such as forge script with --broadcast flag or running forge verify-contract on chains with smaller block times such as Lightlink (main net: phoenix, test net: pegasus; 1 block created every 0.5 second), produces errors, this was not an issue with previous versions such as `forge 0.2.0 (85f25c6 2023-11-08T00:39:13.596331000Z)` it works fine.

here is a repo that you can use to replicate: https://github.com/HareemSaad/Lightlink-Issue-Foundry-Bug.git

there is my output for pegasus deployment
<img width="1508" alt="Screenshot 2024-07-04 at 1 33 38 PM" src="https://github.com/foundry-rs/foundry/assets/88980688/6db7137c-4dae-4826-8398-e8558a614862">

this is my output for Sepolia deployment
<img width="1508" alt="Screenshot 2024-07-04 at 1 43 39 PM" src="https://github.com/foundry-rs/foundry/assets/88980688/fb643b25-2cae-45e1-b786-2e4e5e79893a">

as you can see pegasus deployment fails at getting receipts and verifying contracts, but Sepolia does not, **BUT even though pegasus shows my deployment as failed it still deploys the contract but it does not verify**

**Comment by klkvr** [comment] 2024-07-04 14:24
The issue is that mentioned network `eth_getTransactionReceipt` returns incorrect responses. `cast receipt` is also failing for transactions on those networks:
```
~ cast receipt 0x5bda9ea41560032e6fc3c71105faa33e85e188f02d949952031d55a3b2e85170 --rpc-url https://replicator.phoenix.lightlink.io/rpc/v1 
Error: 
deserialization error: missing field `effectiveGasPrice` at line 1 column 2544

Context:
- missing field `effectiveGasPrice` at line 1 column 2544
```

**Comment by HareemSaad** [comment] 2024-07-05 08:52
Hey @klkvr  so is there a fix for it?

**Comment by HareemSaad** [comment] 2024-07-05 08:52
> The issue is that mentioned network `eth_getTransactionReceipt` returns incorrect responses. `cast receipt` is also failing for transactions on those networks:
> 
> ```
> ~ cast receipt 0x5bda9ea41560032e6fc3c71105faa33e85e188f02d949952031d55a3b2e85170 --rpc-url https://replicator.phoenix.lightlink.io/rpc/v1 
> Error: 
> deserialization error: missing field `effectiveGasPrice` at line 1 column 2544
> 
> Context:
> - missing field `effectiveGasPrice` at line 1 column 2544
> ```

Hey @klkvr so is there a fix for it?

**Comment by DaniPopes** [comment] 2024-07-05 11:19
Not on our side, it's the RPC returning an off-spec response so it should be fixed there

**Closed** 2024-07-05 11:20 UTC
Labels: T-bug
