### ISSUE TITLE
Seeing requests timeout using Alchemy provider in forked mode. Alchemy reports no issues.

### ISSUE THREAD

**Issue by sunwrobert** [foundry-rs/foundry#2755] opened 2022-08-13 03:42 UTC
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

0.1.0 (bdc661f 2022-08-12T00:07:28.790638089Z)

### Describe the bug

Hey again. So my original setBalance issue #2646  seems to be fixed, but I'm still seeing some timeouts which eventually lead to the Anvil node crashing. 

The tail end of the log output is here: 

```
api_local-ethereum-mainnet-1  | [2m2022-08-13T02:59:22.887240Z[0m [35mTRACE[0m [2mbackend[0m[2m:[0m creating new block with 1 transactions
api_local-ethereum-mainnet-1  | thread 'fork-backend-thread' panicked at 'Failed to get storage for 0xfad4…7607 at 10932696885632322209407033095380116964487118333948220950585551810232368538524
api_local-ethereum-mainnet-1  | ProviderError(ReqwestError(reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("eth-mainnet.g.alchemy.com")), port: None, path: "/v2/wjHFOUwHNdrFd0eogO0IP4oA0PxhDRSD", query: None, fragment: None }, source: TimedOut }))', evm/src/executor/fork/backend.rs:302:33
api_local-ethereum-mainnet-1  | stack backtrace:
api_local-ethereum-mainnet-1  | [2m2022-08-13T03:01:22.863573Z[0m [32m INFO[0m [2mnode::user[0m[2m:[0m eth_getBalance
api_local-ethereum-mainnet-1  | [2m2022-08-13T03:01:22.863592Z[0m [35mTRACE[0m [2mbackend[0m[2m:[0m get balance for 0x71942e1aad7a968f86e979b0ea07708456b80e39
api_local-ethereum-mainnet-1  |    0:     0x5639f8bcf200 - <unknown>
api_local-ethereum-mainnet-1  |    1:     0x5639f897f0cc - <unknown>
api_local-ethereum-mainnet-1  |    2:     0x5639f8bacdd0 - <unknown>
api_local-ethereum-mainnet-1  |    3:     0x5639f8bcff05 - <unknown>
api_local-ethereum-mainnet-1  |    4:     0x5639f8bd0d04 - <unknown>
api_local-ethereum-mainnet-1  |    5:     0x5639f8bd08a2 - <unknown>
api_local-ethereum-mainnet-1  |    6:     0x5639f8bd0816 - <unknown>
api_local-ethereum-mainnet-1  |    7:     0x5639f8bd07d2 - <unknown>
api_local-ethereum-mainnet-1  |    8:     0x5639f865f322 - <unknown>
api_local-ethereum-mainnet-1  |    9:     0x5639f89f0dbf - <unknown>
api_local-ethereum-mainnet-1  |   10:     0x5639f86b6b23 - <unknown>
api_local-ethereum-mainnet-1  |   11:     0x5639f86881b8 - <unknown>
api_local-ethereum-mainnet-1  |   12:     0x5639f868cad4 - <unknown>
api_local-ethereum-mainnet-1  |   13:     0x5639f8bd1ac5 - <unknown>
api_local-ethereum-mainnet-1  |   14:     0x7f3794e7aea7 - start_thread
api_local-ethereum-mainnet-1  |   15:     0x7f3794c60def - clone
api_local-ethereum-mainnet-1  |   16:                0x0 - <unknown>
api_local-ethereum-mainnet-1  | ./scripts/run_ethereum.sh: line 4:    10 Aborted                 (core dumped) RUST_LOG=backend,node,miner,rpc=warn RUST_BACKTRACE=full anvil --host 0.0.0.0 --fork-url="https://eth-mainnet.g.alchemy.com/v2/wjHFOUwHNdrFd0eogO0IP4oA0PxhDRSD" --fork-block-number=15187941 --port=8545 --block-time=5 --chain-id=1
api_local-ethereum-mainnet-1 exited with code 134
```

[ethereum-mainnet.log](https://github.com/foundry-rs/foundry/files/9330728/ethereum-mainnet.log)

Our alchemy dashboards don't show any requests explicitly timing out or failing, so it's quite strange.

Questions I have:
Should timeouts crash the node? 
Is there a way to specify the number of retries? 
Does the timeout already take into account retries?

**Comment by onbjerg** [comment] 2022-08-15 17:49
> Should timeouts crash the node?

Probably, albeit a bit more gracefully. The reason we want to fail in this state is that it could otherwise lead to invalid state silently, which would *then* lead to very very hard to reproduce/fix bug reports

Do you think the timeout might be on your end? I.e. Alchemy is not timing out but your connection is flaky or something like that. Anvil might be sending too many requests too quickly

**Comment by sunwrobert** [comment] 2022-08-15 19:43
@onbjerg We aren't seeing the same issues with Hardhat so I think it's an Anvil issue, no? I don't think our connection would be flaky. It's totally possible that Anvil would be sending in too many requests as we have a good number of parallel workers in our tests leading to sending in RPC requests. However, yeah we're running the same exact environment and test suite between Hardhat and Anvil and Hardhat doesn't seem to have these issues as frequently.

**Comment by mattsse** [comment] 2022-08-16 03:15
> source: TimedOut

this is a http request timed out error that is thrown when the HTTP request does not finish in a certain time, it's configured to 120secs which usually should be more than sufficient.

this is for individual HTTP requests. if a request times out it would make sense that they don't appear in the dashboard because they're not processed.

this is definitely unrelated to retries etc because this happens directly in reqwest

https://github.com/seanmonstar/reqwest/blob/61474f422caa6f9f843ae3a5bf656b5b3f507241/src/async_impl/client.rs#L1874

so the request is either not sent at all or alchemy drops it and doesn't send a response?

**Comment by sunwrobert** [comment] 2022-08-16 03:20
Are there any config options/environment variables I can set that might help debug this?

**Comment by onbjerg** [comment] 2022-08-16 09:24
I don't think dropping the request and ignoring it is preferable since it would just silently lead to incorrect state as mentioned in my first comment, so I don't think adding support for that makes a lot of sense. It's much more preferable that we figure out what the underlying cause is

**Comment by sunwrobert** [comment] 2022-08-17 00:07
This issue from hardhat seems a little bit similar: https://github.com/NomicFoundation/hardhat/issues/2672#issue-1227453780. 

I'm trying to find a repro in this thread that would also cause a timeout on the Anvil node.

**Comment by sunwrobert** [comment] 2022-08-17 11:18
@onbjerg Yeah, I do think a solution instead of ignoring it would be to at least be able to config the timeout parameters. Hardhat lets you do that in their config (linked in the issue above), and it does seem to help people out with that specific issue.

**Comment by mattsse** [comment] 2022-08-17 13:35
hey @sunwrobert 

I've added a quick debug pr #2816 that allows you to manually set the req time out quick and dirty via `REQ_TIMEOUT` env var which expects milliseconds

```console
REQ_TIMEOUT=100000 anvil -f https://eth-mainnet.alchemyapi.io/v2/...                                                                                             
using 100s request timeout
```

the default timeout is `120s`

you should be able to install the branch via `foundryup --pr 2816`

**Comment by sunwrobert** [comment] 2022-08-22 11:10
Ugh, just tried this branch and still getting the same error:

```
api_local_334b46eadb717b99b8cd214d0f8d32e860b94b96-ethereum-mainnet-1  | thread 'fork-backend-thread' panicked at 'Failed to get account for 0x898b…10b1
api_local_334b46eadb717b99b8cd214d0f8d32e860b94b96-ethereum-mainnet-1  | ProviderError(ReqwestError(reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("eth-mainnet.g.alchemy.com")), port: None, path: "/v2/wjHFOUwHNdrFd0eogO0IP4oA0PxhDRSD", query: None, fragment: None }, source: TimedOut }))', evm/src/executor/fork/backend.rs:271:33
api_local_334b46eadb717b99b8cd214d0f8d32e860b94b96-ethereum-mainnet-1  | stack backtrace:
api_local_334b46eadb717b99b8cd214d0f8d32e860b94b96-ethereum-mainnet-1  |    0:     0x55821301e5d3 - <unknown>
api_local_334b46eadb717b99b8cd214d0f8d32e860b94b96-ethereum-mainnet-1  |    1:     0x558212d1d00c - <unknown>
api_local_334b46eadb717b99b8cd214d0f8d32e860b94b96-ethereum-mainnet-1  |    2:     0x558212ffb2be - <unknown>
api_local_334b46eadb717b99b8cd214d0f8d32e860b94b96-ethereum-mainnet-1  |    3:     0x55821301f2d5 - <unknown>
api_local_334b46eadb717b99b8cd214d0f8d32e860b94b96-ethereum-mainnet-1  |    4:     0x5582130200b4 - <unknown>
api_local_334b46eadb717b99b8cd214d0f8d32e860b94b96-ethereum-mainnet-1  |    5:     0x55821301fc52 - <unknown>
api_local_334b46eadb717b99b8cd214d0f8d32e860b94b96-ethereum-mainnet-1  |    6:     0x55821301fbc6 - <unknown>
api_local_334b46eadb717b99b8cd214d0f8d32e860b94b96-ethereum-mainnet-1  |    7:     0x55821301fb82 - <unknown>
api_local_334b46eadb717b99b8cd214d0f8d32e860b94b96-ethereum-mainnet-1  |    8:     0x5582129f58b2 - <unknown>
api_local_334b46eadb717b99b8cd214d0f8d32e860b94b96-ethereum-mainnet-1  |    9:     0x558212e47dd2 - <unknown>
api_local_334b46eadb717b99b8cd214d0f8d32e860b94b96-ethereum-mainnet-1  |   10:     0x558212a45afb - <unknown>
api_local_334b46eadb717b99b8cd214d0f8d32e860b94b96-ethereum-mainnet-1  |   11:     0x558212a1e7af - <unknown>
api_local_334b46eadb717b99b8cd214d0f8d32e860b94b96-ethereum-mainnet-1  |   12:     0x558212a1f5b8 - <unknown>
api_local_334b46eadb717b99b8cd214d0f8d32e860b94b96-ethereum-mainnet-1  |   13:     0x558213020e95 - <unknown>
api_local_334b46eadb717b99b8cd214d0f8d32e860b94b96-ethereum-mainnet-1  |   14:     0x7f8d9a25eea7 - start_thread
api_local_334b46eadb717b99b8cd214d0f8d32e860b94b96-ethereum-mainnet-1  |   15:     0x7f8d9a188def - clone
api_local_334b46eadb717b99b8cd214d0f8d32e860b94b96-ethereum-mainnet-1  |   16:                0x0 - <unknown>
api_local_334b46eadb717b99b8cd214d0f8d32e860b94b96-ethereum-mainnet-1  | ./scripts/run_ethereum.sh: line 4:    10 Aborted                 (core dumped) REQ_TIMEOUT=240000 RUST_LOG=backend,node,miner,rpc=warn RUST_BACKTRACE=full anvil --host 0.0.0.0 --fork-url="https://eth-mainnet.g.alchemy.com/v2/wjHFOUwHNdrFd0eogO0IP4oA0PxhDRSD" --fork-block-number=15347924 --port=8545 --block-time=5 --chain-id=1
api_local_334b46eadb717b99b8cd214d0f8d32e860b94b96-ethereum-mainnet-1 exited with code 134
```

Stumped :/

**Comment by sunwrobert** [comment] 2022-08-22 11:21
Does anvil retry on timeouts? Or is it just on rate limits? Possible to change the branch where if the request times out, we retry some number of times?

**Comment by mattsse** [comment] 2022-08-22 12:56
what timeout did you set?

it does not exist but we can add this and this makes sense, on it.

looks, like this could be a common issue on "spurious network"

**Comment by sunwrobert** [comment] 2022-08-22 12:57
> what timeout did you set?
> 
> it does not exist but we can add this and this makes sense, on it.
> 
> looks, like this could be a common issue on "spurious network"

I used a 240_000 timeout, which should never take that long..

**Comment by mattsse** [comment] 2022-08-22 13:07
yeh the `spurious network error` warning, makes me think that there are some connectivity issues.

adding retries for timed out request should fix this I hope, will add this today

**Comment by mattsse** [comment] 2022-08-22 19:20
@sunwrobert timed out request should now be retried as well

**Comment by sunwrobert** [comment] 2022-08-23 02:34
@mattsse Results generally look better (a lot more tests passing!). One last request if possible. Any way for us to also do the original solution of 

1. specifying the timeout seconds 
2. maybe specifying number of retries (not as important).

I think being able to specify the timeout would be useful in general. Maybe we only care about the retries and not so much about the timeout threshold, e.g 100s timeout seems long when that request itself might just be botched, and we only care about retrying it.

**Comment by mattsse** [comment] 2022-08-23 15:46
agreed, will definitely add this as a config option

will close this and track separately

**Closed by mattsse** 2022-08-23 15:46 UTC
Labels: T-bug, C-anvil

**Comment by andy2020star** [comment] 2024-02-01 19:33
curl -L https://foundry.paradigm.xyz | bash
foundryup
