### ISSUE TITLE
feat: `forge test -vvv` Add the line of the test in the Traces

### ISSUE THREAD

**Issue by Strapontin** [foundry-rs/foundry#8772] opened 2024-08-28 13:13 UTC
It would be so useful and reduce a lot of debugging time to have the line of executed instructions in the Traces when running tests.

**Comment by onbjerg** [comment] 2024-08-29 12:12
This is the wrong repo for feature requests, moved it to the appropriate one:)

**Comment by zerosnacks** [comment] 2024-09-03 09:03
Marking as duplicate of https://github.com/foundry-rs/foundry/issues/2328

**Closed by zerosnacks** 2024-09-03 09:03 UTC
