### ISSUE TITLE
`cast run --debug` exits with a panic when running Seaport transactions

### ISSUE THREAD

**Issue by jameswenzel** [foundry-rs/foundry#5227] opened 2023-06-27 00:45 UTC
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

cast 0.2.0 (2e18681 2023-06-26T00:15:26.624789000Z)

### What command(s) is the bug in?

cast run --debug

### Operating System

macOS (Apple Silicon)

### Describe the bug

Calling `cast run --debug` on Seaport transactions, when it does not result in a compilation error (#5225), results in a panic. Possibly related to #5224.

[Seaport 1.5](https://etherscan.io/address/0x00000000000000ADc04C56Bf30aC9d3c0aAF14dC):
```bash
❯ cast run 0x4ef8d57902b8b8913774bf796548d33ad63e449d41fb34f9eab131bbf030d740 --debug
Executing previous transactions from the block.
Compiling: Seaport 0x00000000000000adc04c56bf30ac9d3c0aaf14dc
Compiling: OperatorFilterRegistry 0x000000000000aaeb6d7670e522a718067333cd4e
Compiling: PayableProxy 0x0000a26b00c1f0df003000390027140000faa719
Compiling: Conduit 0x1e0049783f008a0085193e00003d00cd54003c71
Compiling: OrangApes 0x20be20060a10c34f381059200e000d8ccf465bb5
The application panicked (crashed).
Message:  there should be a contract with bytecode
Location: /Users/runner/work/foundry/foundry/common/src/compile.rs:418

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
[1]    66651 abort      cast run 0x4ef8d57902b8b8913774bf796548d33ad63e449d41fb34f9eab131bbf030d740 
```

From what I recall, [Seaport 1.4](0x00000000000001ad428e4906ae43d8f9852d0dd6) also has this issue, but it's hard to track down a tx that doesn't result in the compiler error reported in #5225. 

[Seaport 1.1](https://https://etherscan.io/address/0x00000000006c3852cbEf3e08E8dF289169EdE581)  does not seem to have this issue:
```bash
❯ cast run --debug 0x6adaa4083db30a07e616cd57403cc5282915de6706265c7f519c2035018d1599
Executing previous transactions from the block.
Compiling: Seaport 0x00000000006c3852cbef3e08e8df289169ede581
```

**Comment by Evalir** [comment] 2023-07-18 21:48
Closed by #5393 — could not reproduce anymore!

**Closed by Evalir** 2023-07-18 21:48 UTC
Labels: T-bug
