### ISSUE TITLE
vm.writeLine write six lines at a time

### ISSUE THREAD

**Issue by john-starry** [foundry-rs/foundry#3069] opened 2022-09-03 09:37 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (4b9cca1 2022-09-03T00:07:15.538624Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

<img width="719" alt="image" src="https://user-images.githubusercontent.com/106139201/188264882-d86e7d4a-9a19-47ce-88f8-3cf8db57b059.png">

after `forge script script/ReadLine.s.sol`, generate six lines

<img width="260" alt="image" src="https://user-images.githubusercontent.com/106139201/188264935-e88861e5-ae1e-48a6-9a9c-1cf6caae7b2d.png">

**Comment by mds1** [comment] 2022-09-03 18:49
Was able to reproduce this, though for me it was written 5 times, not 6. @shekhirin @joshieDo Guessing this may be because the script file is executed multiple times? But I don't think it executes 5-6 times

**Comment by shekhirin** [comment] 2022-09-04 11:36
tracked the root cause of this behaviour down to this:
https://github.com/foundry-rs/foundry/blob/1c415857dd7b617190834dbcb361506f6143fed4/cli/src/cmd/forge/script/runner.rs#L217-L233

**Comment by shekhirin** [comment] 2022-09-05 17:11
@john-starry @mds1 should be fixed on latest master!

**Closed** 2022-09-05 20:39 UTC
Labels: T-bug, C-forge, Cmd-forge-script
