### ISSUE TITLE
deployCode errors (did not match any variant of untagged enum Bytecode)

### ISSUE THREAD

**Issue by davidbrai** [foundry-rs/foundry#6815] opened 2024-01-16 11:58 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (24abca6 2024-01-16T00:22:43.818205838Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

The following code:
```
address d = deployCode(
    './foundry-out/NounsDescriptorV2.sol/NounsDescriptorV2.json',
    abi.encode(address(0), address(0))
);
```

fails with the following error:
```
[FAIL. Reason: setup failed: data did not match any variant of untagged enum Bytecode at line 1 column 34294] setUp() (gas: 0)
```

I've attached the json file.

[NounsDescriptorV2.json](https://github.com/foundry-rs/foundry/files/13949468/NounsDescriptorV2.json)

**Comment by mattsse** [comment] 2024-01-16 12:33
the issue here is that your bytecode is still unlinked

I think we should add support for linking bytecode via cheatcodes here

**Comment by davidbrai** [comment] 2024-01-16 13:29
@mattsse thanks for the quick diagnosis!

any estimate on when support for linking bytecode will be available?
any workaround we can use in the meantime?

**Comment by mattsse** [comment] 2024-01-16 13:44
> any estimate on when support for linking bytecode will be available?

just checked this is a known feature request, can try to bump prio for this https://github.com/foundry-rs/foundry/issues/6120

workaround would probably be to deploy the linked library first then replace in the code, or do this via an ffi command

**Comment by DaniPopes** [comment] 2024-01-19 13:43
Closing as duplicate of https://github.com/foundry-rs/foundry/issues/6120.

**Closed by DaniPopes** 2024-01-19 13:43 UTC
Labels: T-bug
