### ISSUE TITLE
Incorrect block.number in invariant tests

### ISSUE THREAD

**Issue by 0xmikko** [foundry-rs/foundry#5795] opened 2023-09-07 08:29 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (dbfd8d9 2023-09-06T12:58:39.679860620Z)

### What command(s) is the bug in?

forge t

### Operating System

Linux

### Describe the bug

I have a function which behavior depends on `block.number`. It could not be called twice for one block. For invariant test, I added a handler with function:

```
vm.roll(block.number+1);
testFunction();
```
And it reverts! Furthermore, it's impossible to get stacktrace when it happened.

Then, I add a storage variable to handler contract `blockNum` and change the code into:

```
vm.roll(++blockNum);
testFunction();
```
This code doesn't revert.

So, it seems there is race condition or incorrect mutex for block.number which allow to change it during the parrallel execution

**Comment by simplyoptimistic** [comment] 2023-09-08 23:34
I believe this is a duplicate of this [issue](https://github.com/foundry-rs/foundry/issues/3005). At the moment, state changes are not persisted between tests, which means changes to `block.timestamp` or `block.number` won't persist. You have already figured out the workaround for now which is to persist the state and warp/roll to it. See this [comment](https://github.com/foundry-rs/foundry/issues/4994#issuecomment-1618329347) for a more complete solution.

**Comment by Evalir** [comment] 2023-09-08 23:55
Indeed @simplyoptimistic — this is a duplicate of #3005 and a feature that adds persisting of block-related values will soon be added. Thanks!

**Closed by Evalir** 2023-09-08 23:55 UTC
Labels: T-bug
