### ISSUE TITLE
startPrank does not correctly mock msg.sender when calling a public library from a script

### ISSUE THREAD

**Issue by Kooshaba** [foundry-rs/foundry#4266] opened 2023-02-03 13:32 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (6157d4a 2023-02-03T00:05:03.034611Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

I've created a reproduction here: https://github.com/Kooshaba/forge_bug_repro

It uses an ownable storage contract called by a library from a script. There are two functions in the library: one public, one internal. When using `startPrank` and calling the storage contract via the public method, the `msg.sender` is the address of the library. When using the internal method, it correctly mocks the `msg.sender` to be the pranked address.

**Comment by Kooshaba** [comment] 2023-04-06 15:25
bump this is still ruining my life

**Comment by DaniPopes** [comment] 2023-04-06 21:42
This is not exclusive to scripts: calling a library's public function will invoke a `delegatecall` which sets the `msg.sender` to the test contract's address. I believe this is expected? cc @mattsse

**Comment by mattsse** [comment] 2023-04-07 10:01
I'm not really familiar with how prank is supposed to behave here

cc @mds1

**Comment by mds1** [comment] 2023-04-07 13:21
Expanding on what @DaniPopes said:
- The internal method works because the code gets inlined, so it's as if that logic lived directly in your script. As a result, the `prank` takes place on the `_storage.set` call
- The public method delegatecalls to the function. While this should have the same effect in solidity since it preserves context, I believe this doesn't work with `prank` because delegatecalls change the depth of execution, so the `_storage.set` call happens at a different depth, and as a result the prank does not occur in the delegatecall contract.

I'd recommend always using internal library functions unless you have a reason to use public (i.e. deploying a contract to production, using `public` library methods can shrink code size). But for tests/scripts, you can always use internal

**Comment by zerosnacks** [comment] 2024-06-28 14:36
Marking as resolved by https://github.com/foundry-rs/foundry/issues/4266#issuecomment-1500284318 as it is expected behavior

**Closed by zerosnacks** 2024-06-28 14:36 UTC
Labels: T-bug
