### ISSUE TITLE
a bug

### ISSUE THREAD

**Issue by JameWade** [foundry-rs/foundry#4696] opened 2023-04-05 09:03 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### Operating System

Windows

### Describe the bug

![image](https://user-images.githubusercontent.com/47301518/230034126-aa57fe2c-90fe-47f2-89a6-f7ff5019e305.png)

**Comment by mattsse** [comment] 2023-04-05 09:27
do you have local node running at 7545?

**Comment by Evalir** [comment] 2023-06-16 06:12
Could not reproduce—seems to have been fixed in the past few months.

**Closed by Evalir** 2023-06-16 06:12 UTC
Labels: T-bug
