### ISSUE TITLE
Forge Remappings Path Issue

### ISSUE THREAD

**Issue by adamxyzxyz** [foundry-rs/foundry#4108] opened 2023-01-17 14:22 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (b2baca3 2023-01-15T00:04:32.877705Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

I am having an issue when running forge test with specified remappings. The remapping in my root directory for solmate is as such:

solmate/=lib/solmate/

However, I rely on another submodule, that has it's own remapping of solmate, which is like this:

solmate/=lib/solmate/src

Since the lib I use is mapped to the remapping above, my tests will not run, because forge is trying to apply my remappings to the files inside lib. 

Is there an option to exclude certain paths from the remappping? How can i resolve this?

**Comment by adamxyzxyz** [comment] 2023-01-17 16:12
can i tell foundry to ignore my lib/  folder?

**Comment by MathisGD** [comment] 2023-01-24 09:10
There is a workaround for this: use relative path in either your root project or in the dependency, instead of absolute path with remapping.

**Comment by PaulRBerg** [comment] 2023-03-16 17:18
This issue is a potential duplicate of https://github.com/foundry-rs/foundry/issues/3440.

**Comment by zerosnacks** [comment] 2024-06-28 13:20
Closing as duplicate of #3440

**Closed by zerosnacks** 2024-06-28 13:20 UTC
Labels: T-bug, C-forge, A-config
