### ISSUE TITLE
Compilaiton failure with libs imported via node_modules

### ISSUE THREAD

**Issue by wighawag** [foundry-rs/foundry#1801] opened 2022-06-01 10:40 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [x] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (8216a10 2022-06-01T00:04:28.26657712Z)

### What command(s) is the bug in?

forge build

### Operating System

Linux

### Describe the bug

my foundry.toml
```
[default]
src = 'src'
out = 'out'
libs = ['lib', 'node_modules']
```
When I do  `forge build` I get the following error

It seems forge is failing to import relative import inside libs

```
Error: 
   0: Compiler run failed
      node_modules/@uniswap/v2-core/contracts/UniswapV2ERC20.sol:3:1: ParserError: Source "node_modules/@uniswap/v2-core/contracts/interfaces/IUniswapV2ERC20.sol" not found: File outside of allowed directories.
      import './interfaces/IUniswapV2ERC20.sol';
      ^----------------------------------------^
      

      node_modules/@uniswap/v2-core/contracts/UniswapV2ERC20.sol:4:1: ParserError: Source "node_modules/@uniswap/v2-core/contracts/libraries/SafeMath.sol" not found: File outside of allowed directories.
      import './libraries/SafeMath.sol';
      ^--------------------------------^
      

      error[6275]: ParserError: Source "node_modules/hardhat-deploy/solc_0.8/diamond/libraries/LibDiamond.sol" not found: File outside of allowed directories.
       --> node_modules/hardhat-deploy/solc_0.8/diamond/UsingDiamondOwner.sol:4:1:
        |
      4 | import "./libraries/LibDiamond.sol";
        | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      

      error[6275]: ParserError: Source "node_modules/@uniswap/v2-core/contracts/interfaces/IUniswapV2Factory.sol" not found: File outside of allowed directories.
       --> src/conquest_token/LiquidityEngine.sol:6:1:
        |
      6 | import "@uniswap/v2-core/contracts/interfaces/IUniswapV2Factory.sol";
        | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      
   0: 

Location:
   cli/src/compile.rs:149

```

**Comment by mattsse** [comment] 2022-06-01 10:48
can you please try with an additional `lib/=lib/` remapping? perhaps related to #1797

**Comment by wighawag** [comment] 2022-06-01 11:23
same issue with `remappings = ['node_modules/=node_modules/']`

Repo is not public, I could try to extract these failing scenario though

**Comment by mattsse** [comment] 2022-06-01 11:30
what does `forge remappings` give you?

I spot 

> File outside of allowed directories.

there's a `allow_paths=[]` setting in the toml where you can set the paths that should be allowed, but I wonder why it's not set by default hmm

**Comment by wighawag** [comment] 2022-06-01 12:55
with the `'node_modules/=node_modules/'`

`forge remappings` gives me :

```
forge-std/=lib/forge-std/src/
ds-test/=lib/forge-std/lib/ds-test/src/
```

Actually, I am in a monorepo managed by pnpm, I wonder if the issue is that forge do not follow the symlinks properly

**Comment by mattsse** [comment] 2022-06-01 12:59
that could be it.

curios why no node_modules remappings are detected even though, `node_modules` is added in `libs`

is the `node_modules` folder in the same dir as `foundry.toml`?

**Comment by gakonst** [comment] 2022-06-02 04:18
is this by any chance fixed on latest master / tonight's release?

**Comment by onbjerg** [comment] 2022-07-02 15:15
I can't reproduce this, so I'm going to close the issue. Let us know if you still have the issue @wighawag

**Closed by onbjerg** 2022-07-02 15:15 UTC
Labels: T-bug, C-forge, Cmd-forge-build

**Comment by oishun1112** [comment] 2022-07-29 17:29
I've got same issue here

**Comment by gakonst** [comment] 2022-07-29 17:33
@oishun1112 do you have a repro?

**Comment by oishun1112** [comment] 2022-07-29 17:52
> @oishun1112 do you have a repro?
I had, but somehow I could solve it.

What I did is
```
rm /Users/oishun/.cargo/bin/cast
```
then
```
foundry up
```

Apparently, I had two Foundry in my environment..? I don't know

It still fails to compile directly, but remapping is working.
```
[⠊] Compiling...
[⠒] Unable to resolve import: "node_modules/@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol" with remappings:
        @aave/=/Users/oishun/InsureDAO/depeg/node_modules/@aave/
        @ensdomains/=/Users/oishun/InsureDAO/depeg/node_modules/@ensdomains/
...

[⠊] Compiling 66 files with 0.8.10
[⠆] Solc 0.8.10 finished in 4.72s

```

**Comment by mattsse** [comment] 2022-07-29 20:53
looks like you're just missing remappings for oz

it only lists two remappings

> @aave/=/Users/oishun/InsureDAO/depeg/node_modules/@aave/
> @ensdomains/=/Users/oishun/InsureDAO/depeg/node_modules/@ensdomains/

and the import path is 

"node_modules/@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol"

try adding remappings for openzeppelin

what does `forge remappings` print?

**Comment by oishun1112** [comment] 2022-07-31 05:23
```
forge remappings
```
prints
```
@aave/=node_modules/@aave/
@ensdomains/=node_modules/@ensdomains/
@openzeppelin/=node_modules/@openzeppelin/
@uniswap/=node_modules/@uniswap/
base64-sol/=node_modules/base64-sol/
ds-test/=lib/forge-std/lib/ds-test/src/
eth-gas-reporter/=node_modules/eth-gas-reporter/
forge-std/=lib/forge-std/src/
hardhat/=node_modules/hardhat/
```

foundry.toml
```
libs = ['node_modules', 'lib']
```
