### ISSUE TITLE
Unable to verify contract when deployed with a script calling a FactoryContract

### ISSUE THREAD

**Issue by gperezalba** [foundry-rs/foundry#2361] opened 2022-07-18 10:11 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (3c49efe 2022-07-14T00:14:23.444892Z)

### Operating System

macOS (Apple Silicon)

### Describe the bug

When a contract is deployed with a script through a call to a FactoryContract it doesnt verify the deployed contract (including the flags to the command to run the script the same way I do when I deploy the FactoryContract). 

Public repo: https://github.com/gperezalba/foundry-factory-verify

Steps to reproduce:
- `npm run deploy:goerli`
- `npm run create-token:goerli`

It doesnt even try to verify...

Thanks

**Comment by onbjerg** [comment] 2022-07-19 12:10
Duplicate of #1893

**Closed by onbjerg** 2022-07-19 12:10 UTC
Labels: T-bug
