### ISSUE TITLE
"forge test" throws error when for an underlying delegate call from a static call

### ISSUE THREAD

**Issue by sukanyaparashar** [foundry-rs/foundry#5757] opened 2023-08-30 23:49 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

**ISSUE**

I am trying to run `forge test` on NEON Devnet to get Chainlink price feed. But I am getting an error `[FAIL. Reason: toUint8_outOfBounds]`.

This is the test file:
```
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.21;

import "forge-std/Test.sol";

interface AggregatorV3Interface {
    function decimals() external view returns (uint8);

    function description() external view returns (string memory);

    function version() external view returns (uint256);

    function getRoundData(
        uint80 _roundId
    )
        external
        view
        returns (
            uint80 roundId,
            int256 answer,
            uint256 startedAt,
            uint256 updatedAt,
            uint80 answeredInRound
        );

    function latestRoundData()
        external
        view
        returns (
            uint80 roundId,
            int256 answer,
            uint256 startedAt,
            uint256 updatedAt,
            uint80 answeredInRound
        );
}

contract ChainlinkTestTest is Test {

    AggregatorV3Interface public priceFeed;

    function setUp() public {
        priceFeed = AggregatorV3Interface(0xec852B2A009f49E4eE4ffEddeDcF81a1AD1bbD6d);
    }

    function testPriceFeed() public {
        (, int256 price, , , ) = priceFeed.latestRoundData();
        emit log_named_int("Price:", price);
    }

}
```
And `0xec852B2A009f49E4eE4ffEddeDcF81a1AD1bbD6d` is the Chhainlink price feed on Neon Devnet.

When `forge test` is run, the following error is thrown:
```
$ forge test --rpc-url $RPC_URL -vvvvv
[⠰] Compiling...
No files changed, compilation skipped

Running 1 test for test/ChainlinkTest.t.sol:ChainlinkTestTest
[FAIL. Reason: toUint8_outOfBounds] testPriceFeed() (gas: 17231)
Traces:
  [22269] ChainlinkTestTest::setUp() 
    └─ ← ()

  [17231] ChainlinkTestTest::testPriceFeed() 
    ├─ [12148] 0xec852B2A009f49E4eE4ffEddeDcF81a1AD1bbD6d::latestRoundData() [staticcall]
    │   ├─ [6928] 0xb4820dC05E23d26FfE290Ce82DA94c894903C034::getLatestRound(54711267442576681404593257684989943639952621180004110670920145519824699960726 [5.471e76]) [delegatecall]
    │   │   ├─ [0] 0xff00000000000000000000000000000000000002::2b3c8322(78f57ae1195e8c497a8be054ad52adf4c8976f8436732309e22af7067724ad96000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000c0) [staticcall]
    │   │   │   └─ ← ()
    │   │   ├─ [0] 0xff00000000000000000000000000000000000002::43ca5161(78f57ae1195e8c497a8be054ad52adf4c8976f8436732309e22af7067724ad96000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000c0) [staticcall]
    │   │   │   └─ ← ()
    │   │   └─ ← "toUint8_outOfBounds"
    │   └─ ← "toUint8_outOfBounds"
    └─ ← "toUint8_outOfBounds"

Test result: FAILED. 0 passed; 1 failed; 0 skipped; finished in 31.08s
Ran 1 test suites: 0 tests passed, 1 failed, 0 skipped (1 total tests)

Failing tests:
Encountered 1 failing test in test/ChainlinkTest.t.sol:ChainlinkTestTest
[FAIL. Reason: toUint8_outOfBounds] testPriceFeed() (gas: 17231)

Encountered a total of 1 failing tests, 0 tests succeeded
```
However if I call the function `latestRoundData()` with `cast call` command, it returns the correct data -
```
$ cast call 0xec852B2A009f49E4eE4ffEddeDcF81a1AD1bbD6d --rpc-url $RPC_URL "latestRoundData()"                                                                  1 ↵
0x00000000000000000000000000000000000000000000000000000000008748f7000000000000000000000000000000000000000000000000000000007c6517c00000000000000000000000000000000000000000000000000000000064efd54e0000000000000000000000000000000000000000000000000000000064efd54e00000000000000000000000000000000000000000000000000000000008748f7
```
Any help will be highly appreciated. Thanks!

**Comment by sukanyaparashar** [comment] 2023-09-11 11:57
Hello everyone! Any update on this issue?

**Comment by mds1** [comment] 2023-09-11 14:47
This seems like a bug in your code. That `toUint8_outOfBounds` error is not thrown by forge—it is thrown by a solidity method called `toUint8` that casts some input to a uint8. The value you are trying to cast to a uint8 is too big to fit into a uint8, so it throws that error. Going to close this since it's not a forge issue, but if you are stuck, please provide a repo or full code snippet to reproduce the error with

**Closed by mds1** 2023-09-11 14:47 UTC
Labels: T-bug

**Comment by sukanyaparashar** [comment] 2023-09-11 14:53
Thanks for the reply, @mds1 . I am just not able to understand why `cast call` command doesn't throw error for the same function call but `forge test` does.

**Comment by mds1** [comment] 2023-09-11 14:55
Because `cast call` is printing the raw return data without decoding it. That return data includes multiple values. One of those values is larger than a uint8, but your solidity code is trying to decode it into a uint8
