### ISSUE TITLE
Test suite is stuck during execution when some of the tested method has infinite loop

### ISSUE THREAD

**Issue by Bolee95** [foundry-rs/foundry#5484] opened 2023-07-27 16:34 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

I was trying to run write and run some unit tests for the custom token when I got an issue that tests never finish. I tried to find the reason for this empirically, by commenting out the newly added tests. I found out that the following method was the problem, without previously running it after deployment:

```solidity
    function ownerOfBatch(uint256[] calldata ids) external view returns (address[] memory owners) {
        owners = new address[](ids.length);
        for (uint256 i; i < ids.length; ) {
            owners[i] = _owners[ids[i]];
        }
    }
```

Test for this method was:
```solidity
 function test_ownersOf_userTokenOwner() public {
        address to = makeAddr("to");
        erc1155d.exposed_mintBatch(to, ArrayUtils._asUint256Array(1, 1), "");

        assertEq(
            erc1155d.ownerOfBatch(ArrayUtils._asUint256Array(1, 1)),
            ArrayUtils._asAddressArray(1, to)
        );
    }
```

As can be seen above, this is an infinite loop, as `i` is never incremented. When I tried to run it locally after deployment to a localhost, the output was the following:

```bash
 cast call 0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512 "ownerOfBatch(uint256[])" [1]
Error: 
(code: -32603, message: EVM error OutOfGas, data: None)
```

This is working as expected, the transaction will eventually run out of gas, but following this error, I would expect the test to revert in case the transaction runs out of gas for whatever reason.
Without a revert, I assume it would be really hard to find what causes the test suite to be stuck.

**Comment by zerosnacks** [comment] 2024-07-03 11:56
Unable to reproduce, now throws:

on

```
    function infiniteLoop() public {
        while (true) {
            number++;
        }
    }
```

```
    function test_InfiniteLoop() public {
        counter.infiniteLoop();
    }
```

```
  [1056943993] CounterTest::test_InfiniteLoop()
    ├─ [1056936711] Counter::infiniteLoop()
    │   └─ ← [OutOfGas] EvmError: OutOfGas
    └─ ← [Revert] EvmError: Revert
```

Marking as resolved

**Closed by zerosnacks** 2024-07-03 11:56 UTC
Labels: T-bug
