### ISSUE TITLE
Script: support matching --sig argument with function hex selector

### ISSUE THREAD

**Issue by timurguvenkaya** [foundry-rs/foundry#4325] opened 2023-02-10 15:16 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (249538f 2023-02-10T00:23:08.24269Z)

### What command(s) is the bug in?

forge script DeployTest -s d61d5b11 --broadcast -vvv --force

### Operating System

macOS (Intel)

### Describe the bug

I'm trying to do multichain deployment using CREATE2 with forge script

I use helper which takes fork id and deploys everything. 

When I run everything I get **Script ran successfully** with **Sig is invalid** during the broadcast.

I'm using anvil on different ports & different forks to test deployment locally.
 
Example code 
```solidity
// SPDX-License-Identifier: MIT
pragma solidity 0.8.18;

import {Script, StdUtils} from "forge-std/Script.sol";

import {console2} from "forge-std/console2.sol";

contract TestContract {
    function test() public view returns (uint256) {
        return 1;
    }
}

contract DeployTest is Script {
    bytes32 internal constant TEST_SALT = bytes32(uint256(3));

  uint256 public local = vm.createFork("http://127.0.0.1:8545");
  uint256 public localBSCTest = vm.createFork("http://127.0.0.1:8546");
        
    address create2addrSBT =
        computeCreate2Address(
            TEST_SALT,
            hashInitCode(type(TestContract).creationCode)
        );

    function deployTest() public {
        forkDeployTest(local);
        forkDeployTest(localBSCTest); 
    }

    function forkDeployTest(uint256 fork) public {
        uint256 deployerPrivateKey;
        address owner;

        deployerPrivateKey = vm.envUint("LOCAL_DEPLOYER_KEY");
        owner = vm.envAddress("LOCAL_SAFE_OWNER");

        console2.log("Deploying TestContract on fork", fork);

        vm.selectFork(fork);
        vm.startBroadcast(deployerPrivateKey);

        TestContract testContract = new TestContract{salt: TEST_SALT}();

        console2.log("Test Contract address", address(testContract));

        require(
            create2addrSBT == address(testContract),
            "Address mismatch Test Contract"
        );

        vm.stopBroadcast();
    }
}

```

Anvil: 

```
anvil --fork-url https://rpc.ankr.com/eth_goerli
anvil --fork-url https://rpc.ankr.com/bsc_testnet_chapel -p 8546
```

Output: 
```
Script ran successfully.
Gas used: 151175

== Logs ==
  Deploying TestContract on fork 0
  Test Contract address 0x4C04E31cd475dF0135ceaE24D20Fb3F25b9A472f
  Deploying TestContract on fork 1
  Test Contract address 0x4C04E31cd475dF0135ceaE24D20Fb3F25b9A472f
Multi chain deployment is still under development. Use with caution.

## Setting up (2) EVMs.

==========================

Chain 5

Estimated gas price: 3.049130518 gwei

Estimated total gas used for script: 109692

Estimated amount required: 0.000334465224780456 ETH

==========================

==========================

Chain 97

Estimated gas price: 2 gwei

Estimated total gas used for script: 109692

Estimated amount required: 0.000219384 ETH

==========================
Error:
Sig is invalid.
```

It works when I only leave one fork in **deployTest()** or run manually forkDeployTest() twice for different forks

Not sure whether the issue is on my end

**Comment by mattsse** [comment] 2023-02-10 15:30
@joshieDo this happens when the signature does not contain a `(`, unclear what's going on here or what the assumptions wrt sig are here.

ptal

**Comment by timurguvenkaya** [comment] 2023-02-11 13:41
Rerun with https://github.com/foundry-rs/foundry/pull/4326

It returns 

**Failed to compute file name: Signature d61d5b11 is invalid.**

**Comment by mattsse** [comment] 2023-02-11 13:56
ah that's the raw hex signature of the function.
I see, we expect a name like `run()` because this is generally easier to use, but we def need to support the raw hex sig as well.

can you please try using `deployTest()`

**Comment by mattsse** [comment] 2023-02-11 13:57
> It works if I change deployTest to run

great so this is indeed a bug with how we match signatures.

**Comment by timurguvenkaya** [comment] 2023-02-11 14:03
Yep 
It also works if I use deployTest() directly 

`forge script DeployTest -s "deployTest()" --broadcast -vvv --force
`

**Comment by klkvr** [comment] 2024-07-01 21:34
This was likely fixed with script refactoring. Can't reproduce anymore

**Closed by klkvr** 2024-07-01 21:34 UTC
Labels: T-bug, C-forge, Cmd-forge-script
