### ISSUE TITLE
foundry not able to deserialize "eth_getBlockByNumber"

### ISSUE THREAD

**Issue by ClementWalter** [foundry-rs/foundry#5303] opened 2023-07-05 16:12 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (bf56869 2023-07-05T00:05:02.811991000Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

When trying to run my forge script against a RPC client I am developing, I have this error

```
[⠢] Compiling...
No files changed, compilation skipped
The application panicked (crashed).
Message:  Could not instantiate forked environment:
Could not instantiate forked environment with fork url: http://127.0.0.1:3030

Context:
- Error #0: Failed to get block 2093
- Error #1: Deserialization Error: invalid length 64, expected a (both 0x-prefixed or not) hex string or byte array containing between (0; 8] bytes at line 1 column 1235. Response: {"hash":"0x02be205c992841dadb8308f1d1fa29f4b504d4c6ddc675255884597483d39aca","parentHash":"0x01e20daea836467b10e1b1e050f1a7dcfe9cc35c6935edb8334cc53209002b03","sha3Uncles":"0x01e20daea836467b10e1b1e050f1a7dcfe9cc35c6935edb8334cc53209002b03","miner":"0x000000000000000000000000000000000000dead","stateRoot":"0x0000000000000000000000000000000000000000000000000000000000000000","transactionsRoot":"0x0000000000000000000000000000000000000000000000000000000000000000","receiptsRoot":"0x0000000000000000000000000000000000000000000000000000000000000000","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","difficulty":"0x0000000000000000000000000000000000000000000000000000000000000000","number":"0x000000000000000000000000000000000000000000000000000000000000082d","gasLimit":"0x00000000000000000000000000000000000000000000000000000000000f4240","gasUsed":"0x000000000000000000000000000000000000000000000000000000000007a120","timestamp":"0x0000000000000000000000000000000000000000000000000000000064a595de","extraData":"0x30783030","mixHash":"0x0000000000000000000000000000000000000000000000000000000000000000","nonce":"0x0000000000000000","baseFeePerGas":"0x0000000000000000000000000000000000000000000000000000000000000001","withdrawalsRoot":"0x0000000000000000000000000000000000000000000000000000000000000000","uncles":[],"transactions":[],"size":"0x00000000000000000000000000000000000000000000000000000000000f4240","withdrawals":[]}
Location: /Users/runner/work/foundry/foundry/evm/src/executor/opts.rs:64

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry
```

output json, formatted, looks like
```
{
  "hash": "0x02be205c992841dadb8308f1d1fa29f4b504d4c6ddc675255884597483d39aca",
  "parentHash": "0x01e20daea836467b10e1b1e050f1a7dcfe9cc35c6935edb8334cc53209002b03",
  "sha3Uncles": "0x01e20daea836467b10e1b1e050f1a7dcfe9cc35c6935edb8334cc53209002b03",
  "miner": "0x000000000000000000000000000000000000dead",
  "stateRoot": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "transactionsRoot": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "receiptsRoot": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "difficulty": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "number": "0x000000000000000000000000000000000000000000000000000000000000082d",
  "gasLimit": "0x00000000000000000000000000000000000000000000000000000000000f4240",
  "gasUsed": "0x000000000000000000000000000000000000000000000000000000000007a120",
  "timestamp": "0x0000000000000000000000000000000000000000000000000000000064a595de",
  "extraData": "0x30783030",
  "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "nonce": "0x0000000000000000",
  "baseFeePerGas": "0x0000000000000000000000000000000000000000000000000000000000000001",
  "withdrawalsRoot": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "uncles": [],
  "transactions": [],
  "size": "0x00000000000000000000000000000000000000000000000000000000000f4240",
  "withdrawals": []
}
```

Comparing with a block returned by, for example composer.alchemy

```
{
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "baseFeePerGas": "0xc5ecd2c32",
    "difficulty": "0x0",
    "extraData": "0x6265617665726275696c642e6f7267",
    "gasLimit": "0x1c9c380",
    "gasUsed": "0x161a3a8",
    "hash": "0xdd7b530a14c10d48e6160cde468002a6a4207d9a012e34bf9cb773c9f8c74583",
    "logsBloom": "0x5c61c5a0d0a54031951ee3aaa310c23b80b70019c9210006217b0c78b622ec74824054a092120634a400591023406bd44ab50212c952b1207a9e3005046a8901d068a8e9034a282a59a2531922b58e6c14800a818546088088104079a7305884f248001842b20a0f1484386d1828a9f31078ad109807acb012c96578022cd7c090008b46a38cd1500849a10a1012200a120066a98900546892877359123225888a2d4e4ad685654a84994df33e858605547089246bd76ad300f8222698e6050703504016e300144260200e0a0bfd7ca3bc4dfbc104a8001c02c0452a71a4694c1e9aa2192082908e36069798d9a8009862661847449f615274008983cd941c45",
    "miner": "0x388c818ca8b9251b393131c08a736a67ccb19297",
    "mixHash": "0xe91b55ffb5242ba3a00980b7e734a520e7cb27b8064ca1be156b2f104a1f5a3e",
    "nonce": "0x0000000000000000",
    "number": "0x10cfe7b",
    "parentHash": "0xf3837618456a18bd79408b53ba83a5dd31dda0e41f005633192d2ddaab62b704",
    "receiptsRoot": "0xaca42ce0488b812962863848644d0693ad14aaa4abb6afd53b0ece5212a7d8c4",
    "sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
    "size": "0xa898",
    "stateRoot": "0x96856a08023954bebb1794a16024916f5c43ca309507ebaadf6cd46eb1a6e5d7",
    "timestamp": "0x64a59697",
    "totalDifficulty": "0xc70d815d562d3cfa955",
    "transactions": [],
    "transactionsRoot": "0xc2d26183bbf29a903e3312a2f52f955c0e1ad59cc113c02e33317da759751e54",
    "uncles": [],
    "withdrawals": [],
    "withdrawalsRoot": "0xfcdfa75e476542c63a19555f368717eefcfecb63ee0cad42021334e0e4577498"
  }
}
```

I see that are few fiels that we return as U256/H256 while they are trimmed in composer. But we use reth types so I guess that it should work (see our client [here](https://github.com/kkrt-labs/kakarot-rpc/blob/main/crates/eth-rpc/src/eth_rpc.rs))

**Comment by Evalir** [comment] 2023-07-05 16:30
Hmm, i'm not sure I follow—the json output doesn't seem to be in JSON RPC format, which is a requirement to be able to parse these correctly.

**Comment by ClementWalter** [comment] 2023-07-05 19:50
@Evalir to be more accurate this is the log from our RPC:

```
2023-07-05T16:10:11.116936Z TRACE connection{remote_addr=127.0.0.1:50935 conn_id=17}:method_call{method="eth_getBlockByNumber"}: jsonrpsee_core::tracing: send="{\"jsonrpc\":\"2.0\",\"result\":{\"hash\":\"0x02be205c992841dadb8308f1d1fa29f4b504d4c6ddc675255884597483d39aca\",\"parentHash\":\"0x01e20daea836467b10e1b1e050f1a7dcfe9cc35c6935edb8334cc53209002b03\",\"sha3Uncles\":\"0x01e20daea836467b10e1b1e050f1a7dcfe9cc35c6935edb8334cc53209002b03\",\"miner\":\"0x000000000000000000000000000000000000dead\",\"stateRoot\":\"0x0000000000000000000000000000000000000000000000000000000000000000\",\"transactionsRoot\":\"0x0000000000000000000000000000000000000000000000000000000000000000\",\"receiptsRoot\":\"0x0000000000000000000000000000000000000000000000000000000000000000\",\"logsBloom\":\"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\",\"difficulty\":\"0x0000000000000000000000000000000000000000000000000000000000000000\",\"number\":\"0x000000000000000000000000000000000000000000000000000000000000082d\",\"gasLimit\":\"0x00000000000000000000000000000000000000000000000000000000000f4240\",\"gasUsed\":\"0x000000000000000000000000000000000000000000000000000000000007a120\",\"timestamp\":\"0x0000000000000000000000000000000000000000000000000000000064a595de\",\"extraData\":\"0x30783030\",\"mixHash\":\"0x0000000000000000000000000000000000000000000000000000000000000000\",\"nonce\":\"0x0000000000000000\",\"baseFeePerGas\":\"0x0000000000000000000000000000000000000000000000000000000000000001\",\"withdrawalsRoot\":\"0x0000000000000000000000000000000000000000000000000000000000000000\",\"uncles\":[],\"transactions\":[],\"size\":\"0x00000000000000000000000000000000000000000000000000000000000f4240\",\"withdrawals\":[]},\"id\":4}"
```

which reformatted is indeed
```
{
  "jsonrpc": "2.0",
  "result": {
    "hash": "0x02be205c992841dadb8308f1d1fa29f4b504d4c6ddc675255884597483d39aca",
    "parentHash": "0x01e20daea836467b10e1b1e050f1a7dcfe9cc35c6935edb8334cc53209002b03",
    "sha3Uncles": "0x01e20daea836467b10e1b1e050f1a7dcfe9cc35c6935edb8334cc53209002b03",
    "miner": "0x000000000000000000000000000000000000dead",
    "stateRoot": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "transactionsRoot": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "receiptsRoot": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "difficulty": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "number": "0x000000000000000000000000000000000000000000000000000000000000082d",
    "gasLimit": "0x00000000000000000000000000000000000000000000000000000000000f4240",
    "gasUsed": "0x000000000000000000000000000000000000000000000000000000000007a120",
    "timestamp": "0x0000000000000000000000000000000000000000000000000000000064a595de",
    "extraData": "0x30783030",
    "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "nonce": "0x0000000000000000",
    "baseFeePerGas": "0x0000000000000000000000000000000000000000000000000000000000000001",
    "withdrawalsRoot": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "uncles": [],
    "transactions": [],
    "size": "0x00000000000000000000000000000000000000000000000000000000000f4240",
    "withdrawals": []
  },
  "id": 4
}
```

but forge only returned in the log the `"result"`. See also this raw call with curl
<img width="711" alt="image" src="https://github.com/foundry-rs/foundry/assets/18620296/c1365c7d-d694-4520-919d-1d2e9a3de250">

**Comment by ClementWalter** [comment] 2023-07-05 19:54
can't we try just to send the payload to a integration test in forge?

**Comment by Evalir** [comment] 2023-07-05 20:55
Hmm right. I think what would help is rephrasing somewhat the issue—I don't think I understand exactly what's happening 😅  Could you please explain it again?

**Comment by jobez** [comment] 2023-07-10 01:23
Howdy, I debugged a bit further, we are essentially getting a deserialization error at this point in the `forge script` flow: https://github.com/foundry-rs/foundry/blob/8f20631932be893c3c5e4835077f8a722e14c037/evm/src/executor/fork/init.rs#L38

I was able to reproduce the error in deserializing a ethers-rs Block from a serialized reth RichBlock, see here: https://github.com/gakonst/ethers-rs/issues/2503

**Comment by mattsse** [comment] 2023-07-10 10:30
what's causing the serde error?

**Comment by mattsse** [comment] 2023-07-10 10:48
ah I see now what's happening.

what's the provider/client that returns this response?

because 
> "number":"0x000000000000000000000000000000000000000000000000000000000000082d"

violates the spec

the number must be a QUANTITY, meaning no leading zeros

**Comment by ClementWalter** [comment] 2023-07-10 11:52
linking the doc about [QUANTITIES](https://ethereum.org/en/developers/docs/apis/json-rpc/#quantities-encoding) for the record.

This object is returned by a current WIP implementation we're working on actually, see https://github.com/kkrt-labs/kakarot-rpc/blob/main/crates/eth-rpc/src/eth_rpc.rs

We use Reth types, and consequently the issue is probably related to Reth instead, we're digging into it.

Probably because Reth uses ruint https://github.com/recmo/uint/blob/35167fbf0406c8f925608225225f91f5612e371b/src/support/serde.rs#L73 while ethers-rs use https://github.com/paritytech/parity-common/tree/master/primitive-types

**Comment by mattsse** [comment] 2023-07-10 12:01
the ruint crate is still wip,

please use the patched crate until new release

**Comment by mattsse** [comment] 2023-07-10 12:39
closing this as well

**Closed by mattsse** 2023-07-10 12:39 UTC
Labels: T-bug

**Comment by jobez** [comment] 2023-07-10 12:41
Thank you for your help!
