### ISSUE TITLE
Get `No prank in progress to stop` on test run for `changePrank()`

### ISSUE THREAD

**Issue by vladikopl01** [foundry-rs/foundry#5622] opened 2023-08-14 10:07 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (dffdfde 2023-08-14T00:22:15.788827000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

Actually erroring started when I tried to use `changePrank()` function. For this kind of test:
```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity >=0.8.19 <0.9.0;

import "forge-std/Test.sol";
import { Events } from "../../utils/Events.sol";
import { Errors } from "src/libraries/Errors.sol";
import { Profiles } from "src/Profiles.sol"; 


contract Profiles_Test is Test, Events {
    Profiles internal ggProfilesContract;

    function setUp() internal {
        changePrank(makeAddr("Admin"));
        ggProfilesContract = new Profiles(makeAddr("Admin"));
    }
}
```

I get this kind of output for running tests with `forge test`:
```
2023-08-14T09:54:57.204116Z ERROR forge::runner: setUp failed reason="No prank in progress to stop" contract=0x7fa9385be102ac3eac297483dd6233d62b3e1496
2023-08-14T09:54:57.204116Z ERROR forge::runner: setUp failed reason="No prank in progress to stop" contract=0x7fa9385be102ac3eac297483dd6233d62b3e1496

Running 1 test for test/integration/basic/Quest.t.sol:Quest_Test
[FAIL. Reason: Setup failed: No prank in progress to stop] setUp() (gas: 0)
Test result: FAILED. 0 passed; 1 failed; 0 skipped; finished in 3.32ms

Running 1 test for test/integration/basic/QuestFactory.t.sol:QuestFactory_Test
[FAIL. Reason: Setup failed: No prank in progress to stop] setUp() (gas: 0)
Test result: FAILED. 0 passed; 1 failed; 0 skipped; finished in 3.29ms

Running 8 tests for test/integration/basic/BundleWallet.t.sol:BundleWallet_Test
[FAIL. Reason: No prank in progress to stop] test_AssociateWallet() (gas: 95076)
[FAIL. Reason: No prank in progress to stop] test_DisassociateWallet() (gas: 95165)
[FAIL. Reason: No prank in progress to stop] test_RevertAssociateWalletWhen_AlreadyAssociated() (gas: 92915)
[FAIL. Reason: No prank in progress to stop] test_RevertAssociateWalletWhen_WrongSecondaryWallet() (gas: 18049)
[FAIL. Reason: No prank in progress to stop] test_RevertAssociateWalletWhen_WrongSender() (gas: 18614)
[FAIL. Reason: No prank in progress to stop] test_RevertAssociateWalletWhen_WrongSignature() (gas: 22569)
[FAIL. Reason: No prank in progress to stop] test_RevertDisassociateWalletWhen_NotAssociated() (gas: 17055)
[FAIL. Reason: No prank in progress to stop] test_RevertDisassociateWalletWhen_WrongSender() (gas: 95077)
Test result: FAILED. 0 passed; 8 failed; 0 skipped; finished in 6.12ms
Ran 3 test suites: 0 tests passed, 10 failed, 0 skipped (10 total tests)

Failing tests:
Encountered 8 failing tests in test/integration/basic/BundleWallet.t.sol:BundleWallet_Test
[FAIL. Reason: No prank in progress to stop] test_AssociateWallet() (gas: 95076)
[FAIL. Reason: No prank in progress to stop] test_DisassociateWallet() (gas: 95165)
[FAIL. Reason: No prank in progress to stop] test_RevertAssociateWalletWhen_AlreadyAssociated() (gas: 92915)
[FAIL. Reason: No prank in progress to stop] test_RevertAssociateWalletWhen_WrongSecondaryWallet() (gas: 18049)
[FAIL. Reason: No prank in progress to stop] test_RevertAssociateWalletWhen_WrongSender() (gas: 18614)
[FAIL. Reason: No prank in progress to stop] test_RevertAssociateWalletWhen_WrongSignature() (gas: 22569)
[FAIL. Reason: No prank in progress to stop] test_RevertDisassociateWalletWhen_NotAssociated() (gas: 17055)
[FAIL. Reason: No prank in progress to stop] test_RevertDisassociateWalletWhen_WrongSender() (gas: 95077)

Encountered 1 failing test in test/integration/basic/Quest.t.sol:Quest_Test
[FAIL. Reason: Setup failed: No prank in progress to stop] setUp() (gas: 0)

Encountered 1 failing test in test/integration/basic/QuestFactory.t.sol:QuestFactory_Test
[FAIL. Reason: Setup failed: No prank in progress to stop] setUp() (gas: 0)

Encountered a total of 10 failing tests, 0 tests succeeded
```

I'm using 
- `forge-std` v1.3.0
- `forge` v0.2.0

I would appreciate any help to resolve this issue, Thanks!

**Comment by vladikopl01** [comment] 2023-08-14 11:12
An interesting thing is that this test is written by another dev in our repo, and he had not any problems with that. Any ideas why it could happen? 

As https://github.com/foundry-rs/foundry/issues/4835 suggests, could it be the difference in `forge` versioning?

**Comment by Evalir** [comment] 2023-08-14 14:19
It probably is forge versioning issues @vladikopl01 — for this use case I'd recommend using `vm.startPrank` which will work as you want.

Closing—not a bug, but expected behavior

**Closed by Evalir** 2023-08-14 14:19 UTC
Labels: T-bug
