### ISSUE TITLE
feat (cheatcode): ability to know whether broadcast mode is active (--broadcast)

### ISSUE THREAD

**Issue by wighawag** [foundry-rs/foundry#4798] opened 2023-04-22 06:31 UTC
### Component

Forge

### Describe the feature you would like

my tool [forge-deploy](https://github.com/wighawag/forge-deploy) read and write files to manage deployment data.

it currently do that in all context, even when there would be no need for it (`forge test`)

my tool would actually only need to write files if the execution of the deployment is going to be broadcasted

So for optimization purpose it would be great to be able to know whether `--broadcast` was specified

Proposal:

```
function isBroadcasting() external returns (bool);
```

**Comment by mds1** [comment] 2023-04-24 16:43
Seems like a duplicate of https://github.com/foundry-rs/foundry/issues/2900, so closing in favor of that one

**Closed by mds1** 2023-04-24 16:43 UTC
Labels: T-feature
