### ISSUE TITLE
feat(anvil): Set anvil fork cache location (`--cache-path`)

### ISSUE THREAD

**Issue by Szymx95** [foundry-rs/foundry#8654] opened 2024-08-13 09:48 UTC
### Component

Anvil

### Describe the feature you would like

Currently the cache location is fixed to `~/.foundry/anvil/rpc`. It would really simplify the workflow (for example for running fork tests on CI) if we could set custom directory for the cache location. This is related to #4989 however the issue was related to taking too much space.

Another use case would be to save cache on different drive without the need for symlinking.

**Comment by leovct** [comment] 2024-08-14 18:02
I'd like to work on this issue too.

**Comment by Akbar30Bill** [comment] 2024-08-15 15:54
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/foundry).

### My background and how it can be leveraged
I have experience with foundry tooling, and I recently began my journey with Rust. I believe this makes for an excellent opportunity to contribute to the development of blockchain tools.

### How I plan on tackling this issue
I would make the Anvil cache location configurable, with a default setting that points to `.foundry` if no specific location is provided.

**Comment by ScottyDavies** [comment] 2024-08-26 11:28
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/foundry).

### My background and how it can be leveraged
I am frontend developer with years of experience

### How I plan on tackling this issue
I would approach this issue with following steps

Understand Existing Cache Implementation:
Review Anvil codebase to identify where cache location is hardcoded then i assess dependencies and assumptions around cache location.
Design Custom Cache Location Feature:
I find best way to allow users to specify custom cache location (config, CLI, env).
Integrate custom location into Anvil's architecture, considering edge cases.
Implement Changes:
Add code to support custom cache location and update relevant parts of codebase to use new cache location then implement error handling and validation.
Update Configuration and CLI:
Modify Anvil config to include custom cache location option.
Update Anvil CLI to accept new cache location argument.
Document new configuration and CLI options.
Thoroughly Test New Functionality:
I will write unit and integration tests to verify custom cache location and then test in various scenarios, including CI and different drives.
Document the Changes:
Update Anvil and Foundry docs with custom cache location instructions.
Provide examples for common use cases.
Submit Pull Request:
Create PR detailing changes and rationale.
Collaborate with Foundry maintainers and community.

**Comment by gdnathan** [comment] 2024-10-03 10:57
Hi, is this issue still open ? I'd like to contribute to it

**Comment by PedroRosalba** [comment] 2024-11-03 19:07
Can I take this from here?

**Comment by zerosnacks** [comment] 2024-11-05 13:34
Marking as duplicate of https://github.com/foundry-rs/foundry/issues/3512 which aims to add an Anvil cache path

**Closed by zerosnacks** 2024-11-05 13:34 UTC
Labels: good first issue, T-feature, C-anvil

**Comment by folex** [comment] 2025-01-07 13:42
Hello, folks!

It seems that for me, anvil ignores `--cache-path`:

```shell
RUST_LOG=debug,cache=trace anvil --cache-path "/tmp/test" --fork-url https://rpc.testnet.fluence.dev --fork-block-number 295905 --no-rate-limit --fork-chain-id 52164803

2025-01-07T13:37:57.231521Z TRACE cache: reading json cache path="/Users/folex/.foundry/cache/rpc/52164803/295905/storage.json"

^C

2025-01-07T13:38:29.247340Z TRACE flush{path=Some("/Users/folex/.foundry/cache/rpc/52164803/295905/storage.json")}: cache: saving json cache
2025-01-07T13:38:29.247781Z TRACE flush{path=Some("/Users/folex/.foundry/cache/rpc/52164803/295905/storage.json")}: cache: saved json cache
```

```
foundryup: installed - forge 0.3.0 (5e72c69 2025-01-07T00:23:20.105032000Z)
foundryup: installed - cast 0.3.0 (5e72c69 2025-01-07T00:23:20.035938000Z)
foundryup: installed - anvil 0.3.0 (5e72c69 2025-01-07T00:23:20.032323000Z)
foundryup: installed - chisel 0.3.0 (5e72c69 2025-01-07T00:23:19.732130000Z)

% anvil --version
anvil 0.3.0 (5e72c69 2025-01-07T00:23:20.032323000Z)
```

Am I doing something wrong here?
