### ISSUE TITLE
Failing `assertEq` doesn't fail the test if not called from the contract with the test

### ISSUE THREAD

**Issue by CodeSandwich** [foundry-rs/foundry#3189] opened 2022-09-13 11:09 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (63c71b4 2022-09-12T00:04:31.392087873Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

This issue was reported before: https://github.com/dapphub/dapptools/issues/768 and it was fixed. For whatever reason that fix doesn't translate to `forge`.

# The problem

Only the instance containing the currently run test is checked when deciding if the test has failed. This makes it very hard to create a test utility using forge's `Test` asserts (`assertEq`, etc.), which could be used in multiple test contracts. The test utility must inherit from `Test`, but its `failed` state won't be checked and all failing asserts will be silently ignored.

# An example

```solidity
contract MyContract {
    function foo(uint arg) public returns (uint) {
        // do stuff
        return arg + 2;
    }
}

contract MyContractUser is Test {
    MyContract immutable myContract;

    constructor() {
        myContract = new MyContract();
    }

    function foo(uint arg) public returns (uint ret) {
        ret = myContract.foo(arg);
        assertEq(ret, arg + 1, "Invariant failed"); // Always violated, should fail
    }
}

contract MyContractTest is Test {
    function testFoo() public {
        MyContractUser user = new MyContractUser();
        // do stuff
        uint fooRet = user.foo(123);
        // do more stuff
    }
}
```
The `assertEq` here doesn't work. The invariant it's checking is always violated, but the test always passes, it only prints a message to the console. If the code is refactored so `assertEq` is moved to `MyContractTest`, it nicely fails as expected:
```solidity
contract MyContractTest is Test {
    function testFoo() public {
        MyContractUser user = new MyContractUser();
        // do stuff
        uint fooRet = user.foo(123);
        assertEq(fooRet, 123 + 1, "Invariant failed");
        // do more stuff
    }
}
```
```
Running 1 test for src/test/Caller.t.sol:MyContractTest
[FAIL. Reason: Assertion failed.] testFoo() (gas: 599395)
Logs:
  Error: Invariant failed
  Error: a == b not satisfied [uint]
    Expected: 124
      Actual: 125
  Error: Invariant failed
  Error: a == b not satisfied [uint]
    Expected: 124
      Actual: 125
```

**Comment by mattsse** [comment] 2022-09-13 12:33
this is expected because of how the `failed` state is tracked, which is a bool inside the Test state:

https://github.com/dapphub/ds-test/blob/9310e879db8ba3ea6d5c6489a579118fd264a3f5/src/test.sol#L39

you can however call the `failed` function manually
https://github.com/dapphub/ds-test/blob/9310e879db8ba3ea6d5c6489a579118fd264a3f5/src/test.sol#L47

and do 

```solidity
assert(!user.failed());
```

**Comment by mattsse** [comment] 2022-09-13 12:34
closing this, as this is the expected behaviour here

**Comment by CodeSandwich** [comment] 2022-09-13 12:46
Why would a behavior like this be desired? For newcomers who don't know the inner workings it's a very dangerous trap, every other testing framework in the world lets you perform an assert wherever you want. There's no warning and even no documentation for it. It's also against the philosophy of backward compatibility with DappTools.

Like you said, it's a matter of adding a single check to be performed after each test run, DS-Test already provides the necessary mechanism.

**Comment by mattsse** [comment] 2022-09-13 13:20
> It's also against the philosophy of backward compatibility with DappTools.

could you elaborate on this?

we should improve the docs for these scenarios

**Comment by mattsse** [comment] 2022-09-13 13:38
@onbjerg I wonder if this has to do with the `globalFailed` flag, perhaps we're not evaluating this correctly, because I think this should catch things like this

**Comment by mattsse** [comment] 2022-09-13 14:39
@CodeSandwich okay I found the issue, this was indeed an issue with how we evaluated the `globalFailure` flag that is set in failed asserts.

thanks for flagging this!

**Closed** 2022-09-13 17:44 UTC
Labels: T-bug, A-cheatcodes

**Comment by CodeSandwich** [comment] 2022-09-14 07:16
Thank you for fixing it and so fast!
