### ISSUE TITLE
Error:  No previous offset when trying to run forge script

### ISSUE THREAD

**Issue by felipepimsil** [foundry-rs/foundry#8877] opened 2024-09-16 19:00 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (280aa26 2024-09-16T00:21:37.361283000Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

I get `No previous offset` for any script I run.

Example:

```
pragma solidity ^0.8.26;

import {Script, console2} from "forge-std/Script.sol";

contract MyScript is Script {

    receive() external payable {}
    function setUp() public {}

    function run() public {
        
    }
}
```

Using a --rpc-url, local, etc. Everytime I get

```
No files changed, compilation skipped
Error: 
No previous offset
```

**Comment by grandizzy** [comment] 2024-09-17 04:53
@felipepimsil I cannot reproduce this locally with script above 
![image](https://github.com/user-attachments/assets/73142491-9904-4b35-a517-a17775eb474a)
 maybe try `forge clean` and rerun script?

**Comment by DaniPopes** [comment] 2024-09-17 12:37
This error is in artifact source map decoding, fixed by cleaning cache and build artifacts

**Closed by DaniPopes** 2024-09-17 12:37 UTC
Labels: T-bug, T-needs-triage

**Comment by simplyoptimistic** [comment] 2024-10-01 05:29
I had this issue as well and I kept downgrading my foundry until it worked (I downgraded by months). 

This tag worked for me: [nightly-90588120933f587ec61bb141efe306efd79f5f0d](https://github.com/foundry-rs/foundry/releases/tag/nightly-90588120933f587ec61bb141efe306efd79f5f0d). July 1st.

If time permits, I'll add more details, but posted this in case it helps anyone.
