### ISSUE TITLE
bug(forge init): after exec the command 'forge init' has not generate the 'lib' directory  

### ISSUE THREAD

**Issue by fulixia** [foundry-rs/foundry#6014] opened 2023-10-09 10:23 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

 forge: 0.2.0 

### What command(s) is the bug in?

forge init --force 

### Operating System

macOS (Intel)

### Describe the bug

after exec the command 'forge init' has not generate the 'lib' directory

**Comment by mattsse** [comment] 2023-10-09 19:34
did you get any of this output?

```text
forge init --force
Initializing /Users/Matthias/git/rust/dummy1...
Installing forge-std in /Users/Matthias/git/rust/dummy1/lib/forge-std (url: Some("https://github.com/foundry-rs/forge-std"), tag: None)
Cloning into '/Users/Matthias/git/rust/dummy1/lib/forge-std'...
remote: Enumerating objects: 2009, done.
remote: Counting objects: 100% (2005/2005), done.
remote: Compressing objects: 100% (657/657), done.
remote: Total 2009 (delta 1331), reused 1923 (delta 1285), pack-reused 4
Receiving objects: 100% (2009/2009), 536.07 KiB | 922.00 KiB/s, done.
Resolving deltas: 100% (1331/1331), done.
Submodule 'lib/ds-test' (https://github.com/dapphub/ds-test) registered for path 'lib/forge-std/lib/ds-test'
Cloning into '/Users/Matthias/git/rust/dummy1/lib/forge-std/lib/ds-test'...
remote: Enumerating objects: 313, done.
remote: Counting objects: 100% (171/171), done.
remote: Compressing objects: 100% (87/87), done.
remote: Total 313 (delta 90), reused 135 (delta 75), pack-reused 142
Receiving objects: 100% (313/313), 71.98 KiB | 670.00 KiB/s, done.
Resolving deltas: 100% (129/129), done.
    Installed forge-std v1.7.1
    Initialized forge project
```

**Comment by zerosnacks** [comment] 2024-07-04 12:15
Tentatively marking as `can't repro` given the lack of details provided and being unable to reproduce it as it likely requires on a specific state in the existing repository

@fulixia feel free to re-open with additional details and preferably a minimal reproduction

**Closed by zerosnacks** 2024-07-04 12:15 UTC
Labels: T-bug, T-to-reproduce, Cmd-forge-init
