### ISSUE TITLE
get_receipt returns NullResp

### ISSUE THREAD

**Issue by hertarr** [foundry-rs/foundry#7902] opened 2024-05-09 19:08 UTC
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

v0.2.0

### What command(s) is the bug in?

forge script --slow

### Operating System

Linux

### Describe the bug

After deploying each contract, NullResp returned by get_receipt() would exit but tx already successed.

**Comment by klkvr** [comment] 2024-05-10 14:34
What is the specific nightly this is happening on and could you please share complete command and its output?

**Comment by hertarr** [comment] 2024-05-12 18:20
`forge script scripts/Deploy.s.sol:Deploy --private-key $GS_ADMIN_PRIVATE_KEY --broadcast --rpc-url $L1_RPC_URL --slow`

I don't know why need to return NullResp, it's very easy to get NullResp when transaction is committing.

**Comment by hertarr** [comment] 2024-05-24 08:32
Can use loop for waiting `Receipt` instead of returning `NullResp`?

**Comment by zerosnacks** [comment] 2024-10-22 11:53
Hi @hertarr, would you mind checking if this is still an issue for you? 

If so, please provide a minimal reproduction and if relevant, the RPC URL you are running the script against?

For now, marking as `resolved` as there have been relevant changes since that likely have resolved this issue.

Thanks!

**Closed by zerosnacks** 2024-10-22 11:53 UTC
Labels: T-bug, C-forge, Cmd-forge-script, T-to-reproduce
